/*
  ZPAQBSC: a libbsc 3.3.12 decoder written in ZPAQL, for zpaq-std -ma:bsc (the
  block zpaq-std writes: no LZP, the ST3/ST4/ST5 sort transform, the static QLFC
  coder). zpaq-std, 2026, written from libbsc's code. Generated by gen.py next to
  this file (ZPAQL has no subroutines: everything is a macro expanded in place);
  ref.py is the Python reference decoder it was checked against, which matches
  libbsc on every test stream.

  Every block starts with a fixed 40,960-byte data prefix, QLFC's two state tables
  (zpaqbsc_tablas.h), then the bsc block. The whole input is kept in M and
  decoded at the end: QLFC (a 32-bit range coder over 16-bit words, each bit
  predicted by a fixed mix of three adaptive counters -- by state, by symbol and
  static -- whose updates are C's signed ">> 12", reproduced here with floor
  shifts), sub-block by sub-block, then the inverse sort transform (libbsc's
  reconstruction, generalised so it has no 2^23 limit).

  M: the input, 16 zero bytes, the transform's input and the output. H: the
  counters (about 810,000) under 2^20, and one word per output byte from 2^20 on,
  so ph = log2(2^20 + n) rounded up (at least 21).

  Verified with zpaqd 7.15 on 177 bsc streams from 59 inputs (49 corpus files of
  every type up to 9.8 MB, 16 and 17.5 MB blocks, zeros, random data, patterns)
  at ST3, ST4 and ST5.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQBSC_CUERPO[] = R"ZBSC(hcomp
halt
pcomp zpaqbsc ;
(ZPAQBSC: decodificador de libbsc 3.3.12 en ZPAQL, para zpaq-std -ma:bsc (sin LZP,
 ST3/ST4/ST5 y QLFC estatico). zpaq-std, 2026. Entrada: las dos tablas de estados del
 QLFC y el bloque de bsc; se guarda en M y se decodifica al final.)
a> 255 ifl
  a=c r=a 1
  a=0 r=a 44 do *c=a c++ a=r 44 a++ r=a 44 a< 16 while
a= 8
a<<= 8
  r=a 100
a= 1
a<<= 8 a+= 8
a<<= 8
  r=a 101
a= 13
a<<= 8 a+= 94
a<<= 8 a+= 40
  r=a 102
a= 16
a<<= 8
a<<= 8
  r=a 103
a= 7
a<<= 8
  r=a 104
a= 1
a<<= 8 a+= 8
a<<= 8
  r=a 105
a= 1
a<<= 8 a+= 8
a<<= 8 a+= 1
  r=a 106
a= 1
a<<= 8 a+= 9
a<<= 8 a+= 1
  r=a 107
a= 1
a<<= 8 a+= 10
a<<= 8 a+= 1
  r=a 108
a= 1
a<<= 8 a+= 10
a<<= 8 a+= 9
  r=a 109
a= 1
a<<= 8 a+= 18
a<<= 8 a+= 9
  r=a 110
a= 3
a<<= 8 a+= 23
a<<= 8 a+= 7
  r=a 111
a= 3
a<<= 8 a+= 24
a<<= 8 a+= 7
  r=a 112
a= 4
a<<= 8 a+= 24
a<<= 8 a+= 7
  r=a 113
a= 5
a<<= 8 a+= 24
a<<= 8 a+= 7
  r=a 114
a= 5
a<<= 8 a+= 24
a<<= 8 a+= 8
  r=a 115
a= 5
a<<= 8 a+= 25
a<<= 8 a+= 8
  r=a 116
a= 5
a<<= 8 a+= 26
a<<= 8 a+= 8
  r=a 117
a= 5
a<<= 8 a+= 26
a<<= 8 a+= 40
  r=a 118
a= 5
a<<= 8 a+= 58
a<<= 8 a+= 40
  r=a 119
a= 5
a<<= 8 a+= 90
a<<= 8 a+= 40
  r=a 120
  a= 1 a<<= 16 r=a 70 a= 128 a<<= 24 r=a 72
a= 7
a<<= 8 a+= 1
  d=a
a= 1
a<<= 8 a+= 26
a<<= 8 a+= 9
  *d=a
a= 7
a<<= 8 a+= 2
  d=a
a= 1
a<<= 8 a+= 30
a<<= 8 a+= 11
  *d=a
a= 7
a<<= 8 a+= 3
  d=a
a= 1
a<<= 8 a+= 38
a<<= 8 a+= 15
  *d=a
a= 7
a<<= 8 a+= 4
  d=a
a= 1
a<<= 8 a+= 54
a<<= 8 a+= 23
  *d=a
a= 7
a<<= 8 a+= 5
  d=a
a= 1
a<<= 8 a+= 86
a<<= 8 a+= 39
  *d=a
a= 7
a<<= 8 a+= 6
  d=a
a= 1
a<<= 8 a+= 150
a<<= 8 a+= 71
  *d=a
a= 7
a<<= 8 a+= 7
  d=a
a= 2
a<<= 8 a+= 22
a<<= 8 a+= 135
  *d=a
  a= 160 a<<= 8 r=a 44
  a=r 44 a+= 4 r=a 45
a=r 45 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 5
  a=r 44 a+= 8 r=a 45
a=r 45 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 46
  a=r 46 a&= 31 r=a 6
  a=r 44 a+= 12 r=a 45
a=r 45 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 7
  a=r 1 a+= 16 r=a 8 r=a 10 b=r 5 a+=b r=a 9
  a=r 46 a> 0 ifl
  a=r 44 a+= 28 r=a 55 c=a a=*c r=a 11
  a=r 11 a== 1 ifl
    a=r 55 a++ r=a 14
a=r 101 d=a a=r 102 r=a 38
do a= 8 a<<= 8 *d=a d++ a=d b=r 38 a<b while
a=r 14 r=a 2 a=0 r=a 3 a=0 a-- r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=0 r=a 20 r=a 21 r=a 22 r=a 24 a= 7 r=a 23
a=0 r=a 40
do
  a=r 40 a+= 255 a++ d=a a=0 *d=a a=r 40 a+= 255 a+= 255 a+= 2 d=a a=0 *d=a a=r 40 a+= 255 a+= 255 a+= 255 a+= 3 d=a a=0 *d=a
  a=r 40 a++ r=a 40 a> 255 until
a=0 r=a 15
a=0 r=a 40
do
  a= 8 a<<= 8 r=a 36
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
  a=r 15 a<<= 1 b=r 32 a+=b r=a 15
  a=r 40 a++ r=a 40 a< 32 while
a=r 10 b=r 15 a+=b r=a 16
a= 3 a<<= 8 a+= 231 r=a 41 a=0 r=a 40
do
  a=0 r=a 42 a= 7 r=a 43
  do
    a=r 43 a++ b=a a=r 42 a<<=b r=a 44 a=r 42 a++ a<<=b r=a 45 a=0 r=a 46 r=a 47
    do
      a=r 44 b=r 41 a==b ifl a= 1 elsel a=r 44 a+= 255 a+= 255 a+= 255 a+= 3 d=a a=*d a== 0 ifl a= 1 elsel a=0 endif endif
      a> 0 ifl
        a= 1 b=r 43 a<<=b b=a a=r 44 a&=b a> 0 ifl a= 1 r=a 47 elsel a= 1 r=a 46 endif
      endif
      a=r 44 a++ r=a 44 b=r 45 a<b ifl a=r 46 a> 0 ifl a=r 47 a== 0 ifl a= 1 elsel a=0 endif elsel a= 1 endif elsel a=0 endif
    a> 0 while
    a=r 46 a> 0 ifl a=r 47 a> 0 ifl
      a= 8 a<<= 8
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
      a=r 42 a<<= 1 b=r 32 a+=b r=a 42
    elsel a=r 42 a<<= 1 r=a 42 endif
    elsel a=r 47 a> 0 ifl a=r 42 a<<= 1 a++ r=a 42 endif endif
    a=r 43 a> 0 ifl a-- r=a 43 a= 1 elsel a=0 endif
  a> 0 while
  a=r 40 d=a a=r 42 *d=a
  a=r 42 b=r 41 a==b ifl
    a=r 40 a> 1 ifl a-- r=a 44
a=0 r=a 23 a=r 44 a>>= 1 a> 0 ifl do r=a 38 a=r 23 a++ r=a 23 a=r 38 a>>= 1 a> 0 while endif
    elsel a= 63 r=a 23 endif
    a=0 r=a 44
  elsel
    a=r 42 r=a 41 a+= 255 a+= 255 a+= 255 a+= 3 d=a a= 1 *d=a
    a=r 40 a++ r=a 40 a> 255 ifl a=0 elsel a= 1 endif r=a 44
  endif
  a=r 44
a> 0 while
a=r 10 b=r 16 a<b ifl
do
  a=0 d=a a=*d r=a 25
  a=r 25 a+= 255 a++ d=a a=*d r=a 44 a=r 22 a<<= 11 b=a a=r 21 a<<= 3 a+=b b=r 44 a+=b c=a a=*c r=a 26
  a= 1 r=a 27
  a=r 24 a< 32 ifl
    a=r 26 b=r 106 a+=b r=a 33 a=r 25 b=r 107 a+=b r=a 34 a=r 105 r=a 35
a=r 34 d=a a=*d
a*= 17
r=a 39
a=r 33 d=a a=*d
a*= 14
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 1
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
    a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 178
b=a a=r 38 a-=b
a*= 34
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 12
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 18
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 55
b=a a=r 38 a-=b
r=a 38
a= 4
a<<= 8 a+= 161
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 26 a<<= 3 b=r 109 a+=b r=a 33 a=r 25 a<<= 3 b=r 110 a+=b r=a 34 a=r 108 r=a 35
      a= 1 r=a 28
      do
        a=r 28 b=r 23 a==b ifl a=0 elsel
a=r 34 d=a a=*d
a*= 22
r=a 39
a=r 33 d=a a=*d
a*= 6
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 4
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
        a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 254
a<<= 8 a+= 142
b=a a=r 38 a-=b
a*= 11
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 3
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 52
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 135
b=a a=r 38 a-=b
r=a 38
a= 5
a<<= 8 a+= 84
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
          a=r 33 a++ r=a 33 a=r 34 a++ r=a 34 a=r 35 a++ r=a 35 a=r 28 a++ r=a 28 a= 1
        elsel
a= 16
a<<= 8 a+= 177
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 23
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 14
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 15
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 3
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 3
a<<= 8 a+= 20
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
          a=0
        endif endif
      a> 0 while
      a=r 25 a+= 255 a++ d=a a=r 28 *d=a
      a=r 28 b=r 104 a+=b d=a a=*d r=a 45
      a=r 28 r=a 46
      do
        a=r 45 b=r 27 a+=b r=a 35
        a= 1 b=r 28 a<<=b r=a 47 a=r 26 a<<=b b=r 47 a+=b b=r 35 a+=b r=a 33
        a=r 28 b=a a= 1 a<<= 8 a<<=b r=a 47 a=r 25 a<<=b r=a 48 a= 1 a<<=b b=r 47 a+=b b=r 48 a+=b b=r 35 a+=b r=a 34
a=r 34 d=a a=*d
a*= 15
r=a 39
a=r 33 d=a a=*d
a*= 10
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 7
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 20
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 242
a<<= 8 a+= 44
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 16
r=a 38
a= 255
a<<= 8 a+= 225
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 74
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 100
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 73
r=a 38
a= 4
a<<= 8 a+= 143
a<<= 8 a+= 176
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
r=a 38
a= 4
a<<= 8 a+= 149
b=a a=r 38 a*=b
r=a 38
a= 29
a<<= 8 a+= 227
a<<= 8 a+= 254
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
r=a 38
a= 2
a<<= 8 a+= 63
b=a a=r 38 a*=b
r=a 38
a= 35
a<<= 8 a+= 237
a<<= 8 a+= 123
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
        a=r 27 a<<= 1 b=r 32 a+=b r=a 27
        a=r 46 a-- r=a 46
      a> 0 while
    elsel
      a=r 25 a+= 255 a++ d=a a=0 *d=a
a= 16
a<<= 8 a+= 116
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 33
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 2
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 26
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 15
a<<= 8 a+= 252
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 2
a<<= 8 a+= 185
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
    endif
  elsel
    a=0 r=a 27 a= 1 r=a 30 a=r 23 a++ r=a 46
    do
      a=r 30 b=r 111 a+=b r=a 35
      a=r 26 a<<= 8 b=r 30 a+=b b=r 112 a+=b r=a 33
      a=r 25 a<<= 8 b=r 30 a+=b b=r 113 a+=b r=a 34
a=r 34 d=a a=*d
a*= 16
r=a 39
a=r 33 d=a a=*d
a*= 11
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 5
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 32
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 64
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 32
r=a 38
a= 1
a<<= 8 a+= 255
a<<= 8 a+= 193
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 157
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 171
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 120
r=a 38
a= 7
a<<= 8 a+= 127
a<<= 8 a+= 121
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
r=a 38
a= 1
a<<= 8 a+= 19
b=a a=r 38 a*=b
r=a 38
a= 161
a<<= 8 a+= 34
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
r=a 38
a= 2
a<<= 8 a+= 73
b=a a=r 38 a*=b
r=a 38
a= 36
a<<= 8 a+= 141
a<<= 8 a+= 183
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 30 a<<= 1 b=r 32 a+=b r=a 30 a=r 27 a<<= 1 b=r 32 a+=b r=a 27
      a=r 46 a-- r=a 46
    a> 0 while
a=0 r=a 44 a=r 27 a>>= 1 a> 0 ifl do r=a 38 a=r 44 a++ r=a 44 a=r 38 a>>= 1 a> 0 while endif
    a=r 25 a+= 255 a++ d=a a=r 44 *d=a
  endif
  a=r 27 a> 0 ifl a=0 d=a do d++ a=*d d-- *d=a d++ a=d b=r 27 a<b while endif
  a=r 27 d=a a=r 25 *d=a
  a=r 24 a*= 124 r=a 44 a=r 27 a<<= 2 b=r 44 a+=b a>>= 7 r=a 24
  a=r 27 a-- r=a 27
  a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d a> 7 ifl a= 7 endif r=a 44
  a=r 27 a> 7 ifl a= 7 endif a<<= 3 b=r 44 a+=b r=a 44 a=r 22 a<<= 6 b=r 44 a+=b r=a 44 a=r 20 a<<= 10 b=r 44 a+=b r=a 44
  a= 128 a<<= 8 b=r 44 a+=b c=a a=*c r=a 26
  a=r 26 b=r 115 a+=b r=a 33 a=r 25 b=r 116 a+=b r=a 34 a=r 114 r=a 35
a=r 34 d=a a=*d
a*= 14
r=a 39
a=r 33 d=a a=*d
a*= 18
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 0
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
  a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 144
b=a a=r 38 a-=b
a*= 36
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 243
b=a a=r 38 a-=b
a*= 231
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
    a=r 26 a<<= 5 b=r 118 a+=b r=a 33 a=r 25 a<<= 5 b=r 119 a+=b r=a 34 a=r 117 r=a 35
    a= 1 r=a 29 r=a 28
    do
a=r 34 d=a a=*d
a*= 14
r=a 39
a=r 33 d=a a=*d
a*= 15
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 3
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
      a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 164
b=a a=r 38 a-=b
a*= 44
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 245
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 85
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 252
b=a a=r 38 a-=b
r=a 38
a= 2
a<<= 8 a+= 253
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
        a=r 33 a++ r=a 33 a=r 34 a++ r=a 34 a=r 35 a++ r=a 35 a=r 28 a++ r=a 28 a> 31 ifl a=0 elsel a= 1 endif
      elsel
a= 16
a<<= 8 a+= 90
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 45
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 3
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 69
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 15
a<<= 8 a+= 232
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 3
a<<= 8 a+= 119
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
        a=0
      endif
    a> 0 while
    a=r 28 a> 31 ifl a= 31 r=a 28 endif
    a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d r=a 44 a=r 28 a*= 3 a+= 3 b=r 44 a+=b a>>= 2 *d=a
    a=r 28 r=a 38
a= 64
a<<= 8 a+= 32
    b=r 38 a*=b b=r 120 a+=b r=a 45
    a= 1 r=a 30 a=r 28 r=a 46
    do
      a=r 45 b=r 30 a+=b r=a 35
      a=r 26 a<<= 5 b=r 35 a+=b a+= 32 r=a 33
      a=r 25 a<<= 5 b=r 35 a+=b a+= 32 r=a 34 a= 32 a<<= 8 b=r 34 a+=b r=a 34
a=r 34 d=a a=*d
a*= 7
r=a 39
a=r 33 d=a a=*d
a*= 15
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 10
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 22
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 26
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 14
r=a 38
a= 223
a<<= 8 a+= 11
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 241
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 241
a<<= 8 a+= 225
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 191
r=a 38
a= 11
a<<= 8 a+= 237
a<<= 8 a+= 111
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
a*= 19
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 30
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
a*= 54
r=a 38
a= 3
a<<= 8 a+= 95
a<<= 8 a+= 103
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 29 a<<= 1 b=r 32 a+=b r=a 29
      a=r 28 a> 5 ifl a=r 30 a++ elsel a=r 30 a<<= 1 b=r 32 a+=b endif r=a 30
      a=r 46 a-- r=a 46
    a> 0 while
    a=r 29 a< 3 ifl a= 1 elsel a=0 endif r=a 44
    do a=r 25
r=a 37 a=r 10 b=r 16 a<b ifl c=a a=r 37 *c=a a=c a++ r=a 10 endif
      a=r 29 a-- r=a 29 a> 0 while
  elsel
    a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d a+= 2 a>>= 2 *d=a
a= 16
a<<= 8 a+= 68
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 38
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 4
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
a*= 221
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
    a= 1 r=a 44 a=r 25
r=a 37 a=r 10 b=r 16 a<b ifl c=a a=r 37 *c=a a=c a++ r=a 10 endif
  endif
  a=r 20 a<<= 1 r=a 45 a=r 27 a== 0 ifl a=r 45 a++ r=a 45 endif a=r 45 a&= 7 r=a 20
  a=r 27 a> 3 ifl a= 3 endif r=a 45 a=r 21 a<<= 2 b=r 45 a+=b a&= 255 r=a 21
  a=r 22 a<<= 1 b=r 44 a+=b a&= 15 r=a 22
  a=r 10 b=r 16 a<b ifl a=r 1 a+= 64 b=a a=r 2 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
a> 0 while
endif
  elsel
    a=r 11 a<<= 3 b=r 55 a+=b a++ r=a 14 a=0 r=a 12
    a=r 11 a> 0 ifl
    do
      a=r 12 a<<= 3 b=r 55 a+=b a++ r=a 50
a=r 50 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 51
      a=r 50 a+= 4 r=a 50
a=r 50 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 52
      a=r 51 b=r 52 a==b ifl
        a=r 10 b=r 52 a+=b r=a 16
        a=r 52 a> 0 ifl a=r 14 r=a 53 do a=r 53 c=a a=*c
r=a 37 a=r 10 b=r 16 a<b ifl c=a a=r 37 *c=a a=c a++ r=a 10 endif
          a=r 53 a++ r=a 53 a=r 52 a-- r=a 52 a> 0 while endif
      elsel
        a=r 10 b=r 51 a+=b r=a 54
a=r 101 d=a a=r 102 r=a 38
do a= 8 a<<= 8 *d=a d++ a=d b=r 38 a<b while
a=r 14 r=a 2 a=0 r=a 3 a=0 a-- r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
b=a a=r 3 a<<= 16 a+=b r=a 3
a=0 r=a 20 r=a 21 r=a 22 r=a 24 a= 7 r=a 23
a=0 r=a 40
do
  a=r 40 a+= 255 a++ d=a a=0 *d=a a=r 40 a+= 255 a+= 255 a+= 2 d=a a=0 *d=a a=r 40 a+= 255 a+= 255 a+= 255 a+= 3 d=a a=0 *d=a
  a=r 40 a++ r=a 40 a> 255 until
a=0 r=a 15
a=0 r=a 40
do
  a= 8 a<<= 8 r=a 36
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
  a=r 15 a<<= 1 b=r 32 a+=b r=a 15
  a=r 40 a++ r=a 40 a< 32 while
a=r 10 b=r 15 a+=b r=a 16
a= 3 a<<= 8 a+= 231 r=a 41 a=0 r=a 40
do
  a=0 r=a 42 a= 7 r=a 43
  do
    a=r 43 a++ b=a a=r 42 a<<=b r=a 44 a=r 42 a++ a<<=b r=a 45 a=0 r=a 46 r=a 47
    do
      a=r 44 b=r 41 a==b ifl a= 1 elsel a=r 44 a+= 255 a+= 255 a+= 255 a+= 3 d=a a=*d a== 0 ifl a= 1 elsel a=0 endif endif
      a> 0 ifl
        a= 1 b=r 43 a<<=b b=a a=r 44 a&=b a> 0 ifl a= 1 r=a 47 elsel a= 1 r=a 46 endif
      endif
      a=r 44 a++ r=a 44 b=r 45 a<b ifl a=r 46 a> 0 ifl a=r 47 a== 0 ifl a= 1 elsel a=0 endif elsel a= 1 endif elsel a=0 endif
    a> 0 while
    a=r 46 a> 0 ifl a=r 47 a> 0 ifl
      a= 8 a<<= 8
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
      a=r 42 a<<= 1 b=r 32 a+=b r=a 42
    elsel a=r 42 a<<= 1 r=a 42 endif
    elsel a=r 47 a> 0 ifl a=r 42 a<<= 1 a++ r=a 42 endif endif
    a=r 43 a> 0 ifl a-- r=a 43 a= 1 elsel a=0 endif
  a> 0 while
  a=r 40 d=a a=r 42 *d=a
  a=r 42 b=r 41 a==b ifl
    a=r 40 a> 1 ifl a-- r=a 44
a=0 r=a 23 a=r 44 a>>= 1 a> 0 ifl do r=a 38 a=r 23 a++ r=a 23 a=r 38 a>>= 1 a> 0 while endif
    elsel a= 63 r=a 23 endif
    a=0 r=a 44
  elsel
    a=r 42 r=a 41 a+= 255 a+= 255 a+= 255 a+= 3 d=a a= 1 *d=a
    a=r 40 a++ r=a 40 a> 255 ifl a=0 elsel a= 1 endif r=a 44
  endif
  a=r 44
a> 0 while
a=r 10 b=r 16 a<b ifl
do
  a=0 d=a a=*d r=a 25
  a=r 25 a+= 255 a++ d=a a=*d r=a 44 a=r 22 a<<= 11 b=a a=r 21 a<<= 3 a+=b b=r 44 a+=b c=a a=*c r=a 26
  a= 1 r=a 27
  a=r 24 a< 32 ifl
    a=r 26 b=r 106 a+=b r=a 33 a=r 25 b=r 107 a+=b r=a 34 a=r 105 r=a 35
a=r 34 d=a a=*d
a*= 17
r=a 39
a=r 33 d=a a=*d
a*= 14
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 1
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
    a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 178
b=a a=r 38 a-=b
a*= 34
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 12
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 18
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 55
b=a a=r 38 a-=b
r=a 38
a= 4
a<<= 8 a+= 161
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 26 a<<= 3 b=r 109 a+=b r=a 33 a=r 25 a<<= 3 b=r 110 a+=b r=a 34 a=r 108 r=a 35
      a= 1 r=a 28
      do
        a=r 28 b=r 23 a==b ifl a=0 elsel
a=r 34 d=a a=*d
a*= 22
r=a 39
a=r 33 d=a a=*d
a*= 6
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 4
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
        a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 254
a<<= 8 a+= 142
b=a a=r 38 a-=b
a*= 11
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 3
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 52
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 135
b=a a=r 38 a-=b
r=a 38
a= 5
a<<= 8 a+= 84
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
          a=r 33 a++ r=a 33 a=r 34 a++ r=a 34 a=r 35 a++ r=a 35 a=r 28 a++ r=a 28 a= 1
        elsel
a= 16
a<<= 8 a+= 177
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 23
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 14
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 15
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 3
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 3
a<<= 8 a+= 20
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
          a=0
        endif endif
      a> 0 while
      a=r 25 a+= 255 a++ d=a a=r 28 *d=a
      a=r 28 b=r 104 a+=b d=a a=*d r=a 45
      a=r 28 r=a 46
      do
        a=r 45 b=r 27 a+=b r=a 35
        a= 1 b=r 28 a<<=b r=a 47 a=r 26 a<<=b b=r 47 a+=b b=r 35 a+=b r=a 33
        a=r 28 b=a a= 1 a<<= 8 a<<=b r=a 47 a=r 25 a<<=b r=a 48 a= 1 a<<=b b=r 47 a+=b b=r 48 a+=b b=r 35 a+=b r=a 34
a=r 34 d=a a=*d
a*= 15
r=a 39
a=r 33 d=a a=*d
a*= 10
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 7
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 20
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 242
a<<= 8 a+= 44
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 16
r=a 38
a= 255
a<<= 8 a+= 225
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 74
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 100
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 73
r=a 38
a= 4
a<<= 8 a+= 143
a<<= 8 a+= 176
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
r=a 38
a= 4
a<<= 8 a+= 149
b=a a=r 38 a*=b
r=a 38
a= 29
a<<= 8 a+= 227
a<<= 8 a+= 254
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
r=a 38
a= 2
a<<= 8 a+= 63
b=a a=r 38 a*=b
r=a 38
a= 35
a<<= 8 a+= 237
a<<= 8 a+= 123
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
        a=r 27 a<<= 1 b=r 32 a+=b r=a 27
        a=r 46 a-- r=a 46
      a> 0 while
    elsel
      a=r 25 a+= 255 a++ d=a a=0 *d=a
a= 16
a<<= 8 a+= 116
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 33
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 2
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 26
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 15
a<<= 8 a+= 252
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 2
a<<= 8 a+= 185
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
    endif
  elsel
    a=0 r=a 27 a= 1 r=a 30 a=r 23 a++ r=a 46
    do
      a=r 30 b=r 111 a+=b r=a 35
      a=r 26 a<<= 8 b=r 30 a+=b b=r 112 a+=b r=a 33
      a=r 25 a<<= 8 b=r 30 a+=b b=r 113 a+=b r=a 34
a=r 34 d=a a=*d
a*= 16
r=a 39
a=r 33 d=a a=*d
a*= 11
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 5
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 32
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 64
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 32
r=a 38
a= 1
a<<= 8 a+= 255
a<<= 8 a+= 193
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 157
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 171
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 120
r=a 38
a= 7
a<<= 8 a+= 127
a<<= 8 a+= 121
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
r=a 38
a= 1
a<<= 8 a+= 19
b=a a=r 38 a*=b
r=a 38
a= 161
a<<= 8 a+= 34
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
r=a 38
a= 2
a<<= 8 a+= 73
b=a a=r 38 a*=b
r=a 38
a= 36
a<<= 8 a+= 141
a<<= 8 a+= 183
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 30 a<<= 1 b=r 32 a+=b r=a 30 a=r 27 a<<= 1 b=r 32 a+=b r=a 27
      a=r 46 a-- r=a 46
    a> 0 while
a=0 r=a 44 a=r 27 a>>= 1 a> 0 ifl do r=a 38 a=r 44 a++ r=a 44 a=r 38 a>>= 1 a> 0 while endif
    a=r 25 a+= 255 a++ d=a a=r 44 *d=a
  endif
  a=r 27 a> 0 ifl a=0 d=a do d++ a=*d d-- *d=a d++ a=d b=r 27 a<b while endif
  a=r 27 d=a a=r 25 *d=a
  a=r 24 a*= 124 r=a 44 a=r 27 a<<= 2 b=r 44 a+=b a>>= 7 r=a 24
  a=r 27 a-- r=a 27
  a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d a> 7 ifl a= 7 endif r=a 44
  a=r 27 a> 7 ifl a= 7 endif a<<= 3 b=r 44 a+=b r=a 44 a=r 22 a<<= 6 b=r 44 a+=b r=a 44 a=r 20 a<<= 10 b=r 44 a+=b r=a 44
  a= 128 a<<= 8 b=r 44 a+=b c=a a=*c r=a 26
  a=r 26 b=r 115 a+=b r=a 33 a=r 25 b=r 116 a+=b r=a 34 a=r 114 r=a 35
a=r 34 d=a a=*d
a*= 14
r=a 39
a=r 33 d=a a=*d
a*= 18
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 0
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
  a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 144
b=a a=r 38 a-=b
a*= 36
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 243
b=a a=r 38 a-=b
a*= 231
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
    a=r 26 a<<= 5 b=r 118 a+=b r=a 33 a=r 25 a<<= 5 b=r 119 a+=b r=a 34 a=r 117 r=a 35
    a= 1 r=a 29 r=a 28
    do
a=r 34 d=a a=*d
a*= 14
r=a 39
a=r 33 d=a a=*d
a*= 15
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 3
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
      a> 0 ifl
a=r 33 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 164
b=a a=r 38 a-=b
a*= 44
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 34 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 245
b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 85
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 35 d=a a=*d r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 252
b=a a=r 38 a-=b
r=a 38
a= 2
a<<= 8 a+= 253
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
        a=r 33 a++ r=a 33 a=r 34 a++ r=a 34 a=r 35 a++ r=a 35 a=r 28 a++ r=a 28 a> 31 ifl a=0 elsel a= 1 endif
      elsel
a= 16
a<<= 8 a+= 90
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 45
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 3
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 1
a<<= 8 a+= 69
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
a= 15
a<<= 8 a+= 232
r=a 38 a=r 35 d=a a=*d b=a a=r 38 a-=b
r=a 38
a= 3
a<<= 8 a+= 119
b=a a=r 38 a*=b
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a+=b *d=a
        a=0
      endif
    a> 0 while
    a=r 28 a> 31 ifl a= 31 r=a 28 endif
    a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d r=a 44 a=r 28 a*= 3 a+= 3 b=r 44 a+=b a>>= 2 *d=a
    a=r 28 r=a 38
a= 64
a<<= 8 a+= 32
    b=r 38 a*=b b=r 120 a+=b r=a 45
    a= 1 r=a 30 a=r 28 r=a 46
    do
      a=r 45 b=r 30 a+=b r=a 35
      a=r 26 a<<= 5 b=r 35 a+=b a+= 32 r=a 33
      a=r 25 a<<= 5 b=r 35 a+=b a+= 32 r=a 34 a= 32 a<<= 8 b=r 34 a+=b r=a 34
a=r 34 d=a a=*d
a*= 7
r=a 39
a=r 33 d=a a=*d
a*= 15
b=r 39 a+=b r=a 39
a=r 35 d=a a=*d
a*= 10
b=r 39 a+=b a>>= 5
r=a 36
a=r 4 b=r 70 a<b ifl
  a=r 4 a<<= 16 r=a 4
a=r 2 c=a a=*c r=a 37 c++ a=*c a<<= 8 b=r 37 a+=b r=a 37 a=r 2 a+= 2 r=a 2 a=r 37
  b=a a=r 3 a<<= 16 a+=b r=a 3
endif
a=r 4 a>>= 12 b=r 36 a*=b r=a 37 b=a a=r 3 a<b ifl
  a=r 37 r=a 4 a=0
elsel
  a=r 3 a-=b r=a 3 a=r 4 a-=b r=a 4 a= 1
endif
r=a 32
a=r 32 a> 0 ifl
  a=r 33 d=a a=*d
a*= 22
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 26
b=a a=r 38 a-=b
elsel
  a=r 33 d=a a=*d
a*= 14
r=a 38
a= 223
a<<= 8 a+= 11
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 34 d=a a=*d
a*= 241
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 241
a<<= 8 a+= 225
b=a a=r 38 a-=b
elsel
  a=r 34 d=a a=*d
a*= 191
r=a 38
a= 11
a<<= 8 a+= 237
a<<= 8 a+= 111
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a-=b *d=a
a=r 32 a> 0 ifl
  a=r 35 d=a a=*d
a*= 19
r=a 38
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 240
a<<= 8 a+= 30
b=a a=r 38 a-=b
elsel
  a=r 35 d=a a=*d
a*= 54
r=a 38
a= 3
a<<= 8 a+= 95
a<<= 8 a+= 103
b=a a=r 38 a-=b
endif
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 35 d=a a=*d a-=b *d=a
      a=r 29 a<<= 1 b=r 32 a+=b r=a 29
      a=r 28 a> 5 ifl a=r 30 a++ elsel a=r 30 a<<= 1 b=r 32 a+=b endif r=a 30
      a=r 46 a-- r=a 46
    a> 0 while
    a=r 29 a< 3 ifl a= 1 elsel a=0 endif r=a 44
    do a=r 25
r=a 37 a=r 10 b=r 16 a<b ifl c=a a=r 37 *c=a a=c a++ r=a 10 endif
      a=r 29 a-- r=a 29 a> 0 while
  elsel
    a=r 25 a+= 255 a+= 255 a+= 2 d=a a=*d a+= 2 a>>= 2 *d=a
a= 16
a<<= 8 a+= 68
r=a 38 a=r 33 d=a a=*d b=a a=r 38 a-=b
a*= 38
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 33 d=a a=*d a+=b *d=a
a= 16
a<<= 8 a+= 4
r=a 38 a=r 34 d=a a=*d b=a a=r 38 a-=b
a*= 221
b=r 72 a<b ifl a>>= 12 elsel b=a a=0 a-- a^=b a>>= 12 b=a a=0 a-- a^=b endif
b=a a=r 34 d=a a=*d a+=b *d=a
    a= 1 r=a 44 a=r 25
r=a 37 a=r 10 b=r 16 a<b ifl c=a a=r 37 *c=a a=c a++ r=a 10 endif
  endif
  a=r 20 a<<= 1 r=a 45 a=r 27 a== 0 ifl a=r 45 a++ r=a 45 endif a=r 45 a&= 7 r=a 20
  a=r 27 a> 3 ifl a= 3 endif r=a 45 a=r 21 a<<= 2 b=r 45 a+=b a&= 255 r=a 21
  a=r 22 a<<= 1 b=r 44 a+=b a&= 15 r=a 22
  a=r 10 b=r 16 a<b ifl a=r 1 a+= 64 b=a a=r 2 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
a> 0 while
endif
        a=r 54 r=a 10
      endif
      a=r 50 a-= 4 r=a 50
a=r 50 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 51
      a=r 50 a+= 4 r=a 50
a=r 50 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 52
      a=r 14 b=r 52 a+=b r=a 14
      a=r 12 a++ r=a 12 b=r 11 a<b
    while
    endif
  endif
a=r 5 a> 1 ifl
a=0 r=a 40
a=r 5 a> 0 ifl
do
  a=r 40 b=r 103 a+=b d=a a=0 *d=a
  a=r 40 a++ r=a 40 b=r 5 a<b while
endif
a=0 r=a 40
do
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a a=0 *d=a
  a=r 40 a++ r=a 40 a> 255 until
a=r 100 d=a a=0 r=a 44 do a=0 *d=a d++ a=r 44 a++ r=a 44 a=r 44 a>>= 16 a== 0 while
a=0 r=a 40
a=r 5 a> 0 ifl
do
a=r 40 b=r 8 a+=b c=a a=*c r=a 44
  a=r 44 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a *d++
  a=r 40 a++ r=a 40 b=r 5 a<b while
endif
a=0 r=a 45
a=0 r=a 40
do
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a a=*d r=a 46 a=r 45 *d=a r=a 47 b=r 46 a+=b r=a 45
  a=r 47 b=r 45 a<b ifl
    do
a=r 47 b=r 8 a+=b c=a a=*c r=a 48
      a=r 40 a<<= 8 b=r 48 a+=b b=r 100 a+=b d=a *d++
      a=r 47 a++ r=a 47 b=r 45 a<b
    while
  endif
  a=r 40 a++ r=a 40 a> 255 until
a=0 r=a 40
do
  a=r 40 a> 0 ifl
  a=0 r=a 44
  do
    a=r 44 a<<= 8 b=r 40 a+=b b=r 100 a+=b r=a 46 d=a a=*d r=a 48
    a=r 40 a<<= 8 b=r 44 a+=b b=r 100 a+=b d=a a=*d r=a 49 a=r 48 *d=a a=r 46 d=a a=r 49 *d=a
    a=r 44 a++ r=a 44 b=r 40 a<b
  while
  endif
  a=r 40 a++ r=a 40 a> 255 until
a=r 6 a== 3 ifl
  a=0 r=a 45 r=a 40
  do
    a=r 40 b=r 100 a+=b d=a a=*d a> 0 ifl r=a 46 a=r 45 b=r 103 a+=b d=a a= 1 *d=a a=r 45 b=r 46 a+=b r=a 45 endif
    a=r 40 a++ r=a 40 a>>= 16 a== 0
  while
elsel
a=0 r=a 40
do
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a a=*d r=a 44
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=r 44 *d=a
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=0 a-- *d=a
  a=r 40 a++ r=a 40 a> 255 until
  a=0 r=a 45 r=a 40
  do
    a=r 40 b=r 100 a+=b d=a a=*d r=a 46 a=r 45 r=a 47 b=r 46 a+=b r=a 45
    a=r 47 b=r 45 a<b ifl
      do
a=r 47 b=r 8 a+=b c=a a=*c r=a 48
        a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=*d b=r 40 a==b ifnotl
          a=r 40 *d=a a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=*d b=r 103 a+=b d=a a=r 72 *d=a
        endif
        a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a *d++
        a=r 47 a++ r=a 47 b=r 45 a<b
      while
    endif
    a=r 40 a++ r=a 40 a>>= 16 a== 0
  while
  a=r 72 r=a 50 a>>= 1 r=a 51 a= 4 r=a 52
  a=r 52 b=r 6 a<b ifl
  do
a=0 r=a 40
do
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a a=*d r=a 44
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=r 44 *d=a
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=0 a-- *d=a
  a=r 40 a++ r=a 40 a> 255 until
    a=0 r=a 53 r=a 40
    do
a=r 40 b=r 103 a+=b d=a a=*d r=a 44
      a=r 44 b=r 50 a&=b a> 0 ifl a=r 40 r=a 53 endif
a=r 40 b=r 8 a+=b c=a a=*c r=a 48
      a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=*d b=r 53 a==b ifnotl
        a=r 53 *d=a a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=*d b=r 103 a+=b d=a a=*d b=r 51 a+=b *d=a
      endif
      a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a *d++
      a=r 40 a++ r=a 40 b=r 5 a<b
    while
    a=r 50 a>>= 1 r=a 50 a=r 51 a>>= 1 r=a 51 a=r 52 a++ r=a 52
    b=r 6 a<b
  while
  endif
endif
a=0 r=a 40
do
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 4 d=a a=*d r=a 44
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=r 44 *d=a
  a=r 40 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=0 *d=a
  a=r 40 a++ r=a 40 a> 255 until
a=0 r=a 53 r=a 40
do
a=r 40 b=r 103 a+=b d=a a=*d r=a 44
  a=r 44 a> 0 ifl a=r 40 r=a 53 endif
a=r 40 b=r 8 a+=b c=a a=*c r=a 48
  a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 6 d=a a=*d r=a 49 b=r 53 a>b ifl
    a=r 49 a-- r=a 49 b=r 72 a+=b r=a 46
    a=r 40 b=r 103 a+=b d=a a=r 46 *d=a
    a=r 49 b=r 103 a+=b d=a *d++
  elsel
    a=r 40 a++ *d=a
    a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a a=*d r=a 46 a=r 40 b=r 103 a+=b d=a a=r 46 *d=a
  endif
  a=r 48 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 5 d=a *d++
  a=r 40 a++ r=a 40 b=r 5 a<b
while
a=r 7 r=a 44 a=r 5 r=a 40
do
  a=r 40 a-- r=a 40
a=r 44 b=r 103 a+=b d=a a=*d r=a 45
  a=r 45 b=r 72 a<b ifnot a-=b r=a 44
a=r 44 b=r 103 a+=b d=a a=*d r=a 45
  endif
  a=r 44 b=r 8 a+=b c=a a=*c r=a 46 a=r 40 b=r 9 a+=b c=a a=r 46 *c=a
  a=r 44 b=r 103 a+=b d=a *d-- a=r 45 r=a 44
  a=r 40
a> 0 while
elsel
  a=r 5 a> 0 ifl a=r 8 c=a a=*c r=a 46 a=r 9 c=a a=r 46 *c=a endif
endif
  elsel
    a=r 5 a> 0 ifl a=r 44 a+= 28 r=a 45 a=0 r=a 46 do a=r 45 b=r 46 a+=b c=a a=*c r=a 47 a=r 9 b=r 46 a+=b c=a a=r 47 *c=a a=r 46 a++ r=a 46 b=r 5 a<b while endif
  endif
  a=r 5 a> 0 ifl a=0 r=a 44 do a=r 9 b=r 44 a+=b c=a a=*c out a=r 44 a++ r=a 44 b=r 5 a<b while endif
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZBSC";
