/*
  ZPAQLIZARDH: a Lizard 2.1 decoder written in ZPAQL, for zpaq-std -ma:lizard,
  levels 30-49 (fastLZ4 and LIZv1 with Huffman). zpaq-std, 2026. Generated by
  gen.py --huff next to this file: the ZPAQLIZARD program plus huff0.py.

  Levels 30-49 code the token, literal and offset streams with Huff0, the
  Huffman coder of zstd 1.4 that Lizard 2.1 embeds: weights coded with FSE (or
  raw, 4 bits each), a canonical code, four bit streams read backwards, or a
  single repeated byte (RLE). The ZPAQL decodes each Huffman stream into M,
  behind the compressed data, and then runs the same LIZv1/fastLZ4 loop as
  ZPAQLIZARD. The four streams are parsed in one loop, so the Huff0 decoder is
  in the program once. The code is decoded bit by bit (like ZPAQDEFLATE), with
  the canonical tables in H (ph = 11).

  It also decodes levels 10-29, but those keep ZPAQLIZARD, so their blocks stay
  byte for byte what pre31-pre33 wrote.

  Verified with zpaqd 7.15 on 1,402 Lizard streams: 35 inputs x levels 10-49,
  plus hand-made RLE streams (also checked against Lizard's own decoder),
  covering FSE and raw weights, zero runs and low-probability symbols in the FSE
  header, and the end of the weight stream on either FSE state.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQLIZARDH_CUERPO[] = R"ZLZH(hcomp
halt
pcomp zpaqlizardh ;
(ZPAQLIZARDH: decodificador de Lizard 2.1, niveles 10-49 - fastLZ4 y LIZv1,
 con y sin Huffman -, en ZPAQL, para zpaq-std -ma:lizard. zpaq-std, 2026. Es
 ZPAQLIZARD mas Huff0, el Huffman de zstd 1.4 que Lizard usa en los niveles
 30-49: pesos con FSE o crudos, cuatro flujos leidos hacia atras. Los flujos
 Huffman se decodifican en M detras de la entrada. Entrada: tamano original, 4
 bytes LE, y el flujo de Lizard. M: la salida, el comprimido y los buffers.)
*c=a c++
d=a
a=r 31
a< 2 ifl
  a== 0 ifl
    a=c a< 4 ifl
      halt
    elsel
      a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 1 r=a 4 c=a a= 1 r=a 31
a=0 r=a 95
a= 1 a<<= 8 r=a 70
a= 2 a<<= 8 r=a 71
a= 33 a<<= 4 r=a 72
a= 34 a<<= 4 r=a 73
a= 35 a<<= 4 r=a 80
a= 36 a<<= 4 r=a 79
a= 37 a<<= 4 r=a 90
a= 75 a<<= 3 r=a 74
a= 107 a<<= 3 r=a 75
a= 139 a<<= 3 r=a 76
a= 147 a<<= 3 r=a 77
a= 155 a<<= 3 r=a 78
a=r 80 d=a a= 2 *d=a d++ a= 3 *d=a d++ a= 1 *d=a d++ a=0 *d=a
      halt
    endif
  elsel
    a=d a> 255 if a= 2 r=a 31 a=c a-- r=a 6 endif
    a=r 31 a== 1 if halt endif
  endif
endif
a== 2 ifnot halt endif
a=0 r=a 5
c=r 4 a=*c
a/= 10 a&= 1 a^= 1 r=a 7
a=r 4 a+= 1 r=a 4
do
c=r 4 a=*c
r=a 20
a=r 4 a+= 1 r=a 4
a=r 20 a== 128 ifl
a=r 4 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 21
a=r 4 a+= 3 r=a 4
a=r 21 a> 0 ifl
  do
    c=r 4 a=*c c=r 5 *c=a out a=r 4 a++ r=a 4 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
elsel
a=r 4 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 4 a+= 3 r=a 4
a=r 4 r=a 11 b=r 24 a+=b r=a 4
a=r 6 a++ r=a 34 a=0 r=a 32
do
a=r 32 b=r 80 a+=b d=a a=*d
  b=a a=r 20 a>>=b a&= 1
  a== 0 ifl
a=r 4 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 4 a+= 3 r=a 4
    a=r 4 r=a 47 b=r 24 a+=b r=a 4 r=a 48
  elsel
a=r 4 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 37
a=r 4 a+= 5 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 36
    a=r 4 a+= 6 r=a 35 b=r 36 a+=b r=a 4
    a=r 34 r=a 38 r=a 47 b=r 37 a+=b r=a 48 r=a 34
a=r 36 a== 1 ifl
  a=r 35 c=a a=*c r=a 46 a=r 37 r=a 45
  do
    a=r 46 c=r 38 *c=a a=c a++ r=a 38 a=r 45 a-- r=a 45
  a> 0 while
elsel
a=r 36 b=r 37 a==b ifl
  a=r 35 r=a 87 a=r 37 r=a 45
  do
    a=r 87 c=a a=*c c=r 38 *c=a a=c a++ r=a 38 a=r 87 a++ r=a 87 a=r 45 a-- r=a 45
  a> 0 while
elsel
  a=r 35 c=a a=*c r=a 46 a=r 35 a++ r=a 87
  a=r 46 a> 127 ifl
    a-= 127 r=a 64 a=0 r=a 66
    do
      a=r 66 a>>= 1 b=r 87 a+=b c=a a=*c r=a 69 a=r 66 a&= 1 a== 0 ifl
        a=r 69 a>>= 4
      elsel
        a=r 69 a&= 15
      endif
      r=a 69
a=r 66 b=r 95 a+=b d=a a=r 69 *d=a
      a=r 66 a++ r=a 66 b=r 64
    a<b while
    a=r 64 a++ a>>= 1 b=r 87 a+=b r=a 87
  elsel
    a=r 46 r=a 51 a=r 87 r=a 52
a=0 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 4 while
a=r 60 a+= 5 r=a 53
a=r 50 a+= 4 r=a 50
a= 1 b=r 53 a<<=b r=a 55 a++ r=a 54 a=r 53 a++ r=a 56
a=0 r=a 57 r=a 58
a=r 54 a> 1 ifl
do
  a=r 58 a> 0 ifl
    a=r 57 r=a 62
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 16 while
      a=r 60 b=a a= 255 a<<= 8 a+= 255 a==b ifl
        a=r 62 a+= 24 r=a 62
a=r 50 a+= 16 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
      a=r 60 a== 3 ifl
        a=r 62 a+= 3 r=a 62
a=r 50 a+= 2 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
    a=r 60 b=r 62 a+=b r=a 62
a=r 50 a+= 2 r=a 50
    a=r 57 b=r 62 a<b ifl
      do
        a= 1 r=a 61
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
        a=r 57 a++ r=a 57 b=r 62
      a<b while
    endif
  endif
  a=r 55 a<<= 1 a-- b=r 54 a-=b r=a 59
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
b=r 56 a<b while
  a=r 55 a-- b=a a=r 60 a&=b r=a 61 b=r 59
  a<b ifl
    a=r 56 a-- b=a a=r 50 a+=b r=a 50
  elsel
    a=r 55 a<<= 1 a-- b=a a=r 60 a&=b r=a 61 b=r 55
    a<b ifnot
      a=r 61 b=r 59 a-=b r=a 61
    endif
    a=r 56 b=a a=r 50 a+=b r=a 50
  endif
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
  a=r 57 a++ r=a 57
  a=r 61 a== 0 ifl
    a=r 54 a-- r=a 54
  elsel
    a-- b=a a=r 54 a-=b r=a 54
  endif
  a=r 61 a== 1 ifl a= 1 elsel a=0 endif r=a 58
  a=r 54 b=r 55 a<b ifl
    do
      a=r 56 a-- r=a 56 a=r 55 a>>= 1 r=a 55 b=a a=r 54
    a<b while
  endif
  a=r 54
a> 1 while
endif
a= 1 b=r 53 a<<=b r=a 81 a-- r=a 82
a=0 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a== 0 ifl
    a=r 66 r=a 69
a=r 82 b=r 76 a+=b d=a a=r 69 *d=a
    a=r 82 a-- r=a 82 a= 1 r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  elsel
    a-- r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=r 81 a>>= 1 r=a 83 a=r 81 a>>= 3 b=r 83 a+=b a+= 3 r=a 83
a=0 r=a 84 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a> 1 ifl
    a-- r=a 68
    do
      a=r 66 r=a 69
a=r 84 b=r 76 a+=b d=a a=r 69 *d=a
      do
        a=r 81 a-- r=a 69 a=r 84 b=r 83 a+=b b=r 69 a&=b r=a 84 b=r 82
      a>b while
      a=r 68 a-- r=a 68
    a> 0 while
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=0 r=a 66
do
a=r 66 b=r 76 a+=b d=a a=*d
  r=a 68
a=r 68 b=r 75 a+=b d=a a=*d
  r=a 67 a++ r=a 69
a=r 68 b=r 75 a+=b d=a a=r 69 *d=a
a=0 r=a 69 a=r 67 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 53 b=r 69 a-=b r=a 69
a=r 66 b=r 77 a+=b d=a a=r 69 *d=a
  b=a a=r 67 a<<=b b=r 81 a-=b r=a 69
a=r 66 b=r 78 a+=b d=a a=r 69 *d=a
  a=r 66 a++ r=a 66 b=r 81
a<b while
a=r 50 a+= 7 a>>= 3 r=a 69 b=r 52 a+=b r=a 46
a=r 51 b=r 69 a-=b r=a 69
a=r 69 r=a 92 a=r 46 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
a=0 r=a 85 a=r 53 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 85 a<<= 1 b=r 69 a+=b r=a 85
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 86 a=r 53 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 86 a<<= 1 b=r 69 a+=b r=a 86
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 64
do
a=r 85 b=r 76 a+=b d=a a=*d
  r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
a=r 85 b=r 77 a+=b d=a a=*d
  r=a 68
a=0 r=a 61 a=r 68 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 61 a<<= 1 b=r 69 a+=b r=a 61
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 85 b=r 78 a+=b d=a a=*d
  b=r 61 a+=b r=a 85
  a=r 42 a> 0 ifl
a=r 86 b=r 76 a+=b d=a a=*d
    r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
    a=r 64 a++ r=a 64
  endif
  a=r 42 a== 0 ifl
a=r 86 b=r 76 a+=b d=a a=*d
  r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
a=r 86 b=r 77 a+=b d=a a=*d
  r=a 68
a=0 r=a 61 a=r 68 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 61 a<<= 1 b=r 69 a+=b r=a 61
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 86 b=r 78 a+=b d=a a=*d
  b=r 61 a+=b r=a 86
  a=r 42 a> 0 ifl
a=r 85 b=r 76 a+=b d=a a=*d
    r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
    a=r 64 a++ r=a 64
  endif
  endif
a=r 42 a== 0 while
    a=r 87 b=r 51 a+=b r=a 87
  endif
  a=0 r=a 65 r=a 66
  do
a=r 66 b=r 95 a+=b d=a a=*d
    b=a a= 1 a<<=b a>>= 1 b=r 65 a+=b r=a 65
    a=r 66 a++ r=a 66 b=r 64
  a<b while
a=0 r=a 63 a=r 65 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 63 a++ r=a 63 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 63 a++ r=a 63
  a= 1 b=r 63 a<<=b b=r 65 a-=b r=a 46
a=0 r=a 69 a=r 46 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 69 a++ r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
  a=0 r=a 66 r=a 69
  do
a=r 66 b=r 73 a+=b d=a a=r 69 *d=a
a=r 66 b=r 71 a+=b d=a a=r 69 *d=a
a=r 66 b=r 72 a+=b d=a a=r 69 *d=a
    a=r 66 a++ r=a 66
  a< 16 while
  a=0 r=a 66
  do
a=r 66 b=r 95 a+=b d=a a=*d
    a> 0 ifl
      b=a a=r 63 a++ a-=b r=a 68
a=r 68 b=r 73 a+=b d=a a=*d
      a++ r=a 69
a=r 68 b=r 73 a+=b d=a a=r 69 *d=a
    endif
    a=r 66 a++ r=a 66 b=r 64
  a<b while
  a=r 63 r=a 68 a=0 r=a 65 r=a 62
  do
    a=r 63 b=r 68 a-=b b=a a=r 65 a>>=b r=a 69
a=r 68 b=r 71 a+=b d=a a=r 69 *d=a
a=r 68 b=r 72 a+=b d=a a=r 62 *d=a
    a=0 r=a 66
    do
a=r 66 b=r 95 a+=b d=a a=*d
      a> 0 ifl
        b=a a=r 63 a++ a-=b b=r 68 a==b ifl
a=r 62 b=r 70 a+=b d=a a=r 66 *d=a
          a=r 62 a++ r=a 62
        endif
      endif
      a=r 66 a++ r=a 66 b=r 64
    a<b while
a=r 68 b=r 73 a+=b d=a a=*d
    r=a 69 a=r 63 b=r 68 a-=b b=a a=r 69 a<<=b b=r 65 a+=b r=a 65
    a=r 68 a-- r=a 68
  a> 0 while
  a=r 87 a+= 6 r=a 69 a=0 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 1 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 1 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 3 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 2 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 5 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 3 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 35 b=r 36 a+=b r=a 69 a= 4 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 37 a+= 3 a>>= 2 r=a 88
  a=0 r=a 89
  do
a=r 89 b=r 90 a+=b d=a a=*d
    r=a 46 a=r 89 a++ r=a 66
a=r 66 b=r 90 a+=b d=a a=*d
    b=r 46 a-=b r=a 67
a=r 67 r=a 92 a=r 46 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
    a=r 88 r=a 45 a=r 89 a== 3 ifl
      a=r 88 a<<= 1 b=r 88 a+=b b=a a=r 37 a-=b r=a 45
    endif
    a=r 45 a> 0 ifl
    do
      a=0 r=a 43 r=a 44
      do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
        r=a 46 a=r 43 a<<= 1 b=r 46 a+=b r=a 43 a=r 44 a++ r=a 44
        b=r 71 a+=b d=a a=*d b=a a=r 43
      a<b while
      a-=b r=a 46 a=r 44 b=r 72 a+=b d=a a=*d b=r 46 a+=b b=r 70 a+=b d=a a=*d
      c=r 38 *c=a a=c a++ r=a 38
      a=r 45 a-- r=a 45
    a> 0 while
    endif
    a=r 89 a++ r=a 89
  a< 4 while
endif
endif
  endif
  a=r 32 a<<= 1 b=r 79 a+=b d=a a=r 47 *d=a d++ a=r 48 *d=a
  a=r 32 a++ r=a 32
a< 4 while
a=r 79 d=a a=*d r=a 12 d++ a=*d r=a 13 d++ a=*d r=a 14 d++ a=*d r=a 15
d++ a=*d r=a 16 d++ a=*d r=a 17 d++ a=*d r=a 18 d++ a=*d r=a 19
  a=0 r=a 23
  a=r 7 a== 0 ifl
    a=r 16 b=r 17 a<b ifl
    do
c=r 16 a=*c
r=a 20
a=r 16 a+= 1 r=a 16
      a=r 20 a&= 15 r=a 21 a== 15 ifl
c=r 18 a=*c
r=a 24
a> 253 ifl
  a== 254 ifl
a=r 18 a+= 2 c=a a=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 2 r=a 18
  elsel
a=r 18 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 3 r=a 18
  endif
endif
a=r 24 a+= 15 r=a 21
a=r 18 a+= 1 r=a 18
      endif
a=r 21 a> 0 ifl
  do
    c=r 18 a=*c c=r 5 *c=a out a=r 18 a++ r=a 18 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
a=r 18 a+= 1 c=a a=*c a<<= 8 c-- a+=*c
r=a 22
a=r 18 a+= 2 r=a 18
      a=r 20 a>>= 4 r=a 21 a== 15 ifl
c=r 18 a=*c
r=a 24
a> 253 ifl
  a== 254 ifl
a=r 18 a+= 2 c=a a=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 2 r=a 18
  elsel
a=r 18 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 3 r=a 18
  endif
endif
a=r 24 a+= 15 r=a 21
a=r 18 a+= 1 r=a 18
      endif
      a=r 21 a+= 4 r=a 21
a=r 5 b=r 22 a-=b r=a 24
a=r 21 a> 0 ifl
  do
    c=r 24 a=*c c=r 5 *c=a out a=r 24 a++ r=a 24 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
      a=r 16 b=r 17
    a<b while
    endif
  elsel
    a=r 16 b=r 17 a<b ifl
    do
c=r 16 a=*c
r=a 20
a=r 16 a+= 1 r=a 16
      a=r 20 a> 31 ifl
        a&= 7 r=a 21 a== 7 ifl
c=r 18 a=*c
r=a 24
a=r 18 a+= 1 r=a 18
a=r 24 a> 253 ifl
  a== 254 ifl
a=r 18 a+= 1 c=a a=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 2 r=a 18
  elsel
a=r 18 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 3 r=a 18
  endif
endif
a=r 24 a+= 7 r=a 21
        endif
a=r 21 a> 0 ifl
  do
    c=r 18 a=*c c=r 5 *c=a out a=r 18 a++ r=a 18 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
        a=r 13 b=r 12 a-=b a> 1 ifl
          a=r 20 a>>= 7 a== 0 ifl
a=r 12 a+= 1 c=a a=*c a<<= 8 c-- a+=*c
r=a 23
a=r 12 a+= 2 r=a 12
          endif
        endif
        a=r 20 a>>= 3 a&= 15 r=a 21 a== 15 ifl
c=r 18 a=*c
r=a 24
a> 253 ifl
  a== 254 ifl
a=r 18 a+= 2 c=a a=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 2 r=a 18
  elsel
a=r 18 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 3 r=a 18
  endif
endif
a=r 24 a+= 15 r=a 21
a=r 18 a+= 1 r=a 18
        endif
      elsel
        a=r 20 a< 31 ifl
          a+= 16 r=a 21
a=r 14 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 23
a=r 14 a+= 3 r=a 14
        elsel
c=r 18 a=*c
r=a 24
a> 253 ifl
  a== 254 ifl
a=r 18 a+= 2 c=a a=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 2 r=a 18
  elsel
a=r 18 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 24
a=r 18 a+= 3 r=a 18
  endif
endif
a=r 24 a+= 47 r=a 21
a=r 18 a+= 1 r=a 18
a=r 14 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 23
a=r 14 a+= 3 r=a 14
        endif
      endif
a=r 5 b=r 23 a-=b r=a 24
a=r 21 a> 0 ifl
  do
    c=r 24 a=*c c=r 5 *c=a out a=r 24 a++ r=a 24 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
      a=r 16 b=r 17
    a<b while
    endif
  endif
  a=r 19 b=r 18 a-=b r=a 21
a=r 21 a> 0 ifl
  do
    c=r 18 a=*c c=r 5 *c=a out a=r 18 a++ r=a 18 a=r 5 a++ r=a 5
    a=r 21 a-- r=a 21
  a> 0 while
endif
endif
a=r 4 b=r 6 a<b if a= 1 else a=0 endif
a> 0 while
a= 3 r=a 31
halt
end
)ZLZH";
