# Generador de ZPAQBZIP2: flujos de bzip2 (libbzip2 1.0.8, niveles 1-9) en ZPAQL.
# ZPAQL no tiene subrutinas: la lectura de bits, el Huffman y las tablas son macros
# expandidas en linea. Mismo algoritmo que la referencia en Python con la que se probo.
#   python3 gen.py salida.txt
#
# Toda la entrada se guarda en M (el flujo no tiene limites de byte entre bloques) y se
# decodifica al final. La salida sale con out, no se guarda. H (ph = 20):
#   0 selectores (hasta 32768)   32768 seqToUnseq   33024 MTF (yy)   33280 MTF de selectores
#   33536 largos por tabla (6 x 264)   35328 cuentas por largo (6 x 24)
#   35584 simbolos ordenados por tabla (6 x 264)   37376 frecuencias   37888 cftab
#   40960 tt: el bloque, byte abajo y puntero arriba (el modo rapido de libbzip2)
# Registros:
#   r1 n (bytes de entrada), r2 pos (bit), r3 valor leido, r4 contador de BITS, r5 hay
#   stream, r6 hay bloque, r7 primer byte del magic, r8 decodificando, r9 temporal de BIT
#   r10 origPtr, r11 nInUse, r12 alphaSize, r13 nGroups, r14 nSelectors, r15 i, r16 j,
#   r17 t, r18 curr, r19 inUse16, r20 EOB, r21 grupo, r22 quedan del grupo, r23 tabla,
#   r24 run, r25 peso de RUNA/RUNB, r26 nblock, r27 simbolo, r28 codigo, r29 first,
#   r30 indice, r31 largo, r32 cuenta, r33 tPos, r34 ultimo byte, r35 repeticiones,
#   r36 byte, r37 r38 r39 temporales, r40 = 0, r41..r49 bases en H, r50 = 264,
#   r51 temporal, r52 r53 r54 bases de la tabla actual, r55 suma, r56 temporal
out = []
def e(s): out.append(s)
SEL, SEQ, YY, PL, LEN, CNT, SYM, FT, CF, TT = 40, 41, 42, 43, 44, 45, 46, 47, 48, 49

def HGET(base, idx):          # a = H[r base + r idx]
    e(f"a=r {idx} b=r {base} a+=b d=a a=*d")
def HSET(base, idx, val):     # H[r base + r idx] = r val
    e(f"a=r {idx} b=r {base} a+=b d=a a=r {val} *d=a")
def BIT():                    # a = siguiente bit (MSB primero); pasado el final, 0
    e("a=r 2 a>>= 3 b=r 1 a<b ifl")
    e("  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1")
    e("elsel")
    e("  a=0")
    e("endif")
    e("r=a 9 a=r 2 a++ r=a 2 a=r 9")
def BITS(k, dst):             # r dst = k bits
    e(f"a=0 r=a {dst} a= {k} r=a 4")
    e("do")
    BIT()
    e(f"  b=a a=r {dst} a<<= 1 a+=b r=a {dst}")
    e("  a=r 4 a-- r=a 4")
    e("a> 0 while")
def SKIP(k):
    e(f"a=r 2 a+= {k} r=a 2")

e("hcomp")
e("halt")
e("pcomp zpaqbzip2 ;")
e("""(ZPAQBZIP2: decodificador de bzip2 en ZPAQL, para zpaq-std -ma:bzip2. zpaq-std,
 2026. Guarda el flujo entero en M y lo decodifica al final: Huffman canonico bit
 a bit, MTF, RUNA/RUNB, BWT inverso con tt en H y el RLE final. La salida sale con
 out. Admite varios bloques y varios streams seguidos.)""")
e("a> 255 ifl")
e("  a=c r=a 1 a=0 c=a")
# constantes
e("  a=0 r=a 40 a= 1 a<<= 15 r=a 41")
for reg, v in [(42, 129), (43, 130), (44, 131), (45, 138), (46, 139), (47, 146), (48, 148), (49, 160)]:
    e(f"  a= {v} a<<= 8 r=a {reg}")
e("  a= 132 a+= 132 r=a 50")
e("  a=0 r=a 2 a= 1 r=a 5")
e("  do")                                             # un stream por vuelta
e("  a=r 2 a>>= 3 a+= 4 b=r 1 a>b ifl a=0 r=a 5 endif")
e("  a=r 5 a> 0 ifl")
BITS(24, 3)
e("    a= 66 a<<= 8 a+= 90 a<<= 8 a+= 104 b=a a=r 3 a==b ifnotl a=0 r=a 5 endif")   # "BZh"
e("  endif")
e("  a=r 5 a> 0 ifl")
SKIP(8)                                               # el nivel: no hace falta
e("    a= 1 r=a 6")
e("    do")                                           # un bloque por vuelta
BITS(8, 7); SKIP(72)                                  # magic (0x31 bloque, 0x17 fin) y CRC
e("      a=r 7 a== 49 ifnotl")
e("        a=r 2 a+= 7 a>>= 3 a<<= 3 r=a 2 a=0 r=a 6")    # fin de stream: relleno a byte
e("      elsel")
SKIP(1)                                               # aleatorizado: libbzip2 1.0 nunca
BITS(24, 10); BITS(16, 19)
# mapa de bytes usados
e("        a=0 r=a 11 r=a 15")
e("        do")
e("          a=r 15 b=a a= 15 a-=b b=a a=r 19 a>>=b a&= 1")
e("          a> 0 ifl")
e("            a=0 r=a 16")
e("            do")
BIT()
e("              a> 0 ifl")
e("                a=r 15 a<<= 4 b=r 16 a+=b r=a 39"); HSET(SEQ, 11, 39)
e("                a=r 11 a++ r=a 11")
e("              endif")
e("              a=r 16 a++ r=a 16")
e("            a< 16 while")
e("          endif")
e("          a=r 15 a++ r=a 15")
e("        a< 16 while")
e("        a=r 11 a++ r=a 20 a++ r=a 12")
BITS(3, 13); BITS(15, 14)
# selectores, en unario y con MTF
e("        a=0 r=a 15")
e("        do")
e("          a=0 r=a 16")
e("          do")
BIT()
e("            r=a 56 a> 0 ifl a=r 16 a++ r=a 16 endif a=r 56")
e("          a> 0 while")
HSET(SEL, 15, 16)
e("          a=r 15 a++ r=a 15 b=r 14")
e("        a<b while")
e("        a=0 r=a 15")
e("        do")
HSET(PL, 15, 15)
e("          a=r 15 a++ r=a 15 b=r 13")
e("        a<b while")
e("        a=0 r=a 15")
e("        do")
HGET(SEL, 15); e("          r=a 37"); HGET(PL, 37); e("          r=a 39")
e("          a=r 37 a> 0 ifl")
e("            do")
e("              a=r 37 a-- r=a 38"); HGET(PL, 38); e("              r=a 56"); HSET(PL, 37, 56)
e("              a=r 38 r=a 37")
e("            a> 0 while")
e("          endif")
HSET(PL, 40, 39); HSET(SEL, 15, 39)
e("          a=r 15 a++ r=a 15 b=r 14")
e("        a<b while")
# tablas de codigos: largos con deltas, y la tabla canonica de cada una
e("        a=0 r=a 17")
e("        do")
e("          a=r 17 b=r 50 a*=b b=r 44 a+=b r=a 52")
e("          a=r 17 a*= 24 b=r 45 a+=b r=a 53")
e("          a=r 17 b=r 50 a*=b b=r 46 a+=b r=a 54")
BITS(5, 18)
e("          a=0 r=a 15")
e("          do")
e("            do")
BIT()
e("              r=a 56 a> 0 ifl")
BIT()
e("                a> 0 ifl a=r 18 a-- r=a 18 elsel a=r 18 a++ r=a 18 endif")
e("              endif")
e("              a=r 56")
e("            a> 0 while")
HSET(52, 15, 18)
e("            a=r 15 a++ r=a 15 b=r 12")
e("          a<b while")
e("          a=0 r=a 15 r=a 56")
e("          do")
HSET(53, 15, 56)
e("            a=r 15 a++ r=a 15")
e("          a< 24 while")
e("          a=0 r=a 30 a= 1 r=a 31")                 # r30 = simbolos ya puestos, r31 = largo
e("          do")
e("            a=0 r=a 15")
e("            do")
HGET(52, 15); e("              b=r 31 a==b ifl")
HSET(54, 30, 15); e("                a=r 30 a++ r=a 30")
HGET(53, 31); e("                a++ r=a 56"); HSET(53, 31, 56)
e("              endif")
e("              a=r 15 a++ r=a 15 b=r 12")
e("            a<b while")
e("            a=r 31 a++ r=a 31")
e("          a< 21 while")
e("          a=r 17 a++ r=a 17 b=r 13")
e("        a<b while")
# Huffman + MTF + RUNA/RUNB -> tt
e("        a=0 r=a 15")
e("        do")
HSET(YY, 15, 15); HSET(FT, 15, 40)
e("          a=r 15 a++ r=a 15")
e("        a> 255 until")
e("        a=0 r=a 26 r=a 24 r=a 25 r=a 22 r=a 21 a= 1 r=a 8")
e("        do")
e("          a=r 22 a== 0 ifl")
e("            a= 50 r=a 22"); HGET(SEL, 21); e("            r=a 23 a=r 21 a++ r=a 21")
e("            a=r 23 a*= 24 b=r 45 a+=b r=a 53")
e("            a=r 23 b=r 50 a*=b b=r 46 a+=b r=a 54")
e("          endif")
e("          a=r 22 a-- r=a 22")
e("          a=0 r=a 28 r=a 29 r=a 30 a= 1 r=a 31")
e("          do")
BIT()
e("            b=a a=r 28 a|=b r=a 28"); HGET(53, 31); e("            r=a 32")
e("            a=r 29 b=r 32 a+=b b=a a=r 28 a<b ifl")
e("              a=r 28 b=r 29 a-=b b=r 30 a+=b b=r 54 a+=b d=a a=*d r=a 27 a=0")
e("            elsel")
e("              a=r 30 b=r 32 a+=b r=a 30 a=r 29 b=r 32 a+=b a<<= 1 r=a 29")
e("              a=r 28 a<<= 1 r=a 28 a=r 31 a++ r=a 31")
e("              a> 21 ifl a=r 20 r=a 27 a=0 elsel a= 1 endif")   # flujo roto: no colgarse
e("            endif")
e("          a> 0 while")
e("          a=r 27 a< 2 ifl")
e("            a=r 27 a++ b=r 25 a<<=b b=r 24 a+=b r=a 24 a=r 25 a++ r=a 25")
e("          elsel")
e("            a=r 24 a> 0 ifl")
HGET(YY, 40); e("              b=r 41 a+=b d=a a=*d r=a 39")
HGET(FT, 39); e("              b=r 24 a+=b r=a 56"); HSET(FT, 39, 56)
e("              do")
HSET(TT, 26, 39); e("                a=r 26 a++ r=a 26 a=r 24 a-- r=a 24")
e("              a> 0 while")
e("              a=0 r=a 25")
e("            endif")
e("            a=r 27 b=r 20 a==b ifl")
e("              a=0 r=a 8")
e("            elsel")
e("              a=r 27 a-- r=a 37"); HGET(YY, 37); e("              r=a 39")
e("              a=r 37 a> 0 ifl")
e("                do")
e("                  a=r 37 a-- r=a 38"); HGET(YY, 38); e("                  r=a 56"); HSET(YY, 37, 56)
e("                  a=r 38 r=a 37")
e("                a> 0 while")
e("              endif")
HSET(YY, 40, 39)
e("              a=r 39 b=r 41 a+=b d=a a=*d r=a 39"); HGET(FT, 39); e("              a++ r=a 56"); HSET(FT, 39, 56)
HSET(TT, 26, 39); e("              a=r 26 a++ r=a 26")
e("            endif")
e("          endif")
e("          a=r 8")
e("        a> 0 while")
# BWT inverso
e("        a=0 r=a 15 r=a 55")
e("        do")
HSET(CF, 15, 55); HGET(FT, 15); e("          b=r 55 a+=b r=a 55")
e("          a=r 15 a++ r=a 15")
e("        a> 255 until")
e("        a=0 r=a 15")
e("        a=r 26 a> 0 ifl")
e("        do")
HGET(TT, 15); e("          a&= 255 r=a 39"); HGET(CF, 39); e("          r=a 37 a++ r=a 56"); HSET(CF, 39, 56)
HGET(TT, 37); e("          r=a 38 a=r 15 a<<= 8 b=r 38 a|=b r=a 38"); HSET(TT, 37, 38)
e("          a=r 15 a++ r=a 15 b=r 26")
e("        a<b while")
e("        endif")
HGET(TT, 10); e("        a>>= 8 r=a 33")
e("        a= 255 a++ r=a 34 a=0 r=a 35 a=r 26 r=a 15")
e("        a> 0 ifl")
e("        do")
HGET(TT, 33); e("          r=a 33 a&= 255 r=a 36 a=r 33 a>>= 8 r=a 33")
e("          a=r 35 a== 4 ifl")
e("            a=r 36 a> 0 ifl")
e("              do")
e("                a=r 34 out a=r 36 a-- r=a 36")
e("              a> 0 while")
e("            endif")
e("            a=0 r=a 35")
e("          elsel")
e("            a=r 36 out b=r 34 a==b ifl")
e("              a=r 35 a++ r=a 35")
e("            elsel")
e("              a=r 36 r=a 34 a= 1 r=a 35")
e("            endif")
e("          endif")
e("          a=r 15 a-- r=a 15")
e("        a> 0 while")
e("        endif")
e("      endif")
e("      a=r 6")
e("    a> 0 while")
e("  endif")
e("  a=r 5")
e("  a> 0 while")
e("  a=0 c=a")
e("elsel")
e("  *c=a c++")
e("endif")
e("halt")
e("end")
import sys
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
