/*
  ZPAQBZIP2: a bzip2 decoder written in ZPAQL, for zpaq-std -ma:bzip2 (libbzip2
  1.0.8, levels 1-9). zpaq-std, 2026. Generated by gen.py next to this file
  (ZPAQL has no subroutines: bit reading, Huffman decoding and table building
  are macros expanded in place).

  bzip2 streams are not byte-aligned between blocks, so the whole stream is kept
  in M and decoded at the end of the segment; the output goes out with OUT and
  is not stored. Per block: the byte map, the selectors (unary + MTF), the code
  lengths (deltas), canonical Huffman decoded one bit at a time from per-length
  counts (Mark Adler's puff method, as in ZPAQDEFLATE), MTF and RUNA/RUNB, the
  inverse BWT with a 32-bit tt[] in H (byte in the low 8 bits, pointer above:
  libbzip2's fast mode), and the final run-length step. Several blocks and
  several concatenated streams are handled. Randomised blocks (bzip2 0.9.0,
  never written by libbzip2 1.0) are not. CRCs are skipped: zpaq checks the
  SHA-1 of the output.

  H needs ph = 20 (tt for a 900 KB block + tables); M holds the compressed
  stream.

  Verified with zpaqd 7.15 on 198 streams (22 inputs x levels 1-9), on two
  concatenated streams and on 12 MB at levels 1, 5 and 9.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQBZIP2_CUERPO[] = R"ZBZ2(hcomp
halt
pcomp zpaqbzip2 ;
(ZPAQBZIP2: decodificador de bzip2 en ZPAQL, para zpaq-std -ma:bzip2. zpaq-std,
 2026. Guarda el flujo entero en M y lo decodifica al final: Huffman canonico bit
 a bit, MTF, RUNA/RUNB, BWT inverso con tt en H y el RLE final. La salida sale con
 out. Admite varios bloques y varios streams seguidos.)
a> 255 ifl
  a=c r=a 1 a=0 c=a
  a=0 r=a 40 a= 1 a<<= 15 r=a 41
  a= 129 a<<= 8 r=a 42
  a= 130 a<<= 8 r=a 43
  a= 131 a<<= 8 r=a 44
  a= 138 a<<= 8 r=a 45
  a= 139 a<<= 8 r=a 46
  a= 146 a<<= 8 r=a 47
  a= 148 a<<= 8 r=a 48
  a= 160 a<<= 8 r=a 49
  a= 132 a+= 132 r=a 50
  a=0 r=a 2 a= 1 r=a 5
  do
  a=r 2 a>>= 3 a+= 4 b=r 1 a>b ifl a=0 r=a 5 endif
  a=r 5 a> 0 ifl
a=0 r=a 3 a= 24 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 3 a<<= 1 a+=b r=a 3
  a=r 4 a-- r=a 4
a> 0 while
    a= 66 a<<= 8 a+= 90 a<<= 8 a+= 104 b=a a=r 3 a==b ifnotl a=0 r=a 5 endif
  endif
  a=r 5 a> 0 ifl
a=r 2 a+= 8 r=a 2
    a= 1 r=a 6
    do
a=0 r=a 7 a= 8 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 7 a<<= 1 a+=b r=a 7
  a=r 4 a-- r=a 4
a> 0 while
a=r 2 a+= 72 r=a 2
      a=r 7 a== 49 ifnotl
        a=r 2 a+= 7 a>>= 3 a<<= 3 r=a 2 a=0 r=a 6
      elsel
a=r 2 a+= 1 r=a 2
a=0 r=a 10 a= 24 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 10 a<<= 1 a+=b r=a 10
  a=r 4 a-- r=a 4
a> 0 while
a=0 r=a 19 a= 16 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 19 a<<= 1 a+=b r=a 19
  a=r 4 a-- r=a 4
a> 0 while
        a=0 r=a 11 r=a 15
        do
          a=r 15 b=a a= 15 a-=b b=a a=r 19 a>>=b a&= 1
          a> 0 ifl
            a=0 r=a 16
            do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
              a> 0 ifl
                a=r 15 a<<= 4 b=r 16 a+=b r=a 39
a=r 11 b=r 41 a+=b d=a a=r 39 *d=a
                a=r 11 a++ r=a 11
              endif
              a=r 16 a++ r=a 16
            a< 16 while
          endif
          a=r 15 a++ r=a 15
        a< 16 while
        a=r 11 a++ r=a 20 a++ r=a 12
a=0 r=a 13 a= 3 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 13 a<<= 1 a+=b r=a 13
  a=r 4 a-- r=a 4
a> 0 while
a=0 r=a 14 a= 15 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 14 a<<= 1 a+=b r=a 14
  a=r 4 a-- r=a 4
a> 0 while
        a=0 r=a 15
        do
          a=0 r=a 16
          do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
            r=a 56 a> 0 ifl a=r 16 a++ r=a 16 endif a=r 56
          a> 0 while
a=r 15 b=r 40 a+=b d=a a=r 16 *d=a
          a=r 15 a++ r=a 15 b=r 14
        a<b while
        a=0 r=a 15
        do
a=r 15 b=r 43 a+=b d=a a=r 15 *d=a
          a=r 15 a++ r=a 15 b=r 13
        a<b while
        a=0 r=a 15
        do
a=r 15 b=r 40 a+=b d=a a=*d
          r=a 37
a=r 37 b=r 43 a+=b d=a a=*d
          r=a 39
          a=r 37 a> 0 ifl
            do
              a=r 37 a-- r=a 38
a=r 38 b=r 43 a+=b d=a a=*d
              r=a 56
a=r 37 b=r 43 a+=b d=a a=r 56 *d=a
              a=r 38 r=a 37
            a> 0 while
          endif
a=r 40 b=r 43 a+=b d=a a=r 39 *d=a
a=r 15 b=r 40 a+=b d=a a=r 39 *d=a
          a=r 15 a++ r=a 15 b=r 14
        a<b while
        a=0 r=a 17
        do
          a=r 17 b=r 50 a*=b b=r 44 a+=b r=a 52
          a=r 17 a*= 24 b=r 45 a+=b r=a 53
          a=r 17 b=r 50 a*=b b=r 46 a+=b r=a 54
a=0 r=a 18 a= 5 r=a 4
do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
  b=a a=r 18 a<<= 1 a+=b r=a 18
  a=r 4 a-- r=a 4
a> 0 while
          a=0 r=a 15
          do
            do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
              r=a 56 a> 0 ifl
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
                a> 0 ifl a=r 18 a-- r=a 18 elsel a=r 18 a++ r=a 18 endif
              endif
              a=r 56
            a> 0 while
a=r 15 b=r 52 a+=b d=a a=r 18 *d=a
            a=r 15 a++ r=a 15 b=r 12
          a<b while
          a=0 r=a 15 r=a 56
          do
a=r 15 b=r 53 a+=b d=a a=r 56 *d=a
            a=r 15 a++ r=a 15
          a< 24 while
          a=0 r=a 30 a= 1 r=a 31
          do
            a=0 r=a 15
            do
a=r 15 b=r 52 a+=b d=a a=*d
              b=r 31 a==b ifl
a=r 30 b=r 54 a+=b d=a a=r 15 *d=a
                a=r 30 a++ r=a 30
a=r 31 b=r 53 a+=b d=a a=*d
                a++ r=a 56
a=r 31 b=r 53 a+=b d=a a=r 56 *d=a
              endif
              a=r 15 a++ r=a 15 b=r 12
            a<b while
            a=r 31 a++ r=a 31
          a< 21 while
          a=r 17 a++ r=a 17 b=r 13
        a<b while
        a=0 r=a 15
        do
a=r 15 b=r 42 a+=b d=a a=r 15 *d=a
a=r 15 b=r 47 a+=b d=a a=r 40 *d=a
          a=r 15 a++ r=a 15
        a> 255 until
        a=0 r=a 26 r=a 24 r=a 25 r=a 22 r=a 21 a= 1 r=a 8
        do
          a=r 22 a== 0 ifl
            a= 50 r=a 22
a=r 21 b=r 40 a+=b d=a a=*d
            r=a 23 a=r 21 a++ r=a 21
            a=r 23 a*= 24 b=r 45 a+=b r=a 53
            a=r 23 b=r 50 a*=b b=r 46 a+=b r=a 54
          endif
          a=r 22 a-- r=a 22
          a=0 r=a 28 r=a 29 r=a 30 a= 1 r=a 31
          do
a=r 2 a>>= 3 b=r 1 a<b ifl
  c=a a=r 2 a&= 7 b=a a= 7 a-=b b=a a=*c a>>=b a&= 1
elsel
  a=0
endif
r=a 9 a=r 2 a++ r=a 2 a=r 9
            b=a a=r 28 a|=b r=a 28
a=r 31 b=r 53 a+=b d=a a=*d
            r=a 32
            a=r 29 b=r 32 a+=b b=a a=r 28 a<b ifl
              a=r 28 b=r 29 a-=b b=r 30 a+=b b=r 54 a+=b d=a a=*d r=a 27 a=0
            elsel
              a=r 30 b=r 32 a+=b r=a 30 a=r 29 b=r 32 a+=b a<<= 1 r=a 29
              a=r 28 a<<= 1 r=a 28 a=r 31 a++ r=a 31
              a> 21 ifl a=r 20 r=a 27 a=0 elsel a= 1 endif
            endif
          a> 0 while
          a=r 27 a< 2 ifl
            a=r 27 a++ b=r 25 a<<=b b=r 24 a+=b r=a 24 a=r 25 a++ r=a 25
          elsel
            a=r 24 a> 0 ifl
a=r 40 b=r 42 a+=b d=a a=*d
              b=r 41 a+=b d=a a=*d r=a 39
a=r 39 b=r 47 a+=b d=a a=*d
              b=r 24 a+=b r=a 56
a=r 39 b=r 47 a+=b d=a a=r 56 *d=a
              do
a=r 26 b=r 49 a+=b d=a a=r 39 *d=a
                a=r 26 a++ r=a 26 a=r 24 a-- r=a 24
              a> 0 while
              a=0 r=a 25
            endif
            a=r 27 b=r 20 a==b ifl
              a=0 r=a 8
            elsel
              a=r 27 a-- r=a 37
a=r 37 b=r 42 a+=b d=a a=*d
              r=a 39
              a=r 37 a> 0 ifl
                do
                  a=r 37 a-- r=a 38
a=r 38 b=r 42 a+=b d=a a=*d
                  r=a 56
a=r 37 b=r 42 a+=b d=a a=r 56 *d=a
                  a=r 38 r=a 37
                a> 0 while
              endif
a=r 40 b=r 42 a+=b d=a a=r 39 *d=a
              a=r 39 b=r 41 a+=b d=a a=*d r=a 39
a=r 39 b=r 47 a+=b d=a a=*d
              a++ r=a 56
a=r 39 b=r 47 a+=b d=a a=r 56 *d=a
a=r 26 b=r 49 a+=b d=a a=r 39 *d=a
              a=r 26 a++ r=a 26
            endif
          endif
          a=r 8
        a> 0 while
        a=0 r=a 15 r=a 55
        do
a=r 15 b=r 48 a+=b d=a a=r 55 *d=a
a=r 15 b=r 47 a+=b d=a a=*d
          b=r 55 a+=b r=a 55
          a=r 15 a++ r=a 15
        a> 255 until
        a=0 r=a 15
        a=r 26 a> 0 ifl
        do
a=r 15 b=r 49 a+=b d=a a=*d
          a&= 255 r=a 39
a=r 39 b=r 48 a+=b d=a a=*d
          r=a 37 a++ r=a 56
a=r 39 b=r 48 a+=b d=a a=r 56 *d=a
a=r 37 b=r 49 a+=b d=a a=*d
          r=a 38 a=r 15 a<<= 8 b=r 38 a|=b r=a 38
a=r 37 b=r 49 a+=b d=a a=r 38 *d=a
          a=r 15 a++ r=a 15 b=r 26
        a<b while
        endif
a=r 10 b=r 49 a+=b d=a a=*d
        a>>= 8 r=a 33
        a= 255 a++ r=a 34 a=0 r=a 35 a=r 26 r=a 15
        a> 0 ifl
        do
a=r 33 b=r 49 a+=b d=a a=*d
          r=a 33 a&= 255 r=a 36 a=r 33 a>>= 8 r=a 33
          a=r 35 a== 4 ifl
            a=r 36 a> 0 ifl
              do
                a=r 34 out a=r 36 a-- r=a 36
              a> 0 while
            endif
            a=0 r=a 35
          elsel
            a=r 36 out b=r 34 a==b ifl
              a=r 35 a++ r=a 35
            elsel
              a=r 36 r=a 34 a= 1 r=a 35
            endif
          endif
          a=r 15 a-- r=a 15
        a> 0 while
        endif
      endif
      a=r 6
    a> 0 while
  endif
  a=r 5
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZBZ2";
