/*
  ZPAQPPMD: a PPMd var.H decoder written in ZPAQL (Ppmd7 from the 7-Zip SDK, with
  7z's range coder), for zpaq-std -ma:ppmd (orders 2-32, 64 MB model memory).
  zpaq-std, 2026, written from Ppmd7.c and Ppmd7Dec.c. Generated by gen.py next
  to this file (ZPAQL has no subroutines: everything is a macro expanded in
  place); ref.py is the Python reference decoder it was checked against, which
  matches the SDK on every test stream.

  A block is [order u8][memory u32][original size u32] and the 7z PPMd stream
  (the stream itself has neither). PPMd's model lives in a heap and depends on
  its allocator: it compares heap offsets, glues free blocks and restarts when
  the memory runs out. So the heap is reproduced byte for byte in M, at offset
  0, with the SDK's 12-byte units, free lists, GlueFreeBlocks and
  RestartModel; the input is moved above it. Each symbol is done in phases
  (decode, then Rescale, then NextContext or UpdateModel, with RestartModel
  left as a flag for the next symbol) so every heavy function appears once.

  M: the model memory (64 MB) plus the stream, so pm = 27. H needs ph = 14
  (BinSumm, the SEE contexts, the free lists and Ppmd7_Construct's tables).

  Verified with zpaqd 7.15 on 213 PPMd streams: 49 corpus files of every type at
  orders 2, 6, 16 and 32 with 64 MB, 16 MB blocks (order 32 restarts the model
  6 times and glues free blocks 12,107 times), and small memories from 4 KB to
  4 MB to force restarts and glueing on small inputs.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQPPMD_CUERPO[] = R"ZPPM(hcomp
halt
pcomp zpaqppmd ;
(ZPAQPPMD: decodificador de PPMd var.H - Ppmd7 del 7-Zip SDK con el codificador de
 rango de 7z - en ZPAQL, para zpaq-std -ma:ppmd. zpaq-std, 2026. Entrada: orden, memoria,
 tamano original y el flujo; el monticulo del modelo se reproduce byte a byte en M.)
a> 255 ifl
  a=c r=a 1
a= 0
  r=a 200
a= 32
a<<= 8
  r=a 201
a= 36
a<<= 8 a+= 184
  r=a 202
a= 36
a<<= 8 a+= 192
  r=a 203
a= 36
a<<= 8 a+= 232
  r=a 204
a= 37
a<<= 8 a+= 16
  r=a 205
a= 37
a<<= 8 a+= 144
  r=a 206
a= 38
a<<= 8 a+= 144
  r=a 207
a= 39
a<<= 8 a+= 144
  r=a 208
a= 39
a<<= 8 a+= 160
  r=a 209
a= 40
a<<= 8 a+= 160
  r=a 210
a= 40
a<<= 8 a+= 224
  r=a 211
  a= 1 a<<= 24 r=a 24 a= 128 a<<= 24 r=a 25
  a=0 c=a a=*c r=a 8
  a= 4 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 7
  a= 8 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 5
  a=r 1 a-= 9 r=a 150 b=r 7 a+=b r=a 28 a=r 7 r=a 2
  a=r 150 a> 0 ifl do
    a=r 150 a-- r=a 150 a+= 9 b=a a=r 150 b=r 7 a+=b c=a
    a=r 150 a+= 9 b=a *c=*b a=r 150 a> 0 while endif
  a=r 1 b=r 7 a>b ifl a=b endif r=a 150 a> 0 ifl a=0 c=a do a=0 *c=a c++ a=c b=r 150 a<b while endif
  a=0 r=a 151 r=a 152
  do
    a=r 151 a> 11 ifl a= 4 elsel a=r 151 a>>= 2 a++ endif r=a 153
    do
a=r 152 b=r 205 a+=b d=a a=r 151 *d=a
      a=r 152 a++ r=a 152 a=r 153 a-- r=a 153 a> 0 while
a=r 151 b=r 204 a+=b d=a a=r 152 *d=a
    a=r 151 a++ r=a 151 a< 38 while
  a=0 r=a 151
  do a=r 151 a== 0 ifl a=0 elsel a== 1 ifl a= 2 elsel a< 11 ifl a= 4 elsel a= 6 endif endif endif r=a 150
a=r 151 b=r 206 a+=b d=a a=r 150 *d=a
    a=r 151 a++ r=a 151 a> 255 until
  a=0 r=a 151 do
a=r 151 b=r 207 a+=b d=a a=r 151 *d=a
    a=r 151 a++ r=a 151 a< 3 while
  a= 3 r=a 152 a= 1 r=a 153
  do
a=r 151 b=r 207 a+=b d=a a=r 152 *d=a
    a=r 153 a-- r=a 153 a== 0 ifl a=r 152 a++ r=a 152 a-- a-- r=a 153 endif a=r 151 a++ r=a 151 a> 255 until
  a= 0 r=a 151 a= 25 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 1 r=a 151 a= 14 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 2 r=a 151 a= 9 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 3 r=a 151 a= 7 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 4 r=a 151 a= 5 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 5 r=a 151 a= 5 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 6 r=a 151 a= 4 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 7 r=a 151 a= 4 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 8 r=a 151 a= 4 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 9 r=a 151 a= 3 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 10 r=a 151 a= 3 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 11 r=a 151 a= 3 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 12 r=a 151 a= 2 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 13 r=a 151 a= 2 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 14 r=a 151 a= 2 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 15 r=a 151 a= 2 r=a 150
a=r 151 b=r 208 a+=b d=a a=r 150 *d=a
  a= 0 r=a 151
a= 60
a<<= 8 a+= 221
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 1 r=a 151
a= 31
a<<= 8 a+= 63
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 2 r=a 151
a= 89
a<<= 8 a+= 191
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 3 r=a 151
a= 72
a<<= 8 a+= 243
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 4 r=a 151
a= 100
a<<= 8 a+= 161
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 5 r=a 151
a= 90
a<<= 8 a+= 188
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 6 r=a 151
a= 102
a<<= 8 a+= 50
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a= 7 r=a 151
a= 96
a<<= 8 a+= 81
  r=a 150
a=r 151 b=r 211 a+=b d=a a=r 150 *d=a
  a=0 r=a 15 r=a 13 r=a 6 a= 1 r=a 23
  a=0 r=a 3 a=0 a-- r=a 4
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  a> 0 ifl a=r 5 r=a 6 endif
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3
  a=r 6 b=r 5 a<b ifl
  do
    a=r 23 a> 0 ifl
a=0 r=a 150
a=0 r=a 151
do
a=r 151 b=r 203 a+=b d=a a=r 150 *d=a
  a=r 151 a++ r=a 151 a< 38 while
a=0 r=a 19 a=r 7 r=a 21
a=r 7 a>>= 3 r=a 150 a= 12 b=a a=r 150 a/=b a*= 84 b=a a=r 21 a-=b r=a 20 r=a 22
a=0 r=a 18 a=r 8 r=a 12
a=r 8 a> 12 ifl a= 12 endif a++ b=a a=0 a-=b r=a 16 r=a 17 a=0 r=a 14
a=r 21 a-= 12 r=a 21 r=a 9 r=a 10 a=r 20 r=a 11 a= 128 a*= 12 b=r 20 a+=b r=a 20
a= 1 a<<= 8 r=a 150
a=r 9
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a= 1 a<<= 8 a++ r=a 150
a=r 9
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 9
a+= 4
c=a a=r 11 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=0 r=a 150
a=r 9
a+= 8
c=a a=r 150 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 11 c=a a=0 r=a 151
do a=r 151 *c=a c++ a= 1 *c=a c++ a=0 *c=a c++ *c=a c++ *c=a c++ *c=a c++ a=r 151 a++ r=a 151 a> 255 until
a=0 r=a 151
do
  a=0 r=a 152
  do
a=r 152 b=r 211 a+=b d=a a=*d
    r=a 153 a=r 151 a+= 2 b=a a=r 153 a/=b b=a a= 64 a<<= 8 a-=b r=a 154
    a=r 151 a<<= 6 b=r 152 a+=b d=a
    a=r 154 *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a
    d++ d++ d++ d++ d++ d++ d++ d++ *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a d++ d++ d++ d++ d++ d++ d++ d++ *d=a
    a=r 152 a++ r=a 152 a< 8 while
  a=r 151 a++ r=a 151 a< 128 while
a=r 201 d=a a=0 r=a 151
do
  a=r 151 a*= 5 a+= 10 a<<= 3 r=a 152 a=0 r=a 153
  do a=r 152 *d=a d++ a= 3 *d=a d++ a= 4 *d=a d++ a=r 153 a++ r=a 153 a< 16 while
  a=r 151 a++ r=a 151 a< 25 while
a=r 202 d=a a=0 *d=a d++ a= 7 *d=a d++ a= 64 *d=a
      a=0 r=a 23
    endif
a=0 r=a 27 r=a 26 r=a 41 r=a 53
a=0 r=a 52
do
  a=r 52 a<<= 2 b=r 209 a+=b d=a a= 255 *d=a d++ *d=a d++ *d=a d++ *d=a
  a=r 52 a++ r=a 52 a< 64 while
a=r 9
c=a c++ a=*c a<<= 8 c-- a+=*c
a== 1 ifnotl
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
  r=a 42
a=r 9
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
  r=a 46
a=r 4 b=r 46 a/=b r=a 4 b=a a=r 3 a/=b
  r=a 44 r=a 45
a=r 42
a+= 1
c=a a=*c
  b=a a=r 44 a-=b r=a 44 b=r 25 a<b ifnotl
    a=0 r=a 150
a=r 42
a+= 1
c=a a=*c
    r=a 151
a=r 150 b=r 4 a*=b b=a a=r 3 a-=b r=a 3 a=r 4 b=r 151 a*=b r=a 4
a=r 4 b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
    b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  endif
endif
    a=r 42 r=a 11
a=r 42
c=a a=*c
    r=a 40
a=r 42
a+= 1
c=a a=*c
    r=a 54
a=r 9
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
    r=a 55 a=r 54 a<<= 1 b=r 55 a>b ifl a= 1 elsel a=0 endif r=a 14 b=r 16 a+=b r=a 16
    a=r 55 a+= 4 r=a 150
a=r 9
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
    a=r 54 a+= 4 r=a 54
a=r 42
a+= 1
c=a a=r 54 *c=a
    a=r 54 a> 124 ifl a= 1 r=a 27 endif a= 1 r=a 41 r=a 53
  elsel
    a=0 r=a 14
a=r 9
c=a c++ a=*c a<<= 8 c-- a+=*c
    a-- r=a 43
    do
      a=r 42 a+= 6 r=a 42
a=r 42
a+= 1
c=a a=*c
      b=a a=r 44 a-=b r=a 44 b=r 25 a<b ifnotl
a=r 42
a+= 1
c=a a=*c
        r=a 151 b=a a=r 45 b=r 44 a-=b b=r 151 a-=b r=a 150
a=r 150 b=r 4 a*=b b=a a=r 3 a-=b r=a 3 a=r 4 b=r 151 a*=b r=a 4
a=r 4 b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
    b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  endif
endif
        a=r 42 r=a 11
a=r 42
c=a a=*c
        r=a 40
a=r 42
a+= 1
c=a a=*c
        a+= 4 r=a 54
a=r 9
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
        a+= 4 r=a 150
a=r 9
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 42
a+= 1
c=a a=r 54 *c=a
a=r 42
        a-= 5 c=a a=*c b=a a=r 54 a>b ifl
a=r 42 c=a a-= 6 b=a
a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++
          a=r 42 a-= 6 r=a 42 r=a 11 a=r 54 a> 124 ifl a= 1 r=a 27 endif
        endif
        a= 1 r=a 41 r=a 53 a=0
      elsel
        a=r 43 a-- r=a 43
      endif
    a> 0 while
    a=r 53 a== 0 ifl
      a=r 45 b=r 44 a-=b r=a 45 a=r 46 b=r 45 a-=b r=a 150
a=r 45 b=r 4 a*=b b=a a=r 3 a-=b r=a 3 a=r 4 b=r 150 a*=b r=a 4
a=r 11
c=a a=*c
      a+= 192 a>>= 5 a&= 8 r=a 15
a=r 42
c=a a=*c
      r=a 150 a=0 r=a 151
a=r 150 b=r 209 a+=b d=a a=r 151 *d=a
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 52
      do
a=r 52
c=a a=*c
        r=a 150
a=r 150 b=r 209 a+=b d=a a=r 151 *d=a
a=r 52
a+= 6
c=a a=*c
        r=a 150
a=r 150 b=r 209 a+=b d=a a=r 151 *d=a
        a=r 52 a+= 12 r=a 52 b=r 42 a<b while
    endif
  endif
elsel
  a=r 9 a+= 2 r=a 42
a=r 42
a+= 1
c=a a=*c
  r=a 54
a=r 11
c=a a=*c
  a+= 192 a>>= 5 a&= 8 r=a 15
a=r 9
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
  r=a 150
a=r 150
c=a c++ a=*c a<<= 8 c-- a+=*c
  a-- r=a 150
a=r 150 b=r 206 a+=b d=a a=*d
  r=a 55
a=r 42
c=a a=*c
  a+= 192 a>>= 4 a&= 16 b=r 55 a+=b b=r 15 a+=b b=r 14 a+=b r=a 55
  a=r 16 b=r 25 a<b ifnot a=r 55 a+= 32 r=a 55 endif
  a=r 54 a-- a<<= 6 b=r 55 a+=b b=r 200 a+=b r=a 56 d=a a=*d r=a 57
  a=r 4 a>>= 14 b=r 57 a*=b r=a 58
  a=r 57 a+= 32 a>>= 7 b=a a=r 57 a-=b r=a 57
  a=r 3 b=r 58 a<b ifl
    a=r 57 a+= 128 r=a 150 a=r 56 d=a a=r 150 *d=a a=r 58 r=a 4
a=r 4 b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
endif
a=r 42
c=a a=*c
    r=a 40 a=r 42 r=a 11 a= 1 r=a 14 a=r 16 a++ r=a 16
    a=r 54 a< 128 ifl a++ r=a 150
a=r 42
a+= 1
c=a a=r 150 *c=a
    endif
    a= 1 r=a 41 r=a 53
  elsel
    a=r 56 d=a a=r 57 *d=a a>>= 10 r=a 150
a=r 150 b=r 208 a+=b d=a a=*d
    r=a 13
    a=r 3 b=r 58 a-=b r=a 3 a=r 4 a-=b r=a 4
a=r 42
c=a a=*c
    r=a 150 a=0 r=a 151
a=r 150 b=r 209 a+=b d=a a=r 151 *d=a
    a=0 r=a 14
  endif
endif
a=r 53 a== 0 ifl
do
a=r 4 b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
    b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  endif
endif
  a=r 9 r=a 47
a=r 47
c=a c++ a=*c a<<= 8 c-- a+=*c
  r=a 48
  do
    a=r 12 a++ r=a 12
a=r 47
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
    a== 0 ifl a= 2 r=a 53 a=0 elsel r=a 47
a=r 47
c=a c++ a=*c a<<= 8 c-- a+=*c
      b=r 48 a==b ifl a= 1 elsel a=0 endif endif
  a> 0 while
  a=r 53 a== 0 ifl
a=r 47
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
    r=a 42 a=r 47 r=a 9
a=r 47
c=a c++ a=*c a<<= 8 c-- a+=*c
    r=a 43 a=0 r=a 45 a=r 42 r=a 52
    do
a=r 52
c=a a=*c
      r=a 150
a=r 150 b=r 209 a+=b d=a a=*d
      r=a 151
a=r 52
a+= 1
c=a a=*c
      b=r 151 a&=b b=r 45 a+=b r=a 45
      a=r 52 a+= 6 r=a 52 a=r 43 a-- r=a 43 a> 0 while
a=r 47
c=a c++ a=*c a<<= 8 c-- a+=*c
    r=a 60 a> 255 ifl a=0 elsel a= 1 endif
    a> 0 ifl
      a=r 60 b=r 48 a-=b r=a 61 a-- r=a 150
a=r 150 b=r 207 a+=b d=a a=*d
      a*= 48 r=a 62
a=r 47
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 150
a=r 150
c=a c++ a=*c a<<= 8 c-- a+=*c
      b=r 60 a-=b b=a a=r 61 a<b ifl a= 1 elsel a=0 endif r=a 63
a=r 47
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
      r=a 150 a=r 60 a*= 11 b=a a=r 150 a<b ifl a=r 63 a+= 2 r=a 63 endif
      a=r 48 b=r 61 a>b ifl a=r 63 a+= 4 r=a 63 endif a=r 63 b=r 15 a+=b a*= 3 b=r 62 a+=b b=r 201 a+=b r=a 49
      d=a a=*d a<<= 16 a>>= 16 r=a 150 d++ a=*d b=a a=r 150 a>>=b r=a 151 b=a a=r 150 a-=b d-- *d=a
      a=r 151 a== 0 ifl a= 1 endif r=a 50
    elsel
      a=r 202 r=a 49 a= 1 r=a 50
    endif
    a=r 50 b=r 45 a+=b r=a 50
a=r 4 b=r 50 a/=b r=a 4 b=a a=r 3 a/=b
    r=a 44
    b=r 45 a<b ifl
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 42 a=r 44 r=a 45
      do
a=r 42
c=a a=*c
        r=a 150
a=r 150 b=r 209 a+=b d=a a=*d
        r=a 151
a=r 42
a+= 1
c=a a=*c
        b=r 151 a&=b b=a a=r 44 a-=b r=a 44 a=r 42 a+= 6 r=a 42 a=r 44 b=r 25 a<b while
      a=r 42 a-= 6 r=a 42
a=r 42
a+= 1
c=a a=*c
      r=a 151 b=a a=r 45 b=r 44 a-=b b=r 151 a-=b r=a 150
a=r 150 b=r 4 a*=b b=a a=r 3 a-=b r=a 3 a=r 4 b=r 151 a*=b r=a 4
a=r 4 b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
  b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  b=r 24 a<b ifl
a=r 2 b=r 28 a<b ifl c=a a=*c elsel a=0 endif r=a 150 a=r 2 a++ r=a 2 a=r 150
    b=a a=r 3 a<<= 8 a+=b r=a 3 a=r 4 a<<= 8 r=a 4
  endif
endif
      a=r 49 d=a d++ a=*d a< 7 ifl d++ a=*d a-- a&= 255 *d=a a== 0 ifl d-- d-- a=*d a<<= 1 a<<= 16 a>>= 16 *d=a d++ a=*d b=a a= 3 a<<=b a&= 255 d++ *d=a d-- a=*d a++ *d=a endif endif
      a=r 42 r=a 11
a=r 42
c=a a=*c
      r=a 40
a=r 42
a+= 1
c=a a=*c
      a+= 4 r=a 54 a=r 17 r=a 16
a=r 9
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
      a+= 4 r=a 150
a=r 9
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 42
a+= 1
c=a a=r 54 *c=a
      a=r 54 a> 124 ifl a= 1 r=a 27 endif a= 1 r=a 26 r=a 53
    elsel
      a=r 50 b=a a=r 44 a<b ifnot a= 2 r=a 53 a= 3 r=a 59 endif
      a=r 53 a== 0 ifl
        a=r 50 b=r 45 a-=b r=a 150
a=r 45 b=r 4 a*=b b=a a=r 3 a-=b r=a 3 a=r 4 b=r 150 a*=b r=a 4
        a=r 49 d=a a=*d b=r 50 a+=b a<<= 16 a>>= 16 *d=a
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
        r=a 52
a=r 9
c=a c++ a=*c a<<= 8 c-- a+=*c
        r=a 43 a=0 r=a 151
        do
a=r 52
c=a a=*c
          r=a 150
a=r 150 b=r 209 a+=b d=a a=r 151 *d=a
          a=r 52 a+= 6 r=a 52 a=r 43 a-- r=a 43 a> 0 while
      endif
    endif
  endif
a=r 53 a== 0 while
endif
    a=r 53 a== 1 ifl
      a=r 40 out a=r 6 a++ r=a 6
      a=r 27 a> 0 ifl
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 60 a=r 11 r=a 61
a=r 61 b=r 60 a==b ifnotl
  a=r 61 c=a a=*c r=a 70 c++ a=*c r=a 71 c++ a=*c r=a 72 c++ a=*c r=a 73 c++ a=*c r=a 74 c++ a=*c r=a 75
  do a=r 61 a-= 6 r=a 67
a=r 67 b=a a=r 61 c=a
*c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++
    a=r 67 r=a 61 b=r 60 a==b ifl a=0 elsel a= 1 endif a> 0 while
  a=r 61 c=a a=r 70 *c=a c++ a=r 71 *c=a c++ a=r 72 *c=a c++ a=r 73 *c=a c++ a=r 74 *c=a c++ a=r 75 *c=a
endif
a=r 61
a+= 1
c=a a=*c
r=a 62
a=r 9
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
b=r 62 a-=b r=a 63
a=r 12 a> 0 ifl a= 1 elsel a=0 endif r=a 64
a=r 62 a+= 4 b=r 64 a+=b a>>= 1 r=a 62
a=r 9
c=a c++ a=*c a<<= 8 c-- a+=*c
a-- r=a 65
a=r 61
a+= 1
c=a a=r 62 *c=a
do
  a=r 61 a+= 6 r=a 61
a=r 61
a+= 1
c=a a=*c
  r=a 66 b=a a=r 63 a-=b r=a 63
  a=r 66 b=r 64 a+=b a>>= 1 r=a 66 b=r 62 a+=b r=a 62
a=r 61
a+= 1
c=a a=r 66 *c=a
a=r 61
  a-= 5 c=a a=*c b=a a=r 66 a>b ifl
    a=r 61 c=a a=*c r=a 70 c++ a=*c r=a 71 c++ a=*c r=a 72 c++ a=*c r=a 73 c++ a=*c r=a 74 c++ a=*c r=a 75
    a=r 61 r=a 67
    do a=r 67 a-= 6 r=a 68
a=r 68 b=a a=r 67 c=a
*c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++
      a=r 68 r=a 67 b=r 60 a==b ifl a=0 elsel a=r 67 a-= 5 c=a a=*c b=a a=r 66 a>b ifl a= 1 elsel a=0 endif endif a> 0 while
    a=r 67 c=a a=r 70 *c=a c++ a=r 71 *c=a c++ a=r 72 *c=a c++ a=r 73 *c=a c++ a=r 74 *c=a c++ a=r 75 *c=a
  endif
  a=r 65 a-- r=a 65
a> 0 while
a=r 61
a+= 1
c=a a=*c
a== 0 ifl
  a=0 r=a 65
  do a=r 65 a++ r=a 65 a=r 61 a-= 6 r=a 61 a++ c=a a=*c a== 0 while
  a=r 63 b=r 65 a+=b r=a 63
a=r 9
c=a c++ a=*c a<<= 8 c-- a+=*c
  r=a 68 b=r 65 a-=b r=a 69
a=r 9
c=a a=r 69 *c=a c++ a>>= 8 *c=a
  a=r 68 a++ a>>= 1 r=a 76
  a=r 69 a== 1 ifl
a=r 60
a+= 1
c=a a=*c
    r=a 66
    do a=r 63 a>>= 1 r=a 63 a=r 66 a++ a>>= 1 r=a 66 a=r 63 a> 1 while
    a=r 9 a+= 2 r=a 67
a=r 60 b=a a=r 67 c=a
*c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++
a=r 9
a+= 3
c=a a=r 66 *c=a
    a=r 9 a+= 2 r=a 11
a=r 76 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 77
a=r 77 b=r 203 a+=b d=a a=*d
r=a 158
a=r 60
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 77 b=r 203 a+=b d=a a=r 60 *d=a
    a= 1 r=a 78
  elsel
    a=r 69 a++ a>>= 1 r=a 77
    a=r 76 b=r 77 a==b ifnotl
a=r 76 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 70
a=r 77 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 71
      a=r 70 b=r 71 a==b ifnotl
a=r 71 b=r 203 a+=b d=a a=*d
        a> 0 ifl
a=r 71 b=r 203 a+=b d=a a=*d
r=a 72
a=r 72
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 71 b=r 203 a+=b d=a a=r 159 *d=a
a=r 9
a+= 4
c=a a=r 72 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
          a=r 77 a*= 12 r=a 73
a=r 60 b=a a=r 72 c=a
a=r 73 a> 0 ifl do *c=*b b++ c++ a-- a> 0 while endif
a=r 70 b=r 203 a+=b d=a a=*d
r=a 158
a=r 60
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 70 b=r 203 a+=b d=a a=r 60 *d=a
        elsel
a=r 70 b=r 204 a+=b d=a a=*d
r=a 130
a=r 71 b=r 204 a+=b d=a a=*d
r=a 131
a=r 130 b=r 131 a-=b r=a 132
a=r 131 a*= 12 b=r 60 a+=b r=a 133
a=r 132 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
a=r 135 b=r 132 a==b ifnotl
  a=r 134 a-- r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
  a=r 135 a*= 12 b=r 133 a+=b r=a 136 a=r 132 b=r 135 a-=b a-- r=a 137
a=r 137 b=r 203 a+=b d=a a=*d
r=a 158
a=r 136
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 137 b=r 203 a+=b d=a a=r 136 *d=a
endif
a=r 134 b=r 203 a+=b d=a a=*d
r=a 158
a=r 133
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 134 b=r 203 a+=b d=a a=r 133 *d=a
        endif
      endif
    endif
    a=0 r=a 78
  endif
elsel a=0 r=a 78 endif
a=r 78 a== 0 ifl
  a=r 63 a>>= 1 b=a a=r 63 a-=b b=r 62 a+=b r=a 150
a=r 9
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 9
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
  r=a 11
endif
      endif
      a=r 26 a> 0 ifl a= 1 elsel
a=r 11
a+= 2
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
        r=a 150 a=r 12 a== 0 ifl a=r 150 b=r 19 a>b ifl a=r 150 r=a 9 r=a 10 a=0 elsel a= 1 endif elsel a= 1 endif
      endif
      a> 0 ifl
a=0 r=a 84 r=a 85 r=a 88
a=r 11
c=a a=*c
r=a 80
a=r 11
a+= 1
c=a a=*c
r=a 81
a=r 9
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 82 a=r 81 a< 31 ifl a=r 82 a> 0 ifl
a=r 82
c=a c++ a=*c a<<= 8 c-- a+=*c
    a== 1 ifl
a=r 82
a+= 3
c=a a=*c
      a< 32 ifl a++ r=a 150
a=r 82
a+= 3
c=a a=r 150 *c=a
      endif
    elsel
a=r 82
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 83
a=r 83
c=a a=*c
      b=r 80 a==b ifnotl
        do a=r 83 a+= 6 r=a 83
a=r 83
c=a a=*c
          b=r 80 a==b ifl a=0 elsel a= 1 endif a> 0 while
a=r 83
a+= 1
c=a a=*c
        r=a 150
a=r 83
        a-= 5 c=a a=*c b=a a=r 150 a<b ifnotl
a=r 83 c=a a-= 6 b=a
a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++ a=*c r=a 150 *c=*b a=r 150 *b=a b++ c++
          a=r 83 a-= 6 r=a 83
        endif
      endif
a=r 83
a+= 1
c=a a=*c
      a< 115 ifl a+= 2 r=a 150
a=r 83
a+= 1
c=a a=r 150 *c=a
a=r 82
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
        a+= 2 r=a 150
a=r 82
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
      endif
    endif
endif endif
a=r 12 a== 0 ifl
  a= 1 r=a 84
elsel
a=r 19
c=a a=r 80 *c=a
  a=r 19 a++ r=a 19 b=r 22 a<b ifnotl a= 1 r=a 23 r=a 85 endif
  a=r 85 a== 0 ifl
    a=r 19 r=a 86
a=r 11
a+= 2
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
    r=a 87
    a> 0 ifl a= 1 r=a 88 a=r 87 b=r 86 a>b ifnot a= 2 r=a 84 endif
    elsel
a=r 11
a+= 2
c=a a=r 86 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
      a=r 9 r=a 87
    endif
  endif
endif
a=r 84 a> 0 ifl
a=r 9 r=a 101
a=r 11
a+= 2
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 102 a=0 r=a 103 r=a 100 r=a 107
a=r 12 a> 0 ifl
a=r 103 b=r 210 a+=b d=a a=r 11 *d=a
  a=r 103 a++ r=a 103 endif
do
a=r 101
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
  a> 0 ifl
    r=a 101
a=r 101
c=a c++ a=*c a<<= 8 c-- a+=*c
    a== 1 ifl a=r 101 a+= 2 r=a 104 elsel
a=r 11
c=a a=*c
      r=a 108
a=r 101
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 104
      do
a=r 104
c=a a=*c
        b=r 108 a==b ifl a=0 elsel a=r 104 a+= 6 r=a 104 a= 1 endif a> 0 while
    endif
a=r 104
a+= 2
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
    b=r 102 a==b ifnotl
      r=a 101 a=r 103 a== 0 ifl a=r 101 r=a 100 a= 2 r=a 107 endif
      a=0
    elsel
a=r 103 b=r 210 a+=b d=a a=r 104 *d=a
      a=r 103 a++ r=a 103 a= 1
    endif
  endif
a> 0 while
a=r 107 a== 0 ifl
a=r 102
c=a a=*c
  r=a 105 a=r 102 a++ r=a 102
a=r 101
c=a c++ a=*c a<<= 8 c-- a+=*c
  a== 1 ifl
a=r 101
a+= 3
c=a a=*c
    r=a 106
  elsel
a=r 101
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
    r=a 104
    do
a=r 104
c=a a=*c
      b=r 105 a==b ifl a=0 elsel a=r 104 a+= 6 r=a 104 a= 1 endif a> 0 while
a=r 104
a+= 1
c=a a=*c
    a-- r=a 108
a=r 101
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
    r=a 109
a=r 101
c=a c++ a=*c a<<= 8 c-- a+=*c
    b=a a=r 109 a-=b b=r 108 a-=b r=a 109
    a=r 108 a<<= 1 b=r 109 a>b ifl
      a=r 109 a<<= 1 r=a 110 a=r 108 a<<= 1 b=r 109 a+=b a-- b=r 110 a/=b a++ a++ r=a 106
    elsel
      a=r 108 a*= 5 b=r 109 a>b ifl a= 2 elsel a= 1 endif r=a 106
    endif
    a=r 106 a&= 255 r=a 106
  endif
  do
    a=r 21 b=r 20 a==b ifnotl a=r 21 a-= 12 r=a 21 r=a 111
    elsel
      a=0 r=a 150
a=r 150 b=r 203 a+=b d=a a=*d
      a> 0 ifl a=0 r=a 150
a=r 150 b=r 203 a+=b d=a a=*d
r=a 111
a=r 111
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 150 b=r 203 a+=b d=a a=r 159 *d=a
      elsel a=0 r=a 120
a=0 r=a 122
a=r 18 a== 0 ifl
a= 255 r=a 18
a=r 20 b=r 21 a==b ifnotl a= 1 r=a 150
a=r 20
c=a a=r 150 *c=a c++ a>>= 8 *c=a
endif
a=0 r=a 138 r=a 143
do
a=r 143 b=r 204 a+=b d=a a=*d
r=a 144
a=r 143 b=r 203 a+=b d=a a=*d
r=a 145 a=0 r=a 150
a=r 143 b=r 203 a+=b d=a a=r 150 *d=a
  a=r 145 a> 0 ifl do
    a=r 145 r=a 146
a=r 146
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 145
    a=0 r=a 150
a=r 146
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 146
a+= 2
c=a a=r 144 *c=a c++ a>>= 8 *c=a
a=r 146
a+= 4
c=a a=r 138 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
    a=r 146 r=a 138 a=r 145 a> 0 while endif
  a=r 143 a++ r=a 143 a< 38 while
a=r 138 r=a 139 a=0 r=a 140
a=r 138 a> 0 ifl do
  a=r 138 r=a 141
a=r 141
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
r=a 142
a=r 141
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 138
  a=r 142 a== 0 ifl
    a=r 140 a== 0 ifl a=r 138 r=a 139 elsel
a=r 140
c=a a=r 138 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
    endif
  elsel
    a=r 141 a+= 4 r=a 140
    do
      a=r 142 a*= 12 b=r 141 a+=b r=a 147
a=r 147
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
b=r 142 a+=b r=a 142
a=r 147
c=a c++ a=*c a<<= 8 c-- a+=*c
      a> 0 ifl a=0 elsel a=r 142 a>>= 16 a> 0 ifl a=0 elsel a= 1 endif endif
      a> 0 ifl
a=r 141
a+= 2
c=a a=r 142 *c=a c++ a>>= 8 *c=a
        a=0 r=a 150
a=r 147
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
        a= 1 endif
    a> 0 while
  endif
  a=r 138 a> 0 while endif
a=r 139 r=a 138
a=r 138 a> 0 ifl do
  a=r 138 r=a 141
a=r 141
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
r=a 142
a=r 141
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 138
  a=r 142 a> 0 ifl
    do a=r 142 a> 128 ifl a= 37 r=a 148
a=r 148 b=r 203 a+=b d=a a=*d
r=a 158
a=r 141
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 148 b=r 203 a+=b d=a a=r 141 *d=a
      a=r 142 a-= 128 r=a 142 a= 128 a*= 12 b=r 141 a+=b r=a 141 a= 1 elsel a=0 endif a> 0 while
a=r 142 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 148
a=r 148 b=r 204 a+=b d=a a=*d
r=a 149
    a=r 149 b=r 142 a==b ifnotl
      a=r 148 a-- r=a 148
a=r 148 b=r 204 a+=b d=a a=*d
r=a 149
      a=r 149 a*= 12 b=r 141 a+=b r=a 146 a=r 142 b=r 149 a-=b a-- r=a 147
a=r 147 b=r 203 a+=b d=a a=*d
r=a 158
a=r 146
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 147 b=r 203 a+=b d=a a=r 146 *d=a
    endif
a=r 148 b=r 203 a+=b d=a a=*d
r=a 158
a=r 141
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 148 b=r 203 a+=b d=a a=r 141 *d=a
  endif
  a=r 138 a> 0 while endif
a=r 120 b=r 203 a+=b d=a a=*d
  a> 0 ifl
a=r 120 b=r 203 a+=b d=a a=*d
r=a 121
a=r 121
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 120 b=r 203 a+=b d=a a=r 159 *d=a
    a= 1 r=a 122 endif
endif
a=r 122 a== 0 ifl
  a=r 120 r=a 123
  do a=r 123 a++ r=a 123 a== 38 ifl a=0 elsel
a=r 123 b=r 203 a+=b d=a a=*d
    a== 0 ifl a= 1 elsel a=0 endif endif a> 0 while
  a=r 123 a== 38 ifl
a=r 120 b=r 204 a+=b d=a a=*d
r=a 124
    a=r 124 a*= 12 r=a 124 a=r 18 a-- r=a 18
    a=r 22 b=r 19 a-=b b=r 124 a>b ifl a=r 22 a-=b r=a 22 r=a 121 elsel a=0 r=a 121 endif
  elsel
a=r 123 b=r 203 a+=b d=a a=*d
r=a 121
a=r 121
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 123 b=r 203 a+=b d=a a=r 159 *d=a
a=r 123 b=r 204 a+=b d=a a=*d
r=a 130
a=r 120 b=r 204 a+=b d=a a=*d
r=a 131
a=r 130 b=r 131 a-=b r=a 132
a=r 131 a*= 12 b=r 121 a+=b r=a 133
a=r 132 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
a=r 135 b=r 132 a==b ifnotl
  a=r 134 a-- r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
  a=r 135 a*= 12 b=r 133 a+=b r=a 136 a=r 132 b=r 135 a-=b a-- r=a 137
a=r 137 b=r 203 a+=b d=a a=*d
r=a 158
a=r 136
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 137 b=r 203 a+=b d=a a=r 136 *d=a
endif
a=r 134 b=r 203 a+=b d=a a=*d
r=a 158
a=r 133
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 134 b=r 203 a+=b d=a a=r 133 *d=a
  endif
endif
        a=r 121 r=a 111
      endif
    endif
    a=r 111 a== 0 ifl a=0 r=a 100 a= 1 r=a 107 a=0 elsel
      a= 1 r=a 150
a=r 111
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 111
a+= 2
c=a a=r 105 *c=a
a=r 111
a+= 3
c=a a=r 106 *c=a
a=r 111
a+= 4
c=a a=r 102 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 111
a+= 8
c=a a=r 101 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
      a=r 103 a-- r=a 103
a=r 103 b=r 210 a+=b d=a a=*d
      r=a 112
a=r 112
a+= 2
c=a a=r 111 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
      a=r 111 r=a 101 a=r 103
    endif
  a> 0 while
  a=r 107 a== 0 ifl a=r 101 r=a 100 endif
endif
  a=r 100 a== 0 ifl
    a= 1 r=a 23 r=a 85
  elsel
    a=r 84 a== 1 ifl
      a=r 100 r=a 9 r=a 10
a=r 11
a+= 2
c=a a=r 100 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
      a= 1 r=a 85
    elsel a=r 100 r=a 87 endif
  endif
endif
a=r 85 a== 0 ifl
  a=r 88 a> 0 ifl a=r 12 a-- r=a 12 a== 0 ifl a=r 87 r=a 86 a=r 10 b=r 9 a==b ifnot a=r 19 a-- r=a 19 endif endif endif
  a=r 9 r=a 89 a=r 10 r=a 82 a=r 87 r=a 9 r=a 10
  a=r 82 b=r 89 a==b ifl a= 1 r=a 85 endif
endif
a=r 85 a== 0 ifl
a=r 89
c=a c++ a=*c a<<= 8 c-- a+=*c
  r=a 90
a=r 89
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
  b=r 90 a-=b b=r 81 a-=b a++ r=a 91
  do
a=r 82
c=a c++ a=*c a<<= 8 c-- a+=*c
    r=a 92 a== 1 ifl a=0 r=a 120 a= 2 r=a 96 elsel
      a=0 r=a 96 a=r 92 a&= 1 a== 0 ifl
        a=r 92 a>>= 1 r=a 97
a=r 97 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 98
        a=r 97 a++ r=a 150
a=r 150 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 99
        a=r 98 b=r 99 a==b ifnot a=r 98 a++ r=a 120 a= 1 r=a 96 endif
      endif
    endif
    a=r 96 a> 0 ifl
a=r 120 b=r 203 a+=b d=a a=*d
a> 0 ifl
a=r 120 b=r 203 a+=b d=a a=*d
r=a 121
a=r 121
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 120 b=r 203 a+=b d=a a=r 159 *d=a
elsel
a=r 120 b=r 204 a+=b d=a a=*d
r=a 124
  a=r 124 a*= 12 r=a 124 a=r 21 b=r 20 a-=b b=r 124 a<b ifnotl
    a=r 20 r=a 121 b=r 124 a+=b r=a 20
  elsel
a=0 r=a 122
a=r 18 a== 0 ifl
a= 255 r=a 18
a=r 20 b=r 21 a==b ifnotl a= 1 r=a 150
a=r 20
c=a a=r 150 *c=a c++ a>>= 8 *c=a
endif
a=0 r=a 138 r=a 143
do
a=r 143 b=r 204 a+=b d=a a=*d
r=a 144
a=r 143 b=r 203 a+=b d=a a=*d
r=a 145 a=0 r=a 150
a=r 143 b=r 203 a+=b d=a a=r 150 *d=a
  a=r 145 a> 0 ifl do
    a=r 145 r=a 146
a=r 146
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 145
    a=0 r=a 150
a=r 146
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 146
a+= 2
c=a a=r 144 *c=a c++ a>>= 8 *c=a
a=r 146
a+= 4
c=a a=r 138 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
    a=r 146 r=a 138 a=r 145 a> 0 while endif
  a=r 143 a++ r=a 143 a< 38 while
a=r 138 r=a 139 a=0 r=a 140
a=r 138 a> 0 ifl do
  a=r 138 r=a 141
a=r 141
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
r=a 142
a=r 141
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 138
  a=r 142 a== 0 ifl
    a=r 140 a== 0 ifl a=r 138 r=a 139 elsel
a=r 140
c=a a=r 138 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
    endif
  elsel
    a=r 141 a+= 4 r=a 140
    do
      a=r 142 a*= 12 b=r 141 a+=b r=a 147
a=r 147
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
b=r 142 a+=b r=a 142
a=r 147
c=a c++ a=*c a<<= 8 c-- a+=*c
      a> 0 ifl a=0 elsel a=r 142 a>>= 16 a> 0 ifl a=0 elsel a= 1 endif endif
      a> 0 ifl
a=r 141
a+= 2
c=a a=r 142 *c=a c++ a>>= 8 *c=a
        a=0 r=a 150
a=r 147
a+= 2
c=a a=r 150 *c=a c++ a>>= 8 *c=a
        a= 1 endif
    a> 0 while
  endif
  a=r 138 a> 0 while endif
a=r 139 r=a 138
a=r 138 a> 0 ifl do
  a=r 138 r=a 141
a=r 141
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
r=a 142
a=r 141
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 138
  a=r 142 a> 0 ifl
    do a=r 142 a> 128 ifl a= 37 r=a 148
a=r 148 b=r 203 a+=b d=a a=*d
r=a 158
a=r 141
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 148 b=r 203 a+=b d=a a=r 141 *d=a
      a=r 142 a-= 128 r=a 142 a= 128 a*= 12 b=r 141 a+=b r=a 141 a= 1 elsel a=0 endif a> 0 while
a=r 142 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 148
a=r 148 b=r 204 a+=b d=a a=*d
r=a 149
    a=r 149 b=r 142 a==b ifnotl
      a=r 148 a-- r=a 148
a=r 148 b=r 204 a+=b d=a a=*d
r=a 149
      a=r 149 a*= 12 b=r 141 a+=b r=a 146 a=r 142 b=r 149 a-=b a-- r=a 147
a=r 147 b=r 203 a+=b d=a a=*d
r=a 158
a=r 146
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 147 b=r 203 a+=b d=a a=r 146 *d=a
    endif
a=r 148 b=r 203 a+=b d=a a=*d
r=a 158
a=r 141
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 148 b=r 203 a+=b d=a a=r 141 *d=a
  endif
  a=r 138 a> 0 while endif
a=r 120 b=r 203 a+=b d=a a=*d
  a> 0 ifl
a=r 120 b=r 203 a+=b d=a a=*d
r=a 121
a=r 121
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 120 b=r 203 a+=b d=a a=r 159 *d=a
    a= 1 r=a 122 endif
endif
a=r 122 a== 0 ifl
  a=r 120 r=a 123
  do a=r 123 a++ r=a 123 a== 38 ifl a=0 elsel
a=r 123 b=r 203 a+=b d=a a=*d
    a== 0 ifl a= 1 elsel a=0 endif endif a> 0 while
  a=r 123 a== 38 ifl
a=r 120 b=r 204 a+=b d=a a=*d
r=a 124
    a=r 124 a*= 12 r=a 124 a=r 18 a-- r=a 18
    a=r 22 b=r 19 a-=b b=r 124 a>b ifl a=r 22 a-=b r=a 22 r=a 121 elsel a=0 r=a 121 endif
  elsel
a=r 123 b=r 203 a+=b d=a a=*d
r=a 121
a=r 121
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
r=a 159
a=r 123 b=r 203 a+=b d=a a=r 159 *d=a
a=r 123 b=r 204 a+=b d=a a=*d
r=a 130
a=r 120 b=r 204 a+=b d=a a=*d
r=a 131
a=r 130 b=r 131 a-=b r=a 132
a=r 131 a*= 12 b=r 121 a+=b r=a 133
a=r 132 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
a=r 135 b=r 132 a==b ifnotl
  a=r 134 a-- r=a 134
a=r 134 b=r 204 a+=b d=a a=*d
r=a 135
  a=r 135 a*= 12 b=r 133 a+=b r=a 136 a=r 132 b=r 135 a-=b a-- r=a 137
a=r 137 b=r 203 a+=b d=a a=*d
r=a 158
a=r 136
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 137 b=r 203 a+=b d=a a=r 136 *d=a
endif
a=r 134 b=r 203 a+=b d=a a=*d
r=a 158
a=r 133
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 134 b=r 203 a+=b d=a a=r 133 *d=a
  endif
endif
  endif
endif
      a=r 121 a== 0 ifl a= 1 r=a 23 r=a 85 endif
    endif
    a=r 85 a== 0 ifl
      a=r 96 a== 2 ifl
a=r 82
a+= 3
c=a a=*c
        r=a 97 a=r 121 r=a 83
a=r 82
a+= 2
c=a a=*c
        r=a 150
a=r 83
c=a a=r 150 *c=a
        a=r 82 a+= 4 b=a a=r 83 a+= 2 c=a *c=*b b++ c++ *c=*b b++ c++ *c=*b b++ c++ *c=*b
a=r 82
a+= 4
c=a a=r 83 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
        a=r 97 a< 30 ifl a<<= 1 elsel a= 120 endif r=a 97
a=r 83
a+= 1
c=a a=r 97 *c=a
        a=r 90 a> 3 ifl a= 1 elsel a=0 endif b=r 13 a+=b b=r 97 a+=b r=a 93
      elsel
        a=r 96 a== 1 ifl
a=r 82
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
          r=a 99 a=r 97 a*= 12 r=a 98
a=r 99 b=a a=r 121 c=a
a=r 98 a> 0 ifl do *c=*b b++ c++ a-- a> 0 while endif
          a=r 97 r=a 150
a=r 150 a-- r=a 151
a=r 151 b=r 205 a+=b d=a a=*d
r=a 151
          a=r 151 r=a 152
a=r 152 b=r 203 a+=b d=a a=*d
r=a 158
a=r 99
c=a a=r 158 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
a=r 152 b=r 203 a+=b d=a a=r 99 *d=a
a=r 82
a+= 4
c=a a=r 121 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
        endif
a=r 82
a+= 2
c=a c++ a=*c a<<= 8 c-- a+=*c
        r=a 93
        a=r 92 a<<= 1 b=r 90 a<b ifl a= 1 elsel a=0 endif r=a 94
        a=r 92 a<<= 2 b=r 90 a>b ifl a=0 elsel a=r 92 a<<= 3 b=a a=r 93 a>b ifl a=0 elsel a= 2 endif endif b=r 94 a+=b b=r 93 a+=b r=a 93
      endif
a=r 82
a+= 4
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 83 a=r 92 a*= 6 b=r 83 a+=b r=a 83
      a=r 93 a+= 6 a<<= 1 b=r 81 a*=b r=a 94 a=r 91 b=r 93 a+=b r=a 95
a=r 83
c=a a=r 80 *c=a
      a=r 92 a++ r=a 150
a=r 82
c=a a=r 150 *c=a c++ a>>= 8 *c=a
a=r 83
a+= 2
c=a a=r 86 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a c++ a>>= 8 *c=a
      a=r 95 a*= 6 b=a a=r 94 a<b ifl
        a=r 95 b=a a=r 94 a>b ifl a= 2 elsel a= 1 endif r=a 150 a=r 95 a<<= 2 b=a a=r 94 a<b ifnot a=r 150 a++ r=a 150 endif a=r 150 r=a 94
        a=r 93 a+= 3 r=a 93
      elsel
        a= 4 r=a 150 a=r 95 a*= 9 b=a a=r 94 a<b ifnot a=r 150 a++ r=a 150 endif a=r 95 a*= 12 b=a a=r 94 a<b ifnot a=r 150 a++ r=a 150 endif
        a=r 95 a*= 15 b=a a=r 94 a<b ifnot a=r 150 a++ r=a 150 endif a=r 150 r=a 94 b=r 93 a+=b r=a 93
      endif
a=r 82
a+= 2
c=a a=r 93 *c=a c++ a>>= 8 *c=a
a=r 83
a+= 1
c=a a=r 94 *c=a
a=r 82
a+= 8
c=a c++ c++ c++ a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 82 b=r 89 a==b ifl a=0 elsel a= 1 endif
    elsel a=0 endif
  a> 0 while
endif
      endif
      a=r 6 b=r 5 a<b
    elsel a=0 endif
  while
  endif
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZPPM";
