/*
  ZPAQZSTD: a zstd decoder (RFC 8878) written in ZPAQL, for zpaq-std -ma:zstd
  (zstd 1.5.7, levels 1-22). zpaq-std, 2026. Generated by gen.py next to this
  file; the Huff0 literal decoder and the FSE table reader/builder are the ones
  of ZPAQLIZARDH (../zpaqlizard/huff0.py). ZPAQL has no subroutines: everything
  is a macro expanded in place.

  The whole frame is kept in M and decoded at the end of the segment. Supported:
  raw, RLE and compressed blocks; raw, RLE, Huffman and treeless literals, with
  1 or 4 streams; sequences with predefined, RLE, transmitted and repeated FSE
  tables; the three repeat offsets (including the "offset - 1" case); several
  frames, skippable frames, and the optional checksum (skipped: zpaq checks the
  SHA-1 of the output). Dictionaries are not (ZSTD_compress never uses one).

  M: the frame from 0, one block of literals after it, then the whole output
  (matches look back into it), which also goes out with OUT. H needs ph = 13.

  Verified with zpaqd 7.15 on 506 zstd frames (23 inputs x levels 1-22), and on
  a stream of two frames (one with checksum) with a skippable frame between them.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQZSTD_CUERPO[] = R"ZZST(hcomp
halt
pcomp zpaqzstd ;
(ZPAQZSTD: decodificador de zstd en ZPAQL, para zpaq-std -ma:zstd. zpaq-std, 2026.
 Guarda el frame entero en M y lo decodifica al final: bloques crudos, RLE y
 comprimidos; literales crudos, RLE y Huff0 con o sin arbol, de 1 o 4 flujos;
 secuencias con tablas FSE predefinidas, RLE, transmitidas o repetidas; los tres
 offsets repetidos. La salida queda en M, detras, y sale con out. El Huff0 y el
 FSE son los de ZPAQLIZARDH.)
a> 255 ifl
  a=c r=a 1
a=0 r=a 95
a= 1 a<<= 8 r=a 70
a= 2 a<<= 8 r=a 71
a= 33 a<<= 4 r=a 72
a= 34 a<<= 4 r=a 73
a= 35 a<<= 4 r=a 80
a= 36 a<<= 4 r=a 79
a= 37 a<<= 4 r=a 90
a= 75 a<<= 3 r=a 74
a= 107 a<<= 3 r=a 75
a= 139 a<<= 3 r=a 76
a= 147 a<<= 3 r=a 77
a= 155 a<<= 3 r=a 78
a=r 80 d=a a= 2 *d=a d++ a= 3 *d=a d++ a= 1 *d=a d++ a=0 *d=a
a= 3 a<<= 9 r=a 110
a= 1 a<<= 11 r=a 111
a= 5 a<<= 9 r=a 112
a= 3 a<<= 10 r=a 113
a= 7 a<<= 9 r=a 114
a= 1 a<<= 12 r=a 115
a= 9 a<<= 9 r=a 116
a= 19 a<<= 8 r=a 117
a= 5 a<<= 10 r=a 118
a= 21 a<<= 8 r=a 119
a= 85 a<<= 6 r=a 120
a= 43 a<<= 7 r=a 121
a= 87 a<<= 6 r=a 122
a= 11 a<<= 9 r=a 123
a= 89 a<<= 6 r=a 124
a= 45 a<<= 7 r=a 125
a= 91 a<<= 6 r=a 127
a=r 119 d=a
a= 0
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a= 18
*d=a d++
a= 20
*d=a d++
a= 22
*d=a d++
a= 24
*d=a d++
a= 28
*d=a d++
a= 32
*d=a d++
a= 40
*d=a d++
a= 48
*d=a d++
a= 64
*d=a d++
a= 128
*d=a d++
a= 1
a<<= 8
*d=a d++
a= 2
a<<= 8
*d=a d++
a= 4
a<<= 8
*d=a d++
a= 8
a<<= 8
*d=a d++
a= 16
a<<= 8
*d=a d++
a= 32
a<<= 8
*d=a d++
a= 64
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 1
a<<= 8
a<<= 8
*d=a d++
a=r 120 d=a
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a=r 121 d=a
a= 3
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a= 17
*d=a d++
a= 18
*d=a d++
a= 19
*d=a d++
a= 20
*d=a d++
a= 21
*d=a d++
a= 22
*d=a d++
a= 23
*d=a d++
a= 24
*d=a d++
a= 25
*d=a d++
a= 26
*d=a d++
a= 27
*d=a d++
a= 28
*d=a d++
a= 29
*d=a d++
a= 30
*d=a d++
a= 31
*d=a d++
a= 32
*d=a d++
a= 33
*d=a d++
a= 34
*d=a d++
a= 35
*d=a d++
a= 37
*d=a d++
a= 39
*d=a d++
a= 41
*d=a d++
a= 43
*d=a d++
a= 47
*d=a d++
a= 51
*d=a d++
a= 59
*d=a d++
a= 67
*d=a d++
a= 83
*d=a d++
a= 99
*d=a d++
a= 131
*d=a d++
a= 1
a<<= 8 a+= 3
*d=a d++
a= 2
a<<= 8 a+= 3
*d=a d++
a= 4
a<<= 8 a+= 3
*d=a d++
a= 8
a<<= 8 a+= 3
*d=a d++
a= 16
a<<= 8 a+= 3
*d=a d++
a= 32
a<<= 8 a+= 3
*d=a d++
a= 64
a<<= 8 a+= 3
*d=a d++
a= 128
a<<= 8 a+= 3
*d=a d++
a= 1
a<<= 8
a<<= 8 a+= 3
*d=a d++
a=r 122 d=a
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a=r 123 d=a
a= 5
*d=a d++
a= 4
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a=r 124 d=a
a= 2
*d=a d++
a= 5
*d=a d++
a= 4
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a=r 125 d=a
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a=r 127 d=a
a=r 110 *d=a d++ a=r 111 *d=a d++ a=r 112 *d=a d++ a=r 123 *d=a d++
a= 36 *d=a d++ a= 6 *d=a d++ a= 6 *d=a d++ a=0 *d=a d++
a=r 116 *d=a d++ a=r 117 *d=a d++ a=r 118 *d=a d++ a=r 125 *d=a d++
a= 29 *d=a d++ a= 5 *d=a d++ a= 4 *d=a d++ a=0 *d=a d++
a=r 113 *d=a d++ a=r 114 *d=a d++ a=r 115 *d=a d++ a=r 124 *d=a d++
a= 53 *d=a d++ a= 6 *d=a d++ a= 2 *d=a d++ a=0 *d=a d++
  a=r 1 r=a 126 r=a 38
  a= 2 a<<= 16 a+= 64 b=r 1 a+=b r=a 3 r=a 4
  a=0 r=a 2 a= 1 r=a 12
  do
  a=r 2 a+= 4 b=r 1 a>b ifl a=0 r=a 12 endif
  a=r 12 a> 0 ifl
    a=r 2 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a>>= 4 r=a 24
    a=r 2 a+= 4 r=a 2
    a= 24 a<<= 8 a+= 77 a<<= 8 a+= 42 a<<= 4 a+= 5 b=a a=r 24 a==b ifl
      a=r 2 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a+= 4 b=r 2 a+=b r=a 2
    elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
      r=a 13
      a>>= 5 a&= 1 a== 0 ifl a=r 2 a++ r=a 2 endif
      a=r 13 a&= 3 a> 0 ifl a== 3 ifl a= 4 endif b=a a=r 2 a+=b r=a 2 endif
      a=r 13 a>>= 6 a== 0 ifl a=r 13 a>>= 5 a&= 1
      elsel a== 1 ifl a= 2 elsel a== 2 ifl a= 4 elsel a= 8 endif endif endif
      b=a a=r 2 a+=b r=a 2
      a= 1 r=a 100 a= 4 r=a 101 a= 8 r=a 102
      a=0 r=a 8
      do
        a=r 2 a+= 2 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 24 a=r 2 a+= 3 r=a 2
        a=r 24 a&= 1 r=a 8 a=r 24 a>>= 1 a&= 3 r=a 9 a=r 24 a>>= 3 r=a 10
        a=r 9 a== 0 ifl
          a=r 10 a> 0 ifl
            do
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
c=r 4 *c=a out a=c a++ r=a 4
              a=r 10 a-- r=a 10
            a> 0 while
          endif
        elsel
        a=r 9 a== 1 ifl
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
          r=a 25 a=r 10 a> 0 ifl
            do
              a=r 25
c=r 4 *c=a out a=c a++ r=a 4
              a=r 10 a-- r=a 10
            a> 0 while
          endif
        elsel
          a=r 2 b=r 10 a+=b r=a 11
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
          r=a 25 a&= 3 r=a 14 a=r 25 a>>= 2 a&= 3 r=a 15
          a=r 14 a< 2 ifl
            a=r 15 a&= 1 a== 0 ifl
              a=r 25 a>>= 3 r=a 16
            elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              a<<= 4 r=a 16 a=r 25 a>>= 4 b=r 16 a+=b r=a 16
              a=r 15 a== 3 ifl
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
                a<<= 12 b=r 16 a+=b r=a 16
              endif
            endif
            a=r 14 a== 0 ifl
              a=r 2 r=a 6 b=r 16 a+=b r=a 2 r=a 7
            elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              r=a 25 a=r 126 r=a 6 c=a a=r 16 r=a 26
              a> 0 ifl
                do
                  a=r 25 *c=a c++ a=r 26 a-- r=a 26
                a> 0 while
              endif
              a=r 6 b=r 16 a+=b r=a 7
            endif
          elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
            r=a 26
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
            r=a 27
            a=r 15 a< 2 ifl
              a=r 26 a&= 63 a<<= 4 r=a 16 a=r 25 a>>= 4 b=r 16 a+=b r=a 16
              a=r 27 a<<= 2 r=a 17 a=r 26 a>>= 6 b=r 17 a+=b r=a 17
            elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              r=a 28
              a=r 15 a== 2 ifl
                a=r 27 a&= 3 a<<= 12 r=a 16 a=r 26 a<<= 4 b=r 16 a+=b r=a 16 a=r 25 a>>= 4 b=r 16 a+=b r=a 16
                a=r 28 a<<= 6 r=a 17 a=r 27 a>>= 2 b=r 17 a+=b r=a 17
              elsel
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
                r=a 29
                a=r 27 a&= 63 a<<= 12 r=a 16 a=r 26 a<<= 4 b=r 16 a+=b r=a 16 a=r 25 a>>= 4 b=r 16 a+=b r=a 16
                a=r 29 a<<= 10 r=a 17 a=r 28 a<<= 2 b=r 17 a+=b r=a 17 a=r 27 a>>= 6 b=r 17 a+=b r=a 17
              endif
            endif
            a=r 2 r=a 35 a=r 17 r=a 36 a=r 16 r=a 37 a=r 126 r=a 38 r=a 6 b=r 16 a+=b r=a 7
            a=r 14 a== 2 ifl
              a= 139 a<<= 3 r=a 76 a= 147 a<<= 3 r=a 77 a= 155 a<<= 3 r=a 78
  a=r 35 c=a a=*c r=a 46 a=r 35 a++ r=a 87
  a=r 46 a> 127 ifl
    a-= 127 r=a 64 a=0 r=a 66
    do
      a=r 66 a>>= 1 b=r 87 a+=b c=a a=*c r=a 69 a=r 66 a&= 1 a== 0 ifl
        a=r 69 a>>= 4
      elsel
        a=r 69 a&= 15
      endif
      r=a 69
a=r 66 b=r 95 a+=b d=a a=r 69 *d=a
      a=r 66 a++ r=a 66 b=r 64
    a<b while
    a=r 64 a++ a>>= 1 b=r 87 a+=b r=a 87
  elsel
    a=r 46 r=a 51 a=r 87 r=a 52
a=0 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 4 while
a=r 60 a+= 5 r=a 53
a=r 50 a+= 4 r=a 50
a= 1 b=r 53 a<<=b r=a 55 a++ r=a 54 a=r 53 a++ r=a 56
a=0 r=a 57 r=a 58
a=r 54 a> 1 ifl
do
  a=r 58 a> 0 ifl
    a=r 57 r=a 62
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 16 while
      a=r 60 b=a a= 255 a<<= 8 a+= 255 a==b ifl
        a=r 62 a+= 24 r=a 62
a=r 50 a+= 16 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
      a=r 60 a== 3 ifl
        a=r 62 a+= 3 r=a 62
a=r 50 a+= 2 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
    a=r 60 b=r 62 a+=b r=a 62
a=r 50 a+= 2 r=a 50
    a=r 57 b=r 62 a<b ifl
      do
        a= 1 r=a 61
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
        a=r 57 a++ r=a 57 b=r 62
      a<b while
    endif
  endif
  a=r 55 a<<= 1 a-- b=r 54 a-=b r=a 59
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
b=r 56 a<b while
  a=r 55 a-- b=a a=r 60 a&=b r=a 61 b=r 59
  a<b ifl
    a=r 56 a-- b=a a=r 50 a+=b r=a 50
  elsel
    a=r 55 a<<= 1 a-- b=a a=r 60 a&=b r=a 61 b=r 55
    a<b ifnot
      a=r 61 b=r 59 a-=b r=a 61
    endif
    a=r 56 b=a a=r 50 a+=b r=a 50
  endif
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
  a=r 57 a++ r=a 57
  a=r 61 a== 0 ifl
    a=r 54 a-- r=a 54
  elsel
    a-- b=a a=r 54 a-=b r=a 54
  endif
  a=r 61 a== 1 ifl a= 1 elsel a=0 endif r=a 58
  a=r 54 b=r 55 a<b ifl
    do
      a=r 56 a-- r=a 56 a=r 55 a>>= 1 r=a 55 b=a a=r 54
    a<b while
  endif
  a=r 54
a> 1 while
endif
a= 1 b=r 53 a<<=b r=a 81 a-- r=a 82
a=0 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a== 0 ifl
    a=r 66 r=a 69
a=r 82 b=r 76 a+=b d=a a=r 69 *d=a
    a=r 82 a-- r=a 82 a= 1 r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  elsel
    a-- r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=r 81 a>>= 1 r=a 83 a=r 81 a>>= 3 b=r 83 a+=b a+= 3 r=a 83
a=0 r=a 84 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a> 1 ifl
    a-- r=a 68
    do
      a=r 66 r=a 69
a=r 84 b=r 76 a+=b d=a a=r 69 *d=a
      do
        a=r 81 a-- r=a 69 a=r 84 b=r 83 a+=b b=r 69 a&=b r=a 84 b=r 82
      a>b while
      a=r 68 a-- r=a 68
    a> 0 while
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=0 r=a 66
do
a=r 66 b=r 76 a+=b d=a a=*d
  r=a 68
a=r 68 b=r 75 a+=b d=a a=*d
  r=a 67 a++ r=a 69
a=r 68 b=r 75 a+=b d=a a=r 69 *d=a
a=0 r=a 69 a=r 67 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 53 b=r 69 a-=b r=a 69
a=r 66 b=r 77 a+=b d=a a=r 69 *d=a
  b=a a=r 67 a<<=b b=r 81 a-=b r=a 69
a=r 66 b=r 78 a+=b d=a a=r 69 *d=a
  a=r 66 a++ r=a 66 b=r 81
a<b while
a=r 50 a+= 7 a>>= 3 r=a 69 b=r 52 a+=b r=a 46
a=r 51 b=r 69 a-=b r=a 69
a=r 69 r=a 92 a=r 46 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
a=0 r=a 85 a=r 53 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 85 a<<= 1 b=r 69 a+=b r=a 85
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 86 a=r 53 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 86 a<<= 1 b=r 69 a+=b r=a 86
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 64
do
a=r 85 b=r 76 a+=b d=a a=*d
  r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
a=r 85 b=r 77 a+=b d=a a=*d
  r=a 68
a=0 r=a 61 a=r 68 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 61 a<<= 1 b=r 69 a+=b r=a 61
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 85 b=r 78 a+=b d=a a=*d
  b=r 61 a+=b r=a 85
  a=r 42 a> 0 ifl
a=r 86 b=r 76 a+=b d=a a=*d
    r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
    a=r 64 a++ r=a 64
  endif
  a=r 42 a== 0 ifl
a=r 86 b=r 76 a+=b d=a a=*d
  r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
a=r 86 b=r 77 a+=b d=a a=*d
  r=a 68
a=0 r=a 61 a=r 68 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 61 a<<= 1 b=r 69 a+=b r=a 61
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 86 b=r 78 a+=b d=a a=*d
  b=r 61 a+=b r=a 86
  a=r 42 a> 0 ifl
a=r 85 b=r 76 a+=b d=a a=*d
    r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
    a=r 64 a++ r=a 64
  endif
  endif
a=r 42 a== 0 while
    a=r 87 b=r 51 a+=b r=a 87
  endif
  a=0 r=a 65 r=a 66
  do
a=r 66 b=r 95 a+=b d=a a=*d
    b=a a= 1 a<<=b a>>= 1 b=r 65 a+=b r=a 65
    a=r 66 a++ r=a 66 b=r 64
  a<b while
a=0 r=a 63 a=r 65 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 63 a++ r=a 63 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 63 a++ r=a 63
  a= 1 b=r 63 a<<=b b=r 65 a-=b r=a 46
a=0 r=a 69 a=r 46 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 69 a++ r=a 69
a=r 64 b=r 95 a+=b d=a a=r 69 *d=a
  a=r 64 a++ r=a 64
  a=0 r=a 66 r=a 69
  do
a=r 66 b=r 73 a+=b d=a a=r 69 *d=a
a=r 66 b=r 71 a+=b d=a a=r 69 *d=a
a=r 66 b=r 72 a+=b d=a a=r 69 *d=a
    a=r 66 a++ r=a 66
  a< 16 while
  a=0 r=a 66
  do
a=r 66 b=r 95 a+=b d=a a=*d
    a> 0 ifl
      b=a a=r 63 a++ a-=b r=a 68
a=r 68 b=r 73 a+=b d=a a=*d
      a++ r=a 69
a=r 68 b=r 73 a+=b d=a a=r 69 *d=a
    endif
    a=r 66 a++ r=a 66 b=r 64
  a<b while
  a=r 63 r=a 68 a=0 r=a 65 r=a 62
  do
    a=r 63 b=r 68 a-=b b=a a=r 65 a>>=b r=a 69
a=r 68 b=r 71 a+=b d=a a=r 69 *d=a
a=r 68 b=r 72 a+=b d=a a=r 62 *d=a
    a=0 r=a 66
    do
a=r 66 b=r 95 a+=b d=a a=*d
      a> 0 ifl
        b=a a=r 63 a++ a-=b b=r 68 a==b ifl
a=r 62 b=r 70 a+=b d=a a=r 66 *d=a
          a=r 62 a++ r=a 62
        endif
      endif
      a=r 66 a++ r=a 66 b=r 64
    a<b while
a=r 68 b=r 73 a+=b d=a a=*d
    r=a 69 a=r 63 b=r 68 a-=b b=a a=r 69 a<<=b b=r 65 a+=b r=a 65
    a=r 68 a-- r=a 68
  a> 0 while
            elsel
              a=r 2 r=a 87
            endif
            a=r 15 a== 0 ifl
  a=r 87 r=a 46 a=r 35 b=r 36 a+=b b=r 87 a-=b r=a 67
a=r 67 r=a 92 a=r 46 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
    a=r 37 r=a 45
    a=r 45 a> 0 ifl
    do
      a=0 r=a 43 r=a 44
      do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
        r=a 46 a=r 43 a<<= 1 b=r 46 a+=b r=a 43 a=r 44 a++ r=a 44
        b=r 71 a+=b d=a a=*d b=a a=r 43
      a<b while
      a-=b r=a 46 a=r 44 b=r 72 a+=b d=a a=*d b=r 46 a+=b b=r 70 a+=b d=a a=*d
      c=r 38 *c=a a=c a++ r=a 38
      a=r 45 a-- r=a 45
    a> 0 while
    endif
            elsel
  a=r 87 a+= 6 r=a 69 a=0 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 1 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 1 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 3 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 2 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 87 a+= 5 c=a a=*c a<<= 8 c-- a+=*c b=r 69 a+=b r=a 69 a= 3 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 35 b=r 36 a+=b r=a 69 a= 4 r=a 66
a=r 66 b=r 90 a+=b d=a a=r 69 *d=a
  a=r 37 a+= 3 a>>= 2 r=a 88
  a=0 r=a 89
  do
a=r 89 b=r 90 a+=b d=a a=*d
    r=a 46 a=r 89 a++ r=a 66
a=r 66 b=r 90 a+=b d=a a=*d
    b=r 46 a-=b r=a 67
a=r 67 r=a 92 a=r 46 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
    a=r 88 r=a 45 a=r 89 a== 3 ifl
      a=r 88 a<<= 1 b=r 88 a+=b b=a a=r 37 a-=b r=a 45
    endif
    a=r 45 a> 0 ifl
    do
      a=0 r=a 43 r=a 44
      do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
        r=a 46 a=r 43 a<<= 1 b=r 46 a+=b r=a 43 a=r 44 a++ r=a 44
        b=r 71 a+=b d=a a=*d b=a a=r 43
      a<b while
      a-=b r=a 46 a=r 44 b=r 72 a+=b d=a a=*d b=r 46 a+=b b=r 70 a+=b d=a a=*d
      c=r 38 *c=a a=c a++ r=a 38
      a=r 45 a-- r=a 45
    a> 0 while
    endif
    a=r 89 a++ r=a 89
  a< 4 while
            endif
            a=r 2 b=r 17 a+=b r=a 2
          endif
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
          r=a 18
          a> 127 ifl
            a== 255 ifl
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              r=a 25
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              a<<= 8 b=r 25 a+=b r=a 26 a= 127 a<<= 8 b=r 26 a+=b r=a 18
            elsel
              a-= 128 a<<= 8 r=a 25
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
              b=r 25 a+=b r=a 18
            endif
          endif
          a=r 18 a> 0 ifl
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
            r=a 19
            a=0 r=a 109
            do
              a=r 109 a<<= 3 b=r 127 a+=b d=a a=*d r=a 76 d++ a=*d r=a 77 d++ a=*d r=a 78
              d++ a=*d r=a 29 d++ a=*d r=a 30 d++ a=*d r=a 31 d++ a=*d b=a a=r 19 a>>=b a&= 3 r=a 28
              a== 0 ifl
                a=0 r=a 66
                do
                  a=r 66 b=r 29 a+=b d=a a=*d r=a 69
a=r 66 b=r 74 a+=b d=a a=r 69 *d=a
                  a=r 66 a++ r=a 66 b=r 30
                a<b while
                a=r 30 r=a 57 a=r 31 r=a 53
a= 1 b=r 53 a<<=b r=a 81 a-- r=a 82
a=0 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a== 0 ifl
    a=r 66 r=a 69
a=r 82 b=r 76 a+=b d=a a=r 69 *d=a
    a=r 82 a-- r=a 82 a= 1 r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  elsel
    a-- r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=r 81 a>>= 1 r=a 83 a=r 81 a>>= 3 b=r 83 a+=b a+= 3 r=a 83
a=0 r=a 84 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a> 1 ifl
    a-- r=a 68
    do
      a=r 66 r=a 69
a=r 84 b=r 76 a+=b d=a a=r 69 *d=a
      do
        a=r 81 a-- r=a 69 a=r 84 b=r 83 a+=b b=r 69 a&=b r=a 84 b=r 82
      a>b while
      a=r 68 a-- r=a 68
    a> 0 while
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=0 r=a 66
do
a=r 66 b=r 76 a+=b d=a a=*d
  r=a 68
a=r 68 b=r 75 a+=b d=a a=*d
  r=a 67 a++ r=a 69
a=r 68 b=r 75 a+=b d=a a=r 69 *d=a
a=0 r=a 69 a=r 67 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 53 b=r 69 a-=b r=a 69
a=r 66 b=r 77 a+=b d=a a=r 69 *d=a
  b=a a=r 67 a<<=b b=r 81 a-=b r=a 69
a=r 66 b=r 78 a+=b d=a a=r 69 *d=a
  a=r 66 a++ r=a 66 b=r 81
a<b while
                a=r 53 r=a 25
              elsel
              a=r 28 a== 1 ifl
a=r 2 c=a a=*c r=a 24 a=r 2 a++ r=a 2 a=r 24
                c=a a=r 76 d=a a=c *d=a a=r 77 d=a a=0 *d=a a=r 78 d=a a=0 *d=a r=a 25
              elsel
              a=r 28 a== 2 ifl
                a=r 11 b=r 2 a-=b r=a 51 a=r 2 r=a 52
a=0 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 4 while
a=r 60 a+= 5 r=a 53
a=r 50 a+= 4 r=a 50
a= 1 b=r 53 a<<=b r=a 55 a++ r=a 54 a=r 53 a++ r=a 56
a=0 r=a 57 r=a 58
a=r 54 a> 1 ifl
do
  a=r 58 a> 0 ifl
    a=r 57 r=a 62
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 16 while
      a=r 60 b=a a= 255 a<<= 8 a+= 255 a==b ifl
        a=r 62 a+= 24 r=a 62
a=r 50 a+= 16 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
    do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
      a=r 60 a== 3 ifl
        a=r 62 a+= 3 r=a 62
a=r 50 a+= 2 r=a 50
        a= 1
      elsel
        a=0
      endif
    a> 0 while
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 2 while
    a=r 60 b=r 62 a+=b r=a 62
a=r 50 a+= 2 r=a 50
    a=r 57 b=r 62 a<b ifl
      do
        a= 1 r=a 61
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
        a=r 57 a++ r=a 57 b=r 62
      a<b while
    endif
  endif
  a=r 55 a<<= 1 a-- b=r 54 a-=b r=a 59
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 51
  a<b ifl
    b=r 52 a+=b c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1
    b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
b=r 56 a<b while
  a=r 55 a-- b=a a=r 60 a&=b r=a 61 b=r 59
  a<b ifl
    a=r 56 a-- b=a a=r 50 a+=b r=a 50
  elsel
    a=r 55 a<<= 1 a-- b=a a=r 60 a&=b r=a 61 b=r 55
    a<b ifnot
      a=r 61 b=r 59 a-=b r=a 61
    endif
    a=r 56 b=a a=r 50 a+=b r=a 50
  endif
a=r 57 b=r 74 a+=b d=a a=r 61 *d=a
  a=r 57 a++ r=a 57
  a=r 61 a== 0 ifl
    a=r 54 a-- r=a 54
  elsel
    a-- b=a a=r 54 a-=b r=a 54
  endif
  a=r 61 a== 1 ifl a= 1 elsel a=0 endif r=a 58
  a=r 54 b=r 55 a<b ifl
    do
      a=r 56 a-- r=a 56 a=r 55 a>>= 1 r=a 55 b=a a=r 54
    a<b while
  endif
  a=r 54
a> 1 while
endif
a= 1 b=r 53 a<<=b r=a 81 a-- r=a 82
a=0 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a== 0 ifl
    a=r 66 r=a 69
a=r 82 b=r 76 a+=b d=a a=r 69 *d=a
    a=r 82 a-- r=a 82 a= 1 r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  elsel
    a-- r=a 69
a=r 66 b=r 75 a+=b d=a a=r 69 *d=a
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=r 81 a>>= 1 r=a 83 a=r 81 a>>= 3 b=r 83 a+=b a+= 3 r=a 83
a=0 r=a 84 r=a 66
do
a=r 66 b=r 74 a+=b d=a a=*d
  a> 1 ifl
    a-- r=a 68
    do
      a=r 66 r=a 69
a=r 84 b=r 76 a+=b d=a a=r 69 *d=a
      do
        a=r 81 a-- r=a 69 a=r 84 b=r 83 a+=b b=r 69 a&=b r=a 84 b=r 82
      a>b while
      a=r 68 a-- r=a 68
    a> 0 while
  endif
  a=r 66 a++ r=a 66 b=r 57
a<b while
a=0 r=a 66
do
a=r 66 b=r 76 a+=b d=a a=*d
  r=a 68
a=r 68 b=r 75 a+=b d=a a=*d
  r=a 67 a++ r=a 69
a=r 68 b=r 75 a+=b d=a a=r 69 *d=a
a=0 r=a 69 a=r 67 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 69 a++ r=a 69 a=r 91 a>>= 1
  a> 0 while
endif
  a=r 53 b=r 69 a-=b r=a 69
a=r 66 b=r 77 a+=b d=a a=r 69 *d=a
  b=a a=r 67 a<<=b b=r 81 a-=b r=a 69
a=r 66 b=r 78 a+=b d=a a=r 69 *d=a
  a=r 66 a++ r=a 66 b=r 81
a<b while
                a=r 50 a+= 7 a>>= 3 b=r 2 a+=b r=a 2 a=r 53 r=a 25
              elsel
                a=r 109 a<<= 3 b=r 127 a+=b a+= 7 d=a a=*d r=a 25
              endif
              endif
              endif
              a=r 109 a<<= 3 b=r 127 a+=b a+= 7 d=a a=r 25 *d=a
              a=r 109 a++ r=a 109
            a< 3 while
            a=r 127 a+= 7 d=a a=*d r=a 103 a=r 127 a+= 15 d=a a=*d r=a 104 a=r 127 a+= 23 d=a a=*d r=a 105
            a=r 11 b=r 2 a-=b r=a 29 a=r 2 r=a 30
a=r 29 r=a 92 a=r 30 r=a 41 b=r 92 a+=b a-- c=a a=*c r=a 93
a=0 r=a 94 a=r 93 a>>= 1
a> 0 ifl
  do
    r=a 91 a=r 94 a++ r=a 94 a=r 91 a>>= 1
  a> 0 while
endif
a=r 92 a-- a<<= 3 b=r 94 a+=b r=a 40 a=0 r=a 42
a=0 r=a 106 a=r 103 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 106 a<<= 1 b=r 69 a+=b r=a 106
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 107 a=r 104 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 107 a<<= 1 b=r 69 a+=b r=a 107
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=0 r=a 108 a=r 105 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 108 a<<= 1 b=r 69 a+=b r=a 108
    a=r 67 a-- r=a 67
  a> 0 while
endif
            a=r 18 r=a 20
            do
a=r 107 b=r 116 a+=b d=a a=*d
              r=a 26
a=r 108 b=r 113 a+=b d=a a=*d
              r=a 27
a=r 106 b=r 110 a+=b d=a a=*d
              r=a 28
a=0 r=a 23 a=r 26 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 23 a<<= 1 b=r 69 a+=b r=a 23
    a=r 67 a-- r=a 67
  a> 0 while
endif
              a= 1 b=r 26 a<<=b b=r 23 a+=b r=a 23
a=r 27 b=r 122 a+=b d=a a=*d
              r=a 29
a=0 r=a 24 a=r 29 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 24 a<<= 1 b=r 69 a+=b r=a 24
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 27 b=r 121 a+=b d=a a=*d
              b=r 24 a+=b r=a 22
a=r 28 b=r 120 a+=b d=a a=*d
              r=a 29
a=0 r=a 24 a=r 29 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 24 a<<= 1 b=r 69 a+=b r=a 24
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 28 b=r 119 a+=b d=a a=*d
              b=r 24 a+=b r=a 21
              a=r 23 a> 3 ifl
                a-= 3 r=a 23 a=r 101 r=a 102 a=r 100 r=a 101 a=r 23 r=a 100
              elsel
                a=r 21 a== 0 ifl a=r 23 a++ r=a 23 endif
                a=r 23 a== 1 ifl
                  a=r 100 r=a 23
                elsel
                a=r 23 a== 2 ifl
                  a=r 101 r=a 23 a=r 100 r=a 101 a=r 23 r=a 100
                elsel
                a=r 23 a== 3 ifl
                  a=r 102 r=a 23 a=r 101 r=a 102 a=r 100 r=a 101 a=r 23 r=a 100
                elsel
                  a=r 100 a-- r=a 23 a=r 101 r=a 102 a=r 100 r=a 101 a=r 23 r=a 100
                endif
                endif
                endif
              endif
              a=r 21 a> 0 ifl
                do
                  a=r 6 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
                  a=r 6 a++ r=a 6 a=r 21 a-- r=a 21
                a> 0 while
              endif
              a=r 4 b=r 23 a-=b r=a 24 a=r 22
              a> 0 ifl
                do
                  a=r 24 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
                  a=r 24 a++ r=a 24 a=r 22 a-- r=a 22
                a> 0 while
              endif
              a=r 20 a-- r=a 20
              a> 0 ifl
a=r 106 b=r 111 a+=b d=a a=*d
                r=a 29
a=0 r=a 24 a=r 29 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 24 a<<= 1 b=r 69 a+=b r=a 24
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 106 b=r 112 a+=b d=a a=*d
                b=r 24 a+=b r=a 106
a=r 108 b=r 114 a+=b d=a a=*d
                r=a 29
a=0 r=a 24 a=r 29 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 24 a<<= 1 b=r 69 a+=b r=a 24
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 108 b=r 115 a+=b d=a a=*d
                b=r 24 a+=b r=a 108
a=r 107 b=r 117 a+=b d=a a=*d
                r=a 29
a=0 r=a 24 a=r 29 r=a 67
a> 0 ifl
  do
a=r 40 a== 0 ifl
  a= 1 r=a 42 a=0
elsel
  a-- r=a 40 a>>= 3 b=r 41 a+=b c=a
  a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
endif
    r=a 69 a=r 24 a<<= 1 b=r 69 a+=b r=a 24
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 107 b=r 118 a+=b d=a a=*d
                b=r 24 a+=b r=a 107
              endif
              a=r 20
            a> 0 while
          endif
          a=r 7 b=r 6 a>b ifl
            do
              a=r 6 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
              a=r 6 a++ r=a 6 b=r 7
            a<b while
          endif
          a=r 11 r=a 2
        endif
        endif
        a=r 8
      a== 0 while
      a=r 13 a>>= 2 a&= 1 a> 0 ifl a=r 2 a+= 4 r=a 2 endif
    endif
  endif
  a=r 12
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZZST";
