#!/usr/bin/env python3
# Generador de ZPAQKANZI: decodificador de kanzi 2.6.0 (bitstream v7, headerless),
# niveles 1 (LZX, sin entropia) y 2 (DNA+LZ, Huffman), en ZPAQL. zpaq-std, 2026.
# ZPAQL no tiene subrutinas: las macros se expanden en linea.
# Entrada del PCOMP: orig (4 LE), nivel (1), el flujo headerless de kanzi.
# M: la entrada desde 0; 32 ceros; A (salida de la entropia) en AB; B (salida de LZ)
# en BB = AB + pre + 32. La salida va con out.
# H: T (tabla de Huffman, 4096 palabras), SIZE, CNT, ORD, IDX2, MAP.
import sys, os
# KZROBUST=1: la version robusta ante datos danados (pre54); sin ella sale el programa congelado
ROBUST = os.environ.get('KZROBUST') == '1'
out = []
def e(s): out.append(s)

# registros
N, POS, AB, BB, PRE, LEVEL, SKIP, MODE, NEXT, READ = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
T1, T2, T3, T4, T5 = 11, 12, 13, 14, 15
LR, DSZ, COPY, TCOPY, SRC, LEN, DST = 16, 17, 18, 19, 20, 21, 22
# Huffman
HN, K, CUR, LOG2, BASE, CODE, CL, SZ0, Q, FP, P, KK, II, S, L = 30, 31, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 46, 47
# SZ0..SZ0+3 = 37..40
# LZ
TK, MI, ML, SE, MM, SI, DI, R0, R1, TOK, MLEN, DIST, W, LIT, CNT = 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64
# DNA
DN, ADJ, SEND, V = 70, 71, 72, 73

HT, HSIZE, HCNT, HORD, HIDX2, HMAP = 0, 4096, 4352, 4400, 4656, 4672
assert HMAP + 256 <= 8192

def LK(v):                    # a = v
    if v < 256: e(f"a= {v}"); return
    bs = []
    while v: bs.append(v & 255); v >>= 8
    e(f"a= {bs[-1]}")
    for b in reversed(bs[:-1]):
        e(f"a<<= 8 a+= {b}" if b else "a<<= 8")

def WORD():                   # a = 32 bits desde POS (el bit POS arriba); usa b, c
    e(f"a=r {POS} a&= 7 b=a a=r {POS} a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b")
def GETK(k, dst):             # r dst = k bits (1..24), MSB primero
    WORD(); e(f"a>>= {32 - k} r=a {dst} a=r {POS} a+= {k} r=a {POS}")
def GETR(kreg, dst):          # r dst = r kreg bits (0..24)
    e(f"a=r {kreg} a> 0 ifl")
    WORD(); e(f"  r=a {T5} a= 32 b=r {kreg} a-=b b=a a=r {T5} a>>=b r=a {dst} a=r {POS} b=r {kreg} a+=b r=a {POS}")
    e(f"elsel a=0 r=a {dst} endif")
def MB(basereg, idxreg):      # a = M[r base + r idx]
    e(f"a=r {basereg} b=r {idxreg} a+=b c=a a=*c")
def MBSET(basereg, idxreg, valreg):
    e(f"a=r {basereg} b=r {idxreg} a+=b c=a a=r {valreg} *c=a")
def HGETK(base, idxreg, dst):  # r dst = H[base + r idx]
    LK(base); e(f"b=r {idxreg} a+=b d=a a=*d r=a {dst}")
def HSETK(base, idxreg, valreg):
    LK(base); e(f"b=r {idxreg} a+=b d=a a=r {valreg} *d=a")
def LE32(basereg, off, dst):  # r dst = LE32 M[r base + off]
    e(f"a=r {basereg} a+= {off + 3} c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a {dst}")
def INC(r, n=1): e(f"a=r {r} a+= {n} r=a {r}")

# ---------------------------------------------------------------------------
def HUFFMAN():                # A[0..PRE) desde el flujo
    e(f"a=0 r=a {DST}")
    e("do")
    # HN = min(16384, PRE - DST)
    e(f"  a=r {PRE} b=r {DST} a-=b r=a {HN}")
    LK(16384); e(f"  b=a a=r {HN} a>b ifl a=b r=a {HN} endif")
    e(f"  a=r {HN} a< 32 ifl")
    e(f"    a=0 r=a {II}")
    e("    do")
    GETK(8, T1)
    e(f"      a=r {DST} b=r {II} a+=b r=a {T2}"); MBSET(AB, T2, T1)
    INC(II); e(f"      a=r {II} b=r {HN} a<b")
    e("    while")
    e("  elsel")
    # tamanos a 0
    e(f"    a=0 r=a {II}")
    e("    do")
    e(f"      a=0 r=a {T1}"); HSETK(HSIZE, II, T1)
    INC(II); e(f"      a=r {II} a> 255 until")
    # alfabeto -> ORD provisional (en orden de simbolo), K = cuenta
    e(f"    a=0 r=a {K}")
    GETK(1, T1)
    e(f"    a=r {T1} a== 0 ifl")
    GETK(1, T1)                         # 0 = 256 simbolos (el otro caso es un error)
    e(f"      a=0 r=a {II}")
    e("      do")
    HSETK(HORD, II, II)
    INC(II); e(f"        a=r {II} a> 255 until")
    e(f"      a= 1 a<<= 8 r=a {K}")
    e("    elsel")
    GETK(5, T3)                         # ultima mascara
    e(f"      a=0 r=a {II}")
    e("      do")
    GETK(8, T4)
    e(f"        a=0 r=a {KK}")
    e("        do")
    e(f"          a=r {T4} b=r {KK} a>>=b a&= 1 a> 0 ifl")
    e(f"            a=r {II} a<<= 3 b=r {KK} a+=b r=a {T1}"); HSETK(HORD, K, T1); INC(K)
    e("          endif")
    INC(KK); e(f"          a=r {KK} a< 8")
    e("        while")
    INC(II); e(f"        a=r {T3} b=r {II} a<b")
    e("      until")
    e("    endif")
    # tamanos: cur = 2, cur += ExpGolomb con signo
    e(f"    a= 2 r=a {CUR} a=0 r=a {II}")
    e("    do")
    HGETK(HORD, II, S)
    GETK(1, T1)
    e(f"      a=r {T1} a== 0 ifl")
    e(f"        a= 1 r=a {LOG2}")
    e("        do")
    GETK(1, T1)
    e(f"          a=r {T1} a== 0 ifl a=r {LOG2} a++ r=a {LOG2} endif")
    e(f"          a=r {T1} a== 0")
    e("        while")
    e(f"        a=r {LOG2} a> 7 ifl a= 7 r=a {LOG2} endif")
    e(f"        a= 1 b=r {LOG2} a<<=b a-- r=a {BASE}")
    e(f"        a=r {LOG2} a++ r=a {T2}"); GETR(T2, T3)
    e(f"        a=r {T3} a>>= 1 b=r {BASE} a+=b r=a {T4}")
    e(f"        a=r {T3} a&= 1 a> 0 ifl")
    e(f"          a=r {CUR} b=r {T4} a-=b r=a {CUR}")
    e("        elsel")
    e(f"          a=r {CUR} b=r {T4} a+=b r=a {CUR}")
    e("        endif")
    e("      endif")
    if ROBUST: e(f"      a=r {CUR} a-- a> 11 ifl error endif")   # largo 1..12, como kanzi
    HSETK(HSIZE, S, CUR)
    INC(II); e(f"      a=r {II} b=r {K} a<b")
    e("    while")
    e(f"    a=r {K} a== 1 ifl")          # un solo simbolo
    HGETK(HORD, II, S)                   # II == 1 aca; ORD[0] esta en HORD+0
    e(f"      a=0 r=a {T2}"); HGETK(HORD, T2, S)
    e(f"      a=0 r=a {II}")
    e("      do")
    e(f"        a=r {DST} b=r {II} a+=b r=a {T2}"); MBSET(AB, T2, S)
    INC(II); e(f"        a=r {II} b=r {HN} a<b")
    e("      while")
    e("    elsel")
    # canonico: CNT[len] = cuenta, luego offsets; ORD = simbolos por (len, simbolo)
    e(f"      a=0 r=a {II}")
    e("      do")
    e(f"        a=0 r=a {T1}"); HSETK(HCNT, II, T1)
    INC(II); e(f"        a=r {II} a< 13")
    e("      while")
    e(f"      a=0 r=a {II}")
    e("      do")
    HGETK(HSIZE, II, L)
    e(f"        a=r {L} a> 0 ifl"); HGETK(HCNT, L, T1); INC(T1); HSETK(HCNT, L, T1); e("        endif")
    INC(II); e(f"        a=r {II} a> 255")
    e("      until")
    e(f"      a=0 r=a {T2} a= 1 r=a {II}")          # T2 = offset acumulado
    e("      do")
    HGETK(HCNT, II, T1); HSETK(HCNT, II, T2)
    e(f"        a=r {T2} b=r {T1} a+=b r=a {T2}")
    INC(II); e(f"        a=r {II} a< 13")
    e("      while")
    e(f"      a=0 r=a {II}")
    e("      do")
    HGETK(HSIZE, II, L)
    e(f"        a=r {L} a> 0 ifl")
    HGETK(HCNT, L, T1); HSETK(HORD, T1, II); INC(T1); HSETK(HCNT, L, T1)
    e("        endif")
    INC(II); e(f"        a=r {II} a> 255")
    e("      until")
    # codigos y tabla
    e(f"      a=0 r=a {CODE} r=a {T2}"); HGETK(HORD, T2, S); HGETK(HSIZE, S, CL)
    e(f"      a=0 r=a {II}")
    e("      do")
    HGETK(HORD, II, S); HGETK(HSIZE, S, L)
    e(f"        a=r {L} b=r {CL} a-=b b=a a=r {CODE} a<<=b r=a {CODE} a=r {L} r=a {CL}")
    # T[code << (12-l) ...] = s<<8 | l, 1 << (12-l) veces
    e(f"        a= 12 b=r {L} a-=b r=a {T3} a=r {CODE} b=r {T3} a<<=b r=a {T1}")   # inicio
    e(f"        a= 1 b=r {T3} a<<=b r=a {T4}")                                   # cuenta
    e(f"        a=r {S} a<<= 8 b=r {L} a+=b r=a {T3}")                            # valor
    e(f"        a=r {T1} d=a")
    e("        do")
    e(f"          a=r {T3} *d=a d++ a=r {T4} a-- r=a {T4} a> 0")
    e("        while")
    INC(CODE)
    INC(II); e(f"        a=r {II} b=r {K} a<b")
    e("      while")
    # 4 tamanos en bits
    for k in range(4):
        e(f"      a=0 r=a {SZ0 + k}")
        # varint: 7 bits por byte
        e(f"      a=0 r=a {T2}")                 # shift
        e("      do")
        GETK(8, T1)
        e(f"        a=r {T1} a&= 127 b=r {T2} a<<=b b=a a=r {SZ0 + k} a|=b r=a {SZ0 + k}")
        e(f"        a=r {T2} a+= 7 r=a {T2} a=r {T1} a> 127")
        e("      while")
    e(f"      a=r {HN} a>>= 2 r=a {Q}")
    e(f"      a=r {POS} r=a {FP}")
    for k in range(4):
        e(f"      a=r {FP} r=a {P}")
        e(f"      a=r {Q} a> 0 ifl")
        e(f"        a=r {Q} b= {k} a*=b b=r {DST} a+=b b=r {AB} a+=b r=a {T4}")   # destino
        e(f"        a=r {Q} r=a {II}")
        e("        do")
        e(f"          a=r {P} a&= 7 b=a a=r {P} a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b")
        e("          a>>= 20 d=a a=*d")           # HT = 0
        e(f"          r=a {T1} a&= 255 b=r {P} a+=b r=a {P}")
        e(f"          a=r {T1} a>>= 8 c=r {T4} *c=a c++ a=c r=a {T4}")
        e(f"          a=r {II} a-- r=a {II} a> 0")
        e("        while")
        e("      endif")
        e(f"      a=r {FP} b=r {SZ0 + k} a+=b r=a {FP}")
    e(f"      a=r {FP} r=a {POS}")
    e(f"      a=r {Q} a<<= 2 r=a {II}")
    e(f"      a=r {II} b=r {HN} a<b ifl")
    e("        do")
    GETK(8, T1)
    e(f"          a=r {DST} b=r {II} a+=b r=a {T2}"); MBSET(AB, T2, T1)
    INC(II); e(f"          a=r {II} b=r {HN} a<b")
    e("        while")
    e("      endif")
    e("    endif")
    e("  endif")
    e(f"  a=r {DST} b=r {HN} a+=b r=a {DST} b=r {PRE} a<b")
    e("while")

def RAW_TO_A():               # A[0..PRE) = PRE bytes crudos del flujo
    e(f"a=0 r=a {II}")
    e(f"a=r {PRE} a> 0 ifl")
    e("  do")
    GETK(8, T1); MBSET(AB, II, T1)
    INC(II); e(f"    a=r {II} b=r {PRE} a<b")
    e("  while")
    e("endif")

def RL(posreg, dst):          # r dst = readLength(S, r pos)
    MB(SRC, posreg); e(f"r=a {dst}"); INC(posreg)
    e(f"a=r {dst} a> 253 ifl")
    e(f"  a== 254 ifl")
    MB(SRC, posreg); e(f"    a<<= 8 r=a {T5}"); INC(posreg); MB(SRC, posreg); e(f"    b=r {T5} a+=b a+= 254 r=a {dst}"); INC(posreg)
    e("  elsel")
    MB(SRC, posreg); e(f"    a<<= 8 r=a {T5}"); INC(posreg); MB(SRC, posreg); e(f"    b=r {T5} a+=b a<<= 8 r=a {T5}"); INC(posreg)
    MB(SRC, posreg); e(f"    b=r {T5} a+=b a+= 255 r=a {dst}"); INC(posreg)
    e("  endif")
    e("endif")

def LZ():                     # M[SRC..+LEN) -> M[BB..), LEN = largo de la salida
    LE32(SRC, 0, TK); LE32(SRC, 4, MI); LE32(SRC, 8, ML)
    e(f"a=r {MI} b=r {TK} a+=b r=a {MI} a=r {ML} b=r {MI} a+=b r=a {ML}")
    e(f"a=r {TK} a-= 13 r=a {SE}")
    e(f"a=r {SRC} a+= 12 c=a a=*c a>>= 1 a&= 7 a+= 2 r=a {MM}")
    e(f"a= 13 r=a {SI} a=0 r=a {DI} a=r {LEN} r=a {R0} r=a {R1}")
    e("do")
    MB(SRC, TK); e(f"  r=a {TOK}"); INC(TK)
    e(f"  a=r {TOK} a&= 24 a== 0 ifl")
    e(f"    a=r {TOK} a&= 3 r=a {MLEN} a== 3 ifl")
    RL(ML, T2); e(f"      a=r {MLEN} b=r {T2} a+=b b=r {MM} a+=b r=a {MLEN}")
    e(f"    elsel a=r {MLEN} b=r {MM} a+=b r=a {MLEN} endif")
    e(f"    a=r {TOK} a&= 4 a== 0 ifl a=r {R0} elsel a=r {R1} endif r=a {DIST}")
    e("  elsel")
    e(f"    a=r {TOK} a&= 7 r=a {MLEN} a== 7 ifl")
    RL(ML, T2); e(f"      a=r {MLEN} b=r {T2} a+=b b=r {MM} a+=b r=a {MLEN}")
    e(f"    elsel a=r {MLEN} b=r {MM} a+=b r=a {MLEN} endif")
    e(f"    a=r {TOK} a>>= 3 a&= 3 r=a {W}")
    # v = BE32 en S+mi
    e(f"    a=r {SRC} b=r {MI} a+=b c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c r=a {T1}")
    e(f"    a=r {W} a== 1 ifl a=r {T1} a>>= 24 a+= 1 elsel")
    e(f"    a=r {W} a== 2 ifl a=r {T1} a>>= 16 a+= 1 a+= 1 a+= 255 elsel")
    e(f"      a=r {T1} a>>= 8 r=a {T1}"); LK(65793); e(f"      b=r {T1} a+=b")
    e("    endif endif")
    e(f"    r=a {DIST} a=r {MI} b=r {W} a+=b r=a {MI}")
    e("  endif")
    e(f"  a=0 r=a {T4}")                         # T4 = 1 si se corta
    e(f"  a=r {TOK} a> 31 ifl")
    e(f"    a=r {TOK} a> 223 ifl")
    RL(SI, T2); e(f"      a=r {T2} a+= 7 r=a {LIT}")
    e(f"    elsel a=r {TOK} a>>= 5 r=a {LIT} endif")
    e(f"    a=r {LIT} a> 0 ifl")
    e("      do")
    MB(SRC, SI); e(f"        r=a {T1}"); MBSET(BB, DI, T1); INC(SI); INC(DI)
    e(f"        a=r {LIT} a-- r=a {LIT} a> 0")
    e("      while")
    e("    endif")
    e(f"    a=r {SI} b=r {SE} a<b ifnot a= 1 r=a {T4} endif")
    e("  endif")
    e(f"  a=r {T4} a== 0 ifl")
    e(f"    a=r {R0} r=a {R1} a=r {DIST} r=a {R0}")
    e(f"    a=r {BB} b=r {DI} a+=b r=a {T2} b=r {DIST} a-=b r=a {T3}")   # T2 destino, T3 origen
    e(f"    a=r {MLEN} a> 0 ifl")
    e("      do")
    e(f"        a=r {T3} c=a a=*c b=a a=r {T2} c=a a=b *c=a")
    INC(T2); INC(T3)
    e(f"        a=r {MLEN} a-- r=a {MLEN} a> 0")
    e("      while")
    e("    endif")
    e(f"    a=r {T2} b=r {BB} a-=b r=a {DI}")
    e("  endif")
    e(f"  a=r {T4} a> 0")
    e("until")
    e(f"a=r {DI} r=a {LEN}")

def OUTBUF():                 # out M[SRC..+LEN)
    e(f"a=r {LEN} a> 0 ifl")
    e(f"  a=r {SRC} r=a {T1} a=r {LEN} r=a {T2}")
    e("  do")
    e(f"    a=r {T1} c=a a=*c out a=r {T1} a++ r=a {T1} a=r {T2} a-- r=a {T2} a> 0")
    e("  while")
    e("endif")

def DNA():                    # M[SRC..+LEN) -> out
    e(f"a=0 r=a {T1}"); MB(SRC, T1); e(f"r=a {DN}")
    e(f"a=r {DN} a> 239 ifl")
    e(f"  a= 1 a<<= 8 b=r {DN} a-=b r=a {DN}")
    e(f"  a=r {DN} a== 1 ifl")
    e(f"    a= 1 r=a {T1}"); MB(SRC, T1); e(f"    r=a {V}"); LE32(SRC, 2, T2)
    e(f"    a=r {T2} a> 0 ifl")
    e("      do")
    e(f"        a=r {V} out a=r {T2} a-- r=a {T2} a> 0")
    e("      while")
    e("    endif")
    e("  elsel")
    e(f"    a=0 r=a {II}")
    e("    do")
    e(f"      a=r {II} a++ r=a {T1}"); MB(SRC, T1); e(f"      r=a {T1}"); HSETK(HIDX2, II, T1)
    INC(II); e(f"      a=r {II} b=r {DN} a<b")
    e("    while")
    e(f"    a=r {DN} a++ r=a {T1}"); MB(SRC, T1); e(f"    r=a {ADJ} a=r {DN} a+= 2 r=a {SI}")
    e(f"    a=r {DN} a< 5 ifl")
    e(f"      a=r {ADJ} a> 0 ifl")
    e("        do")
    MB(SRC, SI); e(f"          out"); INC(SI)
    e(f"          a=r {ADJ} a-- r=a {ADJ} a> 0")
    e("        while")
    e("      endif")
    e(f"      a=r {SI} b=r {LEN} a<b ifl")
    e("        do")
    MB(SRC, SI); e(f"          r=a {V}"); INC(SI)
    for sh in (6, 4, 2, 0):
        e(f"          a=r {V} a>>= {sh} a&= 3 r=a {T1}"); HGETK(HIDX2, T1, T1); e("          out")
    e(f"          a=r {SI} b=r {LEN} a<b")
    e("        while")
    e("      endif")
    e("    elsel")
    e(f"      a=r {ADJ} a> 0 ifl"); MB(SRC, SI); e("        out"); INC(SI); e("      endif")
    e(f"      a=r {SI} b=r {LEN} a<b ifl")
    e("        do")
    MB(SRC, SI); e(f"          r=a {V}"); INC(SI)
    e(f"          a=r {V} a>>= 4 r=a {T1}"); HGETK(HIDX2, T1, T1); e("          out")
    e(f"          a=r {V} a&= 15 r=a {T1}"); HGETK(HIDX2, T1, T1); e("          out")
    e(f"          a=r {SI} b=r {LEN} a<b")
    e("        while")
    e("      endif")
    e("    endif")
    e("  endif")
    e("elsel")
    e(f"  a= 1 r=a {T1}"); MB(SRC, T1); e(f"  r=a {ADJ} a=r {LEN} b=r {ADJ} a-=b r=a {SEND} a= 2 r=a {SI}")
    e(f"  a=0 r=a {II}")
    e("  do")
    e(f"    a= 1 a<<= 16 b=r {II} a+=b r=a {T1}"); HSETK(HMAP, II, T1)
    INC(II); e(f"    a=r {II} a> 255")
    e("  until")
    e(f"  a=r {DN} r=a {KK}")
    if ROBUST: e(f"  a=r {KK} a> 0 ifl")     # DN = 0 (dato danado)
    e("  do")
    e(f"    a=r {SI} a+= 2 r=a {T1}"); MB(SRC, T1); e(f"    r=a {T3}")            # simbolo
    MB(SRC, SI); e(f"    r=a {T1}"); INC(SI); MB(SRC, SI); e(f"    a<<= 8 b=r {T1} a+=b r=a {T1}"); INC(SI); INC(SI)
    e(f"    a= 2 a<<= 16 b=r {T1} a+=b r=a {T1}"); HSETK(HMAP, T3, T1)
    e(f"    a=r {KK} a-- r=a {KK} a> 0")
    e("  while")
    if ROBUST: e("  endif")
    e(f"  a=r {SI} b=r {SEND} a<b ifl")
    e("    do")
    MB(SRC, SI); e(f"      r=a {T1}"); INC(SI); HGETK(HMAP, T1, V)
    e(f"      a=r {V} out a=r {V} a>>= 16 a== 2 ifl a=r {V} a>>= 8 out endif")
    e(f"      a=r {SI} b=r {SEND} a<b")
    e("    while")
    e("  endif")
    e(f"  a=r {ADJ} a> 0 ifl"); MB(SRC, SI); e("    out"); e("  endif")
    e("endif")

# ---------------------------------------------------------------------------
e("hcomp")
e("halt")
e("pcomp zpaqkanzi1b ;" if ROBUST else "pcomp zpaqkanzi ;")
e("""(ZPAQKANZI: decodificador de kanzi 2.6.0, bitstream 7 sin cabecera, niveles 1 LZX
 y 2 DNA+LZ con Huffman, en ZPAQL, para zpaq-std -ma:kanzi. zpaq-std, 2026.
 Guarda el flujo en M y lo decodifica al final.)""")
e("a> 255 ifl")
e(f"  a=c r=a {N}")
e(f"  a=0 r=a {T1} do *c=a c++ a=r {T1} a++ r=a {T1} a< 32 while")
e(f"  a= 4 c=a a=*c r=a {LEVEL}")
e(f"  a= 40 r=a {POS} a=r {N} a+= 32 r=a {AB}")
e("  do")
GETK(5, LR); INC(LR, 3)
e(f"    a=r {LR} a> 24 ifl")
e(f"      a=r {LR} a-= 24 r=a {T1}"); GETR(T1, T2); GETK(24, T3)
e(f"      a=r {T2} a<<= 24 b=r {T3} a+=b r=a {READ}")
e("    elsel")
GETR(LR, READ)
e("    endif")
e(f"    a=r {READ} a> 0 ifl")
e(f"      a=r {POS} b=r {READ} a+=b r=a {NEXT}")
GETK(8, MODE)
e(f"      a=r {MODE} a&= 128 r=a {COPY} a=0 r=a {TCOPY}")
e(f"      a=r {COPY} a> 0 ifl a=r {MODE} a&= 16 a> 0 ifl a= 1 r=a {TCOPY} endif endif")
e(f"      a=r {COPY} a== 0 ifl a=r {MODE} a&= 16 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif")
e("      a> 0 ifl")
GETK(8, SKIP)
e("      elsel")
e(f"        a=r {MODE} a<<= 4 a|= 15 a&= 255 r=a {SKIP}")
e("      endif")
e(f"      a=r {MODE} a>>= 5 a&= 3 a++ r=a {DSZ} a=0 r=a {PRE}")
e("      do")
GETK(8, T1)
e(f"        a=r {PRE} a<<= 8 b=r {T1} a+=b r=a {PRE} a=r {DSZ} a-- r=a {DSZ} a> 0")
e("      while")
GETK(8, T1)                     # checksum de la cabecera del bloque (no se verifica)
e(f"      a=r {COPY} a> 0 ifl a=r {TCOPY} a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif")
e("      a> 0 ifl")              # copia cruda: sin transformaciones ni entropia
e(f"        a=r {PRE} a> 0 ifl")
e("          do")
GETK(8, T1)
e(f"            a=r {T1} out a=r {PRE} a-- r=a {PRE} a> 0")
e("          while")
e("        endif")
e("      elsel")
e(f"        a=r {LEVEL} a== 2 ifl a=r {TCOPY} a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif")
e("        a> 0 ifl")
HUFFMAN()
e("        elsel")
RAW_TO_A()
e("        endif")
e(f"        a=r {AB} r=a {SRC} a=r {PRE} r=a {LEN} b=r {AB} a+=b a+= 32 r=a {BB}")
# LZ: bit 0x80 en nivel 1, 0x40 en nivel 2
e(f"        a=r {LEVEL} a== 1 ifl a= 128 elsel a= 64 endif b=r {SKIP} a&=b")
e("        a== 0 ifl")
LZ()
e(f"          a=r {BB} r=a {SRC}")
e("        endif")
e(f"        a=r {LEVEL} a== 2 ifl a=r {SKIP} a&= 128 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif")
e("        a> 0 ifl")
DNA()
e("        elsel")
OUTBUF()
e("        endif")
e("      endif")
e(f"      a=r {NEXT} r=a {POS} a= 1")
e("    elsel a=0 endif")
e("  a> 0 while")
e("  a=0 c=a")
e("elsel")
e("  *c=a c++")
e("endif")
e("halt")
e("end")
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
