/*
  ZPAQKANZI8: the decoder of zpaq-std -ma:kanzi levels 8 and 9, written in ZPAQL.
  zpaq-std, 2026. Generated by gen8.py (next to this file), which reuses the macros
  of gen3.py (EXE, the alias codec) and gen5.py (UTF, TEXT); ref8.py is the Python
  reference it was written from, itself checked against kanzi's C++ decoder.

  kanzi (github.com/flanglet/kanzi-cpp, Frederic Langlet) 2.6.0, bitstream 7,
  headerless, exactly kanzi's own levels 8 and 9:
    level 8: EXE + RLT + TEXT + UTF + DNA, entropy TPAQ
    level 9: EXE + RLT + TEXT + UTF + DNA, entropy TPAQX
  TPAQ is kanzi's TPAQPredictor (after Tangelo 2.4 and PAQ8): bit histories in hashed
  context slots (order 0 to 3, a sparse and a word/record context, plus one more for
  TPAQX), a match model, a neural mixer of 8 inputs selected by the last byte, and
  one or two adaptive probability maps, behind the 56-bit binary arithmetic decoder.
  Its tables are sized from the kanzi block size and the block's input length, and
  TPAQX makes them 4 times larger (and gives TEXT's hash table one more bit). Signed
  arithmetic is done on ZPAQL's unsigned registers: two's complement for sums and
  products, arithmetic shifts as ~((~x) >> k). Every block type and every combination
  of skipped transforms is handled.

  Input: original size (4 bytes LE), level (1 byte), kanzi's static dictionary
  (5487 bytes, zpaqkanzi_dict.h), then kanzi's stream. M: the input, two buffers and
  TPAQ's byte tables; H: small tables, then TPAQ's hashes, mixers and SSE (or TEXT's
  tables, after the entropy stage). zpaq-std sets ph and pm so that they fit; a
  16 MB block needs about 400 MB at level 8 and 1.5 GB at level 9 in another zpaq.
  The output goes out with OUT.

Verified with zpaqd 7.15 on 222 streams, identical to the input and to ref8.py:
  198 written by kanzi (99 inputs x levels 8 and 9: English text up to 21 MB, UTF-8
  Spanish, Japanese and Cyrillic, DNA, x86 and ARM64 executables, audio, images,
  random data, sizes 10 bytes up) and 24 blocks rebuilt by craft.py with kanzi's own
  transforms in other combinations of skipped transforms, all checked with kanzi's
  decoder; and with zpaq 7.15 on -m5 archives of 63 MB blocks at both levels.

  FROZEN, like the other portable decoders. A later kanzi format gets a new program.
*/
static const char ZPAQKANZI8_CUERPO[] = R"ZKNZ8(hcomp
halt
pcomp zpaqkanzi8 ;
(ZPAQKANZI8: decodificador de kanzi 2.6.0, bitstream 7 sin cabecera, niveles 8
 EXE+RLT+TEXT+UTF+DNA con TPAQ y 9 lo mismo con TPAQX, en ZPAQL, para zpaq-std
 -ma:kanzi. zpaq-std, 2026. Guarda la entrada en M y decodifica al final. La entrada
 lleva el diccionario estatico de kanzi detras de la cabecera.)
a> 255 ifl
  a=c r=a 1
  a=0 r=a 41 do a=0 *c=a c++ a=r 41 a++ r=a 41 a< 128 while
  a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 4
  a= 4 c=a a=*c r=a 3
  a=r 4 a+= 15 a>>= 4 a<<= 4 r=a 5
a= 4
a<<= 8
  b=a a=r 5 a<b ifl a=b r=a 5 endif
  a=r 5 a>>= 4 b=r 5 a+=b r=a 6 a=r 5 a+= 255 a+= 255 a+= 2 b=r 6 a>b ifl r=a 6 endif
a= 1
a<<= 8 a+= 49
a<<= 8
  d=a
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
a= 1
a<<= 8
d=a
a= 1 *d=a d++
a= 3 *d=a d++
a= 143 *d=a d++
a= 4 *d=a d++
a= 5 *d=a d++
a= 6 *d=a d++
a= 7 *d=a d++
a= 8 *d=a d++
a= 9 *d=a d++
a= 10 *d=a d++
a= 11 *d=a d++
a= 12 *d=a d++
a= 13 *d=a d++
a= 14 *d=a d++
a= 15 *d=a d++
a= 16 *d=a d++
a= 17 *d=a d++
a= 18 *d=a d++
a= 19 *d=a d++
a= 20 *d=a d++
a= 21 *d=a d++
a= 22 *d=a d++
a= 23 *d=a d++
a= 24 *d=a d++
a= 25 *d=a d++
a= 26 *d=a d++
a= 27 *d=a d++
a= 28 *d=a d++
a= 29 *d=a d++
a= 30 *d=a d++
a= 31 *d=a d++
a= 32 *d=a d++
a= 33 *d=a d++
a= 34 *d=a d++
a= 35 *d=a d++
a= 36 *d=a d++
a= 37 *d=a d++
a= 38 *d=a d++
a= 39 *d=a d++
a= 40 *d=a d++
a= 41 *d=a d++
a= 42 *d=a d++
a= 43 *d=a d++
a= 44 *d=a d++
a= 45 *d=a d++
a= 46 *d=a d++
a= 47 *d=a d++
a= 48 *d=a d++
a= 49 *d=a d++
a= 50 *d=a d++
a= 51 *d=a d++
a= 52 *d=a d++
a= 47 *d=a d++
a= 54 *d=a d++
a= 55 *d=a d++
a= 56 *d=a d++
a= 57 *d=a d++
a= 58 *d=a d++
a= 59 *d=a d++
a= 60 *d=a d++
a= 61 *d=a d++
a= 62 *d=a d++
a= 63 *d=a d++
a= 64 *d=a d++
a= 65 *d=a d++
a= 66 *d=a d++
a= 67 *d=a d++
a= 68 *d=a d++
a= 69 *d=a d++
a= 6 *d=a d++
a= 71 *d=a d++
a= 71 *d=a d++
a= 71 *d=a d++
a= 61 *d=a d++
a= 75 *d=a d++
a= 56 *d=a d++
a= 77 *d=a d++
a= 78 *d=a d++
a= 77 *d=a d++
a= 80 *d=a d++
a= 81 *d=a d++
a= 82 *d=a d++
a= 83 *d=a d++
a= 84 *d=a d++
a= 85 *d=a d++
a= 86 *d=a d++
a= 87 *d=a d++
a= 88 *d=a d++
a= 77 *d=a d++
a= 90 *d=a d++
a= 91 *d=a d++
a= 92 *d=a d++
a= 80 *d=a d++
a= 94 *d=a d++
a= 95 *d=a d++
a= 96 *d=a d++
a= 97 *d=a d++
a= 98 *d=a d++
a= 99 *d=a d++
a= 90 *d=a d++
a= 101 *d=a d++
a= 94 *d=a d++
a= 103 *d=a d++
a= 101 *d=a d++
a= 102 *d=a d++
a= 104 *d=a d++
a= 107 *d=a d++
a= 104 *d=a d++
a= 105 *d=a d++
a= 108 *d=a d++
a= 111 *d=a d++
a= 112 *d=a d++
a= 113 *d=a d++
a= 114 *d=a d++
a= 115 *d=a d++
a= 116 *d=a d++
a= 92 *d=a d++
a= 118 *d=a d++
a= 94 *d=a d++
a= 103 *d=a d++
a= 119 *d=a d++
a= 122 *d=a d++
a= 123 *d=a d++
a= 94 *d=a d++
a= 113 *d=a d++
a= 126 *d=a d++
a= 113 *d=a d++
a= 128 *d=a d++
a= 129 *d=a d++
a= 114 *d=a d++
a= 131 *d=a d++
a= 132 *d=a d++
a= 112 *d=a d++
a= 134 *d=a d++
a= 111 *d=a d++
a= 134 *d=a d++
a= 110 *d=a d++
a= 134 *d=a d++
a= 134 *d=a d++
a= 128 *d=a d++
a= 128 *d=a d++
a= 142 *d=a d++
a= 143 *d=a d++
a= 115 *d=a d++
a= 113 *d=a d++
a= 142 *d=a d++
a= 128 *d=a d++
a= 148 *d=a d++
a= 149 *d=a d++
a= 79 *d=a d++
a= 148 *d=a d++
a= 142 *d=a d++
a= 148 *d=a d++
a= 150 *d=a d++
a= 155 *d=a d++
a= 149 *d=a d++
a= 157 *d=a d++
a= 149 *d=a d++
a= 159 *d=a d++
a= 149 *d=a d++
a= 131 *d=a d++
a= 101 *d=a d++
a= 98 *d=a d++
a= 115 *d=a d++
a= 114 *d=a d++
a= 91 *d=a d++
a= 79 *d=a d++
a= 58 *d=a d++
a= 1 *d=a d++
a= 170 *d=a d++
a= 129 *d=a d++
a= 128 *d=a d++
a= 110 *d=a d++
a= 174 *d=a d++
a= 128 *d=a d++
a= 176 *d=a d++
a= 129 *d=a d++
a= 174 *d=a d++
a= 179 *d=a d++
a= 174 *d=a d++
a= 176 *d=a d++
a= 141 *d=a d++
a= 157 *d=a d++
a= 179 *d=a d++
a= 185 *d=a d++
a= 157 *d=a d++
a= 187 *d=a d++
a= 188 *d=a d++
a= 168 *d=a d++
a= 151 *d=a d++
a= 191 *d=a d++
a= 192 *d=a d++
a= 188 *d=a d++
a= 187 *d=a d++
a= 172 *d=a d++
a= 175 *d=a d++
a= 170 *d=a d++
a= 152 *d=a d++
a= 185 *d=a d++
a= 170 *d=a d++
a= 176 *d=a d++
a= 170 *d=a d++
a= 203 *d=a d++
a= 148 *d=a d++
a= 185 *d=a d++
a= 203 *d=a d++
a= 185 *d=a d++
a= 192 *d=a d++
a= 209 *d=a d++
a= 188 *d=a d++
a= 211 *d=a d++
a= 192 *d=a d++
a= 213 *d=a d++
a= 214 *d=a d++
a= 188 *d=a d++
a= 216 *d=a d++
a= 168 *d=a d++
a= 84 *d=a d++
a= 54 *d=a d++
a= 54 *d=a d++
a= 221 *d=a d++
a= 54 *d=a d++
a= 55 *d=a d++
a= 85 *d=a d++
a= 69 *d=a d++
a= 63 *d=a d++
a= 56 *d=a d++
a= 86 *d=a d++
a= 58 *d=a d++
a= 230 *d=a d++
a= 231 *d=a d++
a= 57 *d=a d++
a= 229 *d=a d++
a= 56 *d=a d++
a= 224 *d=a d++
a= 54 *d=a d++
a= 54 *d=a d++
a= 66 *d=a d++
a= 58 *d=a d++
a= 54 *d=a d++
a= 61 *d=a d++
a= 57 *d=a d++
a= 222 *d=a d++
a= 78 *d=a d++
a= 85 *d=a d++
a= 82 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 2 *d=a d++
a= 163 *d=a d++
a= 169 *d=a d++
a= 163 *d=a d++
a= 165 *d=a d++
a= 89 *d=a d++
a= 245 *d=a d++
a= 217 *d=a d++
a= 245 *d=a d++
a= 245 *d=a d++
a= 233 *d=a d++
a= 244 *d=a d++
a= 227 *d=a d++
a= 74 *d=a d++
a= 221 *d=a d++
a= 221 *d=a d++
a= 218 *d=a d++
a= 226 *d=a d++
a= 243 *d=a d++
a= 218 *d=a d++
a= 238 *d=a d++
a= 242 *d=a d++
a= 74 *d=a d++
a= 238 *d=a d++
a= 241 *d=a d++
a= 240 *d=a d++
a= 239 *d=a d++
a= 224 *d=a d++
a= 225 *d=a d++
a= 221 *d=a d++
a= 232 *d=a d++
a= 72 *d=a d++
a= 224 *d=a d++
a= 228 *d=a d++
a= 223 *d=a d++
a= 225 *d=a d++
a= 238 *d=a d++
a= 73 *d=a d++
a= 167 *d=a d++
a= 76 *d=a d++
a= 237 *d=a d++
a= 234 *d=a d++
a= 231 *d=a d++
a= 72 *d=a d++
a= 31 *d=a d++
a= 63 *d=a d++
a= 225 *d=a d++
a= 237 *d=a d++
a= 236 *d=a d++
a= 235 *d=a d++
a= 53 *d=a d++
a= 234 *d=a d++
a= 53 *d=a d++
a= 234 *d=a d++
a= 229 *d=a d++
a= 219 *d=a d++
a= 229 *d=a d++
a= 233 *d=a d++
a= 232 *d=a d++
a= 228 *d=a d++
a= 226 *d=a d++
a= 72 *d=a d++
a= 74 *d=a d++
a= 222 *d=a d++
a= 75 *d=a d++
a= 220 *d=a d++
a= 167 *d=a d++
a= 57 *d=a d++
a= 218 *d=a d++
a= 70 *d=a d++
a= 168 *d=a d++
a= 72 *d=a d++
a= 73 *d=a d++
a= 74 *d=a d++
a= 217 *d=a d++
a= 76 *d=a d++
a= 167 *d=a d++
a= 79 *d=a d++
a= 79 *d=a d++
a= 166 *d=a d++
a= 162 *d=a d++
a= 162 *d=a d++
a= 162 *d=a d++
a= 162 *d=a d++
a= 165 *d=a d++
a= 89 *d=a d++
a= 89 *d=a d++
a= 165 *d=a d++
a= 89 *d=a d++
a= 162 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 161 *d=a d++
a= 100 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 93 *d=a d++
a= 161 *d=a d++
a= 102 *d=a d++
a= 120 *d=a d++
a= 104 *d=a d++
a= 105 *d=a d++
a= 106 *d=a d++
a= 108 *d=a d++
a= 106 *d=a d++
a= 109 *d=a d++
a= 110 *d=a d++
a= 160 *d=a d++
a= 134 *d=a d++
a= 108 *d=a d++
a= 108 *d=a d++
a= 126 *d=a d++
a= 117 *d=a d++
a= 117 *d=a d++
a= 121 *d=a d++
a= 119 *d=a d++
a= 120 *d=a d++
a= 107 *d=a d++
a= 124 *d=a d++
a= 117 *d=a d++
a= 117 *d=a d++
a= 125 *d=a d++
a= 127 *d=a d++
a= 124 *d=a d++
a= 139 *d=a d++
a= 130 *d=a d++
a= 124 *d=a d++
a= 133 *d=a d++
a= 109 *d=a d++
a= 110 *d=a d++
a= 135 *d=a d++
a= 110 *d=a d++
a= 136 *d=a d++
a= 137 *d=a d++
a= 138 *d=a d++
a= 127 *d=a d++
a= 140 *d=a d++
a= 141 *d=a d++
a= 145 *d=a d++
a= 144 *d=a d++
a= 124 *d=a d++
a= 125 *d=a d++
a= 146 *d=a d++
a= 147 *d=a d++
a= 151 *d=a d++
a= 125 *d=a d++
a= 150 *d=a d++
a= 127 *d=a d++
a= 152 *d=a d++
a= 153 *d=a d++
a= 154 *d=a d++
a= 156 *d=a d++
a= 139 *d=a d++
a= 158 *d=a d++
a= 139 *d=a d++
a= 156 *d=a d++
a= 139 *d=a d++
a= 130 *d=a d++
a= 117 *d=a d++
a= 163 *d=a d++
a= 164 *d=a d++
a= 141 *d=a d++
a= 163 *d=a d++
a= 147 *d=a d++
a= 2 *d=a d++
a= 2 *d=a d++
a= 199 *d=a d++
a= 171 *d=a d++
a= 172 *d=a d++
a= 173 *d=a d++
a= 177 *d=a d++
a= 175 *d=a d++
a= 171 *d=a d++
a= 171 *d=a d++
a= 178 *d=a d++
a= 180 *d=a d++
a= 172 *d=a d++
a= 181 *d=a d++
a= 182 *d=a d++
a= 183 *d=a d++
a= 184 *d=a d++
a= 186 *d=a d++
a= 178 *d=a d++
a= 189 *d=a d++
a= 181 *d=a d++
a= 181 *d=a d++
a= 190 *d=a d++
a= 193 *d=a d++
a= 182 *d=a d++
a= 182 *d=a d++
a= 194 *d=a d++
a= 195 *d=a d++
a= 196 *d=a d++
a= 197 *d=a d++
a= 198 *d=a d++
a= 169 *d=a d++
a= 200 *d=a d++
a= 201 *d=a d++
a= 202 *d=a d++
a= 204 *d=a d++
a= 180 *d=a d++
a= 205 *d=a d++
a= 206 *d=a d++
a= 207 *d=a d++
a= 208 *d=a d++
a= 210 *d=a d++
a= 194 *d=a d++
a= 212 *d=a d++
a= 184 *d=a d++
a= 215 *d=a d++
a= 193 *d=a d++
a= 184 *d=a d++
a= 208 *d=a d++
a= 193 *d=a d++
a= 163 *d=a d++
a= 219 *d=a d++
a= 168 *d=a d++
a= 94 *d=a d++
a= 217 *d=a d++
a= 223 *d=a d++
a= 224 *d=a d++
a= 225 *d=a d++
a= 76 *d=a d++
a= 227 *d=a d++
a= 217 *d=a d++
a= 229 *d=a d++
a= 219 *d=a d++
a= 79 *d=a d++
a= 86 *d=a d++
a= 165 *d=a d++
a= 217 *d=a d++
a= 214 *d=a d++
a= 225 *d=a d++
a= 216 *d=a d++
a= 216 *d=a d++
a= 234 *d=a d++
a= 75 *d=a d++
a= 214 *d=a d++
a= 237 *d=a d++
a= 74 *d=a d++
a= 74 *d=a d++
a= 163 *d=a d++
a= 217 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 0 *d=a d++
a= 3
a<<= 8
d=a
a= 7
a<<= 8 a+= 225
*d=a d++
a= 6
a<<= 8 a+= 112
*d=a d++
a= 9
a<<= 8 a+= 150
*d=a d++
a= 5
a<<= 8 a+= 221
*d=a d++
a= 5
a<<= 8 a+= 126
*d=a d++
a= 5
a<<= 8 a+= 25
*d=a d++
a= 4
a<<= 8 a+= 197
*d=a d++
a= 4
a<<= 8 a+= 123
*d=a d++
a= 4
a<<= 8 a+= 123
*d=a d++
a= 4
a<<= 8 a+= 50
*d=a d++
a= 4
a<<= 8 a+= 79
*d=a d++
a= 4
a<<= 8 a+= 69
*d=a d++
a= 3
a<<= 8 a+= 220
*d=a d++
a= 3
a<<= 8 a+= 249
*d=a d++
a= 3
a<<= 8 a+= 236
*d=a d++
a= 4
a<<= 8 a+= 68
*d=a d++
a= 4
a<<= 8 a+= 30
*d=a d++
a= 3
a<<= 8 a+= 245
*d=a d++
a= 3
a<<= 8 a+= 133
*d=a d++
a= 3
a<<= 8 a+= 211
*d=a d++
a= 3
a<<= 8 a+= 169
*d=a d++
a= 3
a<<= 8 a+= 135
*d=a d++
a= 3
a<<= 8 a+= 184
*d=a d++
a= 3
a<<= 8 a+= 196
*d=a d++
a= 3
a<<= 8 a+= 109
*d=a d++
a= 3
a<<= 8 a+= 81
*d=a d++
a= 3
a<<= 8 a+= 218
*d=a d++
a= 2
a<<= 8 a+= 38
*d=a d++
a= 3
a<<= 8 a+= 81
*d=a d++
a= 3
a<<= 8 a+= 81
*d=a d++
a= 2
a<<= 8 a+= 208
*d=a d++
a= 2
a<<= 8 a+= 131
*d=a d++
a= 3
a<<= 8 a+= 5
*d=a d++
a= 3
a<<= 8 a+= 32
*d=a d++
a= 3
a<<= 8 a+= 113
*d=a d++
a= 2
a<<= 8 a+= 88
*d=a d++
a= 2
a<<= 8 a+= 95
*d=a d++
a= 3
a<<= 8 a+= 81
*d=a d++
a= 2
a<<= 8 a+= 179
*d=a d++
a= 3
a<<= 8 a+= 120
*d=a d++
a= 2
a<<= 8 a+= 99
*d=a d++
a= 2
a<<= 8 a+= 108
*d=a d++
a= 3
a<<= 8 a+= 42
*d=a d++
a= 2
a<<= 8 a+= 193
*d=a d++
a= 2
a<<= 8 a+= 10
*d=a d++
a= 2
a<<= 8 a+= 205
*d=a d++
a= 2
a<<= 8 a+= 93
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 4
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 7
a<<= 8 a+= 24
*d=a d++
a= 6
a<<= 8 a+= 98
*d=a d++
a= 5
a<<= 8 a+= 195
*d=a d++
a= 5
a<<= 8 a+= 251
*d=a d++
a= 5
a<<= 8
*d=a d++
a= 5
a<<= 8 a+= 141
*d=a d++
a= 5
a<<= 8 a+= 102
*d=a d++
a= 5
a<<= 8 a+= 124
*d=a d++
a= 5
a<<= 8 a+= 28
*d=a d++
a= 5
a<<= 8 a+= 47
*d=a d++
a= 4
a<<= 8 a+= 195
*d=a d++
a= 4
a<<= 8 a+= 254
*d=a d++
a= 4
a<<= 8 a+= 61
*d=a d++
a= 4
a<<= 8 a+= 161
*d=a d++
a= 3
a<<= 8 a+= 181
*d=a d++
a= 4
a<<= 8 a+= 213
*d=a d++
a= 4
a<<= 8 a+= 194
*d=a d++
a= 6
a<<= 8 a+= 235
*d=a d++
a= 3
a<<= 8 a+= 244
*d=a d++
a= 6
a<<= 8 a+= 226
*d=a d++
a= 7
a<<= 8 a+= 38
*d=a d++
a= 7
a<<= 8 a+= 214
*d=a d++
a= 6
a<<= 8 a+= 101
*d=a d++
a= 8
a<<= 8 a+= 141
*d=a d++
a= 4
a<<= 8 a+= 10
*d=a d++
a= 3
a<<= 8 a+= 252
*d=a d++
a= 7
a<<= 8 a+= 30
*d=a d++
a= 6
a<<= 8 a+= 43
*d=a d++
a= 5
a<<= 8 a+= 228
*d=a d++
a= 5
a<<= 8 a+= 195
*d=a d++
a= 5
a<<= 8 a+= 187
*d=a d++
a= 5
a<<= 8 a+= 174
*d=a d++
a= 5
a<<= 8 a+= 158
*d=a d++
a= 5
a<<= 8 a+= 140
*d=a d++
a= 5
a<<= 8 a+= 57
*d=a d++
a= 5
a<<= 8 a+= 98
*d=a d++
a= 7
a<<= 8 a+= 112
*d=a d++
a= 6
a<<= 8 a+= 104
*d=a d++
a= 6
a<<= 8 a+= 27
*d=a d++
a= 6
a<<= 8 a+= 48
*d=a d++
a= 7
a<<= 8 a+= 83
*d=a d++
a= 7
a<<= 8 a+= 35
*d=a d++
a= 6
a<<= 8 a+= 202
*d=a d++
a= 6
a<<= 8 a+= 177
*d=a d++
a= 6
a<<= 8 a+= 137
*d=a d++
a= 6
a<<= 8 a+= 188
*d=a d++
a= 6
a<<= 8 a+= 99
*d=a d++
a= 7
a<<= 8 a+= 157
*d=a d++
a= 7
a<<= 8 a+= 77
*d=a d++
a= 7
a<<= 8 a+= 151
*d=a d++
a= 7
a<<= 8 a+= 106
*d=a d++
a= 7
a<<= 8 a+= 193
*d=a d++
a= 7
a<<= 8 a+= 247
*d=a d++
a= 8
a<<= 8 a+= 56
*d=a d++
a= 8
a<<= 8 a+= 83
*d=a d++
a= 8
a<<= 8 a+= 119
*d=a d++
a= 8
a<<= 8 a+= 144
*d=a d++
a= 8
a<<= 8 a+= 198
*d=a d++
a= 8
a<<= 8 a+= 118
*d=a d++
a= 7
a<<= 8 a+= 214
*d=a d++
a= 7
a<<= 8 a+= 160
*d=a d++
a= 7
a<<= 8 a+= 68
*d=a d++
a= 6
a<<= 8 a+= 227
*d=a d++
a= 6
a<<= 8 a+= 136
*d=a d++
a= 8
a<<= 8 a+= 107
*d=a d++
a= 7
a<<= 8 a+= 118
*d=a d++
a= 8
a<<= 8 a+= 38
*d=a d++
a= 7
a<<= 8 a+= 174
*d=a d++
a= 8
a<<= 8 a+= 186
*d=a d++
a= 7
a<<= 8 a+= 142
*d=a d++
a= 7
a<<= 8 a+= 66
*d=a d++
a= 8
a<<= 8 a+= 200
*d=a d++
a= 9
a<<= 8 a+= 71
*d=a d++
a= 8
a<<= 8 a+= 65
*d=a d++
a= 9
a<<= 8 a+= 150
*d=a d++
a= 8
a<<= 8 a+= 108
*d=a d++
a= 7
a<<= 8 a+= 161
*d=a d++
a= 9
a<<= 8 a+= 52
*d=a d++
a= 8
a<<= 8 a+= 171
*d=a d++
a= 7
a<<= 8 a+= 238
*d=a d++
a= 9
a<<= 8 a+= 87
*d=a d++
a= 8
a<<= 8 a+= 135
*d=a d++
a= 9
a<<= 8 a+= 142
*d=a d++
a= 9
a<<= 8 a+= 159
*d=a d++
a= 9
a<<= 8 a+= 208
*d=a d++
a= 10
a<<= 8 a+= 2
*d=a d++
a= 9
a<<= 8 a+= 238
*d=a d++
a= 9
a<<= 8 a+= 252
*d=a d++
a= 10
a<<= 8 a+= 7
*d=a d++
a= 8
a<<= 8 a+= 92
*d=a d++
a= 7
a<<= 8 a+= 133
*d=a d++
a= 9
a<<= 8 a+= 87
*d=a d++
a= 10
a<<= 8 a+= 63
*d=a d++
a= 10
a<<= 8 a+= 73
*d=a d++
a= 10
a<<= 8 a+= 4
*d=a d++
a= 7
a<<= 8 a+= 249
*d=a d++
a= 7
a<<= 8 a+= 100
*d=a d++
a= 8
a<<= 8 a+= 209
*d=a d++
a= 10
a<<= 8 a+= 62
*d=a d++
a= 10
a<<= 8 a+= 101
*d=a d++
a= 10
a<<= 8 a+= 109
*d=a d++
a= 10
a<<= 8 a+= 158
*d=a d++
a= 8
a<<= 8 a+= 107
*d=a d++
a= 11
a<<= 8 a+= 221
*d=a d++
a= 8
a<<= 8 a+= 210
*d=a d++
a= 11
a<<= 8 a+= 193
*d=a d++
a= 8
a<<= 8 a+= 246
*d=a d++
a= 8
a<<= 8 a+= 254
*d=a d++
a= 7
a<<= 8 a+= 244
*d=a d++
a= 7
a<<= 8 a+= 148
*d=a d++
a= 8
a<<= 8 a+= 97
*d=a d++
a= 9
a<<= 8 a+= 25
*d=a d++
a= 7
a<<= 8 a+= 113
*d=a d++
a= 8
a<<= 8 a+= 41
*d=a d++
a= 8
a<<= 8 a+= 173
*d=a d++
a= 7
a<<= 8 a+= 47
*d=a d++
a= 10
a<<= 8 a+= 71
*d=a d++
a= 7
a<<= 8 a+= 201
*d=a d++
a= 8
a<<= 8 a+= 250
*d=a d++
a= 9
a<<= 8 a+= 98
*d=a d++
a= 10
a<<= 8 a+= 46
*d=a d++
a= 8
a<<= 8 a+= 43
*d=a d++
a= 9
a<<= 8 a+= 18
*d=a d++
a= 8
a<<= 8 a+= 14
*d=a d++
a= 9
a<<= 8 a+= 232
*d=a d++
a= 10
a<<= 8 a+= 33
*d=a d++
a= 8
a<<= 8 a+= 84
*d=a d++
a= 10
a<<= 8 a+= 16
*d=a d++
a= 10
a<<= 8 a+= 7
*d=a d++
a= 10
a<<= 8 a+= 75
*d=a d++
a= 10
a<<= 8 a+= 122
*d=a d++
a= 10
a<<= 8 a+= 151
*d=a d++
a= 8
a<<= 8 a+= 95
*d=a d++
a= 10
a<<= 8 a+= 188
*d=a d++
a= 8
a<<= 8 a+= 94
*d=a d++
a= 7
a<<= 8 a+= 72
*d=a d++
a= 10
a<<= 8 a+= 218
*d=a d++
a= 10
a<<= 8 a+= 230
*d=a d++
a= 8
a<<= 8 a+= 162
*d=a d++
a= 7
a<<= 8 a+= 246
*d=a d++
a= 10
a<<= 8 a+= 196
*d=a d++
a= 10
a<<= 8 a+= 180
*d=a d++
a= 11
a<<= 8 a+= 5
*d=a d++
a= 10
a<<= 8 a+= 195
*d=a d++
a= 11
a<<= 8 a+= 87
*d=a d++
a= 11
a<<= 8 a+= 43
*d=a d++
a= 10
a<<= 8 a+= 191
*d=a d++
a= 11
a<<= 8 a+= 22
*d=a d++
a= 11
a<<= 8 a+= 103
*d=a d++
a= 11
a<<= 8 a+= 38
*d=a d++
a= 8
a<<= 8 a+= 9
*d=a d++
a= 11
a<<= 8 a+= 99
*d=a d++
a= 11
a<<= 8 a+= 72
*d=a d++
a= 11
a<<= 8 a+= 222
*d=a d++
a= 11
a<<= 8 a+= 255
*d=a d++
a= 13
a<<= 8 a+= 129
*d=a d++
a= 8
a<<= 8 a+= 194
*d=a d++
a= 13
a<<= 8 a+= 117
*d=a d++
a= 8
a<<= 8 a+= 183
*d=a d++
a= 13
a<<= 8 a+= 182
*d=a d++
a= 8
a<<= 8 a+= 178
*d=a d++
a= 7
a<<= 8 a+= 233
*d=a d++
a= 13
a<<= 8 a+= 123
*d=a d++
a= 8
a<<= 8 a+= 247
*d=a d++
a= 8
a<<= 8 a+= 172
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 7
a<<= 8 a+= 224
*d=a d++
a= 7
a<<= 8 a+= 86
*d=a d++
a= 8
a<<= 8 a+= 72
*d=a d++
a= 6
a<<= 8 a+= 4
*d=a d++
a= 7
a<<= 8 a+= 210
*d=a d++
a= 6
a<<= 8 a+= 147
*d=a d++
a= 7
a<<= 8 a+= 230
*d=a d++
a= 7
a<<= 8 a+= 110
*d=a d++
a= 8
a<<= 8 a+= 101
*d=a d++
a= 7
a<<= 8 a+= 238
*d=a d++
a= 7
a<<= 8 a+= 93
*d=a d++
a= 6
a<<= 8 a+= 90
*d=a d++
a= 6
a<<= 8 a+= 51
*d=a d++
a= 7
a<<= 8 a+= 110
*d=a d++
a= 7
a<<= 8 a+= 187
*d=a d++
a= 7
a<<= 8 a+= 178
*d=a d++
a= 6
a<<= 8 a+= 193
*d=a d++
a= 6
a<<= 8 a+= 178
*d=a d++
a= 7
a<<= 8 a+= 24
*d=a d++
a= 7
a<<= 8 a+= 157
*d=a d++
a= 8
a<<= 8
*d=a d++
a= 8
a<<= 8 a+= 47
*d=a d++
a= 7
a<<= 8 a+= 182
*d=a d++
a= 8
a<<= 8
*d=a d++
a= 6
a<<= 8 a+= 60
*d=a d++
a= 8
a<<= 8 a+= 14
*d=a d++
a= 7
a<<= 8 a+= 199
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 8
a<<= 8 a+= 1
*d=a d++
a= 4
a<<= 8
d=a
a= 0
*d=a d++
a= 64
*d=a d++
a= 128
*d=a d++
a= 192
*d=a d++
a= 1
a<<= 8
*d=a d++
a= 1
a<<= 8 a+= 64
*d=a d++
a= 1
a<<= 8 a+= 128
*d=a d++
a= 1
a<<= 8 a+= 192
*d=a d++
a= 2
a<<= 8
*d=a d++
a= 2
a<<= 8 a+= 64
*d=a d++
a= 2
a<<= 8 a+= 128
*d=a d++
a= 2
a<<= 8 a+= 192
*d=a d++
a= 3
a<<= 8
*d=a d++
a= 3
a<<= 8 a+= 64
*d=a d++
a= 3
a<<= 8 a+= 128
*d=a d++
a= 3
a<<= 8 a+= 192
*d=a d++
a= 4
a<<= 8
*d=a d++
a= 4
a<<= 8 a+= 14
*d=a d++
a= 4
a<<= 8 a+= 29
*d=a d++
a= 4
a<<= 8 a+= 43
*d=a d++
a= 4
a<<= 8 a+= 58
*d=a d++
a= 4
a<<= 8 a+= 72
*d=a d++
a= 4
a<<= 8 a+= 87
*d=a d++
a= 4
a<<= 8 a+= 101
*d=a d++
a= 4
a<<= 8 a+= 115
*d=a d++
a= 4
a<<= 8 a+= 130
*d=a d++
a= 4
a<<= 8 a+= 144
*d=a d++
a= 4
a<<= 8 a+= 159
*d=a d++
a= 4
a<<= 8 a+= 173
*d=a d++
a= 4
a<<= 8 a+= 187
*d=a d++
a= 4
a<<= 8 a+= 202
*d=a d++
a= 4
a<<= 8 a+= 216
*d=a d++
a= 4
a<<= 8 a+= 231
*d=a d++
a= 4
a<<= 8 a+= 245
*d=a d++
a= 5
a<<= 8 a+= 4
*d=a d++
a= 5
a<<= 8 a+= 18
*d=a d++
a= 5
a<<= 8 a+= 32
*d=a d++
a= 5
a<<= 8 a+= 47
*d=a d++
a= 5
a<<= 8 a+= 61
*d=a d++
a= 5
a<<= 8 a+= 76
*d=a d++
a= 5
a<<= 8 a+= 90
*d=a d++
a= 5
a<<= 8 a+= 105
*d=a d++
a= 5
a<<= 8 a+= 119
*d=a d++
a= 5
a<<= 8 a+= 133
*d=a d++
a= 5
a<<= 8 a+= 148
*d=a d++
a= 5
a<<= 8 a+= 162
*d=a d++
a= 5
a<<= 8 a+= 177
*d=a d++
a= 5
a<<= 8 a+= 191
*d=a d++
a= 5
a<<= 8 a+= 206
*d=a d++
a= 5
a<<= 8 a+= 220
*d=a d++
a= 5
a<<= 8 a+= 234
*d=a d++
a= 5
a<<= 8 a+= 249
*d=a d++
a= 6
a<<= 8 a+= 7
*d=a d++
a= 6
a<<= 8 a+= 22
*d=a d++
a= 6
a<<= 8 a+= 36
*d=a d++
a= 6
a<<= 8 a+= 50
*d=a d++
a= 6
a<<= 8 a+= 65
*d=a d++
a= 6
a<<= 8 a+= 79
*d=a d++
a= 6
a<<= 8 a+= 94
*d=a d++
a= 6
a<<= 8 a+= 108
*d=a d++
a= 6
a<<= 8 a+= 123
*d=a d++
a= 6
a<<= 8 a+= 137
*d=a d++
a= 6
a<<= 8 a+= 151
*d=a d++
a= 6
a<<= 8 a+= 166
*d=a d++
a= 6
a<<= 8 a+= 180
*d=a d++
a= 6
a<<= 8 a+= 195
*d=a d++
a= 6
a<<= 8 a+= 209
*d=a d++
a= 6
a<<= 8 a+= 224
*d=a d++
a= 6
a<<= 8 a+= 238
*d=a d++
a= 6
a<<= 8 a+= 252
*d=a d++
a= 7
a<<= 8 a+= 11
*d=a d++
a= 7
a<<= 8 a+= 25
*d=a d++
a= 7
a<<= 8 a+= 40
*d=a d++
a= 7
a<<= 8 a+= 54
*d=a d++
a= 7
a<<= 8 a+= 69
*d=a d++
a= 7
a<<= 8 a+= 83
*d=a d++
a= 7
a<<= 8 a+= 97
*d=a d++
a= 7
a<<= 8 a+= 112
*d=a d++
a= 7
a<<= 8 a+= 126
*d=a d++
a= 7
a<<= 8 a+= 141
*d=a d++
a= 7
a<<= 8 a+= 155
*d=a d++
a= 7
a<<= 8 a+= 169
*d=a d++
a= 7
a<<= 8 a+= 184
*d=a d++
a= 7
a<<= 8 a+= 198
*d=a d++
a= 7
a<<= 8 a+= 213
*d=a d++
a= 7
a<<= 8 a+= 227
*d=a d++
a= 7
a<<= 8 a+= 242
*d=a d++
a= 7
a<<= 8 a+= 255
*d=a d++
a= 36
a<<= 8 a+= 128
d=a
a= 0
*d=a d++
a= 8
*d=a d++
a= 22
*d=a d++
a= 47
*d=a d++
a= 88
*d=a d++
a= 160
*d=a d++
a= 1
a<<= 8 a+= 27
*d=a d++
a= 1
a<<= 8 a+= 236
*d=a d++
a= 3
a<<= 8 a+= 80
*d=a d++
a= 5
a<<= 8 a+= 171
*d=a d++
a= 9
a<<= 8 a+= 155
*d=a d++
a= 16
a<<= 8 a+= 21
*d=a d++
a= 26
a<<= 8 a+= 110
*d=a d++
a= 42
a<<= 8 a+= 67
*d=a d++
a= 64
a<<= 8 a+= 224
*d=a d++
a= 94
a<<= 8 a+= 63
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 161
a<<= 8 a+= 193
*d=a d++
a= 191
a<<= 8 a+= 32
*d=a d++
a= 213
a<<= 8 a+= 189
*d=a d++
a= 229
a<<= 8 a+= 146
*d=a d++
a= 239
a<<= 8 a+= 235
*d=a d++
a= 246
a<<= 8 a+= 101
*d=a d++
a= 250
a<<= 8 a+= 85
*d=a d++
a= 252
a<<= 8 a+= 176
*d=a d++
a= 254
a<<= 8 a+= 20
*d=a d++
a= 254
a<<= 8 a+= 229
*d=a d++
a= 255
a<<= 8 a+= 96
*d=a d++
a= 255
a<<= 8 a+= 168
*d=a d++
a= 255
a<<= 8 a+= 209
*d=a d++
a= 255
a<<= 8 a+= 234
*d=a d++
a= 255
a<<= 8 a+= 248
*d=a d++
a= 1
a<<= 8
a<<= 8
*d=a d++
a= 1 r=a 33
do
a=r 33 a&= 127 r=a 41 a=r 33 a>>= 7 r=a 42
a= 36
a<<= 8 a+= 128
b=r 42 a+=b d=a a=*d r=a 43
a=r 42 a++ r=a 42
a= 36
a<<= 8 a+= 128
b=r 42 a+=b d=a a=*d r=a 44
a= 128 b=r 41 a-=b b=r 43 a*=b r=a 45 a=r 44 b=r 41 a*=b b=r 45 a+=b a>>= 11 r=a 45
a=r 33 a-- r=a 46
a= 4
a<<= 8 a+= 128
b=r 46 a+=b d=a a=r 45 *d=a
a=r 33 a+= 1 r=a 33
a= 16
a<<= 8
b=a a=r 33 a<b
while
a= 15
a<<= 8 a+= 255
r=a 45
a= 15
a<<= 8 a+= 255
r=a 46
a= 4
a<<= 8 a+= 128
b=r 46 a+=b d=a a=r 45 *d=a
a=0 r=a 34 r=a 33
do
a= 4
a<<= 8 a+= 128
b=r 33 a+=b d=a a=*d r=a 41
a= 7
a<<= 8 a+= 255
b=a a=r 33 a-=b r=a 42
a=r 34 b=r 41 a>b ifnotl
do
a= 20
a<<= 8 a+= 128
b=r 34 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 41 a>b ifnot
a= 16
a<<= 8
b=a a=r 34 a<b elsel a=0 a> 0 endif
while
endif
a=r 33 a+= 1 r=a 33
a= 16
a<<= 8
b=a a=r 34 a<b ifl
a= 15
a<<= 8 a+= 255
b=a a=r 33 a<b elsel a=0 a> 0 endif
while
a= 7
a<<= 8 a+= 255
r=a 45
a= 15
a<<= 8 a+= 255
r=a 46
a= 20
a<<= 8 a+= 128
b=r 46 a+=b d=a a=r 45 *d=a
a=0 r=a 32 r=a 41
a= 5 r=a 42
a= 21
a<<= 8 a+= 111
r=a 43
a=0 r=a 33
a=r 43 a> 0 ifl
do
a= 4
a<<= 8
b=a a=r 32 a<b ifl
a=r 42 b=r 33 a+=b c=a a=*c r=a 44
a=r 44 a> 64 ifl a< 91 ifl
  a=r 33 b=r 41 a>b ifl
    a=r 42 b=r 41 a+=b r=a 45
a= 37
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
    a=r 33 b=r 41 a-=b r=a 45
a= 41
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 32 a+= 1 r=a 32
    a=r 33 r=a 41
  endif
  a=r 42 b=r 33 a+=b c=a a=*c a^= 32 *c=a
endif endif
endif
a=r 33 a+= 1 r=a 33
a=r 33 b=r 43 a<b
while
endif
a= 4
a<<= 8
b=a a=r 32 a<b ifl
a=r 42 b=r 41 a+=b r=a 45
a= 37
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 43 b=r 41 a-=b r=a 45
a= 41
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 32 a+= 1 r=a 32
endif
a=0 r=a 33
do
a= 37
a<<= 8
b=r 33 a+=b d=a a=*d r=a 45
a= 41
a<<= 8
b=r 33 a+=b d=a a=*d r=a 46
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 44
do
a=r 45 c=a a=*c r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 44 a*=b r=a 44
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 47 a*=b b=r 44 a^=b r=a 44
a=r 45 a+= 1 r=a 45
a=r 46 a-- r=a 46 a> 0
while
a= 45
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a=r 33 a+= 1 r=a 33
a= 4
a<<= 8
b=a a=r 33 a<b
while
a= 171
a<<= 8 a+= 160
r=a 2
  do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 15 a=r 2 a+= 5 r=a 2
a=r 15 a+= 3 r=a 15
    a=r 15 a> 24 ifl
      a=r 15 a-= 24 r=a 41
a=r 41 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 48 a= 32 b=r 41 a-=b b=a a=r 48 a>>=b r=a 42 a=r 2 b=r 41 a+=b r=a 2
elsel a=0 r=a 42 endif
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 43 a=r 2 a+= 24 r=a 2
      a=r 42 a<<= 24 b=r 43 a+=b r=a 10
    elsel
a=r 15 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 48 a= 32 b=r 15 a-=b b=a a=r 48 a>>=b r=a 10 a=r 2 b=r 15 a+=b r=a 2
elsel a=0 r=a 10 endif
    endif
    a=r 10 a> 0 ifl
      a=r 2 b=r 10 a+=b r=a 11
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 8 a=r 2 a+= 8 r=a 2
      a=r 8 a&= 128 r=a 12 a=0 r=a 13
      a=r 12 a> 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 r=a 13 endif endif
      a=r 13 a> 0 ifl a= 1 elsel a=r 12 a== 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif endif
      a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 9 a=r 2 a+= 8 r=a 2
      elsel
        a=r 8 a<<= 4 a|= 15 a&= 255 r=a 9
      endif
      a=r 8 a>>= 5 a&= 3 a++ r=a 14 a=0 r=a 7
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
        a=r 7 a<<= 8 b=r 41 a+=b r=a 7 a=r 14 a-- r=a 14 a> 0
      while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
      a=r 7 a+= 255 a+= 255 a+= 2 b=r 6 a<b ifl a=b endif r=a 25 a+= 64 r=a 18
      a=r 6 r=a 26 a=0 r=a 27
      a=r 1 a+= 128 r=a 16 b=r 18 a+=b r=a 17
      a=r 12 a> 0 ifl a=r 13 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
      a> 0 ifl
        a=r 7 a> 0 ifl
          do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
            a=r 41 out a=r 7 a-- r=a 7 a> 0
          while
        endif
      elsel
        a=r 13 a> 0 ifl
a=0 r=a 33
a=r 7 a> 0 ifl
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
a=r 16 b=r 33 a+=b c=a a=r 41 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 7 a<b
while
endif
        elsel
a=r 7 a< 64 ifl a= 64 elsel a=r 7 endif r=a 62
a= 4
a<<= 8
a<<= 8
a<<= 8
b=a a=r 62 a<b ifnotl
  a=r 62 a>>= 3 b=a
a= 4
a<<= 8
a<<= 8
a<<= 8
  a>b ifl a=r 7 a>>= 3 elsel a=r 7 a>>= 4 endif r=a 62
endif
a=r 3 a== 9 ifl a= 2 elsel a=0 endif r=a 65
a= 22 r=a 41
a=r 5 a>>= 20 a> 0 ifl a= 24 r=a 41 endif
a=r 5 a>>= 22 a> 0 ifl a= 26 r=a 41 endif
a=r 5 a>>= 24 a> 0 ifl a= 27 r=a 41 endif
a=r 5 a>>= 26 a> 0 ifl a= 28 r=a 41 endif
a=r 41 b=r 65 a+=b b=a a= 1 a<<=b a-- r=a 66
a= 8 r=a 41
a=r 7 a>>= 20 a> 0 ifl a= 11 r=a 41 endif
a=r 7 a>>= 22 a> 0 ifl a= 13 r=a 41 endif
a=r 7 a>>= 23 a> 0 ifl a= 14 r=a 41 endif
a=r 7 a>>= 24 a> 0 ifl a= 15 r=a 41 endif
a=r 7 a>>= 25 a> 0 ifl a= 16 r=a 41 endif
a=r 41 b=r 65 a+=b b=a a= 1 a<<=b r=a 47 a-- a>>= 1 a<<= 1 r=a 67
a=r 5 r=a 41
a= 4
a<<= 8
a<<= 8
a<<= 8
b=a a=r 41 a>b ifl a=b r=a 41 endif
a= 1 r=a 48
a=r 48 a+=a b=r 41 a>b ifnotl
do
a=r 48 a+=a r=a 48 a+=a b=r 41 a>b ifnot a=r 48 a>>= 31 a== 0 elsel a=0 a> 0 endif
while
endif
a=r 48 r=a 41
a=r 41 a-- r=a 69
a=r 7 a>>= 26 a> 0 ifl a= 1 a<<= 30 elsel a=r 7 a<<= 4 endif r=a 41
a= 1
a<<= 8
a<<= 8
a<<= 8
b=a a=r 41 a>b ifl a=b r=a 41 endif
a= 1 r=a 48
a=r 48 a+=a b=r 41 a>b ifnotl
do
a=r 48 a+=a r=a 48 a+=a b=r 41 a>b ifnot a=r 48 a>>= 31 a== 0 elsel a=0 a> 0 endif
while
endif
a=r 48 r=a 41
a=r 41 b=r 65 a<<=b r=a 41
a= 64
a<<= 8
a<<= 8
a<<= 8
b=a a=r 41 a>b ifl a=b r=a 41 endif
a=r 41 a-- r=a 68
a=r 17 b=r 18 a+=b r=a 70 b=r 69 a+=b a++ r=a 71 a= 1 a<<= 16 b=r 71 a+=b r=a 72
a= 1 a<<= 24 b=r 72 a+=b r=a 73
a=r 73 b=r 66 a+=b a++ b=r 70 a-=b r=a 41
a=r 70 c=a a=r 41 r=a 48
do
a=0 *c=a c++ a=r 48 a-- r=a 48 a> 0
while
a= 2
a<<= 8
a<<= 8
r=a 74
a=r 68 a++ r=a 41 a=0 r=a 42
a=r 74 d=a a=r 41 r=a 48
do
a=r 42 *d=a d++ a=r 48 a-- r=a 48 a> 0
while
a=r 74 b=r 68 a+=b a++ r=a 75
a=r 75 d=a a=r 47 r=a 41
do
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 128
a<<= 8
*d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a= 8
a<<= 8
*d=a d++ a=0 *d=a d++
a= 30
a<<= 8
*d=a d++
a=r 41 a-- r=a 41 a> 0
while
a=r 47 b= 19 a*=b b=r 75 a+=b r=a 76
a= 1
a<<= 8 a+= 51
a<<= 8 a+= 16
r=a 46
a= 1
a<<= 8
r=a 41
a=r 46 d=a a=0 r=a 42
do
a= 0
*d=a d++
a= 0
*d=a d++
a= 16
*d=a d++
a= 32
*d=a d++
a= 80
*d=a d++
a= 160
*d=a d++
a= 1
a<<= 8 a+= 16
*d=a d++
a= 1
a<<= 8 a+= 224
*d=a d++
a= 3
a<<= 8 a+= 80
*d=a d++
a= 5
a<<= 8 a+= 160
*d=a d++
a= 9
a<<= 8 a+= 144
*d=a d++
a= 16
a<<= 8 a+= 16
*d=a d++
a= 26
a<<= 8 a+= 96
*d=a d++
a= 42
a<<= 8 a+= 64
*d=a d++
a= 64
a<<= 8 a+= 224
*d=a d++
a= 94
a<<= 8 a+= 48
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 161
a<<= 8 a+= 192
*d=a d++
a= 191
a<<= 8 a+= 32
*d=a d++
a= 213
a<<= 8 a+= 176
*d=a d++
a= 229
a<<= 8 a+= 144
*d=a d++
a= 239
a<<= 8 a+= 224
*d=a d++
a= 246
a<<= 8 a+= 96
*d=a d++
a= 250
a<<= 8 a+= 80
*d=a d++
a= 252
a<<= 8 a+= 176
*d=a d++
a= 254
a<<= 8 a+= 16
*d=a d++
a= 254
a<<= 8 a+= 224
*d=a d++
a= 255
a<<= 8 a+= 96
*d=a d++
a= 255
a<<= 8 a+= 160
*d=a d++
a= 255
a<<= 8 a+= 208
*d=a d++
a= 255
a<<= 8 a+= 224
*d=a d++
a= 255
a<<= 8 a+= 240
*d=a d++
a= 255
a<<= 8 a+= 240
*d=a d++
a=r 42 a+= 1 r=a 42
a=r 42 b=r 41 a<b
while
a=r 65 a> 0 ifl a= 1 a<<= 16 elsel a= 1 a<<= 8 endif r=a 41
a=r 76 d=a a=0 r=a 42
do
a= 0
*d=a d++
a= 0
*d=a d++
a= 16
*d=a d++
a= 32
*d=a d++
a= 80
*d=a d++
a= 160
*d=a d++
a= 1
a<<= 8 a+= 16
*d=a d++
a= 1
a<<= 8 a+= 224
*d=a d++
a= 3
a<<= 8 a+= 80
*d=a d++
a= 5
a<<= 8 a+= 160
*d=a d++
a= 9
a<<= 8 a+= 144
*d=a d++
a= 16
a<<= 8 a+= 16
*d=a d++
a= 26
a<<= 8 a+= 96
*d=a d++
a= 42
a<<= 8 a+= 64
*d=a d++
a= 64
a<<= 8 a+= 224
*d=a d++
a= 94
a<<= 8 a+= 48
*d=a d++
a= 128
a<<= 8
*d=a d++
a= 161
a<<= 8 a+= 192
*d=a d++
a= 191
a<<= 8 a+= 32
*d=a d++
a= 213
a<<= 8 a+= 176
*d=a d++
a= 229
a<<= 8 a+= 144
*d=a d++
a= 239
a<<= 8 a+= 224
*d=a d++
a= 246
a<<= 8 a+= 96
*d=a d++
a= 250
a<<= 8 a+= 80
*d=a d++
a= 252
a<<= 8 a+= 176
*d=a d++
a= 254
a<<= 8 a+= 16
*d=a d++
a= 254
a<<= 8 a+= 224
*d=a d++
a= 255
a<<= 8 a+= 96
*d=a d++
a= 255
a<<= 8 a+= 160
*d=a d++
a= 255
a<<= 8 a+= 208
*d=a d++
a= 255
a<<= 8 a+= 224
*d=a d++
a= 255
a<<= 8 a+= 240
*d=a d++
a= 255
a<<= 8 a+= 240
*d=a d++
a=r 42 a+= 1 r=a 42
a=r 42 b=r 41 a<b
while
a= 1
a<<= 8 a+= 51
a<<= 8 a+= 16
r=a 111
a=r 76 r=a 112
a=0 r=a 79 r=a 80 r=a 82 r=a 83 r=a 84 r=a 85 r=a 86 r=a 87
a=0 r=a 89
a=0 r=a 90
a=0 r=a 91
a=0 r=a 92
a=0 r=a 93
a=0 r=a 94
a=0 r=a 95
a= 1 r=a 78 a= 8 r=a 81 a=r 75 r=a 88
a= 8
a<<= 8
r=a 77
a=r 71 r=a 96 a=r 72 r=a 97
a=r 73 r=a 98
a=r 73 r=a 99
a=r 73 r=a 100
a=r 73 r=a 101
a=r 73 r=a 102
a=0 r=a 49 r=a 50
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 51
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 52
a=0 r=a 60
do
a=r 7 b=r 60 a-=b r=a 61 b=r 62 a>b ifl a=b r=a 61 endif
a=0 r=a 58 r=a 46
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 45 a=r 2 a+= 8 r=a 2
a=r 45 a&= 127 b=r 46 a<<=b b=a a=r 58 a|=b r=a 58
a=r 46 a+= 7 r=a 46 a=r 45 a> 127
while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 53 a=r 2 a+= 24 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 47 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 54 a=r 2 a+= 16 r=a 2
a=r 47 a<<= 16 b=r 54 a+=b r=a 54
a=r 2 r=a 59 a=r 58 a<<= 3 b=r 2 a+=b r=a 2
a=0 r=a 57 r=a 33
do
a=0 r=a 34 r=a 64
do
a=r 52 b=r 50 a-=b r=a 42
a=r 51 b=r 49 a-=b r=a 43
a=r 52 b=r 50 a<b ifl a=r 43 a-- r=a 43 endif
a=r 43 a>>= 4 r=a 44
a=r 43 a&= 15 a<<= 28 r=a 45 a=r 42 a>>= 4 b=r 45 a+=b r=a 45
a=r 45 a<<= 16 a>>= 16 b=r 77 a*=b r=a 46
a=r 45 a>>= 16 b=r 77 a*=b b=a a=r 46 a>>= 16 a+=b r=a 48
a=r 44 b=r 77 a*=b b=a a=r 48 a>>= 16 a+=b r=a 42
a=r 48 a<<= 16 b=a a=r 46 a<<= 16 a>>= 16 a+=b r=a 43
a=r 42 a>>= 8 r=a 55
a=r 42 a&= 255 a<<= 24 b=a a=r 43 a>>= 8 a+=b r=a 56
a=r 56 b=r 50 a+=b r=a 56
a=r 55 b=r 49 a+=b r=a 55
a=r 56 b=r 50 a<b ifl a=r 55 a++ r=a 55 endif
a=0 r=a 63
a=r 55 b=r 53 a>b ifl a= 1 r=a 63 elsel a=r 55 a==b ifl a=r 56 b=r 54 a<b ifnot a= 1 r=a 63 endif endif endif
a=r 63 a> 0 ifl
  a=r 55 r=a 51 a=r 56 r=a 52
elsel
  a=r 56 a++ r=a 50 a=r 55 r=a 49 a=r 50 a== 0 ifl a=r 49 a++ r=a 49 endif
endif
a=r 88 a+= 16 d=a a=*d r=a 41
a=r 63 a<<= 12 b=r 41 a-=b r=a 114
a=r 88 a+= 18 d=a a=*d b=a a=r 114 a*=b r=a 114
a=r 114 a>>= 31 a> 0 ifl a=r 114 a! a>>= 10 a! elsel a=r 114 a>>= 10 endif r=a 114
a=r 114 a> 0 ifl
  a=r 88 a+= 18 d=a a=*d
a= 5
a<<= 8 a+= 128
  b=a a=*d a>b ifl a-- *d=a endif
  a=r 88 a+= 17 d=a a=*d b=r 114 a+=b *d=a
  a=r 88 a+= 8 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 0 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 9 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 1 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 10 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 2 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 11 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 3 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 12 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 4 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 13 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 5 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 14 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 6 d=a a=*d b=r 42 a+=b *d=a
  a=r 88 a+= 15 d=a a=*d b=r 114 a*=b r=a 42
a=r 42 a>>= 31 a> 0 ifl a=r 42 a! a>>= 12 a! elsel a=r 42 a>>= 12 endif r=a 42
  a=r 88 a+= 7 d=a a=*d b=r 42 a+=b *d=a
endif
a=r 78 a+=a b=r 63 a+=b r=a 78 a=r 81 a-- r=a 81
a=r 81 a== 0 ifl
  a=r 82 b=r 69 a&=b b=r 70 a+=b c=a a=r 78 *c=a
  a=r 82 a++ r=a 82
  a=r 79 a>>= 24 b=a a=r 80 a<<= 8 a|=b r=a 80
  a=r 78 a&= 255 b=a a=r 79 a<<= 8 a|=b r=a 79
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
  b=r 87 a*=b a<<= 4 b=r 79 a+=b b=r 68 a&=b r=a 87
  a= 1 r=a 78 a= 8 r=a 81
  a=r 79 a>>= 7 a&= 1 b=r 83 a+=b r=a 83
  a=r 79 b=r 67 a&=b r=a 41 a=r 84 a> 0 ifl a=r 41 a++ r=a 41 endif
  a=r 41 b= 19 a*=b b=r 75 a+=b r=a 88
  a=r 79 a&= 255 a<<= 8 r=a 89
  a=r 79 a<<= 16 a>>= 8 r=a 90
  a=r 79 a<<= 8 a>>= 8 r=a 45 a= 2 r=a 44
a= 58
a<<= 8 a+= 222
a<<= 8 a+= 104
a<<= 8 a+= 179
b=r 45 a*=b b=r 44 a+=b r=a 48 a<<= 16 r=a 47 a=r 48 a>>= 16 b=r 47 a|=b r=a 48
a= 7
a<<= 8 a+= 91
a<<= 8 a+= 205
a<<= 8 a+= 23
b=r 48 a*=b b=r 44 a+=b r=a 91
  a= 3 r=a 44
a= 58
a<<= 8 a+= 222
a<<= 8 a+= 104
a<<= 8 a+= 179
b=r 79 a*=b b=r 44 a+=b r=a 48 a<<= 16 r=a 47 a=r 48 a>>= 16 b=r 47 a|=b r=a 48
a= 7
a<<= 8 a+= 91
a<<= 8 a+= 205
a<<= 8 a+= 23
b=r 48 a*=b b=r 44 a+=b r=a 92
  a=r 82 a>>= 2 b=a a=r 83 a<b ifl
    a=r 80 a<<= 16 a>>= 16 b=r 79 a^=b r=a 45
a= 58
a<<= 8 a+= 222
a<<= 8 a+= 104
a<<= 8 a+= 179
b=r 45 a*=b b=r 90 a+=b r=a 48 a<<= 16 r=a 47 a=r 48 a>>= 16 b=r 47 a|=b r=a 48
a= 7
a<<= 8 a+= 91
a<<= 8 a+= 205
a<<= 8 a+= 23
b=r 48 a*=b b=r 90 a+=b r=a 93
a= 240
a<<= 8 a+= 240
a<<= 8 a+= 240
a<<= 8
    b=r 79 a&=b a>>= 4 r=a 45
a= 240
a<<= 8 a+= 240
a<<= 8 a+= 240
a<<= 8
    b=r 80 a&=b b=r 45 a|=b r=a 94
    a=r 65 a> 0 ifl
a= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
      b=r 79 a&=b a== 0 ifl
a= 79
a<<= 8 a+= 79
a<<= 8 a+= 255
a<<= 8 a+= 255
      b=r 79 a&=b elsel
a= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
      b=r 79 a&=b endif r=a 38
a= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
      b=r 80 a&=b a== 0 ifl
a= 79
a<<= 8 a+= 79
a<<= 8 a+= 255
a<<= 8 a+= 255
      b=r 80 a&=b elsel
a= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
a<<= 8 a+= 128
      b=r 80 a&=b endif r=a 39
      a=r 38 a<<= 2 r=a 38 a=r 39 a>>= 2 r=a 39
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 38 a*=b r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 39 a*=b b=r 47 a^=b r=a 47 r=a 46
a=r 47 a>>= 31 a> 0 ifl a=r 47 a! a>>= 1 a! elsel a=r 47 a>>= 1 endif r=a 47
a=r 46 a>>= 31 a> 0 ifl a=r 46 a! a>>= 9 a! elsel a=r 46 a>>= 9 endif r=a 46
a=r 47 b=r 46 a^=b r=a 47 a=r 38 a>>= 2 b=r 47 a^=b r=a 47 a=r 39 a>>= 3 b=r 47 a^=b b=a
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
a^=b r=a 95
    endif
  elsel
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
    b=r 84 a+=b r=a 44 a=r 79 a>>= 20 a<<= 20 r=a 45
a= 58
a<<= 8 a+= 222
a<<= 8 a+= 104
a<<= 8 a+= 179
b=r 45 a*=b b=r 44 a+=b r=a 48 a<<= 16 r=a 47 a=r 48 a>>= 16 b=r 47 a|=b r=a 48
a= 7
a<<= 8 a+= 91
a<<= 8 a+= 205
a<<= 8 a+= 23
b=r 48 a*=b b=r 44 a+=b r=a 93
    a=r 80 a<<= 16 b=r 89 a|=b r=a 94
    a=r 65 a> 0 ifl
      a=r 79 a>>= 16 a<<= 16 r=a 38 a=r 80 a>>= 16 r=a 39
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 38 a*=b r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 39 a*=b b=r 47 a^=b r=a 47 r=a 46
a=r 47 a>>= 31 a> 0 ifl a=r 47 a! a>>= 1 a! elsel a=r 47 a>>= 1 endif r=a 47
a=r 46 a>>= 31 a> 0 ifl a=r 46 a! a>>= 9 a! elsel a=r 46 a>>= 9 endif r=a 46
a=r 47 b=r 46 a^=b r=a 47 a=r 38 a>>= 2 b=r 47 a^=b r=a 47 a=r 39 a>>= 3 b=r 47 a^=b b=a
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
a^=b r=a 95
    endif
  endif
a=r 84 a> 0 ifl
  a=r 84 a< 88 ifl a++ r=a 84 endif a=r 85 a++ r=a 85
elsel
  a=r 74 b=r 87 a+=b d=a a=*d r=a 85
  a=r 85 a> 0 ifl a=r 82 b=r 85 a-=b b=r 69 a>b ifl a=0 elsel a= 1 endif elsel a=0 endif
  a> 0 ifl
    a= 2 r=a 41
    do
      a=r 82 b=r 41 a-=b a-- b=r 69 a&=b b=r 70 a+=b c=a a=*c r=a 42
      a=r 85 b=r 41 a-=b a-- b=r 69 a&=b b=r 70 a+=b c=a a=*c b=r 42 a==b ifl
        a=r 82 b=r 41 a-=b b=r 69 a&=b b=r 70 a+=b c=a a=*c r=a 42
        a=r 85 b=r 41 a-=b b=r 69 a&=b b=r 70 a+=b c=a a=*c b=r 42 a==b ifl
          a=r 41 a+= 2 r=a 41 a> 88 ifl a=0 elsel a= 1 endif
        elsel a=0 endif
      elsel a=0 endif
      a> 0
    while
    a=r 41 a-= 2 r=a 84
  endif
endif
  a=r 85 b=r 69 a&=b b=r 70 a+=b c=a a=*c a+= 255 a++ r=a 86
  a=r 74 b=r 87 a+=b d=a a=r 82 *d=a
endif
a=r 96 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 97 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 98 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 99 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 100 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 101 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
a+=b d=a a=*d *c=a
a=r 89 b=r 78 a+=b b=r 71 a+=b r=a 96
a=r 90 b=r 78 a+=b b=r 72 a+=b r=a 97
a=r 91 b=r 78 a+=b b=r 66 a&=b b=r 73 a+=b r=a 98
a=r 92 b=r 78 a+=b b=r 66 a&=b b=r 73 a+=b r=a 99
a=r 93 b=r 78 a+=b b=r 66 a&=b b=r 73 a+=b r=a 100
a=r 94 b=r 78 a^=b b=r 66 a&=b b=r 73 a+=b r=a 101
a=r 96 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 103
a= 8
a<<= 8
b=a a=r 103 a-=b r=a 103
a=r 97 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 104
a= 8
a<<= 8
b=a a=r 104 a-=b r=a 104
a=r 98 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 105
a= 8
a<<= 8
b=a a=r 105 a-=b r=a 105
a=r 99 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 106
a= 8
a<<= 8
b=a a=r 106 a-=b r=a 106
a=r 100 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 107
a= 8
a<<= 8
b=a a=r 107 a-=b r=a 107
a=r 101 c=a a=*c b=a
a= 3
a<<= 8
a+=b d=a a=*d r=a 108
a= 8
a<<= 8
b=a a=r 108 a-=b r=a 108
a=0 r=a 110 a=r 84 a> 0 ifl
  a=r 86 b=r 81 a>>=b b=r 78 a==b ifl
    a=r 84 a-- b=a
a= 4
a<<= 8
    a+=b d=a a=*d r=a 110
    a=r 81 a-- b=a a=r 86 a>>=b a&= 1 a== 0 ifl a=0 b=r 110 a-=b r=a 110 endif
  elsel a=0 r=a 84 endif
endif
a=r 65 a== 0 ifl
  a=r 110 r=a 109
a=0 r=a 41
a=r 88 a+= 8 d=a a=r 103 *d=a a=r 88 a+= 0 d=a a=*d b=r 103 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 9 d=a a=r 104 *d=a a=r 88 a+= 1 d=a a=*d b=r 104 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 10 d=a a=r 105 *d=a a=r 88 a+= 2 d=a a=*d b=r 105 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 11 d=a a=r 106 *d=a a=r 88 a+= 3 d=a a=*d b=r 106 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 12 d=a a=r 107 *d=a a=r 88 a+= 4 d=a a=*d b=r 107 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 13 d=a a=r 108 *d=a a=r 88 a+= 5 d=a a=*d b=r 108 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 14 d=a a=r 109 *d=a a=r 88 a+= 6 d=a a=*d b=r 109 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 15 d=a a=r 110 *d=a a=r 88 a+= 7 d=a a=*d b=r 110 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 17 d=a a=*d b=r 41 a+=b r=a 41
a= 1
a<<= 8
a<<= 8
b=a a=r 41 a+=b r=a 41
a=r 41 a>>= 31 a> 0 ifl a=r 41 a! a>>= 17 a! elsel a=r 41 a>>= 17 endif r=a 41
a=r 41 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 7 r=a 48
a= 15
a<<= 8 a+= 255
b=a a=r 48 a<b ifl
a= 4
a<<= 8 a+= 128
b=r 48 a+=b d=a a=*d r=a 113
elsel
  a=r 41 a>>= 31 a> 0 ifl a=0 elsel
a= 15
a<<= 8 a+= 255
  endif r=a 113
endif
a=r 88 a+= 16 d=a a=r 113 *d=a
  a=r 82 a>>= 3 b=a a=r 83 a<b ifl
a=r 111 a+= 0 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a=r 111 a+= 1 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a= 20
a<<= 8 a+= 128
b=r 113 a+=b d=a a=*d r=a 43
a=r 43 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 8 a>>= 7 r=a 44
a=r 78 b= 33 a*=b b=r 44 a+=b b=a
a= 1
a<<= 8 a+= 51
a<<= 8 a+= 16
a+=b r=a 111
a=r 43 a&= 127 r=a 44
a=r 111 d=a a=*d r=a 45 d++ a=*d b=r 45 a-=b b=r 44 a*=b r=a 46 a=r 45 a<<= 7 b=r 46 a+=b a>>= 11 r=a 41
    a=r 41 b= 3 a*=b b=r 113 a+=b a>>= 2 r=a 113
  endif
elsel
  a=r 102 c=a a=*c b=a a=r 63 a<<= 8 a+=b b=a
a= 1
a<<= 8
  a+=b d=a a=*d *c=a
  a=r 95 b=r 78 a+=b b=r 66 a&=b b=r 73 a+=b r=a 102
  a=r 102 c=a a=*c b=a
a= 3
a<<= 8
  a+=b d=a a=*d r=a 109
a= 8
a<<= 8
  b=a a=r 109 a-=b r=a 109
a=0 r=a 41
a=r 88 a+= 8 d=a a=r 103 *d=a a=r 88 a+= 0 d=a a=*d b=r 103 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 9 d=a a=r 104 *d=a a=r 88 a+= 1 d=a a=*d b=r 104 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 10 d=a a=r 105 *d=a a=r 88 a+= 2 d=a a=*d b=r 105 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 11 d=a a=r 106 *d=a a=r 88 a+= 3 d=a a=*d b=r 106 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 12 d=a a=r 107 *d=a a=r 88 a+= 4 d=a a=*d b=r 107 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 13 d=a a=r 108 *d=a a=r 88 a+= 5 d=a a=*d b=r 108 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 14 d=a a=r 109 *d=a a=r 88 a+= 6 d=a a=*d b=r 109 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 15 d=a a=r 110 *d=a a=r 88 a+= 7 d=a a=*d b=r 110 a*=b b=r 41 a+=b r=a 41
a=r 88 a+= 17 d=a a=*d b=r 41 a+=b r=a 41
a= 1
a<<= 8
a<<= 8
b=a a=r 41 a+=b r=a 41
a=r 41 a>>= 31 a> 0 ifl a=r 41 a! a>>= 17 a! elsel a=r 41 a>>= 17 endif r=a 41
a=r 41 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 7 r=a 48
a= 15
a<<= 8 a+= 255
b=a a=r 48 a<b ifl
a= 4
a<<= 8 a+= 128
b=r 48 a+=b d=a a=*d r=a 113
elsel
  a=r 41 a>>= 31 a> 0 ifl a=0 elsel
a= 15
a<<= 8 a+= 255
  endif r=a 113
endif
a=r 88 a+= 16 d=a a=r 113 *d=a
  a=r 89 b=r 78 a+=b r=a 42
  a=r 82 a>>= 3 b=a a=r 83 a<b ifl
a=r 112 a+= 0 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a=r 112 a+= 1 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a= 20
a<<= 8 a+= 128
b=r 113 a+=b d=a a=*d r=a 43
a=r 43 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 8 a>>= 7 r=a 44
a=r 42 b= 33 a*=b b=r 44 a+=b b=a
a=r 76
a+=b r=a 112
a=r 43 a&= 127 r=a 44
a=r 112 d=a a=*d r=a 45 d++ a=*d b=r 45 a-=b b=r 44 a*=b r=a 46 a=r 45 a<<= 7 b=r 46 a+=b a>>= 11 r=a 113
  elsel
    a=r 82 a>>= 2 b=a a=r 83 a<b ifnotl
a=r 111 a+= 0 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 6 a! elsel a=r 44 a>>= 6 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a=r 111 a+= 1 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 6 a! elsel a=r 44 a>>= 6 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a= 20
a<<= 8 a+= 128
b=r 113 a+=b d=a a=*d r=a 43
a=r 43 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 8 a>>= 7 r=a 44
a=r 78 b= 33 a*=b b=r 44 a+=b b=a
a= 1
a<<= 8 a+= 51
a<<= 8 a+= 16
a+=b r=a 111
a=r 43 a&= 127 r=a 44
a=r 111 d=a a=*d r=a 45 d++ a=*d b=r 45 a-=b b=r 44 a*=b r=a 46 a=r 45 a<<= 7 b=r 46 a+=b a>>= 11 r=a 41
      a=r 41 b= 3 a*=b b=r 113 a+=b a>>= 2 r=a 113
    endif
    a=r 89 b=r 78 a+=b r=a 42
a=r 112 a+= 0 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a=r 112 a+= 1 d=a a=*d r=a 43
a=r 63 a> 0 ifl
a= 255
a<<= 8 a+= 248
elsel a=0 endif
b=r 43 a-=b r=a 44
a=r 44 a>>= 31 a> 0 ifl a=r 44 a! a>>= 7 a! elsel a=r 44 a>>= 7 endif r=a 44
a=r 44 b=r 43 a+=b b=r 63 a+=b a<<= 16 a>>= 16 *d=a
a= 20
a<<= 8 a+= 128
b=r 113 a+=b d=a a=*d r=a 43
a=r 43 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 8 a>>= 7 r=a 44
a=r 42 b= 33 a*=b b=r 44 a+=b b=a
a=r 76
a+=b r=a 112
a=r 43 a&= 127 r=a 44
a=r 112 d=a a=*d r=a 45 d++ a=*d b=r 45 a-=b b=r 44 a*=b r=a 46 a=r 45 a<<= 7 b=r 46 a+=b a>>= 11 r=a 41
    a=r 41 b= 3 a*=b b=r 113 a+=b a>>= 2 r=a 113
  endif
endif
a= 8
a<<= 8
b=a a=r 113 a<b ifl a++ endif r=a 77
a=r 64 a+=a b=r 63 a+=b r=a 64
a=r 49 b=r 51 a==b ifl a=r 50 a>>= 24 b=a a=r 52 a>>= 24 a==b ifl
  a=r 50 a<<= 8 a>>= 8 r=a 49 a=0 r=a 50
  a=r 52 a<<= 8 a>>= 8 r=a 51
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
  r=a 52
  a=r 54 a<<= 8 a>>= 8 r=a 53
  a=r 57 a<<= 3 b=r 59 a+=b r=a 45
a=r 45 a&= 7 b=a a=r 45 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  a>>= 16 a<<= 16 r=a 54 a=r 45 a+= 16 r=a 45
a=r 45 a&= 7 b=a a=r 45 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  a>>= 16 b=r 54 a+=b r=a 54 a=r 57 a+= 4 r=a 57
endif endif
a=r 34 a+= 1 r=a 34
a=r 34 a< 8
while
a=r 60 b=r 33 a+=b r=a 42
a=r 16 b=r 42 a+=b c=a a=r 64 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 61 a<b
while
a=r 60 b=r 61 a+=b r=a 60 b=r 7 a<b
while
        endif
        a=r 16 r=a 21 r=a 19 a=r 17 r=a 23 r=a 20 a=r 7 r=a 22
        a=0 r=a 28 a= 1 r=a 29
        a=r 9 a&= 8 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 123 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 31 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 124
a=r 124 a> 239 ifl
  a= 1 a<<= 8 b=r 124 a-=b r=a 124
  a=r 124 a== 1 ifl
    a= 1 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 36
a=r 21 a+= 5 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 42
a=0 r=a 33
a=r 42 a> 0 ifl
do
a=r 23 b=r 31 a+=b c=a a=r 36 *c=a
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 42 a<b
while
endif
  elsel
a=0 r=a 33
a=r 124 a> 0 ifl
do
a=r 33 a++ r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 33 a+=b d=a a=r 41 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 124 a<b
while
endif
    a=r 124 a++ r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 43
    a=r 124 a+= 2 r=a 125
    a=r 124 a< 5 ifl
a=0 r=a 33
a=r 43 a> 0 ifl
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 43 a<b
while
endif
      a=r 125 b=r 22 a<b ifl
        do
a=r 21 b=r 125 a+=b c=a a=*c r=a 36
a=r 125 a+= 1 r=a 125
          a=r 36 a>>= 6 a&= 3 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 36 a>>= 4 a&= 3 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 36 a>>= 2 a&= 3 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 36 a>>= 0 a&= 3 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 125 b=r 22 a<b
        while
      endif
    elsel
      a=r 43 a> 0 ifl
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
      endif
      a=r 125 b=r 22 a<b ifl
        do
a=r 21 b=r 125 a+=b c=a a=*c r=a 36
a=r 125 a+= 1 r=a 125
          a=r 36 a>>= 4 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 36 a&= 15 r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8
b=r 41 a+=b d=a a=*d r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
          a=r 125 b=r 22 a<b
        while
      endif
    endif
  endif
elsel
  a= 1 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 43
  a=r 22 b=r 43 a-=b r=a 44 a= 2 r=a 125
a=0 r=a 33
do
a= 1 a<<= 16 b=r 33 a+=b r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8 a+= 16
b=r 33 a+=b d=a a=r 41 *d=a
a=r 33 a+= 1 r=a 33
a= 1
a<<= 8
b=a a=r 33 a<b
while
a=0 r=a 35
a=r 124 a> 0 ifl
do
a=r 125 a+= 2 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 42
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 125 a+= 1 r=a 125
a=r 21 b=r 125 a+=b c=a a=*c r=a 45
a=r 125 a+= 1 r=a 125
a=r 125 a+= 1 r=a 125
a=r 45 a<<= 8 b=r 41 a+=b r=a 41 a= 2 a<<= 16 b=r 41 a+=b r=a 41
a= 1
a<<= 8 a+= 50
a<<= 8 a+= 16
b=r 42 a+=b d=a a=r 41 *d=a
a=r 35 a+= 1 r=a 35
a=r 35 b=r 124 a<b
while
endif
  a=r 125 b=r 44 a<b ifl
    do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 125 a+= 1 r=a 125
a= 1
a<<= 8 a+= 50
a<<= 8 a+= 16
b=r 41 a+=b d=a a=*d r=a 36
      a=r 36 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
      a=r 36 a>>= 16 a== 2 ifl a=r 36 a>>= 8 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
      endif
      a=r 125 b=r 44 a<b
    while
  endif
  a=r 43 a> 0 ifl
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
  endif
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 16 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 123 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 3 r=a 42
a= 1 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 3 r=a 43
a= 2 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 44
a= 3 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 45
a=r 44 a<<= 8 b=r 45 a+=b r=a 32
a= 4 r=a 30
a=0 r=a 33
a=r 32 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 45
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 46
a=r 30 a+= 1 r=a 30
a=r 44 a<<= 8 b=r 45 a+=b a<<= 8 b=r 46 a+=b r=a 44
a=r 44 a>>= 19 r=a 45
a=r 45 a== 0 ifl a=r 44 a&= 255 r=a 46 a= 1 r=a 47 elsel
a=r 45 a== 1 ifl a=r 44 a&= 255 a<<= 8 r=a 46 a=r 44 a>>= 8 a&= 255 b=r 46 a+=b r=a 46 a= 2 r=a 47 elsel
a=r 45 a== 2 ifl
  a=r 44 a&= 63 a|= 128 a<<= 8 r=a 46 a=r 44 a>>= 6 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 12 a&= 15 a|= 224 b=r 46 a+=b r=a 46 a= 3 r=a 47
elsel
  a=r 44 a&= 63 a|= 128 a<<= 8 r=a 46 a=r 44 a>>= 6 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 12 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 18 a&= 7 a|= 240 b=r 46 a+=b r=a 46 a= 4 r=a 47
endif endif endif
a= 49
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
a= 177
a<<= 8
b=r 33 a+=b d=a a=r 47 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 32 a<b
while
endif
a=r 22 a-= 4 b=r 43 a+=b r=a 45
a=0 r=a 31
a=0 r=a 33
a=r 42 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 42 a<b
while
endif
a=r 30 b=r 45 a<b ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a=r 30 a+= 1 r=a 30
a=r 32 a> 128 ifl a=r 41 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 30 a+= 1 r=a 30
a=r 44 a<<= 7 b=r 41 a+=b a-= 128 r=a 41 endif endif
a= 49
a<<= 8
b=r 41 a+=b d=a a=*d r=a 46
a= 177
a<<= 8
b=r 41 a+=b d=a a=*d r=a 47
do
a=r 46 a&= 255 r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 31 a+= 1 r=a 31
a=r 46 a>>= 8 r=a 46 a=r 47 a-- r=a 47 a> 0
while
a=r 30 b=r 45 a<b
while
endif
a=r 24 a-= 4 b=r 43 a+=b b=r 31 a>b ifl
a= 4 b=r 43 a-=b r=a 42
a=0 r=a 33
a=r 42 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 42 a<b
while
endif
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 32 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 123 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 16 a> 0 ifl a= 2 elsel a= 1 endif r=a 122
a=r 41 a&= 64 r=a 121
a=r 122 a== 1 ifl a=r 5 a>>= 3 elsel a=r 5 a>>= 5 endif r=a 42
a=0 r=a 43 a=r 42 r=a 48
a=r 48 a> 1 ifl
do
a=r 48 a>>= 1 r=a 48 a=r 43 a++ r=a 43 a=r 48 a> 1
while
endif
a=r 122 a== 1 ifl a=r 43 a> 26 ifl a= 26 r=a 43 endif elsel a=r 43 a> 24 ifl a= 24 r=a 43 endif endif
a=r 43 a< 13 ifl a= 13 r=a 43 endif
a=r 3 a== 9 ifl a=r 43 a++ r=a 43 endif
a= 1 b=r 43 a<<=b a-- r=a 115
a= 13 r=a 43 a=r 123
a= 4
a<<= 8
b=a a=r 123 a<b ifnot a=r 123 a>>= 7 r=a 42
a=0 r=a 43 a=r 42 r=a 48
a=r 48 a> 1 ifl
do
a=r 48 a>>= 1 r=a 48 a=r 43 a++ r=a 43 a=r 48 a> 1
while
endif
a=r 43 a> 18 ifl a= 18 r=a 43 endif a=r 43 a< 13 ifl a= 13 r=a 43 endif
endif
a= 1 b=r 43 a<<=b r=a 116
a=r 122 a== 1 ifl
a= 4
a<<= 8 a+= 2
r=a 117
elsel
a= 4
a<<= 8
r=a 117
endif
a=r 116 b=r 117 a<b ifl a=b r=a 116 endif
a=r 115 a++ r=a 42
a= 26
a<<= 8
a<<= 8
d=a
a=0 r=a 33
do
a=0 *d=a d++ a=r 33 a++ r=a 33 b=r 42 a<b
while
a=0 r=a 33
do
a= 37
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a= 2
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 45
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 41
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a=r 44 a<<= 24 b=r 33 a+=b r=a 44
a= 18
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a=r 33 a+= 1 r=a 33
a= 4
a<<= 8
b=a a=r 33 a<b
while
a=r 122 a== 1 ifl
  a=r 1 a+= 40 c=a a= 14 *c=a c++ a= 15 *c=a
a= 4
a<<= 8
r=a 33
  a=r 1 a+= 40 r=a 44
a= 2
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a=0 r=a 44
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a= 1 a<<= 24 b=r 33 a+=b r=a 44
a= 18
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 4
a<<= 8 a+= 1
r=a 33
  a=r 1 a+= 41 r=a 44
a= 2
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a=0 r=a 44
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a= 1 a<<= 24 b=r 33 a+=b r=a 44
a= 18
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
endif
a=0 r=a 33
a=r 117 a> 0 ifl
do
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a=r 44 b=r 115 a&=b r=a 44 a=r 33 a++ r=a 45
a= 26
a<<= 8
a<<= 8
b=r 44 a+=b d=a a=r 45 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 117 a<b
while
endif
a=r 117 r=a 33
a=r 33 b=r 116 a<b ifl
do
a=0 r=a 44
a= 2
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 18
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 33 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 116 a<b
while
endif
a= 1 r=a 30 a=0 r=a 31
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a= 1
a<<= 8 a+= 49
a<<= 8
b=r 41 a+=b d=a a=*d r=a 42
a=r 42 a== 0 ifl a=r 30 a-- elsel a=r 30 endif r=a 119
a=r 117 r=a 118 a=0 r=a 120
a=r 30 b=r 22 a<b ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 38
a= 1
a<<= 8 a+= 49
a<<= 8
b=r 38 a+=b d=a a=*d r=a 42
a=r 42 a== 0 ifl
a=r 23 b=r 31 a+=b c=a a=r 38 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
elsel
a=r 42 a== 1 ifl a=r 119 a+= 3 b=a a=r 30 a>b ifl
  a=r 30 b=r 119 a-=b a-- r=a 43
  a=r 43 a< 32 ifl
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 44
    a=r 119 a++ r=a 45
    do
a=r 21 b=r 45 a+=b c=a a=*c r=a 46
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 44 a*=b r=a 44
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 46 a*=b b=r 44 a^=b r=a 44
a=r 45 a+= 1 r=a 45
      a=r 45 b=r 30 a<b
    while
    a=r 44 b=r 115 a&=b r=a 45
a= 26
a<<= 8
a<<= 8
b=r 45 a+=b d=a a=*d r=a 46
    a=0 r=a 47
    a=r 46 a> 0 ifl
      a=r 46 a-- r=a 124
a= 10
a<<= 8
a<<= 8
b=r 124 a+=b d=a a=*d r=a 48
      a=r 48 b=r 44 a==b ifl
a= 18
a<<= 8
a<<= 8
b=r 124 a+=b d=a a=*d r=a 48
        a=r 48 a>>= 24 b=r 43 a==b ifl a= 1 r=a 47 endif
      endif
    endif
    a=r 47 a== 0 ifl a=r 46 a== 0 ifl
      a=r 43 a> 3 ifl a= 1 elsel
a= 64
a<<= 8
      b=a a=r 118 a<b ifl a= 1 elsel a=0 endif endif
      a> 0 ifl
a= 18
a<<= 8
a<<= 8
b=r 118 a+=b d=a a=*d r=a 48
a= 7
a<<= 8 a+= 255
a<<= 8 a+= 255
        b=r 48 a&=b b=r 117 a<b ifnotl
a= 10
a<<= 8
a<<= 8
b=r 118 a+=b d=a a=*d r=a 48
          a=r 48 b=r 115 a&=b r=a 48 a=0 r=a 124
a= 26
a<<= 8
a<<= 8
b=r 48 a+=b d=a a=r 124 *d=a
          a=r 21 b=r 119 a+=b a++ r=a 48
a= 2
a<<= 8
a<<= 8
b=r 118 a+=b d=a a=r 48 *d=a
a= 10
a<<= 8
a<<= 8
b=r 118 a+=b d=a a=r 44 *d=a
          a=r 43 a<<= 24 b=r 118 a+=b r=a 48
a= 18
a<<= 8
a<<= 8
b=r 118 a+=b d=a a=r 48 *d=a
        endif
        a=r 118 a++ r=a 48
a= 26
a<<= 8
a<<= 8
b=r 45 a+=b d=a a=r 48 *d=a
a=r 118 a+= 1 r=a 118
        a=r 118 b=r 116 a<b ifnotl
a= 8
a<<= 8
a<<= 8
          b=a a=r 116 a<b ifl
            a=r 116 r=a 33 a+=a r=a 48
            do
              a=0 r=a 124
a= 2
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 124 *d=a
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 124 *d=a
a= 18
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 33 *d=a
a=r 33 a+= 1 r=a 33
              a=r 33 b=r 48 a<b
            while
            a=0 r=a 33
            do
a= 10
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=*d r=a 124
              a=r 124 b=r 115 a&=b r=a 124 a=r 33 a++ r=a 46
a= 26
a<<= 8
a<<= 8
b=r 124 a+=b d=a a=r 46 *d=a
a=r 33 a+= 1 r=a 33
              a=r 33 b=r 116 a<b
            while
            a=r 116 a+=a r=a 116
          elsel
            a=r 117 r=a 118
          endif
        endif
      endif
    endif endif
  endif
endif endif
a=r 30 a+= 1 r=a 30
a=0 r=a 47
a=r 122 a== 1 ifl
  a=r 38 a== 14 ifl a= 1 r=a 47 endif a=r 38 a== 15 ifl a= 1 r=a 47 endif
  a=r 47 a> 0 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 124
a=r 30 a+= 1 r=a 30
    a=r 124 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 45
a=r 30 a+= 1 r=a 30
      a=r 45 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
        a=r 124 a&= 31 a<<= 14 r=a 124 a=r 45 a&= 127 a<<= 7 b=r 124 a+=b b=r 48 a+=b r=a 124
      elsel
        a=r 124 a&= 127 a<<= 7 b=r 45 a+=b r=a 124
      endif
    endif
    a=r 38 a== 14 ifl a= 32 elsel a=0 endif r=a 46
  endif
elsel
  a=r 38 a> 127 ifl
    a= 1 r=a 47 a=0 r=a 46
    a=r 38 a== 128 ifl a= 32 r=a 46
a=r 21 b=r 30 a+=b c=a a=*c r=a 38
a=r 30 a+= 1 r=a 30
    endif
    a=r 38 a&= 127 r=a 124 a< 64 ifl a= 1 elsel a=0 endif r=a 45
    a=r 124 a> 63 ifl
      a=r 124 a> 111 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 43
a=r 30 a+= 1 r=a 30
        a=r 124 a&= 15 a<<= 8 b=r 48 a+=b a<<= 8 b=r 43 a+=b r=a 124
a= 32
a<<= 8 a+= 63
        b=r 124 a+=b r=a 124
      elsel
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
        a=r 124 a&= 31 a<<= 8 b=r 48 a+=b a+= 63 r=a 124
      endif
    endif
    a=r 124 b=r 45 a-=b r=a 124
  endif
endif
a=r 47 a> 0 ifl
a= 18
a<<= 8
a<<= 8
b=r 124 a+=b d=a a=*d r=a 48
  a=r 48 a>>= 24 r=a 43
a= 2
a<<= 8
a<<= 8
b=r 124 a+=b d=a a=*d r=a 44
  a=r 43 a> 1 ifl
    a=r 120 a> 0 ifl a= 32 r=a 45
a=r 23 b=r 31 a+=b c=a a=r 45 *c=a
a=r 31 a+= 1 r=a 31
    endif
    a= 1 r=a 120 a=r 30 r=a 119
  elsel
    a=0 r=a 120 a=r 30 a-- r=a 119
  endif
  a=r 31 r=a 45
  do
    a=r 44 c=a a=*c r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 44 a+= 1 r=a 44
a=r 31 a+= 1 r=a 31
    a=r 43 a-- r=a 43 a> 0
  while
  a=r 23 b=r 45 a+=b c=a a=*c b=r 46 a^=b *c=a
elsel
  a=r 122 a== 2 ifl a=r 38 a== 15 ifl a= 1 elsel a=0 endif elsel a=0 endif
  a> 0 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
  elsel
    a=r 121 a> 0 ifl a=r 38 a== 10 ifl a= 13 r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 31 a+= 1 r=a 31
    endif endif
a=r 23 b=r 31 a+=b c=a a=r 38 *c=a
a=r 31 a+= 1 r=a 31
  endif
  a=0 r=a 120 a=r 30 a-- r=a 119
endif
endif
a=r 30 b=r 22 a<b ifl a=r 31 b=r 123 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
a> 0
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 64 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 123 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 36
a= 1 r=a 125 a=0 r=a 31
a=r 125 b=r 22 a<b ifl
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
  a=r 41 b=r 36 a==b ifl
a=r 125 a+= 1 r=a 125
a=r 23 b=r 31 a+=b c=a a=r 36 *c=a
a=r 31 a+= 1 r=a 31
a=r 125 a+= 1 r=a 125
  endif
endif
a=r 125 b=r 22 a<b ifl
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 125 a+= 1 r=a 125
  a=r 41 b=r 36 a==b ifnotl
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
  elsel
a=r 21 b=r 125 a+=b c=a a=*c r=a 42
a=r 125 a+= 1 r=a 125
    a=r 42 a== 0 ifl
a=r 23 b=r 31 a+=b c=a a=r 36 *c=a
a=r 31 a+= 1 r=a 31
    elsel
      a=r 42 a== 255 ifl
a=r 21 b=r 125 a+=b c=a a=*c r=a 43
a=r 125 a+= 1 r=a 125
a=r 21 b=r 125 a+=b c=a a=*c r=a 44
a=r 125 a+= 1 r=a 125
        a=r 43 a<<= 8 b=r 44 a+=b r=a 42
a= 31
a<<= 8
        b=a a=r 42 a+=b r=a 42
      elsel
        a=r 42 a> 223 ifl
a=r 21 b=r 125 a+=b c=a a=*c r=a 43
a=r 125 a+= 1 r=a 125
          a=r 42 a-= 224 a<<= 8 b=r 43 a+=b a+= 224 r=a 42
        endif
      endif
      a=r 42 a+= 2 r=a 42 a=r 31 a-- r=a 43
a=r 23 b=r 43 a+=b c=a a=*c r=a 43
      a=r 23 b=r 31 a+=b c=a
      do
        a=r 43 *c=a c++ a=r 42 a-- r=a 42 a> 0
      while
      a=c b=r 23 a-=b r=a 31
    endif
  endif
  a=r 125 b=r 22 a<b
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 128 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 123 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 47
a=r 21 a+= 4 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 126
a=r 21 a+= 8 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 127
a= 9 r=a 125 a=0 r=a 31
a=0 r=a 33
a=r 126 a> 0 ifl
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 126 a<b
while
endif
a=r 47 a== 64 ifl
  a=r 125 b=r 127 a<b ifl
  do
    a=0 r=a 128
a=r 21 b=r 125 a+=b c=a a=*c r=a 38
    a=r 38 a== 15 ifl
      a=r 125 a++ b=r 127 a<b ifnotl
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
        a= 2 r=a 128
      elsel
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 21 b=r 125 a+=b c=a a=*c r=a 38
        a=r 38 a&= 240 a== 128 ifl a= 1 r=a 128 elsel
          a=r 38 a== 155 ifl
a=r 125 a+= 1 r=a 125
          endif
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
        endif
      endif
    elsel
      a=r 38 a&= 254 a== 232 ifl a= 1 r=a 128 elsel
        a=r 38 a== 155 ifl
a=r 125 a+= 1 r=a 125
        endif
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
      endif
    endif
    a=r 128 a== 1 ifl
      a=r 21 b=r 125 a+=b a++ c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c r=a 42
a= 240
a<<= 8 a+= 240
a<<= 8 a+= 240
a<<= 8 a+= 240
      b=r 42 a^=b b=r 31 a-=b r=a 42
      a>>= 31 a> 0 ifl a=0 b=r 42 a-=b a<<= 8 a>>= 8 b=a a=0 a-=b r=a 42 endif
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
      a=r 42 a>>= 0 a&= 255 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
      a=r 42 a>>= 8 a&= 255 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
      a=r 42 a>>= 16 a&= 255 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
      a=r 42 a>>= 24 a&= 255 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
a=r 125 a+= 4 r=a 125
    endif
    a=r 128 a< 2 ifl a=r 125 b=r 127 a<b elsel a=0 a> 0 endif
  while
  endif
elsel
  a=r 125 b=r 127 a<b ifl
  do
    a=r 21 b=r 125 a+=b a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 42
    a>>= 26 a<<= 26 r=a 43 a=0 r=a 128
a= 20
a<<= 8
a<<= 8
a<<= 8
    b=r 43 a==b ifl a= 1 r=a 128 endif
a= 148
a<<= 8
a<<= 8
a<<= 8
    b=r 43 a==b ifl a= 1 r=a 128 endif
    a=r 128 a== 0 ifl
a=0 r=a 35
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 35 a+= 1 r=a 35
a=r 35 a< 4
while
    elsel
      a=r 42 a<<= 6 a>>= 4 r=a 44
      a=r 44 a== 0 ifl
a=r 125 a+= 4 r=a 125
a=0 r=a 35
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 35 a+= 1 r=a 35
a=r 35 a< 4
while
      elsel
        a=r 44 b=r 31 a-=b a>>= 2 a<<= 6 a>>= 6 b=r 43 a|=b r=a 45
        a=r 45 a>>= 0 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
        a=r 45 a>>= 8 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
        a=r 45 a>>= 16 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
        a=r 45 a>>= 24 a&= 255 r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 31 a+= 1 r=a 31
a=r 125 a+= 4 r=a 125
      endif
    endif
    a=r 125 b=r 127 a<b
  while
  endif
endif
a=r 125 b=r 22 a<b ifl
do
a=r 21 b=r 125 a+=b c=a a=*c r=a 41
a=r 23 b=r 31 a+=b c=a a=r 41 *c=a
a=r 125 a+= 1 r=a 125
a=r 31 a+= 1 r=a 31
a=r 125 b=r 22 a<b
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
a=r 22 a> 0 ifl
  a=r 21 r=a 41 a=r 22 r=a 42
  do
    a=r 41 c=a a=*c out a=r 41 a++ r=a 41 a=r 42 a-- r=a 42 a> 0
  while
endif
      endif
      a=r 11 r=a 2 a= 1
    elsel a=0 endif
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZKNZ8";
