/*
  ZPAQKANZI7B: the decoder of zpaq-std -ma:kanzi level 7 since 65.4m-pre54, written in
  ZPAQL. zpaq-std, 2026. Generated by `KZROBUST=1 python3 gen7.py`; the same generator
  without KZROBUST gives ZPAQKANZI7. Changes, all for damaged data:
  - TEXT, static dictionary: a damaged dictionary with fewer than 1024 words no
    longer hashes an empty word 2^32 times.
  - TEXT: a dictionary entry of length 0 copies nothing, as kanzi's memcpy does.
    Before, the copy counted down from 0 and ran about 2^32 times.
  - UTF: an index outside the table emits nothing instead of looping 2^32 times.
  Each of these loops starts with a count that intact data never makes 0, so with
  intact data it decodes exactly what ZPAQKANZI7 decodes. With a damaged block another
  zpaq (7.15, zpaqfranz) took minutes instead of reporting an error; zpaq-std always
  decodes kanzi natively and was not affected. ZPAQKANZI7 stays frozen for the archives
  that already carry it.

  FROZEN, like the other portable decoders. A later kanzi format gets a new program.
*/
static const char ZPAQKANZI7B_CUERPO[] = R"ZKNZ7B(hcomp
halt
pcomp zpaqkanzi7b ;
(ZPAQKANZI7: decodificador de kanzi 2.6.0, bitstream 7 sin cabecera, nivel 7
 LZP+TEXT+UTF+BWT+LZP con CM, en ZPAQL, para zpaq-std -ma:kanzi. zpaq-std, 2026.
 Guarda la entrada en M y decodifica al final. La entrada lleva el diccionario
 estatico de kanzi detras de la cabecera.)
a> 255 ifl
  a=c r=a 1
  a=0 r=a 41 do a=0 *c=a c++ a=r 41 a++ r=a 41 a< 128 while
  a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 4
  a= 4 c=a a=*c r=a 3
  a=r 4 a+= 15 a>>= 4 a<<= 4 r=a 5
a= 4
a<<= 8
  b=a a=r 5 a<b ifl a=b r=a 5 endif
  a=r 5 a>>= 4 b=r 5 a+=b r=a 6 a=r 5 a+= 255 a+= 255 a+= 2 b=r 6 a>b ifl r=a 6 endif
a= 1
a<<= 8 a+= 14
a<<= 8
  d=a
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
a=0 r=a 32 r=a 41
a= 5 r=a 42
a= 21
a<<= 8 a+= 111
r=a 43
a=0 r=a 33
a=r 43 a> 0 ifl
do
a= 4
a<<= 8
b=a a=r 32 a<b ifl
a=r 42 b=r 33 a+=b c=a a=*c r=a 44
a=r 44 a> 64 ifl a< 91 ifl
  a=r 33 b=r 41 a>b ifl
    a=r 42 b=r 41 a+=b r=a 45
a= 2
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
    a=r 33 b=r 41 a-=b r=a 45
a= 6
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 32 a+= 1 r=a 32
    a=r 33 r=a 41
  endif
  a=r 42 b=r 33 a+=b c=a a=*c a^= 32 *c=a
endif endif
endif
a=r 33 a+= 1 r=a 33
a=r 33 b=r 43 a<b
while
endif
a= 4
a<<= 8
b=a a=r 32 a<b ifl
a=r 42 b=r 41 a+=b r=a 45
a= 2
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 43 b=r 41 a-=b r=a 45
a= 6
a<<= 8
b=r 32 a+=b d=a a=r 45 *d=a
a=r 32 a+= 1 r=a 32
endif
a=0 r=a 33
do
a= 2
a<<= 8
b=r 33 a+=b d=a a=*d r=a 45
a= 6
a<<= 8
b=r 33 a+=b d=a a=*d r=a 46
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 44
a=r 46 a> 0 ifl
do
a=r 45 c=a a=*c r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 44 a*=b r=a 44
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 47 a*=b b=r 44 a^=b r=a 44
a=r 45 a+= 1 r=a 45
a=r 46 a-- r=a 46 a> 0
while
endif
a= 10
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a=r 33 a+= 1 r=a 33
a= 4
a<<= 8
b=a a=r 33 a<b
while
a= 171
a<<= 8 a+= 160
r=a 2
  do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 15 a=r 2 a+= 5 r=a 2
a=r 15 a+= 3 r=a 15
    a=r 15 a> 24 ifl
      a=r 15 a-= 24 r=a 41
a=r 41 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 48 a= 32 b=r 41 a-=b b=a a=r 48 a>>=b r=a 42 a=r 2 b=r 41 a+=b r=a 2
elsel a=0 r=a 42 endif
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 43 a=r 2 a+= 24 r=a 2
      a=r 42 a<<= 24 b=r 43 a+=b r=a 10
    elsel
a=r 15 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 48 a= 32 b=r 15 a-=b b=a a=r 48 a>>=b r=a 10 a=r 2 b=r 15 a+=b r=a 2
elsel a=0 r=a 10 endif
    endif
    a=r 10 a> 0 ifl
      a=r 2 b=r 10 a+=b r=a 11
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 8 a=r 2 a+= 8 r=a 2
      a=r 8 a&= 128 r=a 12 a=0 r=a 13
      a=r 12 a> 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 r=a 13 endif endif
      a=r 13 a> 0 ifl a= 1 elsel a=r 12 a== 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif endif
      a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 9 a=r 2 a+= 8 r=a 2
      elsel
        a=r 8 a<<= 4 a|= 15 a&= 255 r=a 9
      endif
      a=r 8 a>>= 5 a&= 3 a++ r=a 14 a=0 r=a 7
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
        a=r 7 a<<= 8 b=r 41 a+=b r=a 7 a=r 14 a-- r=a 14 a> 0
      while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
      a=r 7 a+= 255 a+= 255 a+= 2 b=r 6 a<b ifl a=b endif r=a 25 a+= 64 r=a 18
      a=r 6 r=a 26 a=0 r=a 27
      a=r 1 a+= 128 r=a 16 b=r 18 a+=b r=a 17
      a=r 12 a> 0 ifl a=r 13 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
      a> 0 ifl
        a=r 7 a> 0 ifl
          do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
            a=r 41 out a=r 7 a-- r=a 7 a> 0
          while
        endif
      elsel
        a=r 13 a> 0 ifl
a=0 r=a 33
a=r 7 a> 0 ifl
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 41 a=r 2 a+= 8 r=a 2
a=r 16 b=r 33 a+=b c=a a=r 41 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 7 a<b
while
endif
        elsel
a=r 7 a< 64 ifl a= 64 elsel a=r 7 endif r=a 62
a= 4
a<<= 8
a<<= 8
a<<= 8
b=a a=r 62 a<b ifnotl
  a=r 62 a>>= 3 b=a
a= 4
a<<= 8
a<<= 8
a<<= 8
  a>b ifl a=r 7 a>>= 3 elsel a=r 7 a>>= 4 endif r=a 62
endif
a= 128
a<<= 8
r=a 41
a= 1
a<<= 8 a+= 15
a<<= 8
d=a
a= 1
a<<= 8 a+= 1
a<<= 8
r=a 48
do
a=r 41 *d=a d++ a=r 48 a-- r=a 48 a> 0
while
a=0 r=a 33
do
a= 17
b=r 33 a*=b b=a
a= 2
a<<= 8 a+= 16
a<<= 8
a+=b d=a a=0 r=a 42
do
a=r 42 a<<= 12 *d=a d++ a=r 42 a++ r=a 42 a< 16
while
a= 255
a<<= 8 a+= 255
*d=a
a=r 33 a+= 1 r=a 33
a= 2
a<<= 8
b=a a=r 33 a<b
while
a= 1 r=a 63 a=0 r=a 64 r=a 65 r=a 66
a=0 r=a 49 r=a 50
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 51
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 52
a=0 r=a 60
do
a=r 7 b=r 60 a-=b r=a 61 b=r 62 a>b ifl a=b r=a 61 endif
a=0 r=a 58 r=a 46
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 45 a=r 2 a+= 8 r=a 2
a=r 45 a&= 127 b=r 46 a<<=b b=a a=r 58 a|=b r=a 58
a=r 46 a+= 7 r=a 46 a=r 45 a> 127
while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 53 a=r 2 a+= 24 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 47 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 54 a=r 2 a+= 16 r=a 2
a=r 47 a<<= 16 b=r 54 a+=b r=a 54
a=r 2 r=a 59 a=r 58 a<<= 3 b=r 2 a+=b r=a 2
a=0 r=a 57 r=a 33
do
a=0 r=a 34
do
a= 1
a<<= 8 a+= 1
b=r 63 a*=b b=a
a= 1
a<<= 8 a+= 15
a<<= 8
a+=b r=a 70
a=r 70 a+= 255 a++ d=a a=*d r=a 41
a=r 70 b=r 65 a+=b d=a a=*d b=r 41 a+=b r=a 41 a+=a r=a 42 a+=a r=a 43 a+=a b=r 43 a+=b b=r 41 a+=b r=a 41
a=r 70 b=r 66 a+=b d=a a=*d r=a 42 a+=a b=r 42 a+=b a+=a b=r 41 a+=b a>>= 5 r=a 68
a=r 68 a>>= 12 r=a 69
a=r 63 b=r 64 a|=b r=a 41
a= 17
b=r 41 a*=b b=r 69 a+=b b=a
a= 2
a<<= 8 a+= 16
a<<= 8
a+=b r=a 47
a=r 47 d=a a=*d r=a 41 a=r 47 a++ d=a a=*d b=r 41 a+=b r=a 41 a+=a b=r 41 a+=b r=a 41
a=r 68 a+=a b=r 41 a+=b a+= 64 a>>= 7 r=a 67
a=r 52 b=r 50 a-=b r=a 42
a=r 51 b=r 49 a-=b r=a 43
a=r 52 b=r 50 a<b ifl a=r 43 a-- r=a 43 endif
a=r 43 a>>= 4 r=a 44
a=r 43 a&= 15 a<<= 28 r=a 45 a=r 42 a>>= 4 b=r 45 a+=b r=a 45
a=r 45 a<<= 16 a>>= 16 b=r 67 a*=b r=a 46
a=r 45 a>>= 16 b=r 67 a*=b b=a a=r 46 a>>= 16 a+=b r=a 48
a=r 44 b=r 67 a*=b b=a a=r 48 a>>= 16 a+=b r=a 42
a=r 48 a<<= 16 b=a a=r 46 a<<= 16 a>>= 16 a+=b r=a 43
a=r 42 a>>= 8 r=a 55
a=r 42 a&= 255 a<<= 24 b=a a=r 43 a>>= 8 a+=b r=a 56
a=r 56 b=r 50 a+=b r=a 56
a=r 55 b=r 49 a+=b r=a 55
a=r 56 b=r 50 a<b ifl a=r 55 a++ r=a 55 endif
a=0 r=a 44
a=r 55 b=r 53 a>b ifl a= 1 r=a 44 elsel a=r 55 a==b ifl a=r 56 b=r 54 a<b ifnot a= 1 r=a 44 endif endif endif
a=r 70 a+= 255 a++ r=a 41 a=r 70 b=r 65 a+=b r=a 42 a=r 47 a++ r=a 43
a=r 44 a> 0 ifl
  a=r 55 r=a 51 a=r 56 r=a 52
a=r 41 d=a a=*d r=a 46
a= 255
a<<= 8 a+= 240
b=r 46 a>b ifl
  a-=b a+= 3 a>>= 2 b=r 46 a+=b *d=a
elsel
a= 255
a<<= 8 a+= 240
  b=a a=r 46 a-=b a>>= 2 b=a a=r 46 a-=b *d=a
endif
a=r 42 d=a a=*d r=a 46
a= 255
a<<= 8 a+= 240
b=r 46 a>b ifl
  a-=b a+= 15 a>>= 4 b=r 46 a+=b *d=a
elsel
a= 255
a<<= 8 a+= 240
  b=a a=r 46 a-=b a>>= 4 b=a a=r 46 a-=b *d=a
endif
a=r 47 d=a a=*d r=a 46
a= 255
a<<= 8 a+= 240
b=r 46 a>b ifl
  a-=b a+= 63 a>>= 6 b=r 46 a+=b *d=a
elsel
a= 255
a<<= 8 a+= 240
  b=a a=r 46 a-=b a>>= 6 b=a a=r 46 a-=b *d=a
endif
a=r 43 d=a a=*d r=a 46
a= 255
a<<= 8 a+= 240
b=r 46 a>b ifl
  a-=b a+= 63 a>>= 6 b=r 46 a+=b *d=a
elsel
a= 255
a<<= 8 a+= 240
  b=a a=r 46 a-=b a>>= 6 b=a a=r 46 a-=b *d=a
endif
  a=r 63 a+=a a++ r=a 63
elsel
  a=r 56 a++ r=a 50 a=r 55 r=a 49 a=r 50 a== 0 ifl a=r 49 a++ r=a 49 endif
a=r 41 d=a a=*d r=a 46
a>>= 2 b=a a=r 46 a-=b *d=a
a=r 42 d=a a=*d r=a 46
a>>= 4 b=a a=r 46 a-=b *d=a
a=r 47 d=a a=*d r=a 46
a>>= 6 b=a a=r 46 a-=b *d=a
a=r 43 d=a a=*d r=a 46
a>>= 6 b=a a=r 46 a-=b *d=a
  a=r 63 a+=a r=a 63
endif
a=r 63 a> 255 ifl
  a=r 65 r=a 66 a=r 63 a&= 255 r=a 65 a= 1 r=a 63
  a=0 r=a 64 a=r 65 b=r 66 a==b ifl a= 1 a<<= 8 r=a 64 endif
endif
a=r 49 b=r 51 a==b ifl a=r 50 a>>= 24 b=a a=r 52 a>>= 24 a==b ifl
  a=r 50 a<<= 8 a>>= 8 r=a 49 a=0 r=a 50
  a=r 52 a<<= 8 a>>= 8 r=a 51
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
  r=a 52
  a=r 54 a<<= 8 a>>= 8 r=a 53
  a=r 57 a<<= 3 b=r 59 a+=b r=a 45
a=r 45 a&= 7 b=a a=r 45 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  a>>= 16 a<<= 16 r=a 54 a=r 45 a+= 16 r=a 45
a=r 45 a&= 7 b=a a=r 45 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  a>>= 16 b=r 54 a+=b r=a 54 a=r 57 a+= 4 r=a 57
endif endif
a=r 34 a+= 1 r=a 34
a=r 34 a< 8
while
a=r 60 b=r 33 a+=b r=a 42
a=r 16 b=r 42 a+=b c=a a=r 65 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 61 a<b
while
a=r 60 b=r 61 a+=b r=a 60 b=r 7 a<b
while
        endif
        a=r 16 r=a 21 r=a 19 a=r 17 r=a 23 r=a 20 a=r 7 r=a 22
        a=0 r=a 28 a= 1 r=a 29
        a=r 9 a&= 8 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 79 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a= 2
a<<= 8 a+= 50
a<<= 8
d=a
a= 1
a<<= 8
a<<= 8
r=a 48
do
a=r 41 *d=a d++ a=r 48 a-- r=a 48 a> 0
while
a=0 r=a 33
do
a=r 21 b=r 33 a+=b c=a a=*c r=a 41
a=r 23 b=r 33 a+=b c=a a=r 41 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 a< 4
while
a=r 23 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 83
a= 4 r=a 81 r=a 31
a=r 81 b=r 22 a<b ifl
do
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 83 a*=b a>>= 16 r=a 42
a= 2
a<<= 8 a+= 50
a<<= 8
b=r 42 a+=b d=a a=*d r=a 82
a= 2
a<<= 8 a+= 50
a<<= 8
b=r 42 a+=b d=a a=r 31 *d=a
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
a=0 r=a 44
a=r 43 a== 252 ifl a=r 82 a== 0 ifl a= 1 r=a 44 endif elsel a= 1 r=a 44 endif
a=r 44 a== 1 ifl
  a=r 83 a<<= 8 b=r 43 a+=b r=a 83
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
a=r 81 a+= 1 r=a 81
elsel
a=r 81 a+= 1 r=a 81
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
  a=r 43 a== 255 ifl
    a=r 83 a<<= 8 a+= 252 r=a 83 a= 252 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
a=r 81 a+= 1 r=a 81
  elsel
    a= 64 r=a 84
    a=r 43 a== 254 ifl
    do
a=r 81 a+= 1 r=a 81
      a=r 84 a+= 254 r=a 84
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
      a=r 43 a== 254 ifl a=r 81 b=r 22 a<b elsel a=0 a> 0 endif
    while
    endif
    a=r 84 b=r 43 a+=b r=a 84
a=r 81 a+= 1 r=a 81
    a=r 23 b=r 82 a+=b r=a 45 a=r 23 b=r 31 a+=b r=a 46
    do
      a=r 45 c=a a=*c b=a a=r 46 c=a a=b *c=a a=r 45 a++ r=a 45 a=r 46 a++ r=a 46
      a=r 84 a-- r=a 84 a> 0
    while
    a=r 46 b=r 23 a-=b r=a 31
    a=r 46 a-= 1 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 83
  endif
endif
a=r 81 b=r 22 a<b
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 16 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 79 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a>>= 2 a&= 7 r=a 42 a= 1 b=r 42 a<<=b r=a 42
a=r 41 a&= 3 a++ r=a 43
a=0 r=a 44 a= 1 r=a 30
a=0 r=a 33
a=r 43 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 45
a=r 44 a<<= 8 b=r 45 a+=b r=a 44
a=r 30 a+= 1 r=a 30
a=r 33 a+= 1 r=a 33
a=r 33 b=r 43 a<b
while
endif
a=r 44 a+= 1 r=a 44
a=r 42 b=r 43 a*=b a++ r=a 45
a=r 21 b=r 45 a+=b r=a 21 a=r 22 b=r 45 a-=b r=a 22
a=r 22 a== 1 ifl
  a=0 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a=r 23 b=r 30 a+=b c=a a=r 41 *c=a
elsel
a=0 r=a 33
do
a=0 r=a 41
a= 1
a<<= 8
b=r 33 a+=b d=a a=r 41 *d=a
a=r 33 a+= 1 r=a 33
a= 1
a<<= 8
b=a a=r 33 a<b
while
a=0 r=a 30
a=r 22 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a= 1
a<<= 8
b=r 41 a+=b d=a a=*d r=a 42
a=r 42 a+= 1 r=a 42
a= 1
a<<= 8
b=r 41 a+=b d=a a=r 42 *d=a
a=r 30 a+= 1 r=a 30
a=r 30 b=r 22 a<b
while
endif
a=0 r=a 42
a=0 r=a 33
do
a= 1
a<<= 8
b=r 33 a+=b d=a a=*d r=a 41
a= 1
a<<= 8
b=r 33 a+=b d=a a=r 42 *d=a
a=r 42 b=r 41 a+=b r=a 42
a=r 33 a+= 1 r=a 33
a= 1
a<<= 8
b=a a=r 33 a<b
while
a=0 r=a 30
a=r 22 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a=r 30 a== 0 ifl a=0 elsel a=r 30 b=r 44 a<b ifl a=r 30 a-- elsel a=r 30 endif endif r=a 43
a= 1
a<<= 8
b=r 41 a+=b d=a a=*d r=a 42
a=r 42 b=a
a= 4
a<<= 8
a<<= 8
a+=b d=a a=r 43 *d=a
a=r 42 a+= 1 r=a 42
a= 1
a<<= 8
b=r 41 a+=b d=a a=r 42 *d=a
a=r 30 a+= 1 r=a 30
a=r 30 b=r 22 a<b
while
endif
a=0 r=a 45
a=0 r=a 33
do
a= 1
a<<= 8
b=r 33 a+=b d=a a=*d r=a 46
a=r 45 b=r 46 a<b ifl
do
a=r 21 b=r 45 a+=b c=a a=r 33 *c=a
a=r 45 a+= 1 r=a 45
a=r 45 b=r 46 a<b
while
endif
a=r 33 a+= 1 r=a 33
a= 1
a<<= 8
b=a a=r 33 a<b
while
a=r 44 a-- r=a 41
a=0 r=a 30
a=r 22 a> 0 ifl
do
a=r 21 b=r 41 a+=b c=a a=*c r=a 43
a=r 23 b=r 30 a+=b c=a a=r 43 *c=a
a=r 41 b=a
a= 4
a<<= 8
a<<= 8
a+=b d=a a=*d r=a 41
a=r 30 a+= 1 r=a 30
a=r 30 b=r 22 a<b
while
endif
endif
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 32 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 79 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 3 r=a 42
a= 1 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 3 r=a 43
a= 2 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 44
a= 3 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 45
a=r 44 a<<= 8 b=r 45 a+=b r=a 32
a= 4 r=a 30
a=0 r=a 33
a=r 32 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 45
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 46
a=r 30 a+= 1 r=a 30
a=r 44 a<<= 8 b=r 45 a+=b a<<= 8 b=r 46 a+=b r=a 44
a=r 44 a>>= 19 r=a 45
a=r 45 a== 0 ifl a=r 44 a&= 255 r=a 46 a= 1 r=a 47 elsel
a=r 45 a== 1 ifl a=r 44 a&= 255 a<<= 8 r=a 46 a=r 44 a>>= 8 a&= 255 b=r 46 a+=b r=a 46 a= 2 r=a 47 elsel
a=r 45 a== 2 ifl
  a=r 44 a&= 63 a|= 128 a<<= 8 r=a 46 a=r 44 a>>= 6 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 12 a&= 15 a|= 224 b=r 46 a+=b r=a 46 a= 3 r=a 47
elsel
  a=r 44 a&= 63 a|= 128 a<<= 8 r=a 46 a=r 44 a>>= 6 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 12 a&= 63 a|= 128 b=r 46 a+=b a<<= 8 r=a 46
  a=r 44 a>>= 18 a&= 7 a|= 240 b=r 46 a+=b r=a 46 a= 4 r=a 47
endif endif endif
a= 14
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
a= 142
a<<= 8
b=r 33 a+=b d=a a=r 47 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 32 a<b
while
endif
a=r 22 a-= 4 b=r 43 a+=b r=a 45
a=0 r=a 31
a=0 r=a 33
a=r 42 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 42 a<b
while
endif
a=r 30 b=r 45 a<b ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a=r 30 a+= 1 r=a 30
a=r 32 a> 128 ifl a=r 41 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 30 a+= 1 r=a 30
a=r 44 a<<= 7 b=r 41 a+=b a-= 128 r=a 41 endif endif
a= 14
a<<= 8
b=r 41 a+=b d=a a=*d r=a 46
a= 142
a<<= 8
b=r 41 a+=b d=a a=*d r=a 47
a=r 47 a> 0 ifl
do
a=r 46 a&= 255 r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 31 a+= 1 r=a 31
a=r 46 a>>= 8 r=a 46 a=r 47 a-- r=a 47 a> 0
while
endif
a=r 30 b=r 45 a<b
while
endif
a=r 24 a-= 4 b=r 43 a+=b b=r 31 a>b ifl
a= 4 b=r 43 a-=b r=a 42
a=0 r=a 33
a=r 42 a> 0 ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 44
a=r 23 b=r 31 a+=b c=a a=r 44 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
a=r 33 a+= 1 r=a 33
a=r 33 b=r 42 a<b
while
endif
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 64 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 79 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a=r 21 b=r 41 a+=b c=a a=*c r=a 41
a=r 41 a&= 16 a> 0 ifl a= 2 elsel a= 1 endif r=a 78
a=r 41 a&= 64 r=a 77
a=r 78 a== 1 ifl a=r 5 a>>= 3 elsel a=r 5 a>>= 5 endif r=a 42
a=0 r=a 43 a=r 42 r=a 48
a=r 48 a> 1 ifl
do
a=r 48 a>>= 1 r=a 48 a=r 43 a++ r=a 43 a=r 48 a> 1
while
endif
a=r 78 a== 1 ifl a=r 43 a> 26 ifl a= 26 r=a 43 endif elsel a=r 43 a> 24 ifl a= 24 r=a 43 endif endif
a=r 43 a< 13 ifl a= 13 r=a 43 endif
a= 1 b=r 43 a<<=b a-- r=a 71
a= 13 r=a 43 a=r 79
a= 4
a<<= 8
b=a a=r 79 a<b ifnot a=r 79 a>>= 7 r=a 42
a=0 r=a 43 a=r 42 r=a 48
a=r 48 a> 1 ifl
do
a=r 48 a>>= 1 r=a 48 a=r 43 a++ r=a 43 a=r 48 a> 1
while
endif
a=r 43 a> 18 ifl a= 18 r=a 43 endif a=r 43 a< 13 ifl a= 13 r=a 43 endif
endif
a= 1 b=r 43 a<<=b r=a 72
a=r 78 a== 1 ifl
a= 4
a<<= 8 a+= 2
r=a 73
elsel
a= 4
a<<= 8
r=a 73
endif
a=r 72 b=r 73 a<b ifl a=b r=a 72 endif
a=r 71 a++ r=a 42
a= 28
a<<= 8
a<<= 8
d=a
a=0 r=a 33
do
a=0 *d=a d++ a=r 33 a++ r=a 33 b=r 42 a<b
while
a=0 r=a 33
do
a= 2
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a= 4
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 10
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 6
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a=r 44 a<<= 24 b=r 33 a+=b r=a 44
a= 20
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a=r 33 a+= 1 r=a 33
a= 4
a<<= 8
b=a a=r 33 a<b
while
a=r 78 a== 1 ifl
  a=r 1 a+= 40 c=a a= 14 *c=a c++ a= 15 *c=a
a= 4
a<<= 8
r=a 33
  a=r 1 a+= 40 r=a 44
a= 4
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a=0 r=a 44
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a= 1 a<<= 24 b=r 33 a+=b r=a 44
a= 20
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 4
a<<= 8 a+= 1
r=a 33
  a=r 1 a+= 41 r=a 44
a= 4
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a=0 r=a 44
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
  a= 1 a<<= 24 b=r 33 a+=b r=a 44
a= 20
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
endif
a=0 r=a 33
a=r 73 a> 0 ifl
do
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=*d r=a 44
a=r 44 b=r 71 a&=b r=a 44 a=r 33 a++ r=a 45
a= 28
a<<= 8
a<<= 8
b=r 44 a+=b d=a a=r 45 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 73 a<b
while
endif
a=r 73 r=a 33
a=r 33 b=r 72 a<b ifl
do
a=0 r=a 44
a= 4
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 44 *d=a
a= 20
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 33 *d=a
a=r 33 a+= 1 r=a 33
a=r 33 b=r 72 a<b
while
endif
a= 1 r=a 30 a=0 r=a 31
a=r 21 b=r 30 a+=b c=a a=*c r=a 41
a= 1
a<<= 8 a+= 14
a<<= 8
b=r 41 a+=b d=a a=*d r=a 42
a=r 42 a== 0 ifl a=r 30 a-- elsel a=r 30 endif r=a 75
a=r 73 r=a 74 a=0 r=a 76
a=r 30 b=r 22 a<b ifl
do
a=r 21 b=r 30 a+=b c=a a=*c r=a 38
a= 1
a<<= 8 a+= 14
a<<= 8
b=r 38 a+=b d=a a=*d r=a 42
a=r 42 a== 0 ifl
a=r 23 b=r 31 a+=b c=a a=r 38 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
elsel
a=r 42 a== 1 ifl a=r 75 a+= 3 b=a a=r 30 a>b ifl
  a=r 30 b=r 75 a-=b a-- r=a 43
  a=r 43 a< 32 ifl
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 44
    a=r 75 a++ r=a 45
    do
a=r 21 b=r 45 a+=b c=a a=*c r=a 46
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 44 a*=b r=a 44
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 46 a*=b b=r 44 a^=b r=a 44
a=r 45 a+= 1 r=a 45
      a=r 45 b=r 30 a<b
    while
    a=r 44 b=r 71 a&=b r=a 45
a= 28
a<<= 8
a<<= 8
b=r 45 a+=b d=a a=*d r=a 46
    a=0 r=a 47
    a=r 46 a> 0 ifl
      a=r 46 a-- r=a 80
a= 12
a<<= 8
a<<= 8
b=r 80 a+=b d=a a=*d r=a 48
      a=r 48 b=r 44 a==b ifl
a= 20
a<<= 8
a<<= 8
b=r 80 a+=b d=a a=*d r=a 48
        a=r 48 a>>= 24 b=r 43 a==b ifl a= 1 r=a 47 endif
      endif
    endif
    a=r 47 a== 0 ifl a=r 46 a== 0 ifl
      a=r 43 a> 3 ifl a= 1 elsel
a= 64
a<<= 8
      b=a a=r 74 a<b ifl a= 1 elsel a=0 endif endif
      a> 0 ifl
a= 20
a<<= 8
a<<= 8
b=r 74 a+=b d=a a=*d r=a 48
a= 7
a<<= 8 a+= 255
a<<= 8 a+= 255
        b=r 48 a&=b b=r 73 a<b ifnotl
a= 12
a<<= 8
a<<= 8
b=r 74 a+=b d=a a=*d r=a 48
          a=r 48 b=r 71 a&=b r=a 48 a=0 r=a 80
a= 28
a<<= 8
a<<= 8
b=r 48 a+=b d=a a=r 80 *d=a
          a=r 21 b=r 75 a+=b a++ r=a 48
a= 4
a<<= 8
a<<= 8
b=r 74 a+=b d=a a=r 48 *d=a
a= 12
a<<= 8
a<<= 8
b=r 74 a+=b d=a a=r 44 *d=a
          a=r 43 a<<= 24 b=r 74 a+=b r=a 48
a= 20
a<<= 8
a<<= 8
b=r 74 a+=b d=a a=r 48 *d=a
        endif
        a=r 74 a++ r=a 48
a= 28
a<<= 8
a<<= 8
b=r 45 a+=b d=a a=r 48 *d=a
a=r 74 a+= 1 r=a 74
        a=r 74 b=r 72 a<b ifnotl
a= 8
a<<= 8
a<<= 8
          b=a a=r 72 a<b ifl
            a=r 72 r=a 33 a+=a r=a 48
            do
              a=0 r=a 80
a= 4
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 80 *d=a
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 80 *d=a
a= 20
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=r 33 *d=a
a=r 33 a+= 1 r=a 33
              a=r 33 b=r 48 a<b
            while
            a=0 r=a 33
            do
a= 12
a<<= 8
a<<= 8
b=r 33 a+=b d=a a=*d r=a 80
              a=r 80 b=r 71 a&=b r=a 80 a=r 33 a++ r=a 46
a= 28
a<<= 8
a<<= 8
b=r 80 a+=b d=a a=r 46 *d=a
a=r 33 a+= 1 r=a 33
              a=r 33 b=r 72 a<b
            while
            a=r 72 a+=a r=a 72
          elsel
            a=r 73 r=a 74
          endif
        endif
      endif
    endif endif
  endif
endif endif
a=r 30 a+= 1 r=a 30
a=0 r=a 47
a=r 78 a== 1 ifl
  a=r 38 a== 14 ifl a= 1 r=a 47 endif a=r 38 a== 15 ifl a= 1 r=a 47 endif
  a=r 47 a> 0 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 80
a=r 30 a+= 1 r=a 30
    a=r 80 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 45
a=r 30 a+= 1 r=a 30
      a=r 45 a> 127 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
        a=r 80 a&= 31 a<<= 14 r=a 80 a=r 45 a&= 127 a<<= 7 b=r 80 a+=b b=r 48 a+=b r=a 80
      elsel
        a=r 80 a&= 127 a<<= 7 b=r 45 a+=b r=a 80
      endif
    endif
    a=r 38 a== 14 ifl a= 32 elsel a=0 endif r=a 46
  endif
elsel
  a=r 38 a> 127 ifl
    a= 1 r=a 47 a=0 r=a 46
    a=r 38 a== 128 ifl a= 32 r=a 46
a=r 21 b=r 30 a+=b c=a a=*c r=a 38
a=r 30 a+= 1 r=a 30
    endif
    a=r 38 a&= 127 r=a 80 a< 64 ifl a= 1 elsel a=0 endif r=a 45
    a=r 80 a> 63 ifl
      a=r 80 a> 111 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
a=r 21 b=r 30 a+=b c=a a=*c r=a 43
a=r 30 a+= 1 r=a 30
        a=r 80 a&= 15 a<<= 8 b=r 48 a+=b a<<= 8 b=r 43 a+=b r=a 80
a= 32
a<<= 8 a+= 63
        b=r 80 a+=b r=a 80
      elsel
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 30 a+= 1 r=a 30
        a=r 80 a&= 31 a<<= 8 b=r 48 a+=b a+= 63 r=a 80
      endif
    endif
    a=r 80 b=r 45 a-=b r=a 80
  endif
endif
a=r 47 a> 0 ifl
a= 20
a<<= 8
a<<= 8
b=r 80 a+=b d=a a=*d r=a 48
  a=r 48 a>>= 24 r=a 43
a= 4
a<<= 8
a<<= 8
b=r 80 a+=b d=a a=*d r=a 44
  a=r 43 a> 1 ifl
    a=r 76 a> 0 ifl a= 32 r=a 45
a=r 23 b=r 31 a+=b c=a a=r 45 *c=a
a=r 31 a+= 1 r=a 31
    endif
    a= 1 r=a 76 a=r 30 r=a 75
  elsel
    a=0 r=a 76 a=r 30 a-- r=a 75
  endif
  a=r 31 r=a 45
  a=r 43 a> 0 ifl
  do
    a=r 44 c=a a=*c r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 44 a+= 1 r=a 44
a=r 31 a+= 1 r=a 31
    a=r 43 a-- r=a 43 a> 0
  while
  endif
  a=r 23 b=r 45 a+=b c=a a=*c b=r 46 a^=b *c=a
elsel
  a=r 78 a== 2 ifl a=r 38 a== 15 ifl a= 1 elsel a=0 endif elsel a=0 endif
  a> 0 ifl
a=r 21 b=r 30 a+=b c=a a=*c r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 30 a+= 1 r=a 30
a=r 31 a+= 1 r=a 31
  elsel
    a=r 77 a> 0 ifl a=r 38 a== 10 ifl a= 13 r=a 48
a=r 23 b=r 31 a+=b c=a a=r 48 *c=a
a=r 31 a+= 1 r=a 31
    endif endif
a=r 23 b=r 31 a+=b c=a a=r 38 *c=a
a=r 31 a+= 1 r=a 31
  endif
  a=0 r=a 76 a=r 30 a-- r=a 75
endif
endif
a=r 30 b=r 22 a<b ifl a=r 31 b=r 79 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
a> 0
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
        a=r 9 a&= 128 a== 0 ifl
          a=r 29 a== 0 ifl a=r 25 elsel a=r 29 a== 1 ifl a=r 26 elsel a=r 27 endif endif r=a 24
          a=r 24 b=r 26 a<b ifl
            a=r 29 a< 2 ifl a= 2 r=a 29 endif
            a=r 27 b=r 26 a<b ifl a=b r=a 27 endif
            a=r 27 r=a 24
          endif
          a=r 24 r=a 79 a=r 19 r=a 21 a=r 20 r=a 23
a=0 r=a 41
a= 2
a<<= 8 a+= 50
a<<= 8
d=a
a= 1
a<<= 8
a<<= 8
r=a 48
do
a=r 41 *d=a d++ a=r 48 a-- r=a 48 a> 0
while
a=0 r=a 33
do
a=r 21 b=r 33 a+=b c=a a=*c r=a 41
a=r 23 b=r 33 a+=b c=a a=r 41 *c=a
a=r 33 a+= 1 r=a 33
a=r 33 a< 4
while
a=r 23 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 83
a= 4 r=a 81 r=a 31
a=r 81 b=r 22 a<b ifl
do
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 83 a*=b a>>= 16 r=a 42
a= 2
a<<= 8 a+= 50
a<<= 8
b=r 42 a+=b d=a a=*d r=a 82
a= 2
a<<= 8 a+= 50
a<<= 8
b=r 42 a+=b d=a a=r 31 *d=a
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
a=0 r=a 44
a=r 43 a== 252 ifl a=r 82 a== 0 ifl a= 1 r=a 44 endif elsel a= 1 r=a 44 endif
a=r 44 a== 1 ifl
  a=r 83 a<<= 8 b=r 43 a+=b r=a 83
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
a=r 81 a+= 1 r=a 81
elsel
a=r 81 a+= 1 r=a 81
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
  a=r 43 a== 255 ifl
    a=r 83 a<<= 8 a+= 252 r=a 83 a= 252 r=a 43
a=r 23 b=r 31 a+=b c=a a=r 43 *c=a
a=r 31 a+= 1 r=a 31
a=r 81 a+= 1 r=a 81
  elsel
    a= 64 r=a 84
    a=r 43 a== 254 ifl
    do
a=r 81 a+= 1 r=a 81
      a=r 84 a+= 254 r=a 84
a=r 21 b=r 81 a+=b c=a a=*c r=a 43
      a=r 43 a== 254 ifl a=r 81 b=r 22 a<b elsel a=0 a> 0 endif
    while
    endif
    a=r 84 b=r 43 a+=b r=a 84
a=r 81 a+= 1 r=a 81
    a=r 23 b=r 82 a+=b r=a 45 a=r 23 b=r 31 a+=b r=a 46
    do
      a=r 45 c=a a=*c b=a a=r 46 c=a a=b *c=a a=r 45 a++ r=a 45 a=r 46 a++ r=a 46
      a=r 84 a-- r=a 84 a> 0
    while
    a=r 46 b=r 23 a-=b r=a 31
    a=r 46 a-= 1 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 83
  endif
endif
a=r 81 b=r 22 a<b
while
endif
a=r 31 r=a 22
          a=r 28 r=a 41 a=r 29 r=a 28 a=r 41 r=a 29
          a=r 19 r=a 41 a=r 20 r=a 19 a=r 41 r=a 20
        endif
        a=r 19 r=a 21
a=r 22 a> 0 ifl
  a=r 21 r=a 41 a=r 22 r=a 42
  do
    a=r 41 c=a a=*c out a=r 41 a++ r=a 41 a=r 42 a-- r=a 42 a> 0
  while
endif
      endif
      a=r 11 r=a 2 a= 1
    elsel a=0 endif
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZKNZ7B";
