/*
  ZPAQKANZI1B: the decoder of zpaq-std -ma:kanzi levels 1 and 2 since 65.4m-pre54, written in
  ZPAQL. zpaq-std, 2026. Generated by `KZROBUST=1 python3 gen.py`; the same generator
  without KZROBUST gives ZPAQKANZI. Changes, all for damaged data:
  - Huffman: a code length outside 1..12 stops with a ZPAQL error, as in kanzi.
    Before, the table fill ran about 2^31 times.
  - DNA: an alphabet size of 0 skips the symbol map instead of reading it 2^32 times.
  Each of these loops starts with a count that intact data never makes 0, so with
  intact data it decodes exactly what ZPAQKANZI decodes. With a damaged block another
  zpaq (7.15, zpaqfranz) took minutes instead of reporting an error; zpaq-std always
  decodes kanzi natively and was not affected. ZPAQKANZI stays frozen for the archives
  that already carry it.

  FROZEN, like the other portable decoders. A later kanzi format gets a new program.
*/
static const char ZPAQKANZI1B_CUERPO[] = R"ZKNZ1B(hcomp
halt
pcomp zpaqkanzi1b ;
(ZPAQKANZI: decodificador de kanzi 2.6.0, bitstream 7 sin cabecera, niveles 1 LZX
 y 2 DNA+LZ con Huffman, en ZPAQL, para zpaq-std -ma:kanzi. zpaq-std, 2026.
 Guarda el flujo en M y lo decodifica al final.)
a> 255 ifl
  a=c r=a 1
  a=0 r=a 11 do *c=a c++ a=r 11 a++ r=a 11 a< 32 while
  a= 4 c=a a=*c r=a 6
  a= 40 r=a 2 a=r 1 a+= 32 r=a 3
  do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 16 a=r 2 a+= 5 r=a 2
a=r 16 a+= 3 r=a 16
    a=r 16 a> 24 ifl
      a=r 16 a-= 24 r=a 11
a=r 11 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 15 a= 32 b=r 11 a-=b b=a a=r 15 a>>=b r=a 12 a=r 2 b=r 11 a+=b r=a 2
elsel a=0 r=a 12 endif
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 13 a=r 2 a+= 24 r=a 2
      a=r 12 a<<= 24 b=r 13 a+=b r=a 10
    elsel
a=r 16 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 15 a= 32 b=r 16 a-=b b=a a=r 15 a>>=b r=a 10 a=r 2 b=r 16 a+=b r=a 2
elsel a=0 r=a 10 endif
    endif
    a=r 10 a> 0 ifl
      a=r 2 b=r 10 a+=b r=a 9
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 8 a=r 2 a+= 8 r=a 2
      a=r 8 a&= 128 r=a 18 a=0 r=a 19
      a=r 18 a> 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 r=a 19 endif endif
      a=r 18 a== 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
      a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 7 a=r 2 a+= 8 r=a 2
      elsel
        a=r 8 a<<= 4 a|= 15 a&= 255 r=a 7
      endif
      a=r 8 a>>= 5 a&= 3 a++ r=a 17 a=0 r=a 5
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
        a=r 5 a<<= 8 b=r 11 a+=b r=a 5 a=r 17 a-- r=a 17 a> 0
      while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
      a=r 18 a> 0 ifl a=r 19 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
      a> 0 ifl
        a=r 5 a> 0 ifl
          do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
            a=r 11 out a=r 5 a-- r=a 5 a> 0
          while
        endif
      elsel
        a=r 6 a== 2 ifl a=r 19 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
        a> 0 ifl
a=0 r=a 22
do
  a=r 5 b=r 22 a-=b r=a 30
a= 64
a<<= 8
  b=a a=r 30 a>b ifl a=b r=a 30 endif
  a=r 30 a< 32 ifl
    a=0 r=a 45
    do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
      a=r 22 b=r 45 a+=b r=a 12
a=r 3 b=r 12 a+=b c=a a=r 11 *c=a
a=r 45 a+= 1 r=a 45
      a=r 45 b=r 30 a<b
    while
  elsel
    a=0 r=a 45
    do
      a=0 r=a 11
a= 16
a<<= 8
b=r 45 a+=b d=a a=r 11 *d=a
a=r 45 a+= 1 r=a 45
      a=r 45 a> 255 until
    a=0 r=a 31
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 11 a=r 2 a+= 1 r=a 2
    a=r 11 a== 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 11 a=r 2 a+= 1 r=a 2
      a=0 r=a 45
      do
a= 17
a<<= 8 a+= 48
b=r 45 a+=b d=a a=r 45 *d=a
a=r 45 a+= 1 r=a 45
        a=r 45 a> 255 until
      a= 1 a<<= 8 r=a 31
    elsel
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 13 a=r 2 a+= 5 r=a 2
      a=0 r=a 45
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 14 a=r 2 a+= 8 r=a 2
        a=0 r=a 44
        do
          a=r 14 b=r 44 a>>=b a&= 1 a> 0 ifl
            a=r 45 a<<= 3 b=r 44 a+=b r=a 11
a= 17
a<<= 8 a+= 48
b=r 31 a+=b d=a a=r 11 *d=a
a=r 31 a+= 1 r=a 31
          endif
a=r 44 a+= 1 r=a 44
          a=r 44 a< 8
        while
a=r 45 a+= 1 r=a 45
        a=r 13 b=r 45 a<b
      until
    endif
    a= 2 r=a 32 a=0 r=a 45
    do
a= 17
a<<= 8 a+= 48
b=r 45 a+=b d=a a=*d r=a 46
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 11 a=r 2 a+= 1 r=a 2
      a=r 11 a== 0 ifl
        a= 1 r=a 33
        do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 11 a=r 2 a+= 1 r=a 2
          a=r 11 a== 0 ifl a=r 33 a++ r=a 33 endif
          a=r 11 a== 0
        while
        a=r 33 a> 7 ifl a= 7 r=a 33 endif
        a= 1 b=r 33 a<<=b a-- r=a 34
        a=r 33 a++ r=a 12
a=r 12 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 15 a= 32 b=r 12 a-=b b=a a=r 15 a>>=b r=a 13 a=r 2 b=r 12 a+=b r=a 2
elsel a=0 r=a 13 endif
        a=r 13 a>>= 1 b=r 34 a+=b r=a 14
        a=r 13 a&= 1 a> 0 ifl
          a=r 32 b=r 14 a-=b r=a 32
        elsel
          a=r 32 b=r 14 a+=b r=a 32
        endif
      endif
      a=r 32 a-- a> 11 ifl error endif
a= 16
a<<= 8
b=r 46 a+=b d=a a=r 32 *d=a
a=r 45 a+= 1 r=a 45
      a=r 45 b=r 31 a<b
    while
    a=r 31 a== 1 ifl
a= 17
a<<= 8 a+= 48
b=r 45 a+=b d=a a=*d r=a 46
      a=0 r=a 12
a= 17
a<<= 8 a+= 48
b=r 12 a+=b d=a a=*d r=a 46
      a=0 r=a 45
      do
        a=r 22 b=r 45 a+=b r=a 12
a=r 3 b=r 12 a+=b c=a a=r 46 *c=a
a=r 45 a+= 1 r=a 45
        a=r 45 b=r 30 a<b
      while
    elsel
      a=0 r=a 45
      do
        a=0 r=a 11
a= 17
a<<= 8
b=r 45 a+=b d=a a=r 11 *d=a
a=r 45 a+= 1 r=a 45
        a=r 45 a< 13
      while
      a=0 r=a 45
      do
a= 16
a<<= 8
b=r 45 a+=b d=a a=*d r=a 47
        a=r 47 a> 0 ifl
a= 17
a<<= 8
b=r 47 a+=b d=a a=*d r=a 11
a=r 11 a+= 1 r=a 11
a= 17
a<<= 8
b=r 47 a+=b d=a a=r 11 *d=a
        endif
a=r 45 a+= 1 r=a 45
        a=r 45 a> 255
      until
      a=0 r=a 12 a= 1 r=a 45
      do
a= 17
a<<= 8
b=r 45 a+=b d=a a=*d r=a 11
a= 17
a<<= 8
b=r 45 a+=b d=a a=r 12 *d=a
        a=r 12 b=r 11 a+=b r=a 12
a=r 45 a+= 1 r=a 45
        a=r 45 a< 13
      while
      a=0 r=a 45
      do
a= 16
a<<= 8
b=r 45 a+=b d=a a=*d r=a 47
        a=r 47 a> 0 ifl
a= 17
a<<= 8
b=r 47 a+=b d=a a=*d r=a 11
a= 17
a<<= 8 a+= 48
b=r 11 a+=b d=a a=r 45 *d=a
a=r 11 a+= 1 r=a 11
a= 17
a<<= 8
b=r 47 a+=b d=a a=r 11 *d=a
        endif
a=r 45 a+= 1 r=a 45
        a=r 45 a> 255
      until
      a=0 r=a 35 r=a 12
a= 17
a<<= 8 a+= 48
b=r 12 a+=b d=a a=*d r=a 46
a= 16
a<<= 8
b=r 46 a+=b d=a a=*d r=a 36
      a=0 r=a 45
      do
a= 17
a<<= 8 a+= 48
b=r 45 a+=b d=a a=*d r=a 46
a= 16
a<<= 8
b=r 46 a+=b d=a a=*d r=a 47
        a=r 47 b=r 36 a-=b b=a a=r 35 a<<=b r=a 35 a=r 47 r=a 36
        a= 12 b=r 47 a-=b r=a 13 a=r 35 b=r 13 a<<=b r=a 11
        a= 1 b=r 13 a<<=b r=a 14
        a=r 46 a<<= 8 b=r 47 a+=b r=a 13
        a=r 11 d=a
        do
          a=r 13 *d=a d++ a=r 14 a-- r=a 14 a> 0
        while
a=r 35 a+= 1 r=a 35
a=r 45 a+= 1 r=a 45
        a=r 45 b=r 31 a<b
      while
      a=0 r=a 37
      a=0 r=a 12
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
        a=r 11 a&= 127 b=r 12 a<<=b b=a a=r 37 a|=b r=a 37
        a=r 12 a+= 7 r=a 12 a=r 11 a> 127
      while
      a=0 r=a 38
      a=0 r=a 12
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
        a=r 11 a&= 127 b=r 12 a<<=b b=a a=r 38 a|=b r=a 38
        a=r 12 a+= 7 r=a 12 a=r 11 a> 127
      while
      a=0 r=a 39
      a=0 r=a 12
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
        a=r 11 a&= 127 b=r 12 a<<=b b=a a=r 39 a|=b r=a 39
        a=r 12 a+= 7 r=a 12 a=r 11 a> 127
      while
      a=0 r=a 40
      a=0 r=a 12
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
        a=r 11 a&= 127 b=r 12 a<<=b b=a a=r 40 a|=b r=a 40
        a=r 12 a+= 7 r=a 12 a=r 11 a> 127
      while
      a=r 30 a>>= 2 r=a 41
      a=r 2 r=a 42
      a=r 42 r=a 43
      a=r 41 a> 0 ifl
        a=r 41 b= 0 a*=b b=r 22 a+=b b=r 3 a+=b r=a 14
        a=r 41 r=a 45
        do
          a=r 43 a&= 7 b=a a=r 43 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
          a>>= 20 d=a a=*d
          r=a 11 a&= 255 b=r 43 a+=b r=a 43
          a=r 11 a>>= 8 c=r 14 *c=a c++ a=c r=a 14
          a=r 45 a-- r=a 45 a> 0
        while
      endif
      a=r 42 b=r 37 a+=b r=a 42
      a=r 42 r=a 43
      a=r 41 a> 0 ifl
        a=r 41 b= 1 a*=b b=r 22 a+=b b=r 3 a+=b r=a 14
        a=r 41 r=a 45
        do
          a=r 43 a&= 7 b=a a=r 43 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
          a>>= 20 d=a a=*d
          r=a 11 a&= 255 b=r 43 a+=b r=a 43
          a=r 11 a>>= 8 c=r 14 *c=a c++ a=c r=a 14
          a=r 45 a-- r=a 45 a> 0
        while
      endif
      a=r 42 b=r 38 a+=b r=a 42
      a=r 42 r=a 43
      a=r 41 a> 0 ifl
        a=r 41 b= 2 a*=b b=r 22 a+=b b=r 3 a+=b r=a 14
        a=r 41 r=a 45
        do
          a=r 43 a&= 7 b=a a=r 43 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
          a>>= 20 d=a a=*d
          r=a 11 a&= 255 b=r 43 a+=b r=a 43
          a=r 11 a>>= 8 c=r 14 *c=a c++ a=c r=a 14
          a=r 45 a-- r=a 45 a> 0
        while
      endif
      a=r 42 b=r 39 a+=b r=a 42
      a=r 42 r=a 43
      a=r 41 a> 0 ifl
        a=r 41 b= 3 a*=b b=r 22 a+=b b=r 3 a+=b r=a 14
        a=r 41 r=a 45
        do
          a=r 43 a&= 7 b=a a=r 43 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
          a>>= 20 d=a a=*d
          r=a 11 a&= 255 b=r 43 a+=b r=a 43
          a=r 11 a>>= 8 c=r 14 *c=a c++ a=c r=a 14
          a=r 45 a-- r=a 45 a> 0
        while
      endif
      a=r 42 b=r 40 a+=b r=a 42
      a=r 42 r=a 2
      a=r 41 a<<= 2 r=a 45
      a=r 45 b=r 30 a<b ifl
        do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
          a=r 22 b=r 45 a+=b r=a 12
a=r 3 b=r 12 a+=b c=a a=r 11 *c=a
a=r 45 a+= 1 r=a 45
          a=r 45 b=r 30 a<b
        while
      endif
    endif
  endif
  a=r 22 b=r 30 a+=b r=a 22 b=r 5 a<b
while
        elsel
a=0 r=a 45
a=r 5 a> 0 ifl
  do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 11 a=r 2 a+= 8 r=a 2
a=r 3 b=r 45 a+=b c=a a=r 11 *c=a
a=r 45 a+= 1 r=a 45
    a=r 45 b=r 5 a<b
  while
endif
        endif
        a=r 3 r=a 20 a=r 5 r=a 21 b=r 3 a+=b a+= 32 r=a 4
        a=r 6 a== 1 ifl a= 128 elsel a= 64 endif b=r 7 a&=b
        a== 0 ifl
a=r 20 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 50
a=r 20 a+= 7 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 51
a=r 20 a+= 11 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 52
a=r 51 b=r 50 a+=b r=a 51 a=r 52 b=r 51 a+=b r=a 52
a=r 50 a-= 13 r=a 53
a=r 20 a+= 12 c=a a=*c a>>= 1 a&= 7 a+= 2 r=a 54
a= 13 r=a 55 a=0 r=a 56 a=r 21 r=a 57 r=a 58
do
a=r 20 b=r 50 a+=b c=a a=*c
  r=a 59
a=r 50 a+= 1 r=a 50
  a=r 59 a&= 24 a== 0 ifl
    a=r 59 a&= 3 r=a 60 a== 3 ifl
a=r 20 b=r 52 a+=b c=a a=*c
r=a 12
a=r 52 a+= 1 r=a 52
a=r 12 a> 253 ifl
  a== 254 ifl
a=r 20 b=r 52 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a+= 254 r=a 12
a=r 52 a+= 1 r=a 52
  elsel
a=r 20 b=r 52 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a+= 255 r=a 12
a=r 52 a+= 1 r=a 52
  endif
endif
      a=r 60 b=r 12 a+=b b=r 54 a+=b r=a 60
    elsel a=r 60 b=r 54 a+=b r=a 60 endif
    a=r 59 a&= 4 a== 0 ifl a=r 57 elsel a=r 58 endif r=a 61
  elsel
    a=r 59 a&= 7 r=a 60 a== 7 ifl
a=r 20 b=r 52 a+=b c=a a=*c
r=a 12
a=r 52 a+= 1 r=a 52
a=r 12 a> 253 ifl
  a== 254 ifl
a=r 20 b=r 52 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a+= 254 r=a 12
a=r 52 a+= 1 r=a 52
  elsel
a=r 20 b=r 52 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a<<= 8 r=a 15
a=r 52 a+= 1 r=a 52
a=r 20 b=r 52 a+=b c=a a=*c
    b=r 15 a+=b a+= 255 r=a 12
a=r 52 a+= 1 r=a 52
  endif
endif
      a=r 60 b=r 12 a+=b b=r 54 a+=b r=a 60
    elsel a=r 60 b=r 54 a+=b r=a 60 endif
    a=r 59 a>>= 3 a&= 3 r=a 62
    a=r 20 b=r 51 a+=b c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c r=a 11
    a=r 62 a== 1 ifl a=r 11 a>>= 24 a+= 1 elsel
    a=r 62 a== 2 ifl a=r 11 a>>= 16 a+= 1 a+= 1 a+= 255 elsel
      a=r 11 a>>= 8 r=a 11
a= 1
a<<= 8 a+= 1
a<<= 8 a+= 1
      b=r 11 a+=b
    endif endif
    r=a 61 a=r 51 b=r 62 a+=b r=a 51
  endif
  a=0 r=a 14
  a=r 59 a> 31 ifl
    a=r 59 a> 223 ifl
a=r 20 b=r 55 a+=b c=a a=*c
r=a 12
a=r 55 a+= 1 r=a 55
a=r 12 a> 253 ifl
  a== 254 ifl
a=r 20 b=r 55 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 55 a+= 1 r=a 55
a=r 20 b=r 55 a+=b c=a a=*c
    b=r 15 a+=b a+= 254 r=a 12
a=r 55 a+= 1 r=a 55
  elsel
a=r 20 b=r 55 a+=b c=a a=*c
    a<<= 8 r=a 15
a=r 55 a+= 1 r=a 55
a=r 20 b=r 55 a+=b c=a a=*c
    b=r 15 a+=b a<<= 8 r=a 15
a=r 55 a+= 1 r=a 55
a=r 20 b=r 55 a+=b c=a a=*c
    b=r 15 a+=b a+= 255 r=a 12
a=r 55 a+= 1 r=a 55
  endif
endif
      a=r 12 a+= 7 r=a 63
    elsel a=r 59 a>>= 5 r=a 63 endif
    a=r 63 a> 0 ifl
      do
a=r 20 b=r 55 a+=b c=a a=*c
        r=a 11
a=r 4 b=r 56 a+=b c=a a=r 11 *c=a
a=r 55 a+= 1 r=a 55
a=r 56 a+= 1 r=a 56
        a=r 63 a-- r=a 63 a> 0
      while
    endif
    a=r 55 b=r 53 a<b ifnot a= 1 r=a 14 endif
  endif
  a=r 14 a== 0 ifl
    a=r 57 r=a 58 a=r 61 r=a 57
    a=r 4 b=r 56 a+=b r=a 12 b=r 61 a-=b r=a 13
    a=r 60 a> 0 ifl
      do
        a=r 13 c=a a=*c b=a a=r 12 c=a a=b *c=a
a=r 12 a+= 1 r=a 12
a=r 13 a+= 1 r=a 13
        a=r 60 a-- r=a 60 a> 0
      while
    endif
    a=r 12 b=r 4 a-=b r=a 56
  endif
  a=r 14 a> 0
until
a=r 56 r=a 21
          a=r 4 r=a 20
        endif
        a=r 6 a== 2 ifl a=r 7 a&= 128 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
        a> 0 ifl
a=0 r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
r=a 70
a=r 70 a> 239 ifl
  a= 1 a<<= 8 b=r 70 a-=b r=a 70
  a=r 70 a== 1 ifl
    a= 1 r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
    r=a 73
a=r 20 a+= 5 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 12
    a=r 12 a> 0 ifl
      do
        a=r 73 out a=r 12 a-- r=a 12 a> 0
      while
    endif
  elsel
    a=0 r=a 45
    do
      a=r 45 a++ r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
      r=a 11
a= 18
a<<= 8 a+= 48
b=r 45 a+=b d=a a=r 11 *d=a
a=r 45 a+= 1 r=a 45
      a=r 45 b=r 70 a<b
    while
    a=r 70 a++ r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
    r=a 71 a=r 70 a+= 2 r=a 55
    a=r 70 a< 5 ifl
      a=r 71 a> 0 ifl
        do
a=r 20 b=r 55 a+=b c=a a=*c
          out
a=r 55 a+= 1 r=a 55
          a=r 71 a-- r=a 71 a> 0
        while
      endif
      a=r 55 b=r 21 a<b ifl
        do
a=r 20 b=r 55 a+=b c=a a=*c
          r=a 73
a=r 55 a+= 1 r=a 55
          a=r 73 a>>= 6 a&= 3 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 73 a>>= 4 a&= 3 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 73 a>>= 2 a&= 3 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 73 a>>= 0 a&= 3 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 55 b=r 21 a<b
        while
      endif
    elsel
      a=r 71 a> 0 ifl
a=r 20 b=r 55 a+=b c=a a=*c
        out
a=r 55 a+= 1 r=a 55
      endif
      a=r 55 b=r 21 a<b ifl
        do
a=r 20 b=r 55 a+=b c=a a=*c
          r=a 73
a=r 55 a+= 1 r=a 55
          a=r 73 a>>= 4 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 73 a&= 15 r=a 11
a= 18
a<<= 8 a+= 48
b=r 11 a+=b d=a a=*d r=a 11
          out
          a=r 55 b=r 21 a<b
        while
      endif
    endif
  endif
elsel
  a= 1 r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
  r=a 71 a=r 21 b=r 71 a-=b r=a 72 a= 2 r=a 55
  a=0 r=a 45
  do
    a= 1 a<<= 16 b=r 45 a+=b r=a 11
a= 18
a<<= 8 a+= 64
b=r 45 a+=b d=a a=r 11 *d=a
a=r 45 a+= 1 r=a 45
    a=r 45 a> 255
  until
  a=r 70 r=a 44
  a=r 44 a> 0 ifl
  do
    a=r 55 a+= 2 r=a 11
a=r 20 b=r 11 a+=b c=a a=*c
    r=a 13
a=r 20 b=r 55 a+=b c=a a=*c
    r=a 11
a=r 55 a+= 1 r=a 55
a=r 20 b=r 55 a+=b c=a a=*c
    a<<= 8 b=r 11 a+=b r=a 11
a=r 55 a+= 1 r=a 55
a=r 55 a+= 1 r=a 55
    a= 2 a<<= 16 b=r 11 a+=b r=a 11
a= 18
a<<= 8 a+= 64
b=r 13 a+=b d=a a=r 11 *d=a
    a=r 44 a-- r=a 44 a> 0
  while
  endif
  a=r 55 b=r 72 a<b ifl
    do
a=r 20 b=r 55 a+=b c=a a=*c
      r=a 11
a=r 55 a+= 1 r=a 55
a= 18
a<<= 8 a+= 64
b=r 11 a+=b d=a a=*d r=a 73
      a=r 73 out a=r 73 a>>= 16 a== 2 ifl a=r 73 a>>= 8 out endif
      a=r 55 b=r 72 a<b
    while
  endif
  a=r 71 a> 0 ifl
a=r 20 b=r 55 a+=b c=a a=*c
    out
  endif
endif
        elsel
a=r 21 a> 0 ifl
  a=r 20 r=a 11 a=r 21 r=a 12
  do
    a=r 11 c=a a=*c out a=r 11 a++ r=a 11 a=r 12 a-- r=a 12 a> 0
  while
endif
        endif
      endif
      a=r 9 r=a 2 a= 1
    elsel a=0 endif
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZKNZ1B";
