/*
  ZPAQKANZI5: the decoder of zpaq-std -ma:kanzi levels 5 and 6, written in ZPAQL.
  zpaq-std, 2026. Generated by gen5.py (next to this file); ref5.py is the Python
  reference it was written from, itself checked against kanzi's C++ decoder.

  kanzi (github.com/flanglet/kanzi-cpp, Frederic Langlet) 2.6.0, bitstream 7,
  headerless, exactly kanzi's own levels 5 and 6:
    level 5: TEXT + UTF + BWT + RANK + ZRLT, entropy ANS0 (order-0 rANS, 4 states)
    level 6: TEXT + UTF + BWT + SRT  + ZRLT, entropy FPAQ (binary, 56-bit range)
  TEXT is kanzi's word dictionary in both variants (TextCodec2 for level 5,
  TextCodec1 for level 6): the 1024-word static dictionary plus the dynamic one,
  rebuilt with kanzi's hash, its slot handling and its expansions, sized from the
  block size and from the buffer lengths kanzi's TransformSequence uses.
  Every block type and every combination of skipped transforms is handled.

  Input: original size (4 bytes LE), level (1 byte), kanzi's static dictionary
  (5487 bytes, zpaqkanzi_dict.h), then kanzi's stream. M: the input, then two
  buffers; H: small tables, the BWT inverse array and TEXT's tables. zpaq-std sets
  ph from the block size and pm from the first block's header so that they fit.
  The output goes out with OUT.

  Verified with zpaqd 7.15 on 194 streams, identical to the input and to ref5.py:
  156 written by kanzi (78 inputs x levels 5 and 6: English text up to 10 MB, text
  with CRLF, inflated vocabularies that make the dictionary expand, UTF-8 Spanish,
  Japanese and Cyrillic, binaries, audio, random data, sizes 10 bytes up) and 38
  blocks rebuilt by craft.py with kanzi's own transforms in other combinations of
  skipped transforms, and a one-symbol ANS chunk, all checked with kanzi's decoder.

  FROZEN, like the other portable decoders. A later kanzi format gets a new program.
*/
static const char ZPAQKANZI5_CUERPO[] = R"ZKNZ5(hcomp
halt
pcomp zpaqkanzi5 ;
(ZPAQKANZI5: decodificador de kanzi 2.6.0, bitstream 7 sin cabecera, niveles 5
 TEXT+UTF+BWT+RANK+ZRLT con ANS0 y 6 TEXT+UTF+BWT+SRT+ZRLT con FPAQ, en ZPAQL, para
 zpaq-std -ma:kanzi. zpaq-std, 2026. Guarda la entrada en M y decodifica al final.
 La entrada lleva el diccionario estatico de kanzi detras de la cabecera.)
a> 255 ifl
  a=c r=a 1
  a=0 r=a 42 do *c=a c++ a=r 42 a++ r=a 42 a< 64 while
  a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 4
  a= 4 c=a a=*c r=a 3
  a=r 4 a+= 15 a>>= 4 a<<= 4 r=a 5
a= 4
a<<= 8
  b=a a=r 5 a<b ifl a=b r=a 5 endif
  a=r 5 a>>= 4 b=r 5 a+=b r=a 6 a=r 5 b= 0 a+= 255 a+= 255 a+= 2 b=r 6 a>b ifl r=a 6 endif
a= 1
a<<= 8 a+= 255
a<<= 8
  d=a
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 0 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 1 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
  a= 2 *d=a d++
a=0 r=a 33 r=a 42
a= 5 r=a 43
a= 21
a<<= 8 a+= 111
r=a 44
a=0 r=a 34
a=r 44 a> 0 ifl
do
a= 4
a<<= 8
b=a a=r 33 a<b ifl
a=r 43 b=r 34 a+=b c=a a=*c r=a 45
a=r 45 a> 64 ifl a< 91 ifl
  a=r 34 b=r 42 a>b ifl
    a=r 43 b=r 42 a+=b r=a 46
a= 14
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
    a=r 34 b=r 42 a-=b r=a 46
a= 18
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
a=r 33 a+= 1 r=a 33
    a=r 34 r=a 42
  endif
  a=r 43 b=r 34 a+=b c=a a=*c a^= 32 *c=a
endif endif
endif
a=r 34 a+= 1 r=a 34
a=r 34 b=r 44 a<b
while
endif
a= 4
a<<= 8
b=a a=r 33 a<b ifl
a=r 43 b=r 42 a+=b r=a 46
a= 14
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
a=r 44 b=r 42 a-=b r=a 46
a= 18
a<<= 8
b=r 33 a+=b d=a a=r 46 *d=a
a=r 33 a+= 1 r=a 33
endif
a=0 r=a 34
do
a= 14
a<<= 8
b=r 34 a+=b d=a a=*d r=a 46
a= 18
a<<= 8
b=r 34 a+=b d=a a=*d r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 45
do
a=r 46 c=a a=*c r=a 48
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 45 a*=b r=a 45
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 48 a*=b b=r 45 a^=b r=a 45
a=r 46 a+= 1 r=a 46
a=r 47 a-- r=a 47 a> 0
while
a= 22
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a=r 34 a+= 1 r=a 34
a= 4
a<<= 8
b=a a=r 34 a<b
while
a= 171
a<<= 8 a+= 160
r=a 2
  do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 15 a=r 2 a+= 5 r=a 2
a=r 15 a+= 3 r=a 15
    a=r 15 a> 24 ifl
      a=r 15 a-= 24 r=a 42
a=r 42 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 49 a= 32 b=r 42 a-=b b=a a=r 49 a>>=b r=a 43 a=r 2 b=r 42 a+=b r=a 2
elsel a=0 r=a 43 endif
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 44 a=r 2 a+= 24 r=a 2
      a=r 43 a<<= 24 b=r 44 a+=b r=a 10
    elsel
a=r 15 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 49 a= 32 b=r 15 a-=b b=a a=r 49 a>>=b r=a 10 a=r 2 b=r 15 a+=b r=a 2
elsel a=0 r=a 10 endif
    endif
    a=r 10 a> 0 ifl
      a=r 2 b=r 10 a+=b r=a 11
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 8 a=r 2 a+= 8 r=a 2
      a=r 8 a&= 128 r=a 12 a=0 r=a 13
      a=r 12 a> 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 r=a 13 endif endif
      a=r 13 a> 0 ifl a= 1 elsel a=r 12 a== 0 ifl a=r 8 a&= 16 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif endif
      a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 9 a=r 2 a+= 8 r=a 2
      elsel
        a=r 8 a<<= 4 a|= 15 a&= 255 r=a 9
      endif
      a=r 8 a>>= 5 a&= 3 a++ r=a 14 a=0 r=a 7
      do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 42 a=r 2 a+= 8 r=a 2
        a=r 7 a<<= 8 b=r 42 a+=b r=a 7 a=r 14 a-- r=a 14 a> 0
      while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 42 a=r 2 a+= 8 r=a 2
      a=r 7 a+= 255 a+= 255 a+= 2 b=r 6 a<b ifl a=b endif r=a 23 a+= 64 r=a 18
      a=r 6 r=a 24 a=0 r=a 25
      a=r 1 a+= 128 r=a 16 b=r 18 a+=b r=a 17
      a=r 12 a> 0 ifl a=r 13 a== 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
      a> 0 ifl
        a=r 7 a> 0 ifl
          do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 42 a=r 2 a+= 8 r=a 2
            a=r 42 out a=r 7 a-- r=a 7 a> 0
          while
        endif
      elsel
        a=r 13 a> 0 ifl
a=0 r=a 34
a=r 7 a> 0 ifl
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 42 a=r 2 a+= 8 r=a 2
a=r 16 b=r 34 a+=b c=a a=r 42 *c=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 7 a<b
while
endif
        elsel
          a=r 3 a== 5 ifl
a=r 7 a< 33 ifl
a=0 r=a 34
a=r 7 a> 0 ifl
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 42 a=r 2 a+= 8 r=a 2
a=r 16 b=r 34 a+=b c=a a=r 42 *c=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 7 a<b
while
endif
elsel
a=0 r=a 58
do
a=r 7 b=r 58 a-=b r=a 60
a= 64
a<<= 8
b=a a=r 60 a>b ifl a=b r=a 60 endif
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 29 r=a 54 a=r 2 a+= 3 r=a 2
a=r 54 a+= 8 r=a 54
a= 1 b=r 54 a<<=b r=a 55 a-- r=a 56
a=0 r=a 33
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 42 a=r 2 a+= 1 r=a 2
a=r 42 a== 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 31 r=a 42 a=r 2 a+= 1 r=a 2
a=0 r=a 34
do
a= 0
b=r 34 a+=b d=a a=r 34 *d=a
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a= 1
a<<= 8
r=a 33
elsel
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 27 r=a 44 a=r 2 a+= 5 r=a 2
a=0 r=a 34
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 45 a=r 2 a+= 8 r=a 2
a=0 r=a 36
do
a=r 45 b=r 36 a>>=b a&= 1 a> 0 ifl
a=r 34 a<<= 3 b=r 36 a+=b r=a 42
a= 0
b=r 33 a+=b d=a a=r 42 *d=a
a=r 33 a+= 1 r=a 33
endif
a=r 36 a+= 1 r=a 36
a=r 36 a< 8
while
a=r 34 a+= 1 r=a 34
a=r 44 b=r 34 a<b
until
endif
a=0 r=a 34
do
a=0 r=a 42
a= 1
a<<= 8
b=r 34 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 43
a=r 33 a> 63 ifl a= 8 elsel a= 6 endif r=a 44
a= 1 r=a 34
a=r 34 b=r 33 a<b ifl
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 28 r=a 45 a=r 2 a+= 4 r=a 2
a=r 34 b=r 44 a+=b r=a 35 b=r 33 a>b ifl a=b r=a 35 endif
a=r 34 r=a 36
do
a=r 45 a== 0 ifl a= 1 r=a 46 elsel
a=r 45 a> 0 ifl
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
  r=a 49 a= 32 b=r 45 a-=b b=a a=r 49 a>>=b r=a 46 a=r 2 b=r 45 a+=b r=a 2
elsel a=0 r=a 46 endif
a=r 46 a+= 1 r=a 46
endif
a= 0
b=r 36 a+=b d=a a=*d r=a 47
a= 1
a<<= 8
b=r 47 a+=b d=a a=r 46 *d=a
a=r 43 b=r 46 a+=b r=a 43
a=r 36 a+= 1 r=a 36
a=r 36 b=r 35 a<b
while
a=r 35 r=a 34 b=r 33 a<b
while
endif
a=r 55 b=r 43 a-=b r=a 46 a=0 r=a 47
a= 0
b=r 47 a+=b d=a a=*d r=a 47
a= 1
a<<= 8
b=r 47 a+=b d=a a=r 46 *d=a
a=r 33 a== 1 ifl
a=0 r=a 47
a= 0
b=r 47 a+=b d=a a=*d r=a 47
a=0 r=a 34
a=r 60 a> 0 ifl
do
a=r 58 b=r 34 a+=b r=a 42
a=r 16 b=r 42 a+=b c=a a=r 47 *c=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 60 a<b
while
endif
elsel
a=0 r=a 43
a=0 r=a 34
do
a= 1
a<<= 8
b=r 34 a+=b d=a a=*d r=a 44
a=r 44 a> 0 ifl
a= 2
a<<= 8
b=r 34 a+=b d=a a=r 43 *d=a
a=r 55 a-- b=a a=r 44 a>b ifl a=b endif r=a 45
a= 3
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a=r 44 r=a 45
a= 1
a<<= 8 a+= 26
a<<= 8
b=r 43 a+=b d=a
do
a=r 34 *d=a d++ a=r 45 a-- r=a 45 a> 0
while
a=r 43 b=r 44 a+=b r=a 43
endif
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 70 r=a 47
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 46 a=r 2 a+= 8 r=a 2
a=r 46 a&= 127 b=r 47 a<<=b b=a a=r 70 a|=b r=a 70
a=r 47 a+= 7 r=a 47 a=r 46 a> 127
while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 48 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 50 a=r 2 a+= 16 r=a 2
a=r 48 a<<= 16 b=r 50 a+=b r=a 50
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 48 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 51 a=r 2 a+= 16 r=a 2
a=r 48 a<<= 16 b=r 51 a+=b r=a 51
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 48 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 52 a=r 2 a+= 16 r=a 2
a=r 48 a<<= 16 b=r 52 a+=b r=a 52
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 48 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 53 a=r 2 a+= 16 r=a 2
a=r 48 a<<= 16 b=r 53 a+=b r=a 53
a=r 2 r=a 57
a=r 60 a>>= 2 a<<= 2 r=a 42
a=0 r=a 34
a=r 42 a> 0 ifl
do
a=r 53 b=r 56 a&=b b=a
a= 1
a<<= 8 a+= 26
a<<= 8
a+=b d=a a=*d r=a 44
a=r 58 b=r 34 a+=b a+= 0 r=a 45
a=r 16 b=r 45 a+=b c=a a=r 44 *c=a
a= 3
a<<= 8
b=r 44 a+=b d=a a=*d r=a 46
a= 2
a<<= 8
b=r 44 a+=b d=a a=*d r=a 47
a=r 53 b=r 54 a>>=b b=r 46 a*=b r=a 46
a=r 53 b=r 56 a&=b b=r 46 a+=b b=r 47 a-=b r=a 53
a= 128
a<<= 8
b=a a=r 53 a<b ifl
a=r 57 a&= 7 b=a a=r 57 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 46 a=r 57 a+= 16 r=a 57
a=r 53 a<<= 16 b=r 46 a+=b r=a 53
endif
a=r 52 b=r 56 a&=b b=a
a= 1
a<<= 8 a+= 26
a<<= 8
a+=b d=a a=*d r=a 44
a=r 58 b=r 34 a+=b a+= 1 r=a 45
a=r 16 b=r 45 a+=b c=a a=r 44 *c=a
a= 3
a<<= 8
b=r 44 a+=b d=a a=*d r=a 46
a= 2
a<<= 8
b=r 44 a+=b d=a a=*d r=a 47
a=r 52 b=r 54 a>>=b b=r 46 a*=b r=a 46
a=r 52 b=r 56 a&=b b=r 46 a+=b b=r 47 a-=b r=a 52
a= 128
a<<= 8
b=a a=r 52 a<b ifl
a=r 57 a&= 7 b=a a=r 57 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 46 a=r 57 a+= 16 r=a 57
a=r 52 a<<= 16 b=r 46 a+=b r=a 52
endif
a=r 51 b=r 56 a&=b b=a
a= 1
a<<= 8 a+= 26
a<<= 8
a+=b d=a a=*d r=a 44
a=r 58 b=r 34 a+=b a+= 2 r=a 45
a=r 16 b=r 45 a+=b c=a a=r 44 *c=a
a= 3
a<<= 8
b=r 44 a+=b d=a a=*d r=a 46
a= 2
a<<= 8
b=r 44 a+=b d=a a=*d r=a 47
a=r 51 b=r 54 a>>=b b=r 46 a*=b r=a 46
a=r 51 b=r 56 a&=b b=r 46 a+=b b=r 47 a-=b r=a 51
a= 128
a<<= 8
b=a a=r 51 a<b ifl
a=r 57 a&= 7 b=a a=r 57 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 46 a=r 57 a+= 16 r=a 57
a=r 51 a<<= 16 b=r 46 a+=b r=a 51
endif
a=r 50 b=r 56 a&=b b=a
a= 1
a<<= 8 a+= 26
a<<= 8
a+=b d=a a=*d r=a 44
a=r 58 b=r 34 a+=b a+= 3 r=a 45
a=r 16 b=r 45 a+=b c=a a=r 44 *c=a
a= 3
a<<= 8
b=r 44 a+=b d=a a=*d r=a 46
a= 2
a<<= 8
b=r 44 a+=b d=a a=*d r=a 47
a=r 50 b=r 54 a>>=b b=r 46 a*=b r=a 46
a=r 50 b=r 56 a&=b b=r 46 a+=b b=r 47 a-=b r=a 50
a= 128
a<<= 8
b=a a=r 50 a<b ifl
a=r 57 a&= 7 b=a a=r 57 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 46 a=r 57 a+= 16 r=a 57
a=r 50 a<<= 16 b=r 46 a+=b r=a 50
endif
a=r 34 a+= 4 r=a 34
a=r 34 b=r 42 a<b
while
endif
a=r 42 r=a 34 b=r 60 a<b ifl
do
a=r 57 a&= 7 b=a a=r 57 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 44 a=r 57 a+= 8 r=a 57
a=r 58 b=r 34 a+=b r=a 45
a=r 16 b=r 45 a+=b c=a a=r 44 *c=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 60 a<b
while
endif
a=r 70 a<<= 3 b=r 2 a+=b r=a 2
endif
a=r 58 b=r 60 a+=b r=a 58 b=r 7 a<b
while
endif
          elsel
a= 128 a<<= 8 r=a 42
a= 10
a<<= 8
d=a
a=0 r=a 34
do
a=r 42 *d=a d++ a=r 34 a++ r=a 34
a= 4
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 61 r=a 62
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 63
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
r=a 64
a=0 r=a 58
do
a=r 7 b=r 58 a-=b r=a 60
a= 64
a<<= 8
a<<= 8
b=a a=r 60 a>b ifl a=b r=a 60 endif
a=0 r=a 70 r=a 47
do
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 24 r=a 46 a=r 2 a+= 8 r=a 2
a=r 46 a&= 127 b=r 47 a<<=b b=a a=r 70 a|=b r=a 70
a=r 47 a+= 7 r=a 47 a=r 46 a> 127
while
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 8 r=a 65 a=r 2 a+= 24 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 48 a=r 2 a+= 16 r=a 2
a=r 2 a&= 7 b=a a=r 2 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
a>>= 16 r=a 66 a=r 2 a+= 16 r=a 2
a=r 48 a<<= 16 b=r 66 a+=b r=a 66
a=r 2 r=a 57 a=r 70 a<<= 3 b=r 2 a+=b r=a 2
a=0 r=a 69
a= 10
a<<= 8
r=a 72
a=0 r=a 34
do
a= 1 r=a 71 a=0 r=a 35
do
a=r 72 b=r 71 a+=b d=a a=*d r=a 42
a=r 64 b=r 62 a-=b r=a 43
a=r 63 b=r 61 a-=b r=a 44
a=r 64 b=r 62 a<b ifl a=r 44 a-- r=a 44 endif
a=r 44 a>>= 8 r=a 45
a=r 44 a&= 255 a<<= 24 r=a 46 a=r 43 a>>= 8 b=r 46 a+=b r=a 46
a=r 46 a<<= 16 a>>= 16 b=r 42 a*=b r=a 47
a=r 46 a>>= 16 b=r 42 a*=b b=a a=r 47 a>>= 16 a+=b r=a 48
a=r 45 b=r 42 a*=b b=a a=r 48 a>>= 16 a+=b r=a 43
a=r 48 a<<= 16 b=a a=r 47 a<<= 16 a>>= 16 a+=b r=a 44
a=r 43 a>>= 8 r=a 67
a=r 43 a&= 255 a<<= 24 b=a a=r 44 a>>= 8 a+=b r=a 68
a=r 68 b=r 62 a+=b r=a 68
a=r 67 b=r 61 a+=b r=a 67
a=r 68 b=r 62 a<b ifl a=r 67 a++ r=a 67 endif
a=0 r=a 45
a=r 67 b=r 65 a>b ifl a= 1 r=a 45 elsel a=r 67 a==b ifl a=r 68 b=r 66 a<b ifnot a= 1 r=a 45 endif endif endif
a=r 45 a> 0 ifl
  a=r 67 r=a 63 a=r 68 r=a 64
  a=r 42 b=a
a= 255
a<<= 8 a+= 192
  a>b ifl a-=b a+= 63 a>>= 6 b=r 42 a+=b elsel a=r 42 a-=b a>>= 6 a=r 42 endif
  a<<= 16 a>>= 16 r=a 43
  a=r 72 b=r 71 a+=b d=a a=r 43 *d=a
  a=r 71 a+=a a++ r=a 71
elsel
  a=r 68 a++ r=a 62 a=r 67 r=a 61 a=r 62 a== 0 ifl a=r 61 a++ r=a 61 endif
  a=r 42 a>>= 6 b=a a=r 42 a-=b r=a 43
  a=r 72 b=r 71 a+=b d=a a=r 43 *d=a
  a=r 71 a+=a r=a 71
endif
a=r 61 b=r 63 a==b ifl a=r 62 a>>= 24 b=a a=r 64 a>>= 24 a==b ifl
  a=r 62 a<<= 8 a>>= 8 r=a 61 a=0 r=a 62
  a=r 64 a<<= 8 a>>= 8 r=a 63
a= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
a<<= 8 a+= 255
  r=a 64
  a=r 66 a<<= 8 a>>= 8 r=a 65
  a=r 69 a+= 4 b=r 70 a>b ifl
    a=0 r=a 66 a=r 70 a++ r=a 69
  elsel
    a=r 69 a<<= 3 b=r 57 a+=b r=a 46
a=r 46 a&= 7 b=a a=r 46 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
    a>>= 16 a<<= 16 r=a 66 a=r 46 a+= 16 r=a 46
a=r 46 a&= 7 b=a a=r 46 a>>= 3 c=a a=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<= 8 c++ a+=*c a<<=b
    a>>= 16 b=r 66 a+=b r=a 66 a=r 69 a+= 4 r=a 69
  endif
endif endif
a=r 35 a+= 1 r=a 35
a=r 35 a< 8
while
a=r 71 a&= 255 r=a 42 a=r 58 b=r 34 a+=b r=a 43
a=r 16 b=r 43 a+=b c=a a=r 42 *c=a
a=r 42 a>>= 6 a<<= 8 b=a
a= 10
a<<= 8
a+=b r=a 72
a=r 34 a+= 1 r=a 34
a=r 34 b=r 60 a<b
while
a=r 58 b=r 60 a+=b r=a 58 b=r 7 a<b
while
          endif
        endif
        a=r 16 r=a 19 r=a 29 a=r 17 r=a 21 r=a 30 a=r 7 r=a 20
        a=0 r=a 26 a= 1 r=a 27
        a=r 9 a&= 8 a== 0 ifl
          a=r 27 a== 0 ifl a=r 23 elsel a=r 27 a== 1 ifl a=r 24 elsel a=r 25 endif endif r=a 22
          a=r 22 b=r 24 a<b ifl
            a=r 27 a< 2 ifl a= 2 r=a 27 endif
            a=r 25 b=r 24 a<b ifl a=b r=a 25 endif
            a=r 25 r=a 22
          endif
          a=r 22 r=a 81 a=r 29 r=a 19 a=r 30 r=a 21
a=0 r=a 31 r=a 32 r=a 37 r=a 38
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 39
a=r 39 a< 2 ifl
  a= 1 r=a 37
  do
    a=r 37 a+=a b=r 39 a+=b r=a 37
a=r 31 a+= 1 r=a 31
    a=r 31 b=r 20 a<b ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 39
    a=r 39 a< 2 elsel a= 1 r=a 38 a=0 endif
  while
  a=r 38 a== 0 ifl
    a=r 37 a-- r=a 37 a> 0 ifl
      a=r 22 b=r 32 a-=b b=a a=r 37 a<b ifnot a= 1 r=a 38 elsel
        do
          a=r 21 b=r 32 a+=b c=a a=0 *c=a
a=r 32 a+= 1 r=a 32
          a=r 37 a-- r=a 37 a> 0
        while
        a= 2 r=a 38
      endif
    endif
  endif
endif
a=r 38 a== 0 ifl
  a=r 39 a== 255 ifl
a=r 31 a+= 1 r=a 31
a=r 19 b=r 31 a+=b c=a a=*c r=a 40
    a=r 40 a+= 254 a&= 255 r=a 40
  elsel
    a=r 39 a-- r=a 40
  endif
a=r 21 b=r 32 a+=b c=a a=r 40 *c=a
a=r 31 a+= 1 r=a 31
a=r 32 a+= 1 r=a 32
  a=r 31 b=r 20 a<b ifnot a= 1 r=a 38 endif
  a=r 32 b=r 22 a<b ifnot a= 1 r=a 38 endif
endif
a=r 38 a== 2 ifl a=0 r=a 38 endif
a=r 38 a== 0
while
a=r 37 a> 0 ifl
  a=r 37 a-- r=a 37 a> 0 ifl
    do
      a=r 21 b=r 32 a+=b c=a a=0 *c=a
a=r 32 a+= 1 r=a 32
      a=r 37 a-- r=a 37 a> 0
    while
  endif
endif
a=r 32 r=a 20
          a=r 26 r=a 42 a=r 27 r=a 26 a=r 42 r=a 27
          a=r 29 r=a 42 a=r 30 r=a 29 a=r 42 r=a 30
        endif
        a=r 29 r=a 19
        a=r 9 a&= 16 a== 0 ifl
          a=r 27 a== 0 ifl a=r 23 elsel a=r 27 a== 1 ifl a=r 24 elsel a=r 25 endif endif r=a 22
          a=r 22 b=r 24 a<b ifl
            a=r 27 a< 2 ifl a= 2 r=a 27 endif
            a=r 25 b=r 24 a<b ifl a=b r=a 25 endif
            a=r 25 r=a 22
          endif
          a=r 22 r=a 81 a=r 29 r=a 19 a=r 30 r=a 21
          a=r 3 a== 5 ifl
a=0 r=a 34
do
a=0 r=a 42
a= 4
a<<= 8
b=r 34 a+=b d=a a=r 42 *d=a
a= 5
a<<= 8
b=r 34 a+=b d=a a=r 42 *d=a
a= 6
a<<= 8
b=r 34 a+=b d=a a=r 34 *d=a
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 31
a=r 20 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 39
a= 6
a<<= 8
b=r 39 a+=b d=a a=*d r=a 40
a=r 21 b=r 31 a+=b c=a a=r 40 *c=a
a= 4
a<<= 8
b=r 40 a+=b d=a a=*d r=a 43
a=r 31 b=r 43 a+=b a>>= 1 r=a 41
a= 4
a<<= 8
b=r 40 a+=b d=a a=r 31 *d=a
a= 5
a<<= 8
b=r 40 a+=b d=a a=r 41 *d=a
a=r 39 a> 0 ifl
do
a=r 39 a-- r=a 44
a= 6
a<<= 8
b=r 44 a+=b d=a a=*d r=a 45
a= 5
a<<= 8
b=r 45 a+=b d=a a=*d r=a 46
a=r 46 b=r 41 a>b ifl a=0 elsel
a= 6
a<<= 8
b=r 39 a+=b d=a a=r 45 *d=a
a=r 39 a-- r=a 39 a= 1
endif
a> 0 ifl a=r 39 a> 0 endif
while
endif
a= 6
a<<= 8
b=r 39 a+=b d=a a=r 40 *d=a
a=r 31 a+= 1 r=a 31
a=r 31 b=r 20 a<b
while
endif
          elsel
a=0 r=a 31
a=0 r=a 34
do
a=0 r=a 42 r=a 43
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 44
a=r 31 a+= 1 r=a 31
a=r 44 a&= 127 b=r 43 a<<=b b=a a=r 42 a|=b r=a 42 a=r 43 a+= 7 r=a 43 a=r 44 a> 127
while
a= 1
a<<= 8
b=r 34 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=r 20 b=r 31 a-=b r=a 20 a=r 19 b=r 31 a+=b r=a 19
a=0 r=a 33
a=0 r=a 34
do
a= 1
a<<= 8
b=r 34 a+=b d=a a=*d r=a 42
a=r 42 a> 0 ifl
a= 9
a<<= 8
b=r 33 a+=b d=a a=r 34 *d=a
a=r 33 a+= 1 r=a 33
endif
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a= 1 r=a 34
a=r 34 b=r 33 a<b ifl
do
a= 9
a<<= 8
b=r 34 a+=b d=a a=*d r=a 42
a= 1
a<<= 8
b=r 42 a+=b d=a a=*d r=a 43
a=r 34 r=a 35
do
a=r 35 a> 0 ifl
  a=r 35 a-- r=a 44
a= 9
a<<= 8
b=r 44 a+=b d=a a=*d r=a 45
a= 1
a<<= 8
b=r 45 a+=b d=a a=*d r=a 46
  a=r 46 b=r 43 a<b ifl
a= 9
a<<= 8
b=r 35 a+=b d=a a=r 45 *d=a
    a=r 35 a-- r=a 35 a= 1
  elsel a=0 endif
elsel a=0 endif
a> 0
while
a= 9
a<<= 8
b=r 35 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 33 a<b
while
endif
a=0 r=a 42
a=0 r=a 34
a=r 33 a> 0 ifl
do
a= 9
a<<= 8
b=r 34 a+=b d=a a=*d r=a 43
a=r 19 b=r 42 a+=b c=a a=*c r=a 44
a= 6
a<<= 8
b=r 44 a+=b d=a a=r 43 *d=a
a=r 42 a++ r=a 45
a= 7
a<<= 8
b=r 43 a+=b d=a a=r 45 *d=a
a= 1
a<<= 8
b=r 43 a+=b d=a a=*d r=a 45
a=r 42 b=r 45 a+=b r=a 42
a= 8
a<<= 8
b=r 43 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 33 a<b
while
endif
a=0 r=a 42
a= 6
a<<= 8
b=r 42 a+=b d=a a=*d r=a 40
a=r 33 r=a 41
a=0 r=a 31
a=r 20 a> 0 ifl
do
a=r 21 b=r 31 a+=b c=a a=r 40 *c=a
a= 7
a<<= 8
b=r 40 a+=b d=a a=*d r=a 43
a= 8
a<<= 8
b=r 40 a+=b d=a a=*d r=a 44
a=r 43 b=r 44 a<b ifl
a=r 19 b=r 43 a+=b c=a a=*c r=a 45
a=r 43 a+= 1 r=a 43
a= 7
a<<= 8
b=r 40 a+=b d=a a=r 43 *d=a
  a=r 45 a> 0 ifl
    a=0 r=a 46
    do
      a=r 46 a++ r=a 47
a= 6
a<<= 8
b=r 47 a+=b d=a a=*d r=a 48
a= 6
a<<= 8
b=r 46 a+=b d=a a=r 48 *d=a
      a=r 47 r=a 46 b=r 45 a<b
    while
a= 6
a<<= 8
b=r 45 a+=b d=a a=r 40 *d=a
    a=0 r=a 46
a= 6
a<<= 8
b=r 46 a+=b d=a a=*d r=a 40
  endif
elsel
  a=r 41 a> 1 ifl
    a=r 41 a-- r=a 41 a=0 r=a 46
    do
      a=r 46 a++ r=a 47
a= 6
a<<= 8
b=r 47 a+=b d=a a=*d r=a 48
a= 6
a<<= 8
b=r 46 a+=b d=a a=r 48 *d=a
      a=r 47 r=a 46 b=r 41 a<b
    while
    a=0 r=a 46
a= 6
a<<= 8
b=r 46 a+=b d=a a=*d r=a 40
  endif
endif
a=r 31 a+= 1 r=a 31
a=r 31 b=r 20 a<b
while
endif
          endif
          a=r 26 r=a 42 a=r 27 r=a 26 a=r 42 r=a 27
          a=r 29 r=a 42 a=r 30 r=a 29 a=r 42 r=a 30
        endif
        a=r 29 r=a 19
        a=r 9 a&= 32 a== 0 ifl
          a=r 27 a== 0 ifl a=r 23 elsel a=r 27 a== 1 ifl a=r 24 elsel a=r 25 endif endif r=a 22
          a=r 22 b=r 24 a<b ifl
            a=r 27 a< 2 ifl a= 2 r=a 27 endif
            a=r 25 b=r 24 a<b ifl a=b r=a 25 endif
            a=r 25 r=a 22
          endif
          a=r 22 r=a 81 a=r 29 r=a 19 a=r 30 r=a 21
a=0 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 42
a=r 42 a>>= 2 a&= 7 r=a 43 a= 1 b=r 43 a<<=b r=a 43
a=r 42 a&= 3 a++ r=a 44
a=0 r=a 45 a= 1 r=a 31
a=0 r=a 34
a=r 44 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 46
a=r 45 a<<= 8 b=r 46 a+=b r=a 45
a=r 31 a+= 1 r=a 31
a=r 34 a+= 1 r=a 34
a=r 34 b=r 44 a<b
while
endif
a=r 45 a+= 1 r=a 45
a=r 43 b=r 44 a*=b a++ r=a 46
a=r 19 b=r 46 a+=b r=a 19 a=r 20 b=r 46 a-=b r=a 20
a=r 20 a== 1 ifl
  a=0 r=a 31
a=r 19 b=r 31 a+=b c=a a=*c r=a 42
a=r 21 b=r 31 a+=b c=a a=r 42 *c=a
elsel
a=0 r=a 34
do
a=0 r=a 42
a= 7
a<<= 8
b=r 34 a+=b d=a a=r 42 *d=a
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 31
a=r 20 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 42
a= 7
a<<= 8
b=r 42 a+=b d=a a=*d r=a 43
a=r 43 a+= 1 r=a 43
a= 7
a<<= 8
b=r 42 a+=b d=a a=r 43 *d=a
a=r 31 a+= 1 r=a 31
a=r 31 b=r 20 a<b
while
endif
a=0 r=a 43
a=0 r=a 34
do
a= 7
a<<= 8
b=r 34 a+=b d=a a=*d r=a 42
a= 7
a<<= 8
b=r 34 a+=b d=a a=r 43 *d=a
a=r 43 b=r 42 a+=b r=a 43
a=r 34 a+= 1 r=a 34
a= 1
a<<= 8
b=a a=r 34 a<b
while
a=0 r=a 31
a=r 20 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 42
a=r 31 a== 0 ifl a=r 42 elsel a=r 31 b=r 45 a<b ifl a=r 31 a-- elsel a=r 31 endif a<<= 8 b=r 42 a+=b endif r=a 44
a= 7
a<<= 8
b=r 42 a+=b d=a a=*d r=a 43
a=r 43 b=a
a= 2
a<<= 8
a<<= 8
a+=b d=a a=r 44 *d=a
a=r 43 a+= 1 r=a 43
a= 7
a<<= 8
b=r 42 a+=b d=a a=r 43 *d=a
a=r 31 a+= 1 r=a 31
a=r 31 b=r 20 a<b
while
endif
a=r 45 a-- r=a 42
a=0 r=a 31
a=r 20 a> 0 ifl
do
a=r 42 b=a
a= 2
a<<= 8
a<<= 8
a+=b d=a a=*d r=a 43
a=r 43 a&= 255 r=a 44
a=r 21 b=r 31 a+=b c=a a=r 44 *c=a
a=r 43 a>>= 8 r=a 42
a=r 31 a+= 1 r=a 31
a=r 31 b=r 20 a<b
while
endif
endif
          a=r 26 r=a 42 a=r 27 r=a 26 a=r 42 r=a 27
          a=r 29 r=a 42 a=r 30 r=a 29 a=r 42 r=a 30
        endif
        a=r 29 r=a 19
        a=r 9 a&= 64 a== 0 ifl
          a=r 27 a== 0 ifl a=r 23 elsel a=r 27 a== 1 ifl a=r 24 elsel a=r 25 endif endif r=a 22
          a=r 22 b=r 24 a<b ifl
            a=r 27 a< 2 ifl a= 2 r=a 27 endif
            a=r 25 b=r 24 a<b ifl a=b r=a 25 endif
            a=r 25 r=a 22
          endif
          a=r 22 r=a 81 a=r 29 r=a 19 a=r 30 r=a 21
a=0 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 42
a=r 42 a&= 3 r=a 43
a= 1 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 42
a=r 42 a&= 3 r=a 44
a= 2 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 45
a= 3 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 46
a=r 45 a<<= 8 b=r 46 a+=b r=a 33
a= 4 r=a 31
a=0 r=a 34
a=r 33 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 45
a=r 31 a+= 1 r=a 31
a=r 19 b=r 31 a+=b c=a a=*c r=a 46
a=r 31 a+= 1 r=a 31
a=r 19 b=r 31 a+=b c=a a=*c r=a 47
a=r 31 a+= 1 r=a 31
a=r 45 a<<= 8 b=r 46 a+=b a<<= 8 b=r 47 a+=b r=a 45
a=r 45 a>>= 19 r=a 46
a=r 46 a== 0 ifl a=r 45 a&= 255 r=a 47 a= 1 r=a 48 elsel
a=r 46 a== 1 ifl a=r 45 a&= 255 a<<= 8 r=a 47 a=r 45 a>>= 8 a&= 255 b=r 47 a+=b r=a 47 a= 2 r=a 48 elsel
a=r 46 a== 2 ifl
  a=r 45 a&= 63 a|= 128 a<<= 8 r=a 47 a=r 45 a>>= 6 a&= 63 a|= 128 b=r 47 a+=b a<<= 8 r=a 47
  a=r 45 a>>= 12 a&= 15 a|= 224 b=r 47 a+=b r=a 47 a= 3 r=a 48
elsel
  a=r 45 a&= 63 a|= 128 a<<= 8 r=a 47 a=r 45 a>>= 6 a&= 63 a|= 128 b=r 47 a+=b a<<= 8 r=a 47
  a=r 45 a>>= 12 a&= 63 a|= 128 b=r 47 a+=b a<<= 8 r=a 47
  a=r 45 a>>= 18 a&= 7 a|= 240 b=r 47 a+=b r=a 47 a= 4 r=a 48
endif endif endif
a= 26
a<<= 8
b=r 34 a+=b d=a a=r 47 *d=a
a= 154
a<<= 8
b=r 34 a+=b d=a a=r 48 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 33 a<b
while
endif
a=r 20 a-= 4 b=r 44 a+=b r=a 46
a=0 r=a 32
a=0 r=a 34
a=r 43 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 45
a=r 21 b=r 32 a+=b c=a a=r 45 *c=a
a=r 31 a+= 1 r=a 31
a=r 32 a+= 1 r=a 32
a=r 34 a+= 1 r=a 34
a=r 34 b=r 43 a<b
while
endif
a=r 31 b=r 46 a<b ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 42
a=r 31 a+= 1 r=a 31
a=r 33 a> 128 ifl a=r 42 a> 127 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 45
a=r 31 a+= 1 r=a 31
a=r 45 a<<= 7 b=r 42 a+=b a-= 128 r=a 42 endif endif
a= 26
a<<= 8
b=r 42 a+=b d=a a=*d r=a 47
a= 154
a<<= 8
b=r 42 a+=b d=a a=*d r=a 48
do
a=r 47 a&= 255 r=a 45
a=r 21 b=r 32 a+=b c=a a=r 45 *c=a
a=r 32 a+= 1 r=a 32
a=r 47 a>>= 8 r=a 47 a=r 48 a-- r=a 48 a> 0
while
a=r 31 b=r 46 a<b
while
endif
a=r 22 a-= 4 b=r 44 a+=b b=r 32 a>b ifl
a= 4 b=r 44 a-=b r=a 43
a=0 r=a 34
a=r 43 a> 0 ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 45
a=r 21 b=r 32 a+=b c=a a=r 45 *c=a
a=r 31 a+= 1 r=a 31
a=r 32 a+= 1 r=a 32
a=r 34 a+= 1 r=a 34
a=r 34 b=r 43 a<b
while
endif
endif
a=r 32 r=a 20
          a=r 26 r=a 42 a=r 27 r=a 26 a=r 42 r=a 27
          a=r 29 r=a 42 a=r 30 r=a 29 a=r 42 r=a 30
        endif
        a=r 29 r=a 19
        a=r 9 a&= 128 a== 0 ifl
          a=r 27 a== 0 ifl a=r 23 elsel a=r 27 a== 1 ifl a=r 24 elsel a=r 25 endif endif r=a 22
          a=r 22 b=r 24 a<b ifl
            a=r 27 a< 2 ifl a= 2 r=a 27 endif
            a=r 25 b=r 24 a<b ifl a=b r=a 25 endif
            a=r 25 r=a 22
          endif
          a=r 22 r=a 81 a=r 29 r=a 19 a=r 30 r=a 21
a=0 r=a 42
a=r 19 b=r 42 a+=b c=a a=*c r=a 42
a=r 42 a&= 16 a> 0 ifl a= 2 elsel a= 1 endif r=a 80
a=r 42 a&= 64 r=a 79
a=r 80 a== 1 ifl a=r 5 a>>= 3 elsel a=r 5 a>>= 5 endif r=a 43
a=0 r=a 44 a=r 43 r=a 49
a=r 49 a> 1 ifl
do
a=r 49 a>>= 1 r=a 49 a=r 44 a++ r=a 44 a=r 49 a> 1
while
endif
a=r 80 a== 1 ifl a=r 44 a> 26 ifl a= 26 r=a 44 endif elsel a=r 44 a> 24 ifl a= 24 r=a 44 endif endif
a=r 44 a< 13 ifl a= 13 r=a 44 endif
a= 1 b=r 44 a<<=b a-- r=a 73
a= 13 r=a 44 a=r 81
a= 4
a<<= 8
b=a a=r 81 a<b ifnot a=r 81 a>>= 7 r=a 43
a=0 r=a 44 a=r 43 r=a 49
a=r 49 a> 1 ifl
do
a=r 49 a>>= 1 r=a 49 a=r 44 a++ r=a 44 a=r 49 a> 1
while
endif
a=r 44 a> 18 ifl a= 18 r=a 44 endif a=r 44 a< 13 ifl a= 13 r=a 44 endif
endif
a= 1 b=r 44 a<<=b r=a 74
a=r 80 a== 1 ifl
a= 4
a<<= 8 a+= 2
r=a 75
elsel
a= 4
a<<= 8
r=a 75
endif
a=r 74 b=r 75 a<b ifl a=b r=a 74 endif
a=r 73 a++ r=a 43
a= 26
a<<= 8
a<<= 8
d=a
a=0 r=a 34
do
a=0 *d=a d++ a=r 34 a++ r=a 34 b=r 43 a<b
while
a=0 r=a 34
do
a= 14
a<<= 8
b=r 34 a+=b d=a a=*d r=a 45
a= 2
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a= 22
a<<= 8
b=r 34 a+=b d=a a=*d r=a 45
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a= 18
a<<= 8
b=r 34 a+=b d=a a=*d r=a 45
a=r 45 a<<= 24 b=r 34 a+=b r=a 45
a= 18
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a=r 34 a+= 1 r=a 34
a= 4
a<<= 8
b=a a=r 34 a<b
while
a=r 80 a== 1 ifl
  a=r 1 a+= 40 c=a a= 14 *c=a c++ a= 15 *c=a
a= 4
a<<= 8
r=a 34
  a=r 1 a+= 40 r=a 45
a= 2
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
  a=0 r=a 45
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
  a= 1 a<<= 24 b=r 34 a+=b r=a 45
a= 18
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a= 4
a<<= 8 a+= 1
r=a 34
  a=r 1 a+= 41 r=a 45
a= 2
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
  a=0 r=a 45
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
  a= 1 a<<= 24 b=r 34 a+=b r=a 45
a= 18
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
endif
a=0 r=a 34
a=r 75 a> 0 ifl
do
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=*d r=a 45
a=r 45 b=r 73 a&=b r=a 45 a=r 34 a++ r=a 46
a= 26
a<<= 8
a<<= 8
b=r 45 a+=b d=a a=r 46 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 75 a<b
while
endif
a=r 75 r=a 34
a=r 34 b=r 74 a<b ifl
do
a=0 r=a 45
a= 2
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 45 *d=a
a= 18
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 34 *d=a
a=r 34 a+= 1 r=a 34
a=r 34 b=r 74 a<b
while
endif
a= 1 r=a 31 a=0 r=a 32
a=r 19 b=r 31 a+=b c=a a=*c r=a 42
a= 1
a<<= 8 a+= 255
a<<= 8
b=r 42 a+=b d=a a=*d r=a 43
a=r 43 a== 0 ifl a=r 31 a-- elsel a=r 31 endif r=a 77
a=r 75 r=a 76 a=0 r=a 78
a=r 31 b=r 20 a<b ifl
do
a=r 19 b=r 31 a+=b c=a a=*c r=a 39
a= 1
a<<= 8 a+= 255
a<<= 8
b=r 39 a+=b d=a a=*d r=a 43
a=r 43 a== 0 ifl
a=r 21 b=r 32 a+=b c=a a=r 39 *c=a
a=r 31 a+= 1 r=a 31
a=r 32 a+= 1 r=a 32
elsel
a=r 43 a== 1 ifl a=r 77 a+= 3 b=a a=r 31 a>b ifl
  a=r 31 b=r 77 a-=b a-- r=a 44
  a=r 44 a< 32 ifl
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
r=a 45
    a=r 77 a++ r=a 46
    do
a=r 19 b=r 46 a+=b c=a a=*c r=a 47
a= 127
a<<= 8 a+= 235
a<<= 8 a+= 53
a<<= 8 a+= 45
b=r 45 a*=b r=a 45
a= 132
a<<= 8 a+= 108
a<<= 8 a+= 166
a<<= 8 a+= 139
b=r 47 a*=b b=r 45 a^=b r=a 45
a=r 46 a+= 1 r=a 46
      a=r 46 b=r 31 a<b
    while
    a=r 45 b=r 73 a&=b r=a 46
a= 26
a<<= 8
a<<= 8
b=r 46 a+=b d=a a=*d r=a 47
    a=0 r=a 48
    a=r 47 a> 0 ifl
      a=r 47 a-- r=a 82
a= 10
a<<= 8
a<<= 8
b=r 82 a+=b d=a a=*d r=a 49
      a=r 49 b=r 45 a==b ifl
a= 18
a<<= 8
a<<= 8
b=r 82 a+=b d=a a=*d r=a 49
        a=r 49 a>>= 24 b=r 44 a==b ifl a= 1 r=a 48 endif
      endif
    endif
    a=r 48 a== 0 ifl a=r 47 a== 0 ifl
      a=r 44 a> 3 ifl a= 1 elsel
a= 64
a<<= 8
      b=a a=r 76 a<b ifl a= 1 elsel a=0 endif endif
      a> 0 ifl
a= 18
a<<= 8
a<<= 8
b=r 76 a+=b d=a a=*d r=a 49
a= 7
a<<= 8 a+= 255
a<<= 8 a+= 255
        b=r 49 a&=b b=r 75 a<b ifnotl
a= 10
a<<= 8
a<<= 8
b=r 76 a+=b d=a a=*d r=a 49
          a=r 49 b=r 73 a&=b r=a 49 a=0 r=a 82
a= 26
a<<= 8
a<<= 8
b=r 49 a+=b d=a a=r 82 *d=a
          a=r 19 b=r 77 a+=b a++ r=a 49
a= 2
a<<= 8
a<<= 8
b=r 76 a+=b d=a a=r 49 *d=a
a= 10
a<<= 8
a<<= 8
b=r 76 a+=b d=a a=r 45 *d=a
          a=r 44 a<<= 24 b=r 76 a+=b r=a 49
a= 18
a<<= 8
a<<= 8
b=r 76 a+=b d=a a=r 49 *d=a
        endif
        a=r 76 a++ r=a 49
a= 26
a<<= 8
a<<= 8
b=r 46 a+=b d=a a=r 49 *d=a
a=r 76 a+= 1 r=a 76
        a=r 76 b=r 74 a<b ifnotl
a= 8
a<<= 8
a<<= 8
          b=a a=r 74 a<b ifl
            a=r 74 r=a 34 a+=a r=a 49
            do
              a=0 r=a 82
a= 2
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 82 *d=a
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 82 *d=a
a= 18
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=r 34 *d=a
a=r 34 a+= 1 r=a 34
              a=r 34 b=r 49 a<b
            while
            a=0 r=a 34
            do
a= 10
a<<= 8
a<<= 8
b=r 34 a+=b d=a a=*d r=a 82
              a=r 82 b=r 73 a&=b r=a 82 a=r 34 a++ r=a 47
a= 26
a<<= 8
a<<= 8
b=r 82 a+=b d=a a=r 47 *d=a
a=r 34 a+= 1 r=a 34
              a=r 34 b=r 74 a<b
            while
            a=r 74 a+=a r=a 74
          elsel
            a=r 75 r=a 76
          endif
        endif
      endif
    endif endif
  endif
endif endif
a=r 31 a+= 1 r=a 31
a=0 r=a 48
a=r 80 a== 1 ifl
  a=r 39 a== 14 ifl a= 1 r=a 48 endif a=r 39 a== 15 ifl a= 1 r=a 48 endif
  a=r 48 a> 0 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 82
a=r 31 a+= 1 r=a 31
    a=r 82 a> 127 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 46
a=r 31 a+= 1 r=a 31
      a=r 46 a> 127 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 49
a=r 31 a+= 1 r=a 31
        a=r 82 a&= 31 a<<= 14 r=a 82 a=r 46 a&= 127 a<<= 7 b=r 82 a+=b b=r 49 a+=b r=a 82
      elsel
        a=r 82 a&= 127 a<<= 7 b=r 46 a+=b r=a 82
      endif
    endif
    a=r 39 a== 14 ifl a= 32 elsel a=0 endif r=a 47
  endif
elsel
  a=r 39 a> 127 ifl
    a= 1 r=a 48 a=0 r=a 47
    a=r 39 a== 128 ifl a= 32 r=a 47
a=r 19 b=r 31 a+=b c=a a=*c r=a 39
a=r 31 a+= 1 r=a 31
    endif
    a=r 39 a&= 127 r=a 82 a< 64 ifl a= 1 elsel a=0 endif r=a 46
    a=r 82 a> 63 ifl
      a=r 82 a> 111 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 49
a=r 31 a+= 1 r=a 31
a=r 19 b=r 31 a+=b c=a a=*c r=a 44
a=r 31 a+= 1 r=a 31
        a=r 82 a&= 15 a<<= 8 b=r 49 a+=b a<<= 8 b=r 44 a+=b r=a 82
a= 32
a<<= 8 a+= 63
        b=r 82 a+=b r=a 82
      elsel
a=r 19 b=r 31 a+=b c=a a=*c r=a 49
a=r 31 a+= 1 r=a 31
        a=r 82 a&= 31 a<<= 8 b=r 49 a+=b a+= 63 r=a 82
      endif
    endif
    a=r 82 b=r 46 a-=b r=a 82
  endif
endif
a=r 48 a> 0 ifl
a= 18
a<<= 8
a<<= 8
b=r 82 a+=b d=a a=*d r=a 49
  a=r 49 a>>= 24 r=a 44
a= 2
a<<= 8
a<<= 8
b=r 82 a+=b d=a a=*d r=a 45
  a=r 44 a> 1 ifl
    a=r 78 a> 0 ifl a= 32 r=a 46
a=r 21 b=r 32 a+=b c=a a=r 46 *c=a
a=r 32 a+= 1 r=a 32
    endif
    a= 1 r=a 78 a=r 31 r=a 77
  elsel
    a=0 r=a 78 a=r 31 a-- r=a 77
  endif
  a=r 32 r=a 46
  do
    a=r 45 c=a a=*c r=a 49
a=r 21 b=r 32 a+=b c=a a=r 49 *c=a
a=r 45 a+= 1 r=a 45
a=r 32 a+= 1 r=a 32
    a=r 44 a-- r=a 44 a> 0
  while
  a=r 21 b=r 46 a+=b c=a a=*c b=r 47 a^=b *c=a
elsel
  a=r 80 a== 2 ifl a=r 39 a== 15 ifl a= 1 elsel a=0 endif elsel a=0 endif
  a> 0 ifl
a=r 19 b=r 31 a+=b c=a a=*c r=a 49
a=r 21 b=r 32 a+=b c=a a=r 49 *c=a
a=r 31 a+= 1 r=a 31
a=r 32 a+= 1 r=a 32
  elsel
    a=r 79 a> 0 ifl a=r 39 a== 10 ifl a= 13 r=a 49
a=r 21 b=r 32 a+=b c=a a=r 49 *c=a
a=r 32 a+= 1 r=a 32
    endif endif
a=r 21 b=r 32 a+=b c=a a=r 39 *c=a
a=r 32 a+= 1 r=a 32
  endif
  a=0 r=a 78 a=r 31 a-- r=a 77
endif
endif
a=r 31 b=r 20 a<b ifl a=r 32 b=r 81 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
a> 0
while
endif
a=r 32 r=a 20
          a=r 26 r=a 42 a=r 27 r=a 26 a=r 42 r=a 27
          a=r 29 r=a 42 a=r 30 r=a 29 a=r 42 r=a 30
        endif
        a=r 29 r=a 19
a=r 20 a> 0 ifl
  a=r 19 r=a 42 a=r 20 r=a 43
  do
    a=r 42 c=a a=*c out a=r 42 a++ r=a 42 a=r 43 a-- r=a 43 a> 0
  while
endif
      endif
      a=r 11 r=a 2 a= 1
    elsel a=0 endif
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZKNZ5";
