/*
  ZPAQBZIP3: a bzip3 decoder written in ZPAQL, for zpaq-std -ma:bzip3 (libbz3
  1.5.4, levels 1-9). zpaq-std, 2026. Generated by gen.py next to this file (ZPAQL
  has no subroutines: everything is a macro expanded in place).

  The whole stream is kept in M and decoded at the end, block by block: bzip3's
  context-mixing coder (an order-0 table by bit context, an order-1 table by the
  previous byte, and an APM with interpolation, over a 32-bit arithmetic coder
  whose 32x32->64 multiply is split so no partial product passes 32 bits), the
  inverse BWT (libsais' convention: the sentinel sits in the row of the primary
  index), bzip3's LZP and its run-length step. Raw blocks (under 64 bytes) too.
  The output goes out with OUT.

  M: the stream, then two block buffers of 1.1 MB. H needs ph = 21 (the CM
  tables, the LZP table and tt for a block).

  Verified with zpaqd 7.15 on 77 bzip3 streams: 26 inputs x levels 1, 5 and 9
  (12 MB at level 1 is 120 blocks of 100 KB), and blocks under 64 bytes.

  FROZEN, like the other portable decoders.
*/
static const char ZPAQBZIP3_CUERPO[] = R"ZBZ3(hcomp
halt
pcomp zpaqbzip3 ;
(ZPAQBZIP3: decodificador de bzip3 en ZPAQL, para zpaq-std -ma:bzip3. zpaq-std, 2026.
 Guarda el flujo en M y lo decodifica al final, bloque por bloque: el CM de bzip3,
 el BWT inverso, LZP y RLE. La salida sale con out.)
a> 255 ifl
  a=c r=a 1
a= 0
  r=a 40
a= 1
a<<= 8
a<<= 8
  r=a 41
a= 1
a<<= 8 a+= 1
a<<= 8
  r=a 42
a= 1
a<<= 8 a+= 35
a<<= 8
  r=a 43
a= 1
a<<= 8 a+= 36
a<<= 8
  r=a 44
a= 1
a<<= 8 a+= 37
a<<= 8
  r=a 45
a= 2
a<<= 8
a<<= 8
  r=a 46
a= 8
a<<= 8
a<<= 8
  r=a 47
  a=r 1 a+= 16 r=a 3 a= 18 a<<= 16 b=r 3 a+=b r=a 4
  a= 9 r=a 32
a=r 32 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 5
  a= 13 r=a 2
  a=r 5 a> 0 ifl
  do
a=r 2 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 7
    a=r 2 a+= 4 r=a 32
a=r 32 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 8
    a=r 2 a+= 8 r=a 2 b=r 7 a+=b r=a 6
    a=r 2 a+= 4 r=a 32
a=r 32 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 9
    a=r 9 a++ a== 0 ifl
      a=r 2 a+= 8 r=a 32
      a=r 32 b=r 6 a<b ifl
        do
          a=r 32 c=a a=*c out a=r 32 a++ r=a 32 b=r 6
        a<b while
      endif
    elsel
      a=r 2 a+= 8 c=a a=*c r=a 10 a=r 2 a+= 9 r=a 32
      a=r 10 a&= 2 a> 0 ifl
a=r 32 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 11
        a=r 32 a+= 4 r=a 32 endif
      a=r 10 a&= 4 a> 0 ifl
a=r 32 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 12
        a=r 32 a+= 4 r=a 32 endif
      a=r 32 r=a 14 a=r 6 r=a 15
      a=r 10 a&= 2 a> 0 ifl a=r 11 elsel a=r 10 a&= 4 a> 0 ifl a=r 12 elsel a=r 8 endif endif r=a 13
      a=0 r=a 32 a= 128 a<<= 8 r=a 33
      do
a=r 32 b=r 40 a+=b d=a a=r 33 *d=a
        a=r 32 a++ r=a 32 a>>= 16
      a== 0 while
      a=0 r=a 32
      do
a=r 32 b=r 41 a+=b d=a a=r 33 *d=a
        a=r 32 a++ r=a 32
      a> 255 until
      a=0 r=a 32
      do
        a=0 r=a 34
        do
          a=r 34 a<<= 12 r=a 35 a=r 34 a== 16 ifl a=r 35 a-- r=a 35 endif
          a=r 32 a*= 17 b=r 34 a+=b b=r 42 a+=b d=a a=r 35 *d=a
          a=r 34 a++ r=a 34
        a< 17 while
        a=r 32 a++ r=a 32 a>>= 9
      a== 0 while
      a=0 r=a 16 a-- r=a 16 a=0 r=a 17 r=a 18 r=a 19 r=a 20 r=a 21 r=a 31
a=r 14 b=r 15 a<b ifl c=a a=*c elsel a=0 a-- endif r=a 32 a=r 14 a++ r=a 14 a=r 32
      b=a a=r 18 a<<= 8 a+=b r=a 18
a=r 14 b=r 15 a<b ifl c=a a=*c elsel a=0 a-- endif r=a 32 a=r 14 a++ r=a 14 a=r 32
      b=a a=r 18 a<<= 8 a+=b r=a 18
a=r 14 b=r 15 a<b ifl c=a a=*c elsel a=0 a-- endif r=a 32 a=r 14 a++ r=a 14 a=r 32
      b=a a=r 18 a<<= 8 a+=b r=a 18
a=r 14 b=r 15 a<b ifl c=a a=*c elsel a=0 a-- endif r=a 32 a=r 14 a++ r=a 14 a=r 32
      b=a a=r 18 a<<= 8 a+=b r=a 18
      a=r 13 a> 0 ifl
      do
        a=r 19 b=r 20 a==b ifl a=r 21 a++ elsel a=0 endif r=a 21
        a> 2 ifl a= 1 elsel a=0 endif r=a 22 a= 1 r=a 23
        do
a=r 23 b=r 41 a+=b d=a a=*d
          r=a 32
          a=r 19 a<<= 8 b=r 23 a+=b d=a a=*d r=a 33 a=r 20 a<<= 8 b=r 23 a+=b d=a a=*d r=a 34
          a=r 32 b=r 33 a+=b a*= 7 b=r 34 a+=b a+=b a>>= 4 r=a 24
          a>>= 12 r=a 25
          a=r 23 a+=a b=r 22 a+=b a*= 17 b=r 25 a+=b b=r 42 a+=b r=a 35
          d=a a=*d r=a 26 d++ a=*d r=a 27
          a=r 24 a<<= 20 a>>= 20 r=a 36
          a=r 27 b=r 26 a<b ifl
            a=r 26 b=r 27 a-=b b=r 36 a*=b a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 255 a+= 15 a>>= 12 b=a a=r 26 a-=b
          elsel
            a=r 27 b=r 26 a-=b b=r 36 a*=b a>>= 12 b=r 26 a+=b
          endif
          r=a 28 a+=a b=r 28 a+=b b=r 24 a+=b r=a 37
          a=r 16 b=r 17 a-=b r=a 38 a>>= 18 b=r 37 a*=b r=a 29
          a=r 38 a<<= 14 a>>= 23 b=r 37 a*=b r=a 39
          a=r 38 a&= 255 r=a 32 a=r 38 a>>= 8 a&= 1 a<<= 8 b=r 32 a+=b b=r 37 a*=b a>>= 9 b=r 39 a+=b a>>= 9
          b=r 29 a+=b b=r 17 a+=b r=a 29
          a=r 18 b=r 29 a>b ifl a=0 elsel a= 1 endif r=a 30
          a> 0 ifl a=r 29 r=a 16 elsel a=r 29 a++ r=a 17 endif
          do
            a=r 17 b=r 16 a^=b a>>= 24 a== 0 ifl
              a=r 17 a<<= 8 r=a 17 a=r 16 a<<= 8 a+= 255 r=a 16
a=r 14 b=r 15 a<b ifl c=a a=*c elsel a=0 a-- endif r=a 32 a=r 14 a++ r=a 14 a=r 32
              b=a a=r 18 a<<= 8 a+=b r=a 18 a= 1
            elsel a=0 endif
          a> 0 while
          a=r 30 a> 0 ifl
a=r 23 b=r 41 a+=b d=a a=*d
a=*d b=a a= 255 a<<= 8 a+= 255 a^=b a>>= 2 a+=b *d=a
            a=r 19 a<<= 8 b=r 23 a+=b d=a
a=*d b=a a= 255 a<<= 8 a+= 255 a^=b a>>= 4 a+=b *d=a
            a=r 35 d=a
a=*d b=a a= 255 a<<= 8 a+= 255 a^=b a>>= 6 a+=b *d=a
            d++
a=*d b=a a= 255 a<<= 8 a+= 255 a^=b a>>= 6 a+=b *d=a
            a=r 23 a+=a a++ r=a 23
          elsel
a=r 23 b=r 41 a+=b d=a a=*d
a=*d b=a a>>= 2 r=a 33 a=b b=r 33 a-=b *d=a
            a=r 19 a<<= 8 b=r 23 a+=b d=a
a=*d b=a a>>= 4 r=a 33 a=b b=r 33 a-=b *d=a
            a=r 35 d=a
a=*d b=a a>>= 6 r=a 33 a=b b=r 33 a-=b *d=a
            d++
a=*d b=a a>>= 6 r=a 33 a=b b=r 33 a-=b *d=a
            a=r 23 a+=a r=a 23
          endif
          a=r 23
        a> 255 until
        a=r 19 r=a 20 a=r 23 a&= 255 r=a 19
        a=r 31 b=r 47 a+=b d=a a=r 19 *d=a a=r 31 a++ r=a 31 b=r 13
      a<b while
      endif
      a=0 r=a 32 r=a 33
      do
a=r 32 b=r 44 a+=b d=a a=r 33 *d=a
        a=r 32 a++ r=a 32
      a> 255 until
      a=0 r=a 32
      a=r 13 a> 0 ifl
      do
a=r 32 b=r 47 a+=b d=a a=*d
        a&= 255 r=a 34
a=r 34 b=r 44 a+=b d=a a=*d
        a++ r=a 35
a=r 34 b=r 44 a+=b d=a a=r 35 *d=a
        a=r 32 a++ r=a 32 b=r 13
      a<b while
      endif
      a=0 r=a 32 a= 1 r=a 33
      do
a=r 32 b=r 45 a+=b d=a a=r 33 *d=a
a=r 32 b=r 44 a+=b d=a a=*d
        b=r 33 a+=b r=a 33 a=r 32 a++ r=a 32
      a> 255 until
      a=0 r=a 32
      a=r 13 a> 0 ifl
      do
a=r 32 b=r 47 a+=b d=a a=*d
        a&= 255 r=a 34
a=r 34 b=r 45 a+=b d=a a=*d
        r=a 35 a++ r=a 36
a=r 34 b=r 45 a+=b d=a a=r 36 *d=a
        a=r 35 a<<= 8 b=r 34 a+=b r=a 35
a=r 32 b=r 47 a+=b d=a a=r 35 *d=a
        a=r 32 a++ r=a 32 b=r 13
      a<b while
      a=0 r=a 33 a=r 13 r=a 32
      do
        a=r 32 a-- r=a 32
        a=r 33 b=r 9 a<b ifnot a-- endif r=a 34
a=r 34 b=r 47 a+=b d=a a=*d
        r=a 35 a&= 255 r=a 36 a=r 32 b=r 3 a+=b c=a a=r 36 *c=a a=r 35 a>>= 8 r=a 33
        a=r 32
      a> 0 while
      endif
      a=r 3 r=a 36 a=r 13 r=a 37
      a=r 10 a&= 2 a> 0 ifl
        a=0 r=a 32 r=a 33 a= 4 a<<= 16 r=a 34
        do
a=r 32 b=r 46 a+=b d=a a=r 33 *d=a
          a=r 32 a++ r=a 32 b=r 34
        a<b while
        a=r 10 a&= 4 a> 0 ifl a=r 12 elsel a=r 8 endif r=a 38
        a=r 3 c=a a=*c r=a 32 c++ a=*c r=a 33 c++ a=*c r=a 34 c++ a=*c r=a 35
        a=r 4 c=a a=r 32 *c=a c++ a=r 33 *c=a c++ a=r 34 *c=a c++ a=r 35 *c=a
        a=r 32 a<<= 8 b=r 33 a+=b a<<= 8 b=r 34 a+=b a<<= 8 b=r 35 a+=b r=a 39
        a=r 3 a+= 4 r=a 32 b=r 3 a=r 13 a+=b r=a 33 a=r 4 a+= 4 r=a 34
        a=r 38 b=r 4 a+=b r=a 38
        do
          a=r 32 b=r 33 a<b ifl a=r 34 b=r 38 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
          a> 0 ifl
            a=r 39 a>>= 15 r=a 35 a=r 39 a>>= 3 b=r 35 a^=b b=r 39 a^=b a<<= 14 a>>= 14 r=a 35
a=r 35 b=r 46 a+=b d=a a=*d
            r=a 36 a=r 34 b=r 4 a-=b r=a 37
a=r 35 b=r 46 a+=b d=a a=r 37 *d=a
            a=r 32 c=a a=*c a== 242 ifl a=r 36 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
            a> 0 ifl
              a=r 32 a++ r=a 32 c=a a=*c a== 255 ifnotl
                a= 40 r=a 35
                do
                  a=r 32 c=a a=*c r=a 37 b=r 35 a+=b r=a 35 a=r 32 a++ r=a 32 a=r 37 a== 254
                while
                a=r 36 b=r 4 a+=b r=a 36
                do
                  a=r 34 b=r 38 a<b ifl a=r 35 a> 0 ifl a= 1 elsel a=0 endif elsel a=0 endif
                  a> 0 ifl a=r 36 c=a a=*c c=r 34 *c=a a=c a++ r=a 34 a=r 36 a++ r=a 36 a=r 35 a-- r=a 35 a= 1 endif
                a> 0 while
              elsel
                a=r 32 a++ r=a 32 a=r 34 c=a a= 242 *c=a a=c a++ r=a 34
              endif
              a=r 34 a-- c=a a=*c r=a 39 c-- a=*c a<<= 8 b=r 39 a+=b r=a 39 c-- a=*c a<<= 16 b=r 39 a+=b r=a 39 c-- a=*c a<<= 24 b=r 39 a+=b r=a 39
            elsel
              a=r 32 c=a a=*c c=r 34 *c=a r=a 37 a=c a++ r=a 34 a=r 32 a++ r=a 32 a=r 39 a<<= 8 b=r 37 a+=b r=a 39
            endif
            a= 1
          endif
        a> 0 while
        a=r 4 r=a 36 a=r 34 b=r 4 a-=b r=a 37
      endif
      a=r 10 a&= 4 a> 0 ifl
        a=0 r=a 32
        do
          a=r 32 a>>= 3 b=r 36 a+=b c=a a=r 32 a&= 7 b=a a=*c a>>=b a&= 1 r=a 33
a=r 32 b=r 43 a+=b d=a a=r 33 *d=a
          a=r 32 a++ r=a 32
        a> 255 until
        a=r 36 a+= 32 r=a 32 b=r 37 a=r 36 a+=b r=a 33 a=0 r=a 34
        do
          a=r 34 b=r 8 a<b ifl a=r 32 b=r 33 a<b ifl a= 1 elsel a=0 endif elsel a=0 endif
          a> 0 ifl
            a=r 32 c=a a=*c r=a 35 a=r 32 a++ r=a 32
a=r 35 b=r 43 a+=b d=a a=*d
            a> 0 ifl
              a=0 r=a 38
              do
                a=r 32 b=r 33 a<b ifl a=r 32 c=a a=*c r=a 39 a=r 32 a++ r=a 32 a=r 39 a== 255 ifl a=r 38 a+= 255 r=a 38 a= 1 elsel a=0 endif elsel a=0 r=a 39 endif
              a> 0 while
              a=r 38 b=r 39 a+=b a++ r=a 38
              do
                a=r 38 a> 0 ifl a=r 34 b=r 8 a<b ifl a=r 35 out a=r 34 a++ r=a 34 a=r 38 a-- r=a 38 a= 1 elsel a=0 endif elsel a=0 endif
              a> 0 while
            elsel
              a=r 35 out a=r 34 a++ r=a 34
            endif
            a= 1
          endif
        a> 0 while
      elsel
        a=r 37 a> 0 ifl
          do
            a=r 36 c=a a=*c out a=r 36 a++ r=a 36 a=r 37 a-- r=a 37
          a> 0 while
        endif
      endif
    endif
    a=r 6 r=a 2 a=r 5 a-- r=a 5
  a> 0 while
  endif
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZBZ3";
