/*
  ZPAQBROTLI: a brotli decoder (RFC 7932) written in ZPAQL, for zpaq-std
  -ma:brotli. zpaq-std, 2026. Written from the specification (it does not derive
  from zpaqlpy's GPL-3 decoder). Generated by gen.py next to this file.

  ZPAQL has no subroutines, and brotli reads prefix codes in many places (block
  types and counts of three categories, two context maps, and the literal,
  command and distance trees), so the program is a state machine: one loop, and
  "calling" the prefix-code reader means saving the state to return to. The hot
  paths (symbols, literals, copies, dictionary words) are inline.

  Supported: every meta-block type (compressed, uncompressed, metadata), simple
  and complex prefix codes, block switching for literals, commands and
  distances, context maps with RLE and inverse move-to-front, all four literal
  context modes, NPOSTFIX/NDIRECT, the distance ring buffer and its 16 short
  codes, and static-dictionary words with all 121 transforms. Any window size.

  The input is a FIXED DATA PREFIX of 126608 bytes, then the brotli stream: the
  static dictionary (122784), the context lookup table (2048), the transform
  strings, map and table, the dictionary word sizes and offsets, and the
  constant tables (insert/copy lengths, command cells, block counts, the
  code-length code). zpaq-std builds it at run time from libbrotli
  (zpaqbrotli_prefijo), so it is byte for byte the dictionary brotli uses.
  M: the input from 0, then the whole output (matches, dictionary words and the
  literal context look back into it), which also goes out with OUT. H: ph = 19.

  Verified with zpaqd 7.15 on 182 brotli streams (22 inputs x qualities 0, 1, 5,
  9, 10, 11; 38 more texts at quality 11; windows 10, 16 and 24) and on hand-made
  streams for the transforms the encoder never writes (omit first 1-9),
  accepted by libbrotli's own decoder with the same output.

  FROZEN, like the other portable decoders. The prefix layout is frozen with it.
*/
static const char ZPAQBROTLI_CUERPO[] = R"ZBRO(hcomp
halt
pcomp zpaqbrotli ;
(ZPAQBROTLI: decodificador de brotli - RFC 7932 - en ZPAQL, para zpaq-std -ma:brotli.
 zpaq-std, 2026, escrito desde la especificacion. Entrada: un prefijo de datos fijo con
 el diccionario estatico, la tabla de contexto y las transformaciones, y el flujo. La
 lectura de codigos prefijo es una maquina de estados. La salida queda en M y sale
 con out.)
a> 255 ifl
  a=c r=a 1
a= 0
  r=a 150
a= 24
  r=a 151
a= 48
  r=a 152
a= 72
  r=a 153
a= 96
  r=a 154
a= 107
  r=a 155
a= 118
  r=a 156
a= 144
  r=a 157
a= 170
  r=a 158
a= 188
  r=a 159
a= 204
  r=a 160
a= 1
a<<= 8
  r=a 161
a= 2
a<<= 8
  r=a 162
a= 3
a<<= 8
  r=a 163
a= 4
a<<= 8
  r=a 164
a= 5
a<<= 8
  r=a 165
a= 5
a<<= 8 a+= 32
  r=a 166
a= 5
a<<= 8 a+= 128
  r=a 167
a= 8
a<<= 8 a+= 128
  r=a 168
a= 16
a<<= 8
  r=a 169
a= 80
a<<= 8
  r=a 170
a= 1
a<<= 8 a+= 223
a<<= 8 a+= 160
  r=a 171
a= 1
a<<= 8 a+= 231
a<<= 8 a+= 160
  r=a 172
a= 1
a<<= 8 a+= 232
a<<= 8 a+= 128
  r=a 173
a= 1
a<<= 8 a+= 233
a<<= 8
  r=a 174
a= 1
a<<= 8 a+= 234
a<<= 8 a+= 128
  r=a 175
a= 1
a<<= 8 a+= 234
a<<= 8 a+= 160
  r=a 176
a= 1
a<<= 8 a+= 235
a<<= 8 a+= 32
  r=a 90 a=0 r=a 91
  do
    a=r 90 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 92
    a=r 91 d=a a=r 92 *d=a a=r 90 a+= 4 r=a 90 a=r 91 a++ r=a 91
  a< 220 while
  a=r 1 a+= 16 r=a 3 r=a 4
a= 15
a<<= 8 a+= 116
a<<= 8 a+= 128
  r=a 2
  a= 1 r=a 10 a= 16 r=a 40 a= 15 r=a 41 a= 11 r=a 42 a= 4 r=a 43
  do
a=r 10 a== 1 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    a== 0 ifl a= 16 r=a 9 elsel
a= 3 r=a 245
a=0 r=a 9 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 9 a|=b r=a 9 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
    a=r 9 a> 0 ifl a+= 17 r=a 9 elsel
a= 3 r=a 245
a=0 r=a 9 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 9 a|=b r=a 9 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
    a=r 9 a> 0 ifl a+= 8 r=a 9 elsel a= 17 r=a 9 endif endif endif
    a= 1 b=r 9 a<<=b a-= 16 r=a 5
    a= 2 r=a 10
  endif
a=r 10 a== 2 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    r=a 6 a> 0 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
      a> 0 ifl a= 0 r=a 10 endif
    endif
    a=r 10 a== 2 ifl
a= 2 r=a 245
a=0 r=a 9 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 9 a|=b r=a 9 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      a=r 9 a== 3 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
a= 2 r=a 245
a=0 r=a 9 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 9 a|=b r=a 9 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 9 r=a 98 a<<= 3 r=a 9
a=r 9 r=a 245
a=0 r=a 9 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 9 a|=b r=a 9 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 98 a> 0 ifl a=r 9 a++ r=a 9 endif
        a=r 2 a+= 7 a>>= 3 a<<= 3 b=r 9 a+=b a+=b a+=b a+=b a+=b a+=b a+=b a+=b r=a 2
        a=r 6 a> 0 ifl a= 0 r=a 10 endif
      elsel
        a+= 4 a<<= 2 r=a 9
a=r 9 r=a 245
a=0 r=a 7 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 7 a|=b r=a 7 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 7 a++ r=a 7
        a=0 r=a 9 a=r 6 a== 0 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
          r=a 9 endif
        a=r 9 a> 0 ifl
          a=r 2 a+= 7 a>>= 3 a<<= 3 r=a 2
          do
            a=r 2 a>>= 3 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
            a=r 2 a+= 8 r=a 2 a=r 7 a-- r=a 7
          a> 0 while
        elsel
          a=0 r=a 37 r=a 8 a=r 170 r=a 14 a= 3 r=a 10
        endif
      endif
    endif
  endif
a=r 10 a== 3 ifl
    a=r 37 a== 3 ifl
      a= 6 r=a 10
    elsel
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
a== 0 ifl a=0 r=a 9 elsel
a= 3 r=a 245
a=0 r=a 247 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 247 a|=b r=a 247 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 247 a== 0 ifl a= 1 r=a 9 elsel
a=r 247 r=a 245
a=0 r=a 248 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 248 a|=b r=a 248 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a= 1 b=r 247 a<<=b b=r 248 a+=b r=a 9 endif endif
      a=r 9 a++ r=a 9
      a=r 37 a== 0 ifl a=r 9 r=a 15 a=0 r=a 18 a= 1 r=a 21 endif
      a=r 37 a== 1 ifl a=r 9 r=a 16 a=0 r=a 19 a= 1 r=a 22 endif
      a=r 37 a== 2 ifl a=r 9 r=a 17 a=0 r=a 20 a= 1 r=a 23 endif
      a=r 9 a> 1 ifl
        a+= 2 r=a 12 a=r 14 r=a 13
        a=r 37 a== 0 ifl a=r 14 r=a 27 endif
        a=r 37 a== 1 ifl a=r 14 r=a 28 endif
        a=r 37 a== 2 ifl a=r 14 r=a 29 endif
        a=r 14 a+= 16 b=r 12 a+=b r=a 14
a= 4 r=a 11 a= 11 r=a 10
      elsel
        a=r 37 a== 0 ifl a= 1 a<<= 28 r=a 24 endif
        a=r 37 a== 1 ifl a= 1 a<<= 28 r=a 25 endif
        a=r 37 a== 2 ifl a= 1 a<<= 28 r=a 26 endif
        a=r 37 a++ r=a 37
      endif
    endif
  endif
a=r 10 a== 4 ifl
    a= 26 r=a 12 a=r 14 r=a 13
    a=r 37 a== 0 ifl a=r 14 r=a 30 endif
    a=r 37 a== 1 ifl a=r 14 r=a 31 endif
    a=r 37 a== 2 ifl a=r 14 r=a 32 endif
    a=r 14 a+= 42 r=a 14
a= 5 r=a 11 a= 11 r=a 10
  endif
a=r 10 a== 5 ifl
    a=r 37 a== 0 ifl
a=r 30 d=a a=*d a> 0 ifl
  a=r 30 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 30 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 30 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 24
    endif
    a=r 37 a== 1 ifl
a=r 31 d=a a=*d a> 0 ifl
  a=r 31 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 31 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 31 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 25
    endif
    a=r 37 a== 2 ifl
a=r 32 d=a a=*d a> 0 ifl
  a=r 32 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 32 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 32 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 26
    endif
    a=r 37 a++ r=a 37 a= 3 r=a 10
  endif
a=r 10 a== 6 ifl
a= 2 r=a 245
a=0 r=a 33 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 33 a|=b r=a 33 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a= 4 r=a 245
a=0 r=a 34 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 34 a|=b r=a 34 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
    a=r 33 b=a a=r 34 a<<=b r=a 34
    a=0 r=a 9
    do
a= 2 r=a 245
a=0 r=a 247 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 247 a|=b r=a 247 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 9 b=r 161 a+=b d=a a=r 247 *d=a
      a=r 9 a++ r=a 9 b=r 15
    a<b while
    a=r 15 a<<= 6 r=a 52
a=0 r=a 200 r=a 201
a=r 52 a> 0 ifl
do
a=r 200 b=r 169 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200 b=r 52
a<b while
endif
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
a== 0 ifl a=0 r=a 35 elsel
a= 3 r=a 245
a=0 r=a 247 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 247 a|=b r=a 247 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 247 a== 0 ifl a= 1 r=a 35 elsel
a=r 247 r=a 245
a=0 r=a 248 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 248 a|=b r=a 248 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a= 1 b=r 247 a<<=b b=r 248 a+=b r=a 35 endif endif
    a=r 35 a++ r=a 35
    a=r 35 a> 1 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
      a> 0 ifl
a= 4 r=a 245
a=0 r=a 38 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 38 a|=b r=a 38 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 38 a++ r=a 38 elsel a=0 r=a 38 endif
      a=r 35 b=r 38 a+=b r=a 12 a=r 14 r=a 13 r=a 39 a+= 16 b=r 12 a+=b r=a 14
a= 7 r=a 11 a= 11 r=a 10
    elsel
      a= 7 r=a 10
    endif
    a=r 35 a< 2 ifl a=0 r=a 38 endif
  endif
a=r 10 a== 7 ifl
    a=r 35 a> 1 ifl
      a=0 r=a 53
      do
a=r 39 d=a a=*d a> 0 ifl
  a=r 39 a+= 16 d=a a=*d r=a 54
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 39 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 39 a+=b a+= 16 d=a a=*d r=a 54 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 54 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
        a=r 54 a== 0 ifl
          a=r 53 a++ r=a 53
        elsel a=r 38 b=r 54 a<b ifnotl
a=r 54 r=a 245
a=0 r=a 55 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 55 a|=b r=a 55 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
          a= 1 b=r 54 a<<=b b=r 55 a+=b b=r 53 a+=b r=a 53
        elsel
          a=r 54 b=r 38 a-=b r=a 55
a=r 53 b=r 169 a+=b d=a a=r 55 *d=a
          a=r 53 a++ r=a 53
        endif endif
        a=r 53 b=r 52
      a<b while
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
      a> 0 ifl
        a=0 r=a 53
        do
a=r 53 b=r 167 a+=b d=a a=r 53 *d=a
          a=r 53 a++ r=a 53
        a> 255 until
        a=0 r=a 53
        do
a=r 53 b=r 169 a+=b d=a a=*d
          r=a 54
a=r 54 b=r 167 a+=b d=a a=*d
          r=a 55
a=r 53 b=r 169 a+=b d=a a=r 55 *d=a
          a=r 54 a> 0 ifl
            do
              a=r 54 a-- r=a 56
a=r 56 b=r 167 a+=b d=a a=*d
              r=a 57
a=r 54 b=r 167 a+=b d=a a=r 57 *d=a
              a=r 56 r=a 54
            a> 0 while
a=r 54 b=r 167 a+=b d=a a=r 55 *d=a
          endif
          a=r 53 a++ r=a 53 b=r 52
        a<b while
      endif
    endif
    a=r 17 a<<= 2 r=a 52
a=0 r=a 200 r=a 201
a=r 52 a> 0 ifl
do
a=r 200 b=r 168 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200 b=r 52
a<b while
endif
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
a== 0 ifl a=0 r=a 36 elsel
a= 3 r=a 245
a=0 r=a 247 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 247 a|=b r=a 247 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 247 a== 0 ifl a= 1 r=a 36 elsel
a=r 247 r=a 245
a=0 r=a 248 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 248 a|=b r=a 248 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a= 1 b=r 247 a<<=b b=r 248 a+=b r=a 36 endif endif
    a=r 36 a++ r=a 36
    a=r 36 a> 1 ifl
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
      a> 0 ifl
a= 4 r=a 245
a=0 r=a 38 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 38 a|=b r=a 38 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 38 a++ r=a 38 elsel a=0 r=a 38 endif
      a=r 36 b=r 38 a+=b r=a 12 a=r 14 r=a 13 r=a 39 a+= 16 b=r 12 a+=b r=a 14
a= 8 r=a 11 a= 11 r=a 10
    elsel
      a= 8 r=a 10
    endif
  endif
a=r 10 a== 8 ifl
    a=r 17 a<<= 2 r=a 52
    a=r 36 a> 1 ifl
      a=0 r=a 53
      do
a=r 39 d=a a=*d a> 0 ifl
  a=r 39 a+= 16 d=a a=*d r=a 54
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 39 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 39 a+=b a+= 16 d=a a=*d r=a 54 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 54 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
        a=r 54 a== 0 ifl
          a=r 53 a++ r=a 53
        elsel a=r 38 b=r 54 a<b ifnotl
a=r 54 r=a 245
a=0 r=a 55 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 55 a|=b r=a 55 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
          a= 1 b=r 54 a<<=b b=r 55 a+=b b=r 53 a+=b r=a 53
        elsel
          a=r 54 b=r 38 a-=b r=a 55
a=r 53 b=r 168 a+=b d=a a=r 55 *d=a
          a=r 53 a++ r=a 53
        endif endif
        a=r 53 b=r 52
      a<b while
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
      a> 0 ifl
        a=0 r=a 53
        do
a=r 53 b=r 167 a+=b d=a a=r 53 *d=a
          a=r 53 a++ r=a 53
        a> 255 until
        a=0 r=a 53
        do
a=r 53 b=r 168 a+=b d=a a=*d
          r=a 54
a=r 54 b=r 167 a+=b d=a a=*d
          r=a 55
a=r 53 b=r 168 a+=b d=a a=r 55 *d=a
          a=r 54 a> 0 ifl
            do
              a=r 54 a-- r=a 56
a=r 56 b=r 167 a+=b d=a a=*d
              r=a 57
a=r 54 b=r 167 a+=b d=a a=r 57 *d=a
              a=r 56 r=a 54
            a> 0 while
a=r 54 b=r 167 a+=b d=a a=r 55 *d=a
          endif
          a=r 53 a++ r=a 53 b=r 52
        a<b while
      endif
    endif
    a=0 r=a 44 r=a 45 a= 9 r=a 10
  endif
a=r 10 a== 9 ifl
    a=r 45 a== 0 ifl a=r 44 b=r 35 a<b ifnot a= 1 r=a 45 a=0 r=a 44 endif endif
    a=r 45 a== 1 ifl a=r 44 b=r 16 a<b ifnot a= 2 r=a 45 a=0 r=a 44 endif endif
    a=r 45 a== 2 ifl a=r 44 b=r 36 a<b ifnot a= 3 r=a 45 endif endif
    a=r 45 a== 3 ifl a= 10 r=a 10 elsel
      a=r 45 a== 0 ifl a= 255 a++ r=a 12 a=r 14
a=r 44 b=r 162 a+=b d=a a=r 14 *d=a
      endif
      a=r 45 a== 1 ifl a= 11 a<<= 6 r=a 12
a=r 44 b=r 163 a+=b d=a a=r 14 *d=a
      endif
      a=r 45 a== 2 ifl a= 48 b=r 33 a<<=b a+= 16 b=r 34 a+=b r=a 12
a=r 44 b=r 164 a+=b d=a a=r 14 *d=a
      endif
      a=r 14 r=a 13 a+= 16 b=r 12 a+=b r=a 14 a=r 44 a++ r=a 44
a= 9 r=a 11 a= 11 r=a 10
    endif
  endif
a=r 10 a== 10 ifl
    a=r 8 b=r 7 a<b ifl
      a=r 25 a== 0 ifl
a=r 28 d=a a=*d a> 0 ifl
  a=r 28 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 28 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 28 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 a== 0 ifl
  a=r 22 r=a 208
elsel a== 1 ifl
  a=r 19 a++ r=a 208 b=r 16 a<b ifnot a=0 r=a 208 endif
elsel
  a=r 207 a-= 2 r=a 208
endif endif
a=r 19 r=a 22 a=r 208 r=a 19
a=r 31 d=a a=*d a> 0 ifl
  a=r 31 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 31 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 31 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 25
      endif
      a=r 25 a-- r=a 25
a=r 19 b=r 163 a+=b d=a a=*d
      r=a 58
a=r 58 d=a a=*d a> 0 ifl
  a=r 58 a+= 16 d=a a=*d r=a 46
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 58 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 58 a+=b a+= 16 d=a a=*d r=a 46 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 46 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
      a=r 46 a>>= 6 r=a 59
a=r 59 b=r 154 a+=b d=a a=*d
      r=a 56 a=r 46 a>>= 3 a&= 7 b=r 56 a+=b r=a 56
a=r 59 b=r 155 a+=b d=a a=*d
      r=a 57 a=r 46 a&= 7 b=r 57 a+=b r=a 57
a=r 56 b=r 151 a+=b d=a a=*d
      r=a 59
a=r 59 r=a 245
a=0 r=a 47 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 47 a|=b r=a 47 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 56 b=r 150 a+=b d=a a=*d
      b=r 47 a+=b r=a 47
a=r 57 b=r 153 a+=b d=a a=*d
      r=a 59
a=r 59 r=a 245
a=0 r=a 48 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 48 a|=b r=a 48 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 57 b=r 152 a+=b d=a a=*d
      b=r 48 a+=b r=a 48
      a=r 47 a> 0 ifl
        do
          a=r 24 a== 0 ifl
a=r 27 d=a a=*d a> 0 ifl
  a=r 27 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 27 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 27 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 a== 0 ifl
  a=r 21 r=a 208
elsel a== 1 ifl
  a=r 18 a++ r=a 208 b=r 15 a<b ifnot a=0 r=a 208 endif
elsel
  a=r 207 a-= 2 r=a 208
endif endif
a=r 18 r=a 21 a=r 208 r=a 18
a=r 30 d=a a=*d a> 0 ifl
  a=r 30 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 30 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 30 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 24
          endif
          a=r 24 a-- r=a 24
          a=r 4 a-- c=a a=*c r=a 56 c-- a=*c r=a 57
a=r 18 b=r 161 a+=b d=a a=*d
          a<<= 9 r=a 59 b=r 56 a+=b r=a 56 a=r 59 a+= 255 a++ b=r 57 a+=b r=a 57
a=r 56 b=r 171 a+=b c=a a=*c
          r=a 56
a=r 57 b=r 171 a+=b c=a a=*c
          b=r 56 a|=b r=a 56
          a=r 18 a<<= 6 b=r 56 a+=b r=a 56
a=r 56 b=r 169 a+=b d=a a=*d
          r=a 56
a=r 56 b=r 162 a+=b d=a a=*d
          r=a 58
a=r 58 d=a a=*d a> 0 ifl
  a=r 58 a+= 16 d=a a=*d r=a 56
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 58 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 58 a+=b a+= 16 d=a a=*d r=a 56 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 56 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
          a=r 56
c=r 4 *c=a out a=c a++ r=a 4
          a=r 8 a++ r=a 8 a=r 47 a-- r=a 47
        a> 0 while
      endif
      a=r 8 b=r 7 a<b ifl
        a=0 r=a 49 a=r 46 a> 127 ifl
          a=r 26 a== 0 ifl
a=r 29 d=a a=*d a> 0 ifl
  a=r 29 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 29 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 29 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 a== 0 ifl
  a=r 23 r=a 208
elsel a== 1 ifl
  a=r 20 a++ r=a 208 b=r 17 a<b ifnot a=0 r=a 208 endif
elsel
  a=r 207 a-= 2 r=a 208
endif endif
a=r 20 r=a 23 a=r 208 r=a 20
a=r 32 d=a a=*d a> 0 ifl
  a=r 32 a+= 16 d=a a=*d r=a 207
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 32 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 32 a+=b a+= 16 d=a a=*d r=a 207 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 207 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
a=r 207 b=r 157 a+=b d=a a=*d
r=a 208
a=r 208 r=a 245
a=0 r=a 209 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 209 a|=b r=a 209 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
a=r 207 b=r 156 a+=b d=a a=*d
b=r 209 a+=b r=a 26
          endif
          a=r 26 a-- r=a 26
          a=r 48 a> 4 ifl a= 3 elsel a=r 48 a-= 2 endif r=a 56 a=r 20 a<<= 2 b=r 56 a+=b r=a 56
a=r 56 b=r 168 a+=b d=a a=*d
          r=a 56
a=r 56 b=r 164 a+=b d=a a=*d
          r=a 58
a=r 58 d=a a=*d a> 0 ifl
  a=r 58 a+= 16 d=a a=*d r=a 49
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 58 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 58 a+=b a+= 16 d=a a=*d r=a 49 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 49 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
        endif
        a=r 49 a< 16 ifl
          a< 4 ifl
            a== 0 ifl a=r 43 elsel a== 1 ifl a=r 42 elsel a== 2 ifl a=r 41 elsel a=r 40 endif endif endif r=a 50
          elsel
            a< 10 ifl a-= 4 r=a 56 a=r 43 elsel a-= 10 r=a 56 a=r 42 endif r=a 50
            a=r 56 a>>= 1 a++ r=a 57 a=r 56 a&= 1 a== 0 ifl a=r 50 b=r 57 a-=b elsel a=r 50 b=r 57 a+=b endif r=a 50
          endif
        elsel
          b=r 34 a-= 16 a<b ifl
            a=r 49 a-= 15 r=a 50
          elsel
            a=r 49 a-= 16 b=r 34 a-=b r=a 56 a=r 33 a++ b=a a=r 56 a>>=b a++ r=a 57
            a=r 33 b=a a=r 56 a>>=b a&= 1 a+= 2 b=r 57 a<<=b a-= 4 r=a 59
a=r 57 r=a 245
a=0 r=a 55 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 55 a|=b r=a 55 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
            a=r 59 b=r 55 a+=b b=r 33 a<<=b r=a 50
            a= 1 b=r 33 a<<=b a-- b=r 56 a&=b b=r 50 a+=b b=r 34 a+=b a++ r=a 50
          endif
        endif
        a=r 4 b=r 3 a-=b r=a 51 b=r 5 a>b ifl a=r 5 r=a 51 endif
        a=r 50 b=r 51 a>b ifl
          a-=b a-- r=a 56 a=r 48 r=a 57
a=r 57 b=r 175 a+=b c=a a=*c
          r=a 58 a= 1 b=r 58 a<<=b a-- b=r 56 a&=b r=a 59 a=r 58 b=a a=r 56 a>>=b r=a 60
          a=r 57 a<<= 2 a+= 3 b=r 176 a+=b c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 58
          a=r 59 b=r 57 a*=b b=r 58 a+=b r=a 58
          a=r 60 a+=a b=r 60 a+=b r=a 59
a=r 59 b=r 174 a+=b c=a a=*c
          r=a 61
          a=r 59 a++ r=a 59
a=r 59 b=r 174 a+=b c=a a=*c
          r=a 62
          a=r 59 a++ r=a 59
a=r 59 b=r 174 a+=b c=a a=*c
          r=a 63
          a=r 4 r=a 64
a=r 61 a+=a b=r 173 a+=b c=a a=*c r=a 65 c++ a=*c a<<= 8 b=r 65 a+=b b=r 172 a+=b r=a 65
c=a a=*c r=a 66 a=r 65 a++ r=a 65 a=r 66
a> 0 ifl
  do
    a=r 65 c=a a=*c c=r 4 *c=a a=c a++ r=a 4 a=r 65 a++ r=a 65 a=r 66 a-- r=a 66
  a> 0 while
endif
          a=r 62 a> 0 ifl a< 10 ifl
            b=a a=r 57 a>b ifl a-=b elsel a=0 endif r=a 57
          endif endif
          a=r 62 a> 11 ifl
            a-= 11 b=a a=r 57 a>b ifl a-=b r=a 57 a=r 58 a+=b r=a 58 elsel a=0 r=a 57 endif
          endif
          a=r 4 r=a 67 a=r 57 r=a 66
          a> 0 ifl
            do
              a=r 58 c=a a=*c c=r 4 *c=a a=c a++ r=a 4 a=r 58 a++ r=a 58 a=r 66 a-- r=a 66
            a> 0 while
          endif
          a=r 57 r=a 66
          a=r 62 a== 10 ifl a=r 66 a> 0 ifl
a=r 67 c=a a=*c a< 192 ifl
  a> 96 ifl a< 123 ifl a^= 32 *c=a endif endif a= 1 r=a 68
elsel a< 224 ifl
  a=r 66 a> 1 ifl c++ a=*c a^= 32 *c=a endif a= 2 r=a 68
elsel
  a=r 66 a> 2 ifl c++ c++ a=*c a^= 5 *c=a endif a= 3 r=a 68
endif endif
          endif endif
          a=r 62 a== 11 ifl
            a=r 66 a> 0 ifl
              do
a=r 67 c=a a=*c a< 192 ifl
  a> 96 ifl a< 123 ifl a^= 32 *c=a endif endif a= 1 r=a 68
elsel a< 224 ifl
  a=r 66 a> 1 ifl c++ a=*c a^= 32 *c=a endif a= 2 r=a 68
elsel
  a=r 66 a> 2 ifl c++ c++ a=*c a^= 5 *c=a endif a= 3 r=a 68
endif endif
                a=r 67 b=r 68 a+=b r=a 67 a=r 66 b=r 68 a>b ifl a-=b elsel a=0 endif r=a 66
              a> 0 while
            endif
          endif
a=r 63 a+=a b=r 173 a+=b c=a a=*c r=a 65 c++ a=*c a<<= 8 b=r 65 a+=b b=r 172 a+=b r=a 65
c=a a=*c r=a 66 a=r 65 a++ r=a 65 a=r 66
a> 0 ifl
  do
    a=r 65 c=a a=*c c=r 4 *c=a a=c a++ r=a 4 a=r 65 a++ r=a 65 a=r 66 a-- r=a 66
  a> 0 while
endif
          a=r 64 r=a 66
          a=r 4 b=r 66 a>b ifl
            do
              a=r 66 c=a a=*c out a=r 66 a++ r=a 66 b=r 4
            a<b while
          endif
          a=r 4 b=r 64 a-=b b=r 8 a+=b r=a 8
        elsel
          a=r 4 b=r 50 a-=b r=a 56 a=r 48 r=a 57
          a> 0 ifl
            do
              a=r 56 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
              a=r 56 a++ r=a 56 a=r 57 a-- r=a 57
            a> 0 while
          endif
          a=r 8 b=r 48 a+=b r=a 8
          a=r 49 a> 0 ifl a=r 41 r=a 40 a=r 42 r=a 41 a=r 43 r=a 42 a=r 50 r=a 43 endif
        endif
      endif
    elsel
      a=r 6 a> 0 ifl a= 0 elsel a= 2 endif r=a 10
    endif
  endif
a=r 10 a== 11 ifl
    a=r 12 a-- r=a 100
    a=0 r=a 101 a=r 100 a>>= 1
    a> 0 ifl do r=a 102 a=r 101 a++ r=a 101 a=r 102 a>>= 1 a> 0 while endif
    a=r 101 a++ r=a 101
a= 2 r=a 245
a=0 r=a 103 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 103 a|=b r=a 103 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
    a=r 103 a== 1 ifl
a= 2 r=a 245
a=0 r=a 104 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 104 a|=b r=a 104 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      a=r 104 a++ r=a 104
      a=r 104 a> 0 ifl
a=r 101 r=a 245
a=0 r=a 110 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 110 a|=b r=a 110 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      endif
      a=r 104 a> 1 ifl
a=r 101 r=a 245
a=0 r=a 111 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 111 a|=b r=a 111 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      endif
      a=r 104 a> 2 ifl
a=r 101 r=a 245
a=0 r=a 112 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 112 a|=b r=a 112 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      endif
      a=r 104 a> 3 ifl
a=r 101 r=a 245
a=0 r=a 113 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 113 a|=b r=a 113 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
      endif
a=0 r=a 200 r=a 201
a=r 12 a> 0 ifl
do
a=r 200 b=r 167 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200 b=r 12
a<b while
endif
      a= 1 r=a 105 a=r 104 a== 1 ifl
        a=r 13 d=a a= 1 *d=a a=r 13 a+= 16 d=a a=r 110 *d=a a=0 r=a 105
      elsel a== 2 ifl
        a= 1 r=a 106
a=r 110 b=r 167 a+=b d=a a=r 106 *d=a
a=r 111 b=r 167 a+=b d=a a=r 106 *d=a
      elsel a== 3 ifl
        a= 1 r=a 106
a=r 110 b=r 167 a+=b d=a a=r 106 *d=a
        a= 2 r=a 106
a=r 111 b=r 167 a+=b d=a a=r 106 *d=a
a=r 112 b=r 167 a+=b d=a a=r 106 *d=a
      elsel
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
        a> 0 ifl
          a= 1 r=a 106
a=r 110 b=r 167 a+=b d=a a=r 106 *d=a
          a= 2 r=a 106
a=r 111 b=r 167 a+=b d=a a=r 106 *d=a
          a= 3 r=a 106
a=r 112 b=r 167 a+=b d=a a=r 106 *d=a
a=r 113 b=r 167 a+=b d=a a=r 106 *d=a
        elsel
          a= 2 r=a 106
a=r 110 b=r 167 a+=b d=a a=r 106 *d=a
a=r 111 b=r 167 a+=b d=a a=r 106 *d=a
a=r 112 b=r 167 a+=b d=a a=r 106 *d=a
a=r 113 b=r 167 a+=b d=a a=r 106 *d=a
        endif
      endif endif endif
      a=r 105 a> 0 ifl
        a=r 167 r=a 107
a=0 r=a 200 r=a 201
do
a=r 200 b=r 13 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200
a< 16 while
a=0 r=a 200 r=a 202 r=a 203
do
a=r 200 b=r 107 a+=b d=a a=*d
  a> 0 ifl
    r=a 204 b=r 13 a+=b d=a a=*d a++ *d=a a=r 202 a++ r=a 202 a=r 200 r=a 203
  endif
  a=r 200 a++ r=a 200 b=r 12
a<b while
a=r 202 a< 2 ifl
  a=r 13 d=a a= 1 *d=a a=r 13 a+= 16 d=a a=r 203 *d=a
elsel
  a=r 13 d=a a=0 *d=a r=a 205 a= 1 r=a 206
  do
    a=0 r=a 200
    do
a=r 200 b=r 107 a+=b d=a a=*d
      b=r 206 a==b ifl
        a=r 205 b=r 13 a+=b a+= 16 d=a a=r 200 *d=a a=r 205 a++ r=a 205
      endif
      a=r 200 a++ r=a 200 b=r 12
    a<b while
    a=r 206 a++ r=a 206
  a< 16 while
endif
      endif
    elsel
      a= 18 r=a 106
a=0 r=a 200 r=a 201
a=r 106 a> 0 ifl
do
a=r 200 b=r 165 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200 b=r 106
a<b while
endif
      a= 32 r=a 104 a=r 103 r=a 105
      do
        a=r 2 r=a 108
a= 4 r=a 245
a=0 r=a 109 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 109 a|=b r=a 109 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
        a=r 108 r=a 2
a=r 109 b=r 159 a+=b d=a a=*d
        b=r 2 a+=b r=a 2
a=r 109 b=r 160 a+=b d=a a=*d
        r=a 106
a=r 105 b=r 158 a+=b d=a a=*d
        r=a 107
a=r 107 b=r 165 a+=b d=a a=r 106 *d=a
        a=r 105 a++ r=a 105
        a=r 106 a> 0 ifl
          b=a a= 32 a>>=b b=a a=r 104 a-=b r=a 104
          a> 0 ifl a> 32 ifl a= 18 r=a 105 endif elsel a= 18 r=a 105 endif
        endif
        a=r 105
      a< 18 while
      a= 18 r=a 106 a=r 165 r=a 107 a=r 166 r=a 108
a=0 r=a 200 r=a 201
do
a=r 200 b=r 108 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200
a< 16 while
a=0 r=a 200 r=a 202 r=a 203
do
a=r 200 b=r 107 a+=b d=a a=*d
  a> 0 ifl
    r=a 204 b=r 108 a+=b d=a a=*d a++ *d=a a=r 202 a++ r=a 202 a=r 200 r=a 203
  endif
  a=r 200 a++ r=a 200 b=r 106
a<b while
a=r 202 a< 2 ifl
  a=r 108 d=a a= 1 *d=a a=r 108 a+= 16 d=a a=r 203 *d=a
elsel
  a=r 108 d=a a=0 *d=a r=a 205 a= 1 r=a 206
  do
    a=0 r=a 200
    do
a=r 200 b=r 107 a+=b d=a a=*d
      b=r 206 a==b ifl
        a=r 205 b=r 108 a+=b a+= 16 d=a a=r 200 *d=a a=r 205 a++ r=a 205
      endif
      a=r 200 a++ r=a 200 b=r 106
    a<b while
    a=r 206 a++ r=a 206
  a< 16 while
endif
a=0 r=a 200 r=a 201
a=r 12 a> 0 ifl
do
a=r 200 b=r 167 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200 b=r 12
a<b while
endif
      a= 128 a<<= 8 r=a 104 a=0 r=a 105 r=a 106 r=a 109 a= 8 r=a 107
      do
        a=r 105 b=r 12 a<b ifl a=r 104 a> 0 ifl a=r 104 a>>= 16 a> 0 ifl a=0 elsel a= 1 endif elsel a=0 endif elsel a=0 endif
        a> 0 ifl
          a=r 166 r=a 114
a=r 114 d=a a=*d a> 0 ifl
  a=r 114 a+= 16 d=a a=*d r=a 115
elsel
  a=0 r=a 240 r=a 241 r=a 242 a= 1 r=a 243
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=a a=r 240 a|=b r=a 240
    a=r 114 b=r 243 a+=b d=a a=*d r=a 244
    a=r 241 b=r 244 a+=b b=a a=r 240 a<b ifl
      a=r 240 b=r 241 a-=b b=r 242 a+=b b=r 114 a+=b a+= 16 d=a a=*d r=a 115 a=0
    elsel
      a=r 242 b=r 244 a+=b r=a 242 a=r 241 b=r 244 a+=b a<<= 1 r=a 241 a=r 240 a<<= 1 r=a 240
      a=r 243 a++ r=a 243 a> 15 ifl a=0 r=a 115 a=0 elsel a= 1 endif
    endif
  a> 0 while
endif
          a=r 115 a< 16 ifl
            a=0 r=a 106
a=r 105 b=r 167 a+=b d=a a=r 115 *d=a
            a=r 105 a++ r=a 105
            a=r 115 a> 0 ifl r=a 107 b=a a= 128 a<<= 8 a>>=b b=a a=r 104 a-=b r=a 104 endif
          elsel
            a== 16 ifl a= 2 r=a 116 a=r 107 elsel a= 3 r=a 116 a=0 endif r=a 117
            a=r 109 b=r 117 a==b ifnot a=0 r=a 106 a=r 117 r=a 109 endif
            a=r 106 r=a 118 a> 0 ifl a-= 2 b=r 116 a<<=b r=a 106 endif
a=r 116 r=a 245
a=0 r=a 119 r=a 246 a=r 245
a> 0 ifl
  do
a=r 2 a>>= 3 c=a a=r 2 a&= 7 b=a a=*c a>>=b a&= 1 r=a 250 a=r 2 a++ r=a 2 a=r 250
    b=r 246 a<<=b b=r 119 a|=b r=a 119 a=r 246 a++ r=a 246 b=r 245
  a<b while
endif
            a=r 119 a+= 3 b=r 106 a+=b r=a 106 b=r 118 a-=b r=a 119
            a=r 119 r=a 120
            a> 0 ifl
              do
                a=r 105 b=r 12 a<b ifl
a=r 105 b=r 167 a+=b d=a a=r 117 *d=a
                endif
                a=r 105 a++ r=a 105 a=r 120 a-- r=a 120
              a> 0 while
            endif
            a=r 117 a> 0 ifl a= 15 b=r 117 a-=b b=a a=r 119 a<<=b b=a a=r 104 a-=b r=a 104 endif
          endif
          a= 1
        endif
      a> 0 while
      a=r 167 r=a 107
a=0 r=a 200 r=a 201
do
a=r 200 b=r 13 a+=b d=a a=r 201 *d=a
  a=r 200 a++ r=a 200
a< 16 while
a=0 r=a 200 r=a 202 r=a 203
do
a=r 200 b=r 107 a+=b d=a a=*d
  a> 0 ifl
    r=a 204 b=r 13 a+=b d=a a=*d a++ *d=a a=r 202 a++ r=a 202 a=r 200 r=a 203
  endif
  a=r 200 a++ r=a 200 b=r 12
a<b while
a=r 202 a< 2 ifl
  a=r 13 d=a a= 1 *d=a a=r 13 a+= 16 d=a a=r 203 *d=a
elsel
  a=r 13 d=a a=0 *d=a r=a 205 a= 1 r=a 206
  do
    a=0 r=a 200
    do
a=r 200 b=r 107 a+=b d=a a=*d
      b=r 206 a==b ifl
        a=r 205 b=r 13 a+=b a+= 16 d=a a=r 200 *d=a a=r 205 a++ r=a 205
      endif
      a=r 200 a++ r=a 200 b=r 12
    a<b while
    a=r 206 a++ r=a 206
  a< 16 while
endif
    endif
    a=r 11 r=a 10
  endif
  a=r 10
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZBRO";
