/*
  ZPAQLZFSE: an lzfse decoder written in ZPAQL, for zpaq-std -ma:lzfse (Apple
  lzfse 1.0). zpaq-std, 2026. Generated by gen.py next to this file (ZPAQL has
  no subroutines: everything is a macro expanded in place).

  The whole stream is kept in M and decoded at the end of the segment:
  compressed blocks (bvx2: bit-packed header, frequency tables with lzfse's
  fixed prefix code, FSE decoder tables with contiguous states per symbol,
  literals from four interleaved states, L/M/D from value decoders, D = 0
  repeating the previous distance), LZVN blocks (bvxn, which lzfse writes for
  inputs under 4 KB: every opcode class), raw blocks (bvx-) and the end marker
  (bvx$). Uncompressed-table blocks (bvx1) are not: lzfse never writes them.

  M: the stream from 0, one block of literals after it, then the whole output
  (matches look back into it), which also goes out with OUT. H needs ph = 13.

  Verified with zpaqd 7.15 on 37 lzfse streams: 23 inputs, cuts around the
  4 KB LZVN/FSE threshold, random data (raw blocks) and 12 MB (many blocks).

  FROZEN, like the other portable decoders.
*/
static const char ZPAQLZFSE_CUERPO[] = R"ZLZF(hcomp
halt
pcomp zpaqlzfse ;
(ZPAQLZFSE: decodificador de lzfse en ZPAQL, para zpaq-std -ma:lzfse. zpaq-std, 2026.
 Guarda el flujo entero en M y lo decodifica al final: bloques bvx2 - FSE, literales
 con cuatro estados y L M D con decodificadores de valor -, bvxn - LZVN -, bvx- y bvx$.
 La salida queda en M, detras, y sale con out.)
a> 255 ifl
  a=c r=a 1
a= 0
r=a 70
a= 4
a<<= 8
r=a 71
a= 8
a<<= 8
r=a 72
a= 12
a<<= 8
r=a 73
a= 12
a<<= 8 a+= 64
r=a 74
a= 12
a<<= 8 a+= 128
r=a 75
a= 12
a<<= 8 a+= 192
r=a 76
a= 13
a<<= 8
r=a 77
a= 13
a<<= 8 a+= 64
r=a 78
a= 13
a<<= 8 a+= 128
r=a 79
a= 13
a<<= 8 a+= 192
r=a 80
a= 14
a<<= 8
r=a 81
a= 15
a<<= 8
r=a 82
a= 16
a<<= 8
r=a 83
a= 17
a<<= 8
r=a 84
a= 18
a<<= 8
r=a 85
a= 20
a<<= 8
r=a 86
a= 20
a<<= 8 a+= 20
r=a 87
a= 20
a<<= 8 a+= 40
r=a 88
a= 20
a<<= 8 a+= 60
r=a 89
a= 20
a<<= 8 a+= 80
r=a 90
a= 20
a<<= 8 a+= 144
r=a 91
a= 20
a<<= 8 a+= 208
r=a 92
a= 20
a<<= 8 a+= 240
r=a 93
a=r 86 d=a
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 5
*d=a d++
a= 8
*d=a d++
a=r 87 d=a
a= 0
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a= 20
*d=a d++
a= 28
*d=a d++
a= 60
*d=a d++
a=r 88 d=a
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 3
*d=a d++
a= 5
*d=a d++
a= 8
*d=a d++
a= 11
*d=a d++
a=r 89 d=a
a= 0
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 16
*d=a d++
a= 24
*d=a d++
a= 56
*d=a d++
a= 1
a<<= 8 a+= 56
*d=a d++
a=r 90 d=a
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 4
*d=a d++
a= 4
*d=a d++
a= 4
*d=a d++
a= 5
*d=a d++
a= 5
*d=a d++
a= 5
*d=a d++
a= 5
*d=a d++
a= 6
*d=a d++
a= 6
*d=a d++
a= 6
*d=a d++
a= 6
*d=a d++
a= 7
*d=a d++
a= 7
*d=a d++
a= 7
*d=a d++
a= 7
*d=a d++
a= 8
*d=a d++
a= 8
*d=a d++
a= 8
*d=a d++
a= 8
*d=a d++
a= 9
*d=a d++
a= 9
*d=a d++
a= 9
*d=a d++
a= 9
*d=a d++
a= 10
*d=a d++
a= 10
*d=a d++
a= 10
*d=a d++
a= 10
*d=a d++
a= 11
*d=a d++
a= 11
*d=a d++
a= 11
*d=a d++
a= 11
*d=a d++
a= 12
*d=a d++
a= 12
*d=a d++
a= 12
*d=a d++
a= 12
*d=a d++
a= 13
*d=a d++
a= 13
*d=a d++
a= 13
*d=a d++
a= 13
*d=a d++
a= 14
*d=a d++
a= 14
*d=a d++
a= 14
*d=a d++
a= 14
*d=a d++
a= 15
*d=a d++
a= 15
*d=a d++
a= 15
*d=a d++
a= 15
*d=a d++
a=r 91 d=a
a= 0
*d=a d++
a= 1
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 4
*d=a d++
a= 6
*d=a d++
a= 8
*d=a d++
a= 10
*d=a d++
a= 12
*d=a d++
a= 16
*d=a d++
a= 20
*d=a d++
a= 24
*d=a d++
a= 28
*d=a d++
a= 36
*d=a d++
a= 44
*d=a d++
a= 52
*d=a d++
a= 60
*d=a d++
a= 76
*d=a d++
a= 92
*d=a d++
a= 108
*d=a d++
a= 124
*d=a d++
a= 156
*d=a d++
a= 188
*d=a d++
a= 220
*d=a d++
a= 252
*d=a d++
a= 1
a<<= 8 a+= 60
*d=a d++
a= 1
a<<= 8 a+= 124
*d=a d++
a= 1
a<<= 8 a+= 188
*d=a d++
a= 1
a<<= 8 a+= 252
*d=a d++
a= 2
a<<= 8 a+= 124
*d=a d++
a= 2
a<<= 8 a+= 252
*d=a d++
a= 3
a<<= 8 a+= 124
*d=a d++
a= 3
a<<= 8 a+= 252
*d=a d++
a= 4
a<<= 8 a+= 252
*d=a d++
a= 5
a<<= 8 a+= 252
*d=a d++
a= 6
a<<= 8 a+= 252
*d=a d++
a= 7
a<<= 8 a+= 252
*d=a d++
a= 9
a<<= 8 a+= 252
*d=a d++
a= 11
a<<= 8 a+= 252
*d=a d++
a= 13
a<<= 8 a+= 252
*d=a d++
a= 15
a<<= 8 a+= 252
*d=a d++
a= 19
a<<= 8 a+= 252
*d=a d++
a= 23
a<<= 8 a+= 252
*d=a d++
a= 27
a<<= 8 a+= 252
*d=a d++
a= 31
a<<= 8 a+= 252
*d=a d++
a= 39
a<<= 8 a+= 252
*d=a d++
a= 47
a<<= 8 a+= 252
*d=a d++
a= 55
a<<= 8 a+= 252
*d=a d++
a= 63
a<<= 8 a+= 252
*d=a d++
a= 79
a<<= 8 a+= 252
*d=a d++
a= 95
a<<= 8 a+= 252
*d=a d++
a= 111
a<<= 8 a+= 252
*d=a d++
a= 127
a<<= 8 a+= 252
*d=a d++
a= 159
a<<= 8 a+= 252
*d=a d++
a= 191
a<<= 8 a+= 252
*d=a d++
a= 223
a<<= 8 a+= 252
*d=a d++
a= 255
a<<= 8 a+= 252
*d=a d++
a= 1
a<<= 8 a+= 63
a<<= 8 a+= 252
*d=a d++
a= 1
a<<= 8 a+= 127
a<<= 8 a+= 252
*d=a d++
a= 1
a<<= 8 a+= 191
a<<= 8 a+= 252
*d=a d++
a= 1
a<<= 8 a+= 255
a<<= 8 a+= 252
*d=a d++
a= 2
a<<= 8 a+= 127
a<<= 8 a+= 252
*d=a d++
a= 2
a<<= 8 a+= 255
a<<= 8 a+= 252
*d=a d++
a= 3
a<<= 8 a+= 127
a<<= 8 a+= 252
*d=a d++
a=r 92 d=a
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 5
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 8
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 5
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 14
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 5
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 8
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 5
*d=a d++
a= 2
*d=a d++
a= 3
*d=a d++
a= 2
*d=a d++
a= 14
*d=a d++
a=r 93 d=a
a= 0
*d=a d++
a= 2
*d=a d++
a= 1
*d=a d++
a= 4
*d=a d++
a= 0
*d=a d++
a= 3
*d=a d++
a= 1
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 2
*d=a d++
a= 1
*d=a d++
a= 5
*d=a d++
a= 0
*d=a d++
a= 3
*d=a d++
a= 1
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 2
*d=a d++
a= 1
*d=a d++
a= 6
*d=a d++
a= 0
*d=a d++
a= 3
*d=a d++
a= 1
*d=a d++
a= 0
*d=a d++
a= 0
*d=a d++
a= 2
*d=a d++
a= 1
*d=a d++
a= 7
*d=a d++
a= 0
*d=a d++
a= 3
*d=a d++
a= 1
*d=a d++
a= 0
*d=a d++
  a=r 1 a+= 64 r=a 5 a= 1 a<<= 16 a+= 64 b=r 1 a+=b r=a 3 r=a 4
  a=0 r=a 2 a= 1 r=a 7
  do
  a=r 2 a+= 4 b=r 1 a>b ifl a=0 r=a 7 endif
  a=r 7 a> 0 ifl
a=r 2 a+= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 8
a= 36
a<<= 8 a+= 120
a<<= 8 a+= 118
a<<= 8 a+= 98
    b=a a=r 8 a==b ifl
      a=0 r=a 7
    elsel
a=r 2 a+= 7 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 9
a= 45
a<<= 8 a+= 120
a<<= 8 a+= 118
a<<= 8 a+= 98
    b=a a=r 8 a==b ifl
      a=r 2 a+= 8 r=a 24
a=r 9 a> 0 ifl
  do
    a=r 24 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
    a=r 24 a++ r=a 24 a=r 9 a-- r=a 9
  a> 0 while
endif
      a=r 24 r=a 2
    elsel
a= 110
a<<= 8 a+= 120
a<<= 8 a+= 118
a<<= 8 a+= 98
    b=a a=r 8 a==b ifl
a=r 2 a+= 11 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c r=a 33
      a=r 2 a+= 12 r=a 2 b=r 33 a+=b r=a 33 a=0 r=a 23
      do
      a=r 2 b=r 33 a<b ifl
a=r 2 a+= 0 c=a a=*c
        r=a 24 a=0 r=a 25 r=a 26 r=a 27
        a=r 24 a== 6 ifl
          a=r 33 r=a 2
        elsel
        a=r 24 a== 14 ifl a=r 2 a++ r=a 2 elsel a=r 24 a== 22 ifl a=r 2 a++ r=a 2 elsel
        a=r 24 a> 239 ifl
          a== 240 ifl
a=r 2 a+= 1 c=a a=*c
            a+= 16 r=a 26 a=r 2 a+= 2 r=a 2
          elsel a&= 15 r=a 26 a=r 2 a++ r=a 2 endif
        elsel
        a=r 24 a> 223 ifl
          a== 224 ifl
a=r 2 a+= 1 c=a a=*c
            a+= 16 r=a 25 a=r 2 a+= 2 r=a 2
          elsel a&= 15 r=a 25 a=r 2 a++ r=a 2 endif
        elsel
        a=r 24 a> 159 ifl a< 192 ifl a= 1 elsel a=0 endif elsel a=0 endif
        a> 0 ifl
          a=r 24 a>>= 3 a&= 3 r=a 25
          a=r 2 a+= 2 c=a a=*c a<<= 8 c-- a+=*c r=a 28
          a=r 24 a&= 7 a<<= 2 r=a 26 a=r 28 a&= 3 b=r 26 a+=b a+= 3 r=a 26
          a=r 28 a>>= 2 r=a 28 a= 1 r=a 27 a=r 2 a+= 3 r=a 2
        elsel
          a=r 24 a>>= 6 r=a 25 a=r 24 a>>= 3 a&= 7 a+= 3 r=a 26
          a=r 24 a&= 7 a== 7 ifl
            a=r 2 a+= 2 c=a a=*c a<<= 8 c-- a+=*c r=a 28 a= 1 r=a 27 a=r 2 a+= 3 r=a 2
          elsel a== 6 ifl
            a=r 2 a++ r=a 2
          elsel
            a=r 24 a&= 7 a<<= 8 r=a 28
a=r 2 a+= 1 c=a a=*c
            b=r 28 a+=b r=a 28 a= 1 r=a 27 a=r 2 a+= 2 r=a 2
          endif endif
        endif
        endif
        endif
a=r 25 a> 0 ifl
  do
    a=r 2 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
    a=r 2 a++ r=a 2 a=r 25 a-- r=a 25
  a> 0 while
endif
        a=r 27 a> 0 ifl a=r 28 r=a 23 endif
a=r 26 a> 0 ifl
  a=r 4 b=r 23 a-=b r=a 30
  do
    a=r 30 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
    a=r 30 a++ r=a 30 a=r 26 a-- r=a 26
  a> 0 while
endif
        endif endif
        endif
      endif
      a=r 2 b=r 33
      a<b while
      a=r 33 r=a 2
    elsel
      a=r 2 a+= 8 r=a 52 a+= 24 r=a 51
a= 0 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 20 while
a=r 60 r=a 10
a= 20 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 20 while
a=r 60 r=a 11
a= 40 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 20 while
a=r 60 r=a 12
a= 60 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 3 while
a=r 60 r=a 32
a= 64 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 13
a= 74 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 14
a= 84 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 15
a= 94 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 16
a= 104 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 20 while
a=r 60 r=a 17
a= 124 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 3 while
a=r 60 r=a 18
a= 128 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 32 while
a=r 60 r=a 19
a= 160 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 20
a= 170 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 21
a= 180 r=a 50
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 10 while
a=r 60 r=a 22
      a=r 2 a+= 32 r=a 52 a=r 2 b=r 19 a+=b r=a 51 a=0 r=a 50 r=a 25
a= 1
a<<= 8 a+= 104
      r=a 24
      do
a=0 r=a 60 r=a 66
do
  a=r 50 b=r 66 a+=b r=a 67 a>>= 3 b=r 52 a+=b b=r 51 a<b ifl
    c=a a=r 67 a&= 7 b=a a=*c a>>=b a&= 1 b=r 66 a<<=b b=r 60 a|=b r=a 60
  endif
  a=r 66 a++ r=a 66
a< 14 while
        a=r 60 a&= 31 r=a 27
a=r 27 b=r 92 a+=b d=a a=*d
        r=a 26
        a== 8 ifl
          a=r 60 a>>= 4 a&= 15 a+= 8
        elsel a== 14 ifl
          a=r 60 a>>= 4 a&= 255 r=a 28 a=r 60 a>>= 12 a&= 3 a<<= 8 b=r 28 a+=b a+= 24
        elsel
a=r 27 b=r 93 a+=b d=a a=*d
        endif endif
        r=a 28
a=r 25 b=r 85 a+=b d=a a=r 28 *d=a
        a=r 50 b=r 26 a+=b r=a 50 a=r 25 a++ r=a 25 a=r 24 a-- r=a 24
      a> 0 while
a=0 r=a 24 r=a 25
do
  a=r 24 a+= 0 b=r 85 a+=b d=a a=*d r=a 26
  a> 0 ifl
a=0 r=a 27 a=r 26 a>>= 1
a> 0 ifl
  do
    r=a 69 a=r 27 a++ r=a 27 a=r 69 a>>= 1
  a> 0 while
endif
    a= 6 b=r 27 a-=b r=a 27
    a= 2 a<<= 6 b=r 27 a>>=b b=r 26 a-=b r=a 28
    a=0 r=a 29
    do
      a=r 29 b=r 28 a<b ifl
        a=r 27 r=a 30 a=r 26 b=r 29 a+=b b=r 27 a<<=b b=a a= 1 a<<= 6 r=a 31 a=b b=r 31 a-=b r=a 31
      elsel
        a=r 27 a-- r=a 30 a=r 29 b=r 28 a-=b b=r 30 a<<=b r=a 31
      endif
a=r 24 b=r 87 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 73 a+=b d=a a=r 69 *d=a
a=r 24 b=r 86 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 75 a+=b d=a a=r 69 *d=a
a=r 25 b=r 74 a+=b d=a a=r 30 *d=a
a=r 25 b=r 76 a+=b d=a a=r 31 *d=a
      a=r 25 a++ r=a 25 a=r 29 a++ r=a 29 b=r 26
    a<b while
  endif
  a=r 24 a++ r=a 24
a< 20 while
a=0 r=a 24 r=a 25
do
  a=r 24 a+= 20 b=r 85 a+=b d=a a=*d r=a 26
  a> 0 ifl
a=0 r=a 27 a=r 26 a>>= 1
a> 0 ifl
  do
    r=a 69 a=r 27 a++ r=a 27 a=r 69 a>>= 1
  a> 0 while
endif
    a= 6 b=r 27 a-=b r=a 27
    a= 2 a<<= 6 b=r 27 a>>=b b=r 26 a-=b r=a 28
    a=0 r=a 29
    do
      a=r 29 b=r 28 a<b ifl
        a=r 27 r=a 30 a=r 26 b=r 29 a+=b b=r 27 a<<=b b=a a= 1 a<<= 6 r=a 31 a=b b=r 31 a-=b r=a 31
      elsel
        a=r 27 a-- r=a 30 a=r 29 b=r 28 a-=b b=r 30 a<<=b r=a 31
      endif
a=r 24 b=r 89 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 77 a+=b d=a a=r 69 *d=a
a=r 24 b=r 88 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 79 a+=b d=a a=r 69 *d=a
a=r 25 b=r 78 a+=b d=a a=r 30 *d=a
a=r 25 b=r 80 a+=b d=a a=r 31 *d=a
      a=r 25 a++ r=a 25 a=r 29 a++ r=a 29 b=r 26
    a<b while
  endif
  a=r 24 a++ r=a 24
a< 20 while
a=0 r=a 24 r=a 25
do
  a=r 24 a+= 40 b=r 85 a+=b d=a a=*d r=a 26
  a> 0 ifl
a=0 r=a 27 a=r 26 a>>= 1
a> 0 ifl
  do
    r=a 69 a=r 27 a++ r=a 27 a=r 69 a>>= 1
  a> 0 while
endif
    a= 8 b=r 27 a-=b r=a 27
    a= 2 a<<= 8 b=r 27 a>>=b b=r 26 a-=b r=a 28
    a=0 r=a 29
    do
      a=r 29 b=r 28 a<b ifl
        a=r 27 r=a 30 a=r 26 b=r 29 a+=b b=r 27 a<<=b b=a a= 1 a<<= 8 r=a 31 a=b b=r 31 a-=b r=a 31
      elsel
        a=r 27 a-- r=a 30 a=r 29 b=r 28 a-=b b=r 30 a<<=b r=a 31
      endif
a=r 24 b=r 91 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 81 a+=b d=a a=r 69 *d=a
a=r 24 b=r 90 a+=b d=a a=*d
      r=a 69
a=r 25 b=r 83 a+=b d=a a=r 69 *d=a
a=r 25 b=r 82 a+=b d=a a=r 30 *d=a
a=r 25 b=r 84 a+=b d=a a=r 31 *d=a
      a=r 25 a++ r=a 25 a=r 29 a++ r=a 29 b=r 26
    a<b while
  endif
  a=r 24 a++ r=a 24
a< 64 while
a=0 r=a 24 r=a 25
do
  a=r 24 a+= 104 b=r 85 a+=b d=a a=*d r=a 26
  a> 0 ifl
a=0 r=a 27 a=r 26 a>>= 1
a> 0 ifl
  do
    r=a 69 a=r 27 a++ r=a 27 a=r 69 a>>= 1
  a> 0 while
endif
    a= 10 b=r 27 a-=b r=a 27
    a= 2 a<<= 10 b=r 27 a>>=b b=r 26 a-=b r=a 28
    a=0 r=a 29
    do
      a=r 29 b=r 28 a<b ifl
        a=r 27 r=a 30 a=r 26 b=r 29 a+=b b=r 27 a<<=b b=a a= 1 a<<= 10 r=a 31 a=b b=r 31 a-=b r=a 31
      elsel
        a=r 27 a-- r=a 30 a=r 29 b=r 28 a-=b b=r 30 a<<=b r=a 31
      endif
a=r 25 b=r 70 a+=b d=a a=r 24 *d=a
a=r 25 b=r 71 a+=b d=a a=r 30 *d=a
a=r 25 b=r 72 a+=b d=a a=r 31 *d=a
      a=r 25 a++ r=a 25 a=r 29 a++ r=a 29 b=r 26
    a<b while
  endif
  a=r 24 a++ r=a 24
a> 255 until
      a=r 2 b=r 19 a+=b r=a 2 r=a 41 a=r 11 a<<= 3 b=r 32 a+=b a-= 7 r=a 40
      a=r 5 r=a 6 a=r 10 r=a 25
      a> 0 ifl
      do
a=r 13 b=r 70 a+=b d=a a=*d
        c=r 6 *c=a a=c a++ r=a 6
a=r 13 b=r 71 a+=b d=a a=*d
        r=a 26
a=0 r=a 27 a=r 26 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 27 a<<= 1 a+=b r=a 27
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 13 b=r 72 a+=b d=a a=*d
        b=r 27 a+=b r=a 13
a=r 14 b=r 70 a+=b d=a a=*d
        c=r 6 *c=a a=c a++ r=a 6
a=r 14 b=r 71 a+=b d=a a=*d
        r=a 26
a=0 r=a 27 a=r 26 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 27 a<<= 1 a+=b r=a 27
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 14 b=r 72 a+=b d=a a=*d
        b=r 27 a+=b r=a 14
a=r 15 b=r 70 a+=b d=a a=*d
        c=r 6 *c=a a=c a++ r=a 6
a=r 15 b=r 71 a+=b d=a a=*d
        r=a 26
a=0 r=a 27 a=r 26 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 27 a<<= 1 a+=b r=a 27
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 15 b=r 72 a+=b d=a a=*d
        b=r 27 a+=b r=a 15
a=r 16 b=r 70 a+=b d=a a=*d
        c=r 6 *c=a a=c a++ r=a 6
a=r 16 b=r 71 a+=b d=a a=*d
        r=a 26
a=0 r=a 27 a=r 26 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 27 a<<= 1 a+=b r=a 27
    a=r 67 a-- r=a 67
  a> 0 while
endif
a=r 16 b=r 72 a+=b d=a a=*d
        b=r 27 a+=b r=a 16
        a=r 25 a-= 4 r=a 25
      a> 0 while
      endif
      a=r 2 b=r 11 a+=b r=a 41 a=r 17 a<<= 3 b=r 18 a+=b a-= 7 r=a 40
      a=r 5 r=a 6 a=0 r=a 23 a=r 12 r=a 25
      a> 0 ifl
      do
a=r 20 b=r 74 a+=b d=a a=*d
r=a 26
a=r 20 b=r 75 a+=b d=a a=*d
r=a 27 b=r 26 a+=b r=a 28
a=0 r=a 29 a=r 28 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 29 a<<= 1 a+=b r=a 29
    a=r 67 a-- r=a 67
  a> 0 while
endif
a= 1 b=r 27 a<<=b a-- b=r 29 a&=b r=a 30
a=r 20 b=r 73 a+=b d=a a=*d
b=r 30 a+=b r=a 35
a=r 29 b=r 27 a>>=b r=a 30
a=r 20 b=r 76 a+=b d=a a=*d
b=r 30 a+=b r=a 20
a=r 21 b=r 78 a+=b d=a a=*d
r=a 26
a=r 21 b=r 79 a+=b d=a a=*d
r=a 27 b=r 26 a+=b r=a 28
a=0 r=a 29 a=r 28 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 29 a<<= 1 a+=b r=a 29
    a=r 67 a-- r=a 67
  a> 0 while
endif
a= 1 b=r 27 a<<=b a-- b=r 29 a&=b r=a 30
a=r 21 b=r 77 a+=b d=a a=*d
b=r 30 a+=b r=a 36
a=r 29 b=r 27 a>>=b r=a 30
a=r 21 b=r 80 a+=b d=a a=*d
b=r 30 a+=b r=a 21
a=r 22 b=r 82 a+=b d=a a=*d
r=a 26
a=r 22 b=r 83 a+=b d=a a=*d
r=a 27 b=r 26 a+=b r=a 28
a=0 r=a 29 a=r 28 r=a 67
a> 0 ifl
  do
    a=r 40 a-- r=a 40 a>>= 3 b=r 41 a+=b c=a a=r 40 a&= 7 b=a a=*c a>>=b a&= 1
    b=a a=r 29 a<<= 1 a+=b r=a 29
    a=r 67 a-- r=a 67
  a> 0 while
endif
a= 1 b=r 27 a<<=b a-- b=r 29 a&=b r=a 30
a=r 22 b=r 81 a+=b d=a a=*d
b=r 30 a+=b r=a 37
a=r 29 b=r 27 a>>=b r=a 30
a=r 22 b=r 84 a+=b d=a a=*d
b=r 30 a+=b r=a 22
        a=r 37 a> 0 ifl r=a 23 endif
a=r 35 a> 0 ifl
  do
    a=r 6 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
    a=r 6 a++ r=a 6 a=r 35 a-- r=a 35
  a> 0 while
endif
a=r 36 a> 0 ifl
  a=r 4 b=r 23 a-=b r=a 30
  do
    a=r 30 c=a a=*c
c=r 4 *c=a out a=c a++ r=a 4
    a=r 30 a++ r=a 30 a=r 36 a-- r=a 36
  a> 0 while
endif
        a=r 25 a-- r=a 25
      a> 0 while
      endif
      a=r 2 b=r 11 a+=b b=r 17 a+=b r=a 2
    endif
    endif
    endif
  endif
  a=r 7
  a> 0 while
  a=0 c=a
elsel
  *c=a c++
endif
halt
end
)ZLZF";
