# Generador de ZPAQDEFLATE: decodificador de deflate crudo en ZPAQL.
# ZPAQL no tiene subrutinas: las macros se expanden en linea.
LCNT,LSYM,DCNT,DSYM,CCNT,CSYM,LENS,LBASE,LEXT,DBASE,DEXT,ORDER,OFFS,CLL=0,16,320,336,384,400,448,768,800,832,864,896,928,960
out=[]
def e(s): out.append(s)
def C(v):            # a = v (las constantes inmediatas de ZPAQL van de 0 a 255)
    if v<256: return f"a= {v}"
    return f"a= {v>>8} a<<= 8 a+= {v&255}"
def GETBITS_REG():   # r10 = los r9 bits siguientes (LSB primero); r2 buffer, r3 cuenta, r4 puntero
    e("a=r 3 b=r 9 a<b ifl")
    e("  do")
    e("    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2")
    e("    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9")
    e("  a<b while")
    e("endif")
    e("a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10")
    e("a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3")
def GETBITS(n):
    e(f"a= {n} r=a 9"); GETBITS_REG()
def DECODE(cnt,sym):  # r21 = simbolo, Huffman canonico bit a bit
    e("a=0 r=a 16 r=a 17 r=a 18 a= 1 r=a 19")
    e("do")
    GETBITS(1)
    e("  a=r 16 b=r 10 a|=b r=a 16")
    e(f"  {C(cnt)} b=r 19 a+=b d=a a=*d r=a 20")
    e("  a=r 17 b=r 20 a+=b b=a a=r 16 a<b ifl")
    e(f"    a=r 16 b=r 17 a-=b b=r 18 a+=b b=a {C(sym)} a+=b d=a a=*d r=a 21")
    e("    a= 16 r=a 19")
    e("  elsel")
    e("    a=r 18 b=r 20 a+=b r=a 18")
    e("    a=r 17 b=r 20 a+=b a<<= 1 r=a 17")
    e("    a=r 16 a<<= 1 r=a 16 a=r 19 a++ r=a 19")
    e("  endif")
    e("  a=r 19")
    e("a< 16 while")
def BUILD(ptrreg,nreg,cnt,sym):  # tabla canonica desde LENS[r ptr .. +n)
    e(f"{C(cnt)} d=a")
    for i in range(16): e("a=0 *d=a d++")
    e("a=0 r=a 40")
    e("do")
    e(f"  a=r {ptrreg} b=r 40 a+=b d=a a=*d b=a {C(cnt)} a+=b d=a a=*d a++ *d=a")
    e(f"  a=r 40 a++ r=a 40 b=r {nreg}")
    e("a<b while")
    e("a=0 r=a 41 a= 1 r=a 42")
    e("do")
    e(f"  {C(OFFS)} b=r 42 a+=b d=a a=r 41 *d=a")
    e(f"  {C(cnt)} b=r 42 a+=b d=a a=*d b=r 41 a+=b r=a 41")
    e("  a=r 42 a++ r=a 42")
    e("a< 16 while")
    e("a=0 r=a 40")
    e("do")
    e(f"  a=r {ptrreg} b=r 40 a+=b d=a a=*d")
    e("  a> 0 ifl")
    e(f"    b=a {C(OFFS)} a+=b r=a 43 d=a a=*d r=a 44 a++ *d=a")
    e(f"    a=r 44 b=a {C(sym)} a+=b d=a a=r 40 *d=a")
    e("  endif")
    e(f"  a=r 40 a++ r=a 40 b=r {nreg}")
    e("a<b while")

e("hcomp")
e("halt")
e("pcomp zpaqdeflate ;")
e("""(ZPAQDEFLATE: decodificador de deflate crudo, RFC 1951, en ZPAQL, para zpaq-std
 -ma:deflate. zpaq-std, 2026. Huffman canonico decodificado bit a bit con conteos
 por largo, el metodo de puff de Mark Adler, reescrito en ZPAQL: sin tablas grandes.
 Entrada: tamano original, 4 bytes LE, y el deflate. M: la salida al principio, el
 comprimido detras, desde M[tamano]. H: tablas de Huffman, bases y bits extra.
 r2 buffer de bits, r3 bits en el, r4 puntero de entrada, r5 puntero de salida,
 r6 tamano, r7 ultimo bloque, r8 tipo, r9 bits pedidos, r10 valor leido,
 r16..r21 decodificacion, r22 largos de literal, r23 de distancia, r24 de codigos,
 r25 indice, r28 largo, r29 distancia, r30 fin de bloque, r31 fase.)""")
e("*c=a c++")
e("d=a")
e("a=r 31")
e("a< 2 ifl")
e("  a== 0 ifl")
e("    a=c a< 4 ifl")
e("      halt")
e("    elsel")
e("      a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c")
e("      r=a 6 r=a 4 c=a a= 1 r=a 31")
e("      halt")
e("    endif")
e("  elsel")
e("    a=d a> 255 if a= 2 r=a 31 endif")
e("    a=r 31 a== 1 if halt endif")
e("  endif")
e("endif")
e("a== 2 ifnot halt endif")
# tablas de bases y bits extra
e("a=0 r=a 40 a= 3 r=a 41")
e("do")
e("  a=r 40 a< 8 if a=0 else a-= 4 a>>= 2 endif r=a 42")
e(f"  {C(LEXT)} b=r 40 a+=b d=a a=r 42 *d=a")
e(f"  {C(LBASE)} b=r 40 a+=b d=a a=r 41 *d=a")
e("  a= 1 c=r 42 a<<=c b=r 41 a+=b r=a 41 a=r 40 a++ r=a 40")
e("a< 28 while")
e(f"{C(LBASE+28)} d=a {C(258)} *d=a {C(LEXT+28)} d=a a=0 *d=a")
e("a=0 r=a 40 a= 1 r=a 41")
e("do")
e("  a=r 40 a< 4 if a=0 else a-= 2 a>>= 1 endif r=a 42")
e(f"  {C(DEXT)} b=r 40 a+=b d=a a=r 42 *d=a")
e(f"  {C(DBASE)} b=r 40 a+=b d=a a=r 41 *d=a")
e("  a= 1 c=r 42 a<<=c b=r 41 a+=b r=a 41 a=r 40 a++ r=a 40")
e("a< 30 while")
for i,v in enumerate([16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15]):
    e(f"{C(ORDER+i)} d=a a= {v} *d=a")
e("a=0 r=a 2 r=a 3 r=a 5")
e(f"{C(LENS)} r=a 45")          # r45 = LENS (puntero de los largos de literal)
e(f"{C(CLL)} r=a 46")           # r46 = CLL
e("do")                         # un bloque deflate por vuelta
GETBITS(1); e("a=r 10 r=a 7")
GETBITS(2); e("a=r 10 r=a 8")
e("a=r 8")
e("a== 0 ifl")                  # bloque guardado
e("  a=0 r=a 2 r=a 3")
e("  c=r 4 a=*c c++ b=a a=*c a<<= 8 a+=b r=a 9 c++ c++ c++ a=c r=a 4")
e("  a=r 9 a> 0 ifl")
e("    do")
e("      c=r 4 a=*c c=r 5 *c=a out")
e("      a=r 4 a++ r=a 4 a=r 5 a++ r=a 5 a=r 9 a-- r=a 9")
e("    a> 0 while")
e("  endif")
e("elsel")
e("  a== 1 ifl")                # Huffman fijo
e(f"    {C(LENS)} d=a a=0 r=a 40")
e("    do")
e("      a=r 40 a< 144 if a= 8 else a> 255 if a= 1 a<<= 8 a+= 24 b=a a=r 40 a<b if a= 7 else a= 8 endif else a= 9 endif endif")
e("      *d=a d++ a=r 40 a++ r=a 40 b=a a= 1 a<<= 8 a+= 32 b<>a a<b")
e("    while")
e("    a=0 r=a 40")
e("    do")
e("      a= 5 *d=a d++ a=r 40 a++ r=a 40")
e("    a< 30 while")
e(f"    {C(288)} r=a 22 a= 30 r=a 23")
e("  elsel")                    # Huffman dinamico
GETBITS(5); e(f"  a=r 10 {'b=a'} {C(257)} a+=b r=a 22")
GETBITS(5); e("  a=r 10 a++ r=a 23")
GETBITS(4); e("  a=r 10 a+= 4 r=a 24")
e(f"  {C(CLL)} d=a")
for i in range(19): e("  a=0 *d=a d++")
e("  a=0 r=a 25")
e("  do")
GETBITS(3)
e(f"    {C(ORDER)} b=r 25 a+=b d=a a=*d b=a {C(CLL)} a+=b d=a a=r 10 *d=a")
e("    a=r 25 a++ r=a 25 b=r 24")
e("  a<b while")
e("  a= 19 r=a 47")
BUILD(46,47,CCNT,CSYM)
e("  a=r 22 b=r 23 a+=b r=a 48")      # r48 = total de largos
e("  a=0 r=a 25")
e("  do")
DECODE(CCNT,CSYM)
e("    a=r 21 a< 16 ifl")
e("      a=r 45 b=r 25 a+=b d=a a=r 21 *d=a a=r 25 a++ r=a 25")
e("    elsel")
e("      a== 16 ifl")
GETBITS(2)
e("        a=r 10 a+= 3 r=a 27 a=r 45 b=r 25 a+=b a-- d=a a=*d r=a 26")
e("      elsel")
e("        a== 17 ifl")
GETBITS(3)
e("          a=r 10 a+= 3 r=a 27 a=0 r=a 26")
e("        elsel")
GETBITS(7)
e("          a=r 10 a+= 11 r=a 27 a=0 r=a 26")
e("        endif")
e("      endif")
e("      do")
e("        a=r 45 b=r 25 a+=b d=a a=r 26 *d=a a=r 25 a++ r=a 25 a=r 27 a-- r=a 27")
e("      a> 0 while")
e("    endif")
e("    a=r 25 b=r 48")
e("  a<b while")
e("  endif")
e("endif")
e("a=r 8 a> 0 ifl")               # tablas de Huffman y simbolos (fijo o dinamico)
e("  a=r 22 r=a 49")
BUILD(45,49,LCNT,LSYM)
e("  a=r 45 b=r 22 a+=b r=a 50 a=r 23 r=a 51")
BUILD(50,51,DCNT,DSYM)
e("  a=0 r=a 30")
e("  do")
DECODE(LCNT,LSYM)
e("    a=r 21 a< 128 ifl")          # (dividido para que el salto corto alcance)
e("      c=r 5 *c=a out a=r 5 a++ r=a 5")
e("    elsel")
e("      a< 255 ifl")
e("        c=r 5 *c=a out a=r 5 a++ r=a 5")
e("      elsel")
e("        a== 255 ifl")
e("          c=r 5 *c=a out a=r 5 a++ r=a 5")
e("        elsel")
e("          a-= 255 a-- a== 0 ifl")
e("            a= 1 r=a 30")
e("          elsel")
e("            a-- r=a 32")          # r32 = s - 257
e(f"            {C(LEXT)} b=r 32 a+=b d=a a=*d r=a 9")
GETBITS_REG()
e(f"            {C(LBASE)} b=r 32 a+=b d=a a=*d b=r 10 a+=b r=a 28")
DECODE(DCNT,DSYM)
e(f"            {C(DEXT)} b=r 21 a+=b d=a a=*d r=a 9")
GETBITS_REG()
e(f"            {C(DBASE)} b=r 21 a+=b d=a a=*d b=r 10 a+=b r=a 29")
e("            a=r 5 b=r 29 a-=b r=a 33")
e("            do")
e("              c=r 33 a=*c c=r 5 *c=a out")
e("              a=r 33 a++ r=a 33 a=r 5 a++ r=a 5 a=r 28 a-- r=a 28")
e("            a> 0 while")
e("          endif")
e("        endif")
e("      endif")
e("    endif")
e("    a=r 30")
e("  a== 0 while")
e("endif")
e("a=r 7")
e("a== 0 while")
e("a= 3 r=a 31")
e("halt")
e("end")
import sys
open(sys.argv[1],'w').write('\n'.join(out)+'\n')
print(len('\n'.join(out)))
