/*
  ZPAQDEFLATE: a raw DEFLATE (RFC 1951) decoder written in ZPAQL, for zpaq-std
  -ma:deflate. zpaq-std, 2026. Generated by gen.py next to this file (ZPAQL has
  no subroutines: bit reading, Huffman decoding and table building are macros
  expanded in place).

  Canonical Huffman decoded one bit at a time from per-length counts: the
  method of Mark Adler's puff.c, rewritten in ZPAQL. Stored, fixed and dynamic
  blocks. Input: original size (4 bytes LE), then the deflate stream. M holds
  the whole output, then the compressed data behind it.

  Verified with zpaqd 7.15 on 143 libdeflate streams: 11 inputs x levels 0-12,
  all three block types among them.

  FROZEN, like the other portable decoders: every block carries its own copy
  and zpaq-std recognises it byte for byte. A different program gets a new tag.
*/
static const char ZPAQDEFLATE_CUERPO[] = R"ZDFL(hcomp
halt
pcomp zpaqdeflate ;
(ZPAQDEFLATE: decodificador de deflate crudo, RFC 1951, en ZPAQL, para zpaq-std
 -ma:deflate. zpaq-std, 2026. Huffman canonico decodificado bit a bit con conteos
 por largo, el metodo de puff de Mark Adler, reescrito en ZPAQL: sin tablas grandes.
 Entrada: tamano original, 4 bytes LE, y el deflate. M: la salida al principio, el
 comprimido detras, desde M[tamano]. H: tablas de Huffman, bases y bits extra.
 r2 buffer de bits, r3 bits en el, r4 puntero de entrada, r5 puntero de salida,
 r6 tamano, r7 ultimo bloque, r8 tipo, r9 bits pedidos, r10 valor leido,
 r16..r21 decodificacion, r22 largos de literal, r23 de distancia, r24 de codigos,
 r25 indice, r28 largo, r29 distancia, r30 fin de bloque, r31 fase.)
*c=a c++
d=a
a=r 31
a< 2 ifl
  a== 0 ifl
    a=c a< 4 ifl
      halt
    elsel
      a= 3 c=a a=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c a<<= 8 c-- a+=*c
      r=a 6 r=a 4 c=a a= 1 r=a 31
      halt
    endif
  elsel
    a=d a> 255 if a= 2 r=a 31 endif
    a=r 31 a== 1 if halt endif
  endif
endif
a== 2 ifnot halt endif
a=0 r=a 40 a= 3 r=a 41
do
  a=r 40 a< 8 if a=0 else a-= 4 a>>= 2 endif r=a 42
  a= 3 a<<= 8 a+= 32 b=r 40 a+=b d=a a=r 42 *d=a
  a= 3 a<<= 8 a+= 0 b=r 40 a+=b d=a a=r 41 *d=a
  a= 1 c=r 42 a<<=c b=r 41 a+=b r=a 41 a=r 40 a++ r=a 40
a< 28 while
a= 3 a<<= 8 a+= 28 d=a a= 1 a<<= 8 a+= 2 *d=a a= 3 a<<= 8 a+= 60 d=a a=0 *d=a
a=0 r=a 40 a= 1 r=a 41
do
  a=r 40 a< 4 if a=0 else a-= 2 a>>= 1 endif r=a 42
  a= 3 a<<= 8 a+= 96 b=r 40 a+=b d=a a=r 42 *d=a
  a= 3 a<<= 8 a+= 64 b=r 40 a+=b d=a a=r 41 *d=a
  a= 1 c=r 42 a<<=c b=r 41 a+=b r=a 41 a=r 40 a++ r=a 40
a< 30 while
a= 3 a<<= 8 a+= 128 d=a a= 16 *d=a
a= 3 a<<= 8 a+= 129 d=a a= 17 *d=a
a= 3 a<<= 8 a+= 130 d=a a= 18 *d=a
a= 3 a<<= 8 a+= 131 d=a a= 0 *d=a
a= 3 a<<= 8 a+= 132 d=a a= 8 *d=a
a= 3 a<<= 8 a+= 133 d=a a= 7 *d=a
a= 3 a<<= 8 a+= 134 d=a a= 9 *d=a
a= 3 a<<= 8 a+= 135 d=a a= 6 *d=a
a= 3 a<<= 8 a+= 136 d=a a= 10 *d=a
a= 3 a<<= 8 a+= 137 d=a a= 5 *d=a
a= 3 a<<= 8 a+= 138 d=a a= 11 *d=a
a= 3 a<<= 8 a+= 139 d=a a= 4 *d=a
a= 3 a<<= 8 a+= 140 d=a a= 12 *d=a
a= 3 a<<= 8 a+= 141 d=a a= 3 *d=a
a= 3 a<<= 8 a+= 142 d=a a= 13 *d=a
a= 3 a<<= 8 a+= 143 d=a a= 2 *d=a
a= 3 a<<= 8 a+= 144 d=a a= 14 *d=a
a= 3 a<<= 8 a+= 145 d=a a= 1 *d=a
a= 3 a<<= 8 a+= 146 d=a a= 15 *d=a
a=0 r=a 2 r=a 3 r=a 5
a= 1 a<<= 8 a+= 192 r=a 45
a= 3 a<<= 8 a+= 192 r=a 46
do
a= 1 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
a=r 10 r=a 7
a= 2 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
a=r 10 r=a 8
a=r 8
a== 0 ifl
  a=0 r=a 2 r=a 3
  c=r 4 a=*c c++ b=a a=*c a<<= 8 a+=b r=a 9 c++ c++ c++ a=c r=a 4
  a=r 9 a> 0 ifl
    do
      c=r 4 a=*c c=r 5 *c=a out
      a=r 4 a++ r=a 4 a=r 5 a++ r=a 5 a=r 9 a-- r=a 9
    a> 0 while
  endif
elsel
  a== 1 ifl
    a= 1 a<<= 8 a+= 192 d=a a=0 r=a 40
    do
      a=r 40 a< 144 if a= 8 else a> 255 if a= 1 a<<= 8 a+= 24 b=a a=r 40 a<b if a= 7 else a= 8 endif else a= 9 endif endif
      *d=a d++ a=r 40 a++ r=a 40 b=a a= 1 a<<= 8 a+= 32 b<>a a<b
    while
    a=0 r=a 40
    do
      a= 5 *d=a d++ a=r 40 a++ r=a 40
    a< 30 while
    a= 1 a<<= 8 a+= 32 r=a 22 a= 30 r=a 23
  elsel
a= 5 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 10 b=a a= 1 a<<= 8 a+= 1 a+=b r=a 22
a= 5 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 10 a++ r=a 23
a= 4 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 10 a+= 4 r=a 24
  a= 3 a<<= 8 a+= 192 d=a
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 *d=a d++
  a=0 r=a 25
  do
a= 3 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
    a= 3 a<<= 8 a+= 128 b=r 25 a+=b d=a a=*d b=a a= 3 a<<= 8 a+= 192 a+=b d=a a=r 10 *d=a
    a=r 25 a++ r=a 25 b=r 24
  a<b while
  a= 19 r=a 47
a= 1 a<<= 8 a+= 128 d=a
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 r=a 40
do
  a=r 46 b=r 40 a+=b d=a a=*d b=a a= 1 a<<= 8 a+= 128 a+=b d=a a=*d a++ *d=a
  a=r 40 a++ r=a 40 b=r 47
a<b while
a=0 r=a 41 a= 1 r=a 42
do
  a= 3 a<<= 8 a+= 160 b=r 42 a+=b d=a a=r 41 *d=a
  a= 1 a<<= 8 a+= 128 b=r 42 a+=b d=a a=*d b=r 41 a+=b r=a 41
  a=r 42 a++ r=a 42
a< 16 while
a=0 r=a 40
do
  a=r 46 b=r 40 a+=b d=a a=*d
  a> 0 ifl
    b=a a= 3 a<<= 8 a+= 160 a+=b r=a 43 d=a a=*d r=a 44 a++ *d=a
    a=r 44 b=a a= 1 a<<= 8 a+= 144 a+=b d=a a=r 40 *d=a
  endif
  a=r 40 a++ r=a 40 b=r 47
a<b while
  a=r 22 b=r 23 a+=b r=a 48
  a=0 r=a 25
  do
a=0 r=a 16 r=a 17 r=a 18 a= 1 r=a 19
do
a= 1 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 16 b=r 10 a|=b r=a 16
  a= 1 a<<= 8 a+= 128 b=r 19 a+=b d=a a=*d r=a 20
  a=r 17 b=r 20 a+=b b=a a=r 16 a<b ifl
    a=r 16 b=r 17 a-=b b=r 18 a+=b b=a a= 1 a<<= 8 a+= 144 a+=b d=a a=*d r=a 21
    a= 16 r=a 19
  elsel
    a=r 18 b=r 20 a+=b r=a 18
    a=r 17 b=r 20 a+=b a<<= 1 r=a 17
    a=r 16 a<<= 1 r=a 16 a=r 19 a++ r=a 19
  endif
  a=r 19
a< 16 while
    a=r 21 a< 16 ifl
      a=r 45 b=r 25 a+=b d=a a=r 21 *d=a a=r 25 a++ r=a 25
    elsel
      a== 16 ifl
a= 2 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
        a=r 10 a+= 3 r=a 27 a=r 45 b=r 25 a+=b a-- d=a a=*d r=a 26
      elsel
        a== 17 ifl
a= 3 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
          a=r 10 a+= 3 r=a 27 a=0 r=a 26
        elsel
a= 7 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
          a=r 10 a+= 11 r=a 27 a=0 r=a 26
        endif
      endif
      do
        a=r 45 b=r 25 a+=b d=a a=r 26 *d=a a=r 25 a++ r=a 25 a=r 27 a-- r=a 27
      a> 0 while
    endif
    a=r 25 b=r 48
  a<b while
  endif
endif
a=r 8 a> 0 ifl
  a=r 22 r=a 49
a= 0 d=a
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 r=a 40
do
  a=r 45 b=r 40 a+=b d=a a=*d b=a a= 0 a+=b d=a a=*d a++ *d=a
  a=r 40 a++ r=a 40 b=r 49
a<b while
a=0 r=a 41 a= 1 r=a 42
do
  a= 3 a<<= 8 a+= 160 b=r 42 a+=b d=a a=r 41 *d=a
  a= 0 b=r 42 a+=b d=a a=*d b=r 41 a+=b r=a 41
  a=r 42 a++ r=a 42
a< 16 while
a=0 r=a 40
do
  a=r 45 b=r 40 a+=b d=a a=*d
  a> 0 ifl
    b=a a= 3 a<<= 8 a+= 160 a+=b r=a 43 d=a a=*d r=a 44 a++ *d=a
    a=r 44 b=a a= 16 a+=b d=a a=r 40 *d=a
  endif
  a=r 40 a++ r=a 40 b=r 49
a<b while
  a=r 45 b=r 22 a+=b r=a 50 a=r 23 r=a 51
a= 1 a<<= 8 a+= 64 d=a
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 *d=a d++
a=0 r=a 40
do
  a=r 50 b=r 40 a+=b d=a a=*d b=a a= 1 a<<= 8 a+= 64 a+=b d=a a=*d a++ *d=a
  a=r 40 a++ r=a 40 b=r 51
a<b while
a=0 r=a 41 a= 1 r=a 42
do
  a= 3 a<<= 8 a+= 160 b=r 42 a+=b d=a a=r 41 *d=a
  a= 1 a<<= 8 a+= 64 b=r 42 a+=b d=a a=*d b=r 41 a+=b r=a 41
  a=r 42 a++ r=a 42
a< 16 while
a=0 r=a 40
do
  a=r 50 b=r 40 a+=b d=a a=*d
  a> 0 ifl
    b=a a= 3 a<<= 8 a+= 160 a+=b r=a 43 d=a a=*d r=a 44 a++ *d=a
    a=r 44 b=a a= 1 a<<= 8 a+= 80 a+=b d=a a=r 40 *d=a
  endif
  a=r 40 a++ r=a 40 b=r 51
a<b while
  a=0 r=a 30
  do
a=0 r=a 16 r=a 17 r=a 18 a= 1 r=a 19
do
a= 1 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 16 b=r 10 a|=b r=a 16
  a= 0 b=r 19 a+=b d=a a=*d r=a 20
  a=r 17 b=r 20 a+=b b=a a=r 16 a<b ifl
    a=r 16 b=r 17 a-=b b=r 18 a+=b b=a a= 16 a+=b d=a a=*d r=a 21
    a= 16 r=a 19
  elsel
    a=r 18 b=r 20 a+=b r=a 18
    a=r 17 b=r 20 a+=b a<<= 1 r=a 17
    a=r 16 a<<= 1 r=a 16 a=r 19 a++ r=a 19
  endif
  a=r 19
a< 16 while
    a=r 21 a< 128 ifl
      c=r 5 *c=a out a=r 5 a++ r=a 5
    elsel
      a< 255 ifl
        c=r 5 *c=a out a=r 5 a++ r=a 5
      elsel
        a== 255 ifl
          c=r 5 *c=a out a=r 5 a++ r=a 5
        elsel
          a-= 255 a-- a== 0 ifl
            a= 1 r=a 30
          elsel
            a-- r=a 32
            a= 3 a<<= 8 a+= 32 b=r 32 a+=b d=a a=*d r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
            a= 3 a<<= 8 a+= 0 b=r 32 a+=b d=a a=*d b=r 10 a+=b r=a 28
a=0 r=a 16 r=a 17 r=a 18 a= 1 r=a 19
do
a= 1 r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
  a=r 16 b=r 10 a|=b r=a 16
  a= 1 a<<= 8 a+= 64 b=r 19 a+=b d=a a=*d r=a 20
  a=r 17 b=r 20 a+=b b=a a=r 16 a<b ifl
    a=r 16 b=r 17 a-=b b=r 18 a+=b b=a a= 1 a<<= 8 a+= 80 a+=b d=a a=*d r=a 21
    a= 16 r=a 19
  elsel
    a=r 18 b=r 20 a+=b r=a 18
    a=r 17 b=r 20 a+=b a<<= 1 r=a 17
    a=r 16 a<<= 1 r=a 16 a=r 19 a++ r=a 19
  endif
  a=r 19
a< 16 while
            a= 3 a<<= 8 a+= 96 b=r 21 a+=b d=a a=*d r=a 9
a=r 3 b=r 9 a<b ifl
  do
    c=r 4 a=*c c=r 3 a<<=c b=r 2 a|=b r=a 2
    a=r 4 a++ r=a 4 a=r 3 a+= 8 r=a 3 b=r 9
  a<b while
endif
a= 1 c=r 9 a<<=c a-- b=a a=r 2 a&=b r=a 10
a=r 2 c=r 9 a>>=c r=a 2 a=r 3 b=r 9 a-=b r=a 3
            a= 3 a<<= 8 a+= 64 b=r 21 a+=b d=a a=*d b=r 10 a+=b r=a 29
            a=r 5 b=r 29 a-=b r=a 33
            do
              c=r 33 a=*c c=r 5 *c=a out
              a=r 33 a++ r=a 33 a=r 5 a++ r=a 5 a=r 28 a-- r=a 28
            a> 0 while
          endif
        endif
      endif
    endif
    a=r 30
  a== 0 while
endif
a=r 7
a== 0 while
a= 3 r=a 31
halt
end
)ZDFL";
